# Claim-Amount model — 2026 re-run

This notebook re-runs the **2025 winning severity (claim-amount) model**
([CAA / ENS Challenge Data #161](https://challengedata.ens.fr/challenges/161))
with the **current AutoCarver** (see `pyproject.toml` for the pinned floor).
Companion to `frequency_model_2026.ipynb`.

Everything before the carving step — data loading, the `CM` target, the
stratified split, feature engineering and the column typing — is **identical to
`amount_model.ipynb`** (cells reused verbatim) so the only thing that changes is
the AutoCarver step. That keeps the comparison honest.

**What changes in 2026:**
1. **`ProcessingConfig(n_jobs=...)`** — per-feature carving runs across a process
   pool. Timed below.
2. **`min_freq_alpha`** — bin frequencies are gated by a **Wilson-score CI**, so
   thin bins are merged on statistical grounds (relevant for the heavy-tailed
   amount target).
3. **Selectors** take a `SelectionConfig` and a single `n_best_features` **total**
   budget, split evenly across feature types.
4. **Observation weights** come from the **2026 frequency model's** absolute
   error (exported by `frequency_model_2026.ipynb`), not the 2025 one.

The carver itself stays `ContinuousCarver` — the amount target is continuous,
so there is no `OrdinalCarver`-style upgrade on this side; the Kruskal-Wallis
carving criterion is unchanged from 2025.

## Loading data & target  *(reused from 2025)*

In [1]:
import pandas as pd

data_path = "../data/"

# loading x_train
data = pd.read_csv(data_path + "train_input_Z61KlZo.csv", low_memory=False)
data.set_index("ID", inplace=True)
print("x_train", data.shape)

# loading target
target = pd.read_csv(data_path + "train_output_DzPxaPY.csv", low_memory=False)
target.set_index("ID", inplace=True)
print("y_train", target.shape)

# joining x_train and y_train
data = data.join(target.drop("ANNEE_ASSURANCE", axis=1))
print("data", data.shape)

x_train (383610, 373)
y_train (383610, 4)

data (383610, 376)

## Stratified sampling  *(reused from 2025)*

Stratification uses the discretized claim amount (the saved target carver) so
train and dev share the same amount distribution.

In [2]:
from pathlib import Path

from AutoCarver import BinaryCarver
from sklearn.model_selection import train_test_split

target_col = "CM"

# loading target carver -- re-fitted by frequency_model_2026.ipynb
# (feature = CM, target = frequency), saved light-mode. Same recipe as 2025.
target_carver = BinaryCarver.load(Path("model/cm_carver_freq_tschuprowt_2026.json"))

# discretizing the target
y_freq = target_carver.transform(data)[target_col]

# Train-test split
x_train, x_dev, y_train, y_dev = train_test_split(
    data, data[target_col], test_size=0.2, random_state=42, stratify=y_freq
)
print("y_train mean", y_train.mean())
print("y_dev mean", y_dev.mean())

y_train mean 182.78860026567781
y_dev mean 181.4537592998097

## Feature engineering  *(reused from 2025)*

In [3]:
import warnings
from utils.data_toolkit import Processor

warnings.simplefilter(action="ignore", category=FutureWarning)

proc = Processor()
x_train = proc.fit_transform(x_train)
x_dev = proc.transform(x_dev)
data = proc.transform(data)
data.shape[0], x_train.shape[0], x_dev.shape[0]

(383610, 306888, 76722)

## Column typing  *(reused from 2025)*

In [4]:
from AutoCarver import Features

# sorting columns per type
features = Features.from_dataframe(x_train)

# getting ordinal columns
ordinals = [
    "NB_CASERNES",
    "BDTOPO_BAT_MAX_HAUTEUR",
    "HAUTEUR_MAX",
    "HAUTEUR",
    "BDTOPO_BAT_MAX_HAUTEUR_MAX",
    "MEN_SURF",
    "IND_SNV",
    "IND_INC",
    "IND_Y9",
    "IND_0_Y1",
    "IND",
    "LOG_SOC",
    "LOG_INC",
    "LOG_APA3",
    "LOG_AVA1",
    "MEN_MAIS",
    "MEN_COLL",
    "MEN_FMP",
    "MEN_PROP",
    "MEN_PAUV",
    "MEN",
    "COEFASS",
]
ordinals += [
    "DISTANCE_111",
    "DISTANCE_112",
    "DISTANCE_121",
    "DISTANCE_122",
    "DISTANCE_123",
    "DISTANCE_124",
    "DISTANCE_131",
    "DISTANCE_132",
    "DISTANCE_133",
    "DISTANCE_141",
    "DISTANCE_142",
    "DISTANCE_211",
    "DISTANCE_212",
    "DISTANCE_213",
    "DISTANCE_221",
    "DISTANCE_222",
    "DISTANCE_223",
    "DISTANCE_231",
    "DISTANCE_242",
    "DISTANCE_243",
    "DISTANCE_244",
    "DISTANCE_311",
    "DISTANCE_312",
    "DISTANCE_313",
    "DISTANCE_321",
    "DISTANCE_322",
    "DISTANCE_323",
    "DISTANCE_324",
    "DISTANCE_331",
    "DISTANCE_332",
    "DISTANCE_333",
    "DISTANCE_334",
    "DISTANCE_335",
    "DISTANCE_411",
    "DISTANCE_412",
    "DISTANCE_421",
    "DISTANCE_422",
    "DISTANCE_423",
    "DISTANCE_511",
    "DISTANCE_512",
    "DISTANCE_521",
    "DISTANCE_522",
    "DISTANCE_523",
    "PROPORTION_11",
    "PROPORTION_12",
    "PROPORTION_13",
    "PROPORTION_14",
    "PROPORTION_21",
    "PROPORTION_22",
    "PROPORTION_23",
    "PROPORTION_24",
    "PROPORTION_31",
    "PROPORTION_32",
    "PROPORTION_33",
    "PROPORTION_41",
    "PROPORTION_42",
    "PROPORTION_51",
    "PROPORTION_52",
    "MEN_1IND",
    "MEN_5IND",
    "LOG_A1_A2",
    "LOG_A2_A3",
    "IND_Y1_Y2",
    "IND_Y2_Y3",
    "IND_Y3_Y4",
    "IND_Y4_Y5",
    "IND_Y5_Y6",
    "IND_Y6_Y7",
    "IND_Y7_Y8",
    "IND_Y8_Y9",
    "DISTANCE_1",
    "DISTANCE_2",
    "ALTITUDE_1",
    "ALTITUDE_2",
    "ALTITUDE_3",
    "ALTITUDE_4",
    "ALTITUDE_5",
    "NBJTX25_MM_A",
    "NBJTX25_MMAX_A",
    "NBJTX25_MSOM_A",
    "NBJTX0_MM_A",
    "NBJTX0_MMAX_A",
    "NBJTX0_MSOM_A",
    "NBJTXI27_MM_A",
    "NBJTXI27_MMAX_A",
    "NBJTXI27_MSOM_A",
    "NBJTXS32_MM_A",
    "NBJTXS32_MMAX_A",
    "NBJTXS32_MSOM_A",
    "NBJTXI20_MM_A",
    "NBJTXI20_MMAX_A",
    "NBJTXI20_MSOM_A",
    "NBJTX30_MM_A",
    "NBJTX30_MMAX_A",
    "NBJTX30_MSOM_A",
    "NBJTX35_MM_A",
    "NBJTX35_MMAX_A",
    "NBJTX35_MSOM_A",
    "NBJTN10_MM_A",
    "NBJTN10_MMAX_A",
    "NBJTN10_MSOM_A",
    "NBJTNI10_MM_A",
    "NBJTNI10_MMAX_A",
    "NBJTNI10_MSOM_A",
    "NBJTN5_MM_A",
    "NBJTN5_MMAX_A",
    "NBJTN5_MSOM_A",
    "NBJTNS25_MM_A",
    "NBJTNS25_MMAX_A",
    "NBJTNS25_MSOM_A",
    "NBJTNI15_MM_A",
    "NBJTNI15_MMAX_A",
    "NBJTNI15_MSOM_A",
    "NBJTNI20_MM_A",
    "NBJTNI20_MMAX_A",
    "NBJTNI20_MSOM_A",
    "NBJTNS20_MM_A",
    "NBJTNS20_MMAX_A",
    "NBJTNS20_MSOM_A",
    "NBJTMS24_MM_A",
    "NBJTMS24_MMAX_A",
    "NBJTMS24_MSOM_A",
    "TAMPLIAB_VOR_MM_A",
    "TAMPLIAB_VOR_MMAX_A",
    "TAMPLIM_VOR_MM_A",
    "TAMPLIM_VOR_MMAX_A",
    "TM_VOR_MM_A",
    "TM_VOR_MMAX_A",
    "TMM_VOR_MM_A",
    "TMM_VOR_MMAX_A",
    "TMMAX_VOR_MM_A",
    "TMMAX_VOR_MMAX_A",
    "TMMIN_VOR_MM_A",
    "TMMIN_VOR_MMAX_A",
    "TN_VOR_MM_A",
    "TN_VOR_MMAX_A",
    "TNAB_VOR_MM_A",
    "TNAB_VOR_MMAX_A",
    "TNMAX_VOR_MM_A",
    "TNMAX_VOR_MMAX_A",
    "TX_VOR_MM_A",
    "TX_VOR_MMAX_A",
    "TXAB_VOR_MM_A",
    "TXAB_VOR_MMAX_A",
    "TXMIN_VOR_MM_A",
    "TXMIN_VOR_MMAX_A",
    "NBJFF10_MM_A",
    "NBJFF10_MMAX_A",
    "NBJFF10_MSOM_A",
    "NBJFF16_MM_A",
    "NBJFF16_MMAX_A",
    "NBJFF16_MSOM_A",
    "NBJFF28_MM_A",
    "NBJFF28_MMAX_A",
    "NBJFF28_MSOM_A",
    "NBJFXI3S10_MM_A",
    "NBJFXI3S10_MMAX_A",
    "NBJFXI3S10_MSOM_A",
    "NBJFXI3S16_MM_A",
    "NBJFXI3S16_MMAX_A",
    "NBJFXI3S16_MSOM_A",
    "NBJFXI3S28_MM_A",
    "NBJFXI3S28_MMAX_A",
    "NBJFXI3S28_MSOM_A",
    "NBJFXY8_MM_A",
    "NBJFXY8_MMAX_A",
    "NBJFXY8_MSOM_A",
    "NBJFXY10_MM_A",
    "NBJFXY10_MMAX_A",
    "NBJFXY10_MSOM_A",
    "NBJFXY15_MM_A",
    "NBJFXY15_MMAX_A",
    "NBJFXY15_MSOM_A",
    "FFM_VOR_MM_A",
    "FFM_VOR_MMAX_A",
    "FXI3SAB_VOR_MM_A",
    "FXI3SAB_VOR_MMAX_A",
    "FXIAB_VOR_MM_A",
    "FXIAB_VOR_MMAX_A",
    "FXYAB_VOR_MM_A",
    "FXYAB_VOR_MMAX_A",
    "FFM_VOR_COM_MM_A_Y",
    "FFM_VOR_COM_MMAX_A_Y",
    "FXI3SAB_VOR_COM_MM_A_Y",
    "FXI3SAB_VOR_COM_MMAX_A_Y",
    "NBJRR50_MM_A",
    "NBJRR50_MMAX_A",
    "NBJRR50_MSOM_A",
    "NBJRR1_MM_A",
    "NBJRR1_MMAX_A",
    "NBJRR1_MSOM_A",
    "NBJRR5_MM_A",
    "NBJRR5_MMAX_A",
    "NBJRR5_MSOM_A",
    "NBJRR10_MM_A",
    "NBJRR10_MMAX_A",
    "NBJRR10_MSOM_A",
    "NBJRR30_MM_A",
    "NBJRR30_MMAX_A",
    "NBJRR30_MSOM_A",
    "NBJRR100_MM_A",
    "NBJRR100_MMAX_A",
    "NBJRR100_MSOM_A",
    "RR_VOR_MM_A",
    "RR_VOR_MMAX_A",
    "RRAB_VOR_MM_A",
    "RRAB_VOR_MMAX_A",
]
ordinals += ["TAILLE1", "TAILLE2"]
ordinal_columns = {
    col: list(data[col].value_counts().sort_index().index)
    for col in ordinals
    if col in data.columns
}
ordinal_columns["PROPORTION_32"] += ["10. > 90"]
ordinal_columns.update(
    {
        "CARACT4": [
            "absence de surface",
            "Surface de moins d",
            "Surface entre 501",
            "Surface entre 1001",
            "Surface entre 1501",
            "Surface de plus de",
        ],
        "SURFACE4": [
            "0",
            "500",
            "1000",
            "1500",
            "2000",
            "2500",
            "3000",
            "3500",
            "4000",
            "4500",
            "5000",
            "5500",
            "6000",
            "6500",
            "7000",
            "7000+",
        ],
        "SURFACE6": [
            "0",
            "500",
            "1000",
            "1500",
            "2000",
            "2500",
            "3000",
            "3500",
            "4000",
            "4500",
            "5000",
            "5500",
            "6000",
            "6500",
            "7000",
            "7000+",
        ],
        "total_surface_2023": [
            "Aucun feu",
            "<10ha",
            "10-20ha",
            "20-50ha",
            "50-100ha",
            "100-200ha",
            ">200ha",
        ],
        "total_surface_5y": [
            "Aucun feu",
            "<10ha",
            "10-20ha",
            "20-50ha",
            "50-100ha",
            "100-200ha",
            ">200ha",
        ],
        "surface_over_forest": [
            "Absence de feu",
            "<0.05",
            "0.05-0.1",
            "0.1-0.2",
            "0.5-2",
        ],
        "fire_extinction_rates": ["Aucun feu", "<50%", "50-70%", "70-85%", ">85%"],
    }
)

# columns that are to be removed (target + no values)
to_remove = target.columns.tolist() + [target_col]
to_remove += [c for c in data.columns if "MMSOM" in c]
to_remove += [
    "DEROG3",
    "DEROG13",
    "DEROG16",
    "DEROG8",
    "DEROG14",
    "TARGET",
    "DEROG13_formatted",
    "DEROG8_formatted",
    "DEROG3_formatted",
    "DEROG16_formatted",
    "DEROG14_formatted",
    "IND_Y1_Y2_num",
    "IND_INC_num",
]

# removing columns
categorical_columns = [
    col.name
    for col in features.categoricals
    if col not in to_remove and col not in ordinal_columns
]
categorical_columns += ["TYPERS"]
numerical_columns = [
    col.name
    for col in features.numericals
    if col not in to_remove
    and col not in ordinal_columns
    and col not in categorical_columns
]
print(
    len(categorical_columns),
    len(numerical_columns),
    len(ordinal_columns),
    len(categorical_columns) + len(numerical_columns) + len(ordinal_columns),
)

193 115 238 546

## 2026 carving — ContinuousCarver + multiprocessing + Wilson-CI

Same carver class and `max_n_mod=5` as 2025 — only the execution config is new.
`min_freq` is left at the 7.6+ default of **0.02** where 2025 carved this model at
**0.03**: a deviation between the two eras, on record in the article's setup footnote. The
lower threshold admits thinner buckets, i.e. *more* work (and `ZONE` survives carving where
it did not at 0.03), so it does not flatter the 2026 wall-clock.

`n_jobs` parallelises the per-feature combination search; set it to the core count on the
competition machine. `min_freq_alpha=0.05` is the 95% Wilson interval used to test each
bin's frequency.

In [5]:
import time

from AutoCarver import ContinuousCarver, Features
from AutoCarver.discretizers import ProcessingConfig

N_JOBS = 6

config = ProcessingConfig(
    dropna=False, copy=False, verbose=False, n_jobs=N_JOBS, min_freq_alpha=0.05
)

qualitatives = Features(categoricals=categorical_columns, ordinals=ordinal_columns)

# max_n_mod is 5 by default, as in 2025; min_freq is left at the 7.6+ default (0.02)
# where 2025 carved this model at 0.03 -- a deviation on record in the setup footnote
carver = ContinuousCarver(features=qualitatives, config=config)

t0 = time.perf_counter()
x_train = carver.fit_transform(x_train, y_train, X_dev=x_dev, y_dev=y_dev)
print(
    f"[2026] qualitative carving: {time.perf_counter() - t0:.1f}s on {N_JOBS} workers"
)
carver.summary

[ContinuousCarver] Carving:   0%|          | 0/431 [00:00<?, ?feature/s]

[ContinuousCarver] dropped 1/431 feature(s) (no robust train/dev combination): INDEM1

[2026] qualitative carving: 139.8s on 6 workers

                                                                                                 content  \
feature                          kruskal    n_mod label
Categorical('ACTIVIT2')          159.526506 3.0   0      [ACT2, ACT8, ACT4, ACT6, ACT7, __OTHER__, ACT9]
                                                  1                                                 ACT5
                                                  2                                         [ACT3, ACT1]
Categorical('VOCATION')          507.252150 3.0   0            [VOC7, VOC8, VOC5, VOC3, VOC2, __OTHER__]
                                                  1                                         [VOC4, VOC1]
...                                                                                                  ...
Ordinal('surface_over_forest')   10.096102  4.0   3                                     [0.5-2, 0.1-0.2]
Ordinal('fire_extinction_rates') 2.238349   2.0   0                    [<50%, 50-70%, 70-85%, Aucun feu]
                                                  1                                                 >85%
Categorical('INDEM1')            NaN        NaN   O                                                    O
                                                  N                                                    N

                                                         target_mean  \
feature                          kruskal    n_mod label
Categorical('ACTIVIT2')          159.526506 3.0   0        86.255102
                                                  1       165.349191
                                                  2       194.858259
Categorical('VOCATION')          507.252150 3.0   0        58.531347
                                                  1       116.736895
...                                                              ...
Ordinal('surface_over_forest')   10.096102  4.0   3       196.900856
Ordinal('fire_extinction_rates') 2.238349   2.0   0       161.468501
                                                  1       244.639328
Categorical('INDEM1')            NaN        NaN   O       150.789799
                                                  N       184.348272

                                                         frequency     count  \
feature                          kruskal    n_mod label
Categorical('ACTIVIT2')          159.526506 3.0   0       0.073017   22408.0
                                                  1       0.140289   43053.0
                                                  2       0.786694  241427.0
Categorical('VOCATION')          507.252150 3.0   0       0.285212   87528.0
                                                  1       0.077422   23760.0
...                                                            ...       ...
Ordinal('surface_over_forest')   10.096102  4.0   3       0.054733   16797.0
Ordinal('fire_extinction_rates') 2.238349   2.0   0       0.743659  228220.0
                                                  1       0.256341   78668.0
Categorical('INDEM1')            NaN        NaN   O       0.046476   14263.0
                                                  N       0.953524  292625.0

                                                                 std  dropped  \
feature                          kruskal    n_mod label
Categorical('ACTIVIT2')          159.526506 3.0   0      4147.474384    False
                                                  1      5811.476729    False
                                                  2      7056.154998    False
Categorical('VOCATION')          507.252150 3.0   0      3653.991661    False
                                                  1      5004.026018    False
...                                                              ...      ...
Ordinal('surface_over_forest')   10.096102  4.0   3      7644.996694    False
Ordinal('fire_extinction_rates') 2.238349   2.0   0      5980.619722    False
                                                  1      8509.824244    False
Categorical('INDEM1')            NaN        NaN   O      6736.475887     True
                                                  N      6719.612909     True

                                                                                            dropped_reason
feature                          kruskal    n_mod label
Categorical('ACTIVIT2')          159.526506 3.0   0                                                   None
                                                  1                                                   None
                                                  2                                                   None
Categorical('VOCATION')          507.252150 3.0   0                                                   None
                                                  1                                                   None
...                                                                                                    ...
Ordinal('surface_over_forest')   10.096102  4.0   3                                                   None
Ordinal('fire_extinction_rates') 2.238349   2.0   0                                                   None
                                                  1                                                   None
Categorical('INDEM1')            NaN        NaN   O      No robust combination (Inversion of target rat...
                                                  N      No robust combination (Inversion of target rat...

[1109 rows x 7 columns]

No processing for continuous features

In [6]:
quantitatives = Features(numericals=numerical_columns)

### Apply carver to dev + OOS

In [7]:
x_dev = carver.transform(x_dev)

oos = pd.read_csv(data_path + "test_input_5qJzHrr.csv", low_memory=False)
oos = proc.transform(oos)
oos = carver.transform(oos)
oos.set_index("ID", inplace=True)
oos.shape[0], x_train.shape[0], x_dev.shape[0]

(95852, 306888, 76722)

## Frequency-model predictions & error weights  *(2026 frequency run)*

As in 2025, each observation is weighted by the **absolute error of the
frequency model** so the amount model concentrates on the first stage's
mistakes. The difference: predictions come from `frequency_model_2026.ipynb`,
which writes `data/frequency_2026.csv` (train + dev, carrying the `ID` index)
and `data/oos_frequency_2026.csv`. **Run that notebook first** — these files are
this notebook's inputs, and a stale pair describes a frequency model that no
longer exists.

In [8]:
FREQ_VERSION = "2026"

# frequency predictions on train + dev
merged = pd.read_csv(data_path + f"frequency_{FREQ_VERSION}.csv", low_memory=False)
merged.set_index("ID", inplace=True)

x_train = x_train.join(merged[[c for c in merged.columns if c not in x_train.columns]])
x_dev = x_dev.join(merged[[c for c in merged.columns if c not in x_dev.columns]])

# frequency predictions on OOS
oos_freq = pd.read_csv(
    data_path + f"oos_frequency_{FREQ_VERSION}.csv", low_memory=False
)
oos_freq.set_index("ID", inplace=True)

oos = oos.join(oos_freq[[c for c in oos_freq.columns if c not in oos.columns]])
x_train.shape[0], x_dev.shape[0], oos.shape[0]

(306888, 76722, 95852)

In [9]:
# weight = absolute error of the frequency model (boosting-flavoured hand-off)
w_train = (x_train["pred_sum"] - x_train["FREQ"]).abs()
w_dev = (x_dev["pred_sum"] - x_dev["FREQ"]).abs()

## Feature selection  *(single selector, one config)*

One `RegressionSelector` over **both** feature types with a single `SelectionConfig`,
instead of one selector per type. `n_best_features` is a **total** budget, split **evenly**
across feature types, so the 200 below buys 100 carved qualitative + 100 raw quantitative
features.

Worth knowing: the frequency and severity targets want **opposite** feature mixes. Tilting
the budget towards carved qualitatives helps this arm and hurts the frequency arm, so an
even split is a compromise rather than an optimum on either side.

Measures are `DistanceMeasure` + `SpearmanFilter` on quantitatives and the library-default
Kruskal association on carved qualitatives, with a Cramer's V 0.9 redundancy cut.

In [10]:
from AutoCarver.selectors import (
    CramervFilter,
    DistanceMeasure,
    RegressionSelector,
    SelectionConfig,
    SpearmanFilter,
)

config = SelectionConfig(
    quantitative_measures=[DistanceMeasure(threshold=0.002)],
    quantitative_filters=[SpearmanFilter(threshold=0.9)],
    qualitative_filters=[CramervFilter(threshold=0.9)],
)
selector = RegressionSelector(
    qualitatives + quantitatives, n_best_features=200, config=config
)
selector.fit(x_train, y_train)
print("selected:", len(selector.selected_features))
selector.summary

selected: 200

,feature,Nan,Mode,measure,association,rank,filter,redundancy,redundancy_with,selected
0,Numerical('SURFACE11'),0.228888,0.066145,Distance,-0.032622,0.0,Spearman,0.000000,itself,True
1,Numerical('KAPITAL32'),0.000000,0.348323,Distance,-0.026539,1.0,Spearman,0.632294,SURFACE11,True
2,Numerical('SURFACE17'),0.000000,0.831893,Distance,-0.025193,2.0,Spearman,0.485804,SURFACE11,True
3,Numerical('KAPITAL_MAX'),0.000000,0.248618,Distance,-0.023689,3.0,Spearman,0.824240,KAPITAL32,True
4,Numerical('SURFACE10'),0.019496,0.523396,Distance,-0.020762,4.0,Spearman,0.644371,SURFACE11,True
...,...,...,...,...,...,...,...,...,...,...
540,Ordinal('NBJRR100_MMAX_A'),0.567402,0.370797,KruskalEtaSquared,0.000024,NaN,None,NaN,None,False
541,Ordinal('NBJRR100_MSOM_A'),0.567402,0.376906,KruskalEtaSquared,0.000028,NaN,None,NaN,None,False
542,Ordinal('SURFACE6'),0.000000,0.605025,KruskalEtaSquared,0.002966,NaN,Cramerv,0.999987,SURFACE4,False
543,Ordinal('surface_over_forest'),0.000000,0.721455,KruskalEtaSquared,0.000023,NaN,None,NaN,None,False
544,Ordinal('fire_extinction_rates'),0.000000,0.743659,KruskalEtaSquared,0.000004,NaN,None,NaN,None,False

In [11]:
best_features = selector.selected_features.names

## XGBoost + Optuna  *(unchanged objectives from `utils.objectives`)*

`reg:tweedie` regressor on the frequency-error-weighted samples, exactly as in
2025 — any dev-metric delta is attributable to the carving step, not the tuner. Drop
`N_TRIALS` while iterating.

In [12]:
import optuna

from utils.objectives import get_regression_objective

N_TRIALS = 400

# tweedie requires a non-negative target
y_transform = lambda u: u.where(u >= 0, 0)

objective = get_regression_objective(
    x_train[best_features],
    y_transform(y_train),
    x_dev[best_features],
    y_transform(y_dev),
    objective="reg:tweedie",
    w_train=w_train,
    w_dev=w_dev,
)
# seeded so the tuning is reproducible: the split and every XGBoost estimator
# already use random_state=42, and carving is deterministic, so this is the last
# source of run-to-run variance.
study = optuna.create_study(
    direction="minimize", sampler=optuna.samplers.TPESampler(seed=42)
)
study.optimize(objective, n_trials=N_TRIALS)
study.best_params

[I 2026-08-31 09:15:07,087] A new study created in memory with name: no-name-7e7f1482-0686-4935-a572-9c23ebe4ec60

C:\Users\defra\Desktop\git\PROJECTS\caa-challenge\.venv\Lib\site-packages\xgboost\core.py:751: UserWarning: [09:15:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

[I 2026-08-31 09:15:20,296] Trial 0 finished with value: 1.0552441568676813e+34 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 287, 'learning_rate': 0.9507192349792751, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.3248149123539492, 'colsample_bytree': 0.32479561626896214, 'colsample_bylevel': 0.24646688973455957, 'gamma': 8.661761457749352, 'alpha': 6.011150117432088, 'lambda': 7.080725777960454, 'tweedie_variance_power': 1.216467595436642}. Best is trial 0 with value: 1.0552441568676813e+34.

[I 2026-08-31 09:15:31,162] Trial 1 finished with value: 3494010.1967561687 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 585, 'learning_rate': 0.8324593965363417, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.34672360788274703, 'colsample_bytree': 0.4433937943676302, 'colsample_bylevel': 0.6198051453057902, 'gamma': 4.319450186421157, 'alpha': 2.9122914019804194, 'lambda': 6.118528947223795, 'tweedie_variance_power': 1.3115950885216334}. Best is trial 1 with value: 3494010.1967561687.

[I 2026-08-31 09:15:39,235] Trial 2 finished with value: 7204.383936191784 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 246, 'learning_rate': 0.3664252071093623, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.3597390257266878, 'colsample_bytree': 0.6113875507308892, 'colsample_bylevel': 0.6739316550896339, 'gamma': 0.46450412719997725, 'alpha': 6.075448519014383, 'lambda': 1.7052412368729153, 'tweedie_variance_power': 1.2520412743882237}. Best is trial 2 with value: 7204.383936191784.

[I 2026-08-31 09:15:47,406] Trial 3 finished with value: 1533682392189275.8 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 575, 'learning_rate': 0.9656354698712519, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.2781376912051071, 'colsample_bytree': 0.7473864212097256, 'colsample_bylevel': 0.5521219949916811, 'gamma': 1.2203823484477883, 'alpha': 4.951769101112702, 'lambda': 0.34388521115218396, 'tweedie_variance_power': 1.9274563216630256}. Best is trial 2 with value: 7204.383936191784.

[I 2026-08-31 09:15:54,593] Trial 4 finished with value: 21473.134312099228 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 229, 'learning_rate': 0.6625560321255466, 'max_depth': 4, 'min_child_weight': 11, 'subsample': 0.6373682234746237, 'colsample_bytree': 0.3478835644204217, 'colsample_bylevel': 0.9756677022116469, 'gamma': 7.7513282336111455, 'alpha': 9.394989415641891, 'lambda': 8.948273504276488, 'tweedie_variance_power': 1.6783199830488682}. Best is trial 2 with value: 7204.383936191784.

[I 2026-08-31 09:16:04,323] Trial 5 finished with value: 6619.806913158368 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 561, 'learning_rate': 0.0885836528017143, 'max_depth': 2, 'min_child_weight': 1, 'subsample': 0.4602642646106115, 'colsample_bytree': 0.5109418317515857, 'colsample_bylevel': 0.41707922541911674, 'gamma': 8.287375091519294, 'alpha': 3.567533266935893, 'lambda': 2.8093450968738076, 'tweedie_variance_power': 1.6341568665265989}. Best is trial 5 with value: 6619.806913158368.

[I 2026-08-31 09:16:09,789] Trial 6 finished with value: 6744.353389634932 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 170, 'learning_rate': 0.8022167610559643, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.8177958154373259, 'colsample_bytree': 0.35897254522733796, 'colsample_bylevel': 0.20441769369888194, 'gamma': 8.154614284548341, 'alpha': 7.068573438476172, 'lambda': 7.2900716804098735, 'tweedie_variance_power': 1.8170162773487566}. Best is trial 5 with value: 6619.806913158368.

[I 2026-08-31 09:16:15,293] Trial 7 finished with value: 6620.775825478142 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 137, 'learning_rate': 0.35852988197141816, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.6986385014620464, 'colsample_bytree': 0.46471841988211937, 'colsample_bylevel': 0.25084668022881895, 'gamma': 3.109823217156622, 'alpha': 3.2518332202674705, 'lambda': 7.29606178338064, 'tweedie_variance_power': 1.7100459770841705}. Best is trial 5 with value: 6619.806913158368.

[I 2026-08-31 09:16:24,821] Trial 8 finished with value: 6722.156393264214 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 544, 'learning_rate': 0.4722677036694331, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.8086280388935181, 'colsample_bytree': 0.649021758055597, 'colsample_bylevel': 0.8167737439636489, 'gamma': 4.937955963643907, 'alpha': 5.227328293819941, 'lambda': 4.275410183585496, 'tweedie_variance_power': 1.220335301395276}. Best is trial 5 with value: 6619.806913158368.

[I 2026-08-31 09:16:32,353] Trial 9 finished with value: 6621.797562465582 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 154, 'learning_rate': 0.031526042768165584, 'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.6068565529317622, 'colsample_bytree': 0.9260531791408744, 'colsample_bylevel': 0.39943378331909996, 'gamma': 4.103829230356297, 'alpha': 7.555511385430487, 'lambda': 2.2879816549162246, 'tweedie_variance_power': 1.2615839278630343}. Best is trial 5 with value: 6619.806913158368.

[I 2026-08-31 09:16:44,761] Trial 10 finished with value: 6617.631584727444 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 421, 'learning_rate': 0.006096583237521769, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9691819744254799, 'colsample_bytree': 0.9261318362260142, 'colsample_bylevel': 0.40634156208119365, 'gamma': 6.379717552110608, 'alpha': 0.5831300841506488, 'lambda': 9.923626654603368, 'tweedie_variance_power': 1.524396683607944}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:16:57,133] Trial 11 finished with value: 6618.503263845706 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 433, 'learning_rate': 0.01665340322250372, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9484495008651397, 'colsample_bytree': 0.9915128586132267, 'colsample_bylevel': 0.43945589361810844, 'gamma': 6.662077194400634, 'alpha': 0.04827415963255999, 'lambda': 9.299125876102014, 'tweedie_variance_power': 1.488873048857085}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:17:08,949] Trial 12 finished with value: 6778.217149147894 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 414, 'learning_rate': 0.17304822362172148, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9962083026784908, 'colsample_bytree': 0.9968132253979483, 'colsample_bylevel': 0.44073069402292386, 'gamma': 6.3250071407908734, 'alpha': 0.018322547156963666, 'lambda': 9.82467370121027, 'tweedie_variance_power': 1.4655179201519806}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:17:22,014] Trial 13 finished with value: 6793.6807331269065 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 421, 'learning_rate': 0.19733556384428674, 'max_depth': 10, 'min_child_weight': 4, 'subsample': 0.972270356852364, 'colsample_bytree': 0.8464528275577314, 'colsample_bylevel': 0.4986066745805466, 'gamma': 9.97728027546724, 'alpha': 0.19941623809865386, 'lambda': 8.929498202161971, 'tweedie_variance_power': 1.5079743224979092}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:17:34,564] Trial 14 finished with value: 6618.531004772933 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 431, 'learning_rate': 0.013972294220205699, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8860843565015941, 'colsample_bytree': 0.8388061576130378, 'colsample_bylevel': 0.3293492886713917, 'gamma': 6.230265993074804, 'alpha': 1.415842416523513, 'lambda': 9.772664655950779, 'tweedie_variance_power': 1.4493100637411815}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:17:44,771] Trial 15 finished with value: 6665.140486243813 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 347, 'learning_rate': 0.2347469860775609, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8877199001564409, 'colsample_bytree': 0.996074230322476, 'colsample_bylevel': 0.7313671337647042, 'gamma': 6.44723978328263, 'alpha': 1.6375787300644444, 'lambda': 8.596123207493019, 'tweedie_variance_power': 1.5569160336599166}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:17:59,689] Trial 16 finished with value: 6788.721360749046 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 484, 'learning_rate': 0.1334679610858541, 'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.7871229961034878, 'colsample_bytree': 0.8470817261658005, 'colsample_bylevel': 0.5410773328752753, 'gamma': 2.640703664623703, 'alpha': 1.5374336039395768, 'lambda': 5.355177779968159, 'tweedie_variance_power': 1.378242417240201}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:18:12,572] Trial 17 finished with value: 6900.5571329447785 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 351, 'learning_rate': 0.3244089638352915, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9028936302214957, 'colsample_bytree': 0.20980473423481388, 'colsample_bylevel': 0.34064980639744663, 'gamma': 5.723967276344128, 'alpha': 0.7415463393802799, 'lambda': 8.198252907885834, 'tweedie_variance_power': 1.583482541912194}. Best is trial 10 with value: 6617.631584727444.

[I 2026-08-31 09:18:23,683] Trial 18 finished with value: 6616.858540539475 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 465, 'learning_rate': 0.026702749904235046, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.7280646421107326, 'colsample_bytree': 0.7339584440773386, 'colsample_bylevel': 0.3197062279147466, 'gamma': 7.219110545028451, 'alpha': 2.5997423016857732, 'lambda': 9.813993420338791, 'tweedie_variance_power': 1.377328668570775}. Best is trial 18 with value: 6616.858540539475.

[I 2026-08-31 09:18:35,876] Trial 19 finished with value: 6859.137532790192 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 488, 'learning_rate': 0.5029827747094364, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.5432763999928484, 'colsample_bytree': 0.7244235169857248, 'colsample_bylevel': 0.3301445737915937, 'gamma': 9.608771169328996, 'alpha': 2.6659401677790173, 'lambda': 7.901426689438663, 'tweedie_variance_power': 1.369555660288825}. Best is trial 18 with value: 6616.858540539475.

[I 2026-08-31 09:18:46,092] Trial 20 finished with value: 6660.43821078675 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 341, 'learning_rate': 0.25939652924859774, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.6952161293221044, 'colsample_bytree': 0.7519421773121246, 'colsample_bylevel': 0.3042126875643737, 'gamma': 7.277375536712107, 'alpha': 2.4072819931899763, 'lambda': 9.973110342841618, 'tweedie_variance_power': 1.3755017047852802}. Best is trial 18 with value: 6616.858540539475.

[I 2026-08-31 09:19:00,561] Trial 21 finished with value: 6658.147128602557 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 493, 'learning_rate': 0.06398449195233818, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.934823129271247, 'colsample_bytree': 0.907227642123217, 'colsample_bylevel': 0.47567217423221486, 'gamma': 7.068237463706379, 'alpha': 1.0025580879061076, 'lambda': 9.078492681903501, 'tweedie_variance_power': 1.4407996526316575}. Best is trial 18 with value: 6616.858540539475.

[I 2026-08-31 09:19:14,505] Trial 22 finished with value: 6619.410945857434 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 389, 'learning_rate': 0.013411652295464807, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.7521955265582287, 'colsample_bytree': 0.9244050554523355, 'colsample_bylevel': 0.3892521523525927, 'gamma': 5.126945300286815, 'alpha': 3.7555088497395985, 'lambda': 9.896399511687799, 'tweedie_variance_power': 1.5356475080462901}. Best is trial 18 with value: 6616.858540539475.

[I 2026-08-31 09:19:27,261] Trial 23 finished with value: 6857.335962779975 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 462, 'learning_rate': 0.1282007777201794, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8642261202703352, 'colsample_bytree': 0.6638995078837926, 'colsample_bylevel': 0.571106595609101, 'gamma': 8.883910753504647, 'alpha': 2.1404176486586173, 'lambda': 8.220649560758543, 'tweedie_variance_power': 1.3244667582406282}. Best is trial 18 with value: 6616.858540539475.

[I 2026-08-31 09:19:37,183] Trial 24 finished with value: 6615.967597184198 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 379, 'learning_rate': 0.003665492704766758, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.993248177784054, 'colsample_bytree': 0.8219194861608754, 'colsample_bylevel': 0.4733650941884556, 'gamma': 6.902049290924852, 'alpha': 0.6569205295854252, 'lambda': 6.426560197840569, 'tweedie_variance_power': 1.7592739622649458}. Best is trial 24 with value: 6615.967597184198.

[I 2026-08-31 09:19:49,127] Trial 25 finished with value: 6626.505676821561 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 535, 'learning_rate': 0.12356648910169876, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.5201982289834203, 'colsample_bytree': 0.7933728224608246, 'colsample_bylevel': 0.505347765215097, 'gamma': 7.436800202575678, 'alpha': 4.174082307468559, 'lambda': 5.57050647083671, 'tweedie_variance_power': 1.7699373734836126}. Best is trial 24 with value: 6615.967597184198.

[I 2026-08-31 09:19:58,882] Trial 26 finished with value: 7273.534791945043 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 368, 'learning_rate': 0.27388026442660685, 'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.7236222668150809, 'colsample_bytree': 0.6048162985309102, 'colsample_bylevel': 0.278690176872249, 'gamma': 5.4373822665703155, 'alpha': 2.019817064631601, 'lambda': 4.087386250183299, 'tweedie_variance_power': 1.8990808496223137}. Best is trial 24 with value: 6615.967597184198.

[I 2026-08-31 09:20:06,670] Trial 27 finished with value: 6615.663041213181 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 286, 'learning_rate': 0.08845401704688896, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.85275778664119, 'colsample_bytree': 0.7028215155213722, 'colsample_bylevel': 0.3697934442294738, 'gamma': 4.00522156751162, 'alpha': 0.8283952532416107, 'lambda': 6.214742337504003, 'tweedie_variance_power': 1.8467551321738878}. Best is trial 27 with value: 6615.663041213181.

[I 2026-08-31 09:20:14,738] Trial 28 finished with value: 6619.835117154616 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 290, 'learning_rate': 0.1772592780310151, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.8348803878907999, 'colsample_bytree': 0.6851379612576067, 'colsample_bylevel': 0.36508215431687185, 'gamma': 2.648121093573355, 'alpha': 1.1501973861169992, 'lambda': 6.387122464719103, 'tweedie_variance_power': 1.992206227019641}. Best is trial 27 with value: 6615.663041213181.

[I 2026-08-31 09:20:22,767] Trial 29 finished with value: 6613.521217462371 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 296, 'learning_rate': 0.09127233734241048, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.6675659352994935, 'colsample_bytree': 0.5776841264199901, 'colsample_bylevel': 0.20087607759853637, 'gamma': 4.273205566350821, 'alpha': 4.526329178155393, 'lambda': 4.548698915616803, 'tweedie_variance_power': 1.8337176194043512}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:20:31,020] Trial 30 finished with value: 6620.166868435404 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 301, 'learning_rate': 0.43196156417934645, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.6498139990208478, 'colsample_bytree': 0.5673434588102606, 'colsample_bylevel': 0.23268812619347556, 'gamma': 3.421640542828079, 'alpha': 9.426773191465175, 'lambda': 4.492706765275142, 'tweedie_variance_power': 1.815756008219809}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:20:39,115] Trial 31 finished with value: 6617.2612354336125 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 242, 'learning_rate': 0.10176698653350125, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.761169986478057, 'colsample_bytree': 0.548573831731527, 'colsample_bylevel': 0.2655632840126664, 'gamma': 4.266912290572606, 'alpha': 4.751906438631912, 'lambda': 5.094961142095613, 'tweedie_variance_power': 1.863034501708789}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:20:48,751] Trial 32 finished with value: 6618.5285761435225 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 315, 'learning_rate': 0.07991327986365655, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.625498454410558, 'colsample_bytree': 0.7886493090114022, 'colsample_bylevel': 0.2832045790816116, 'gamma': 1.9105442190248487, 'alpha': 2.998177370469328, 'lambda': 6.394483010199377, 'tweedie_variance_power': 1.7525151258054912}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:20:56,097] Trial 33 finished with value: 6618.3808635108 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 268, 'learning_rate': 0.20855496072647717, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.843104910813824, 'colsample_bytree': 0.7085534859235509, 'colsample_bylevel': 0.23254641334036336, 'gamma': 3.8046348895225623, 'alpha': 6.007092183504682, 'lambda': 3.581489076093976, 'tweedie_variance_power': 1.938595444663072}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:03,847] Trial 34 finished with value: 6619.141257648708 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 204, 'learning_rate': 0.14436326823699674, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.5858298156048463, 'colsample_bytree': 0.625770596586721, 'colsample_bylevel': 0.623711495387768, 'gamma': 4.771407725841974, 'alpha': 4.36039858118694, 'lambda': 6.091183162240489, 'tweedie_variance_power': 1.8429879976765808}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:13,201] Trial 35 finished with value: 777517733.190825 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 317, 'learning_rate': 0.07719414613344747, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.6687235126600685, 'colsample_bytree': 0.7926722800452335, 'colsample_bylevel': 0.36439368341751144, 'gamma': 1.0410690492846966, 'alpha': 5.550705087701982, 'lambda': 0.7535263136997603, 'tweedie_variance_power': 1.9939723680878265}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:20,101] Trial 36 finished with value: 6714.522139249278 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 107, 'learning_rate': 0.2731996908348804, 'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.2301597101707646, 'colsample_bytree': 0.4611577559300153, 'colsample_bylevel': 0.3007379192470929, 'gamma': 5.8693937712667, 'alpha': 1.928132604557983, 'lambda': 6.9326196444260715, 'tweedie_variance_power': 1.663861182712286}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:27,866] Trial 37 finished with value: 6613.532946165714 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 271, 'learning_rate': 0.06671850882459521, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.3741497410624031, 'colsample_bytree': 0.5766185360256796, 'colsample_bylevel': 0.9954415413611334, 'gamma': 8.82729271994338, 'alpha': 6.741213385316838, 'lambda': 3.4420822857161433, 'tweedie_variance_power': 1.7490966781322668}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:35,772] Trial 38 finished with value: 6633.758719395459 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 262, 'learning_rate': 0.30545326225422037, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.4123624271150206, 'colsample_bytree': 0.40833305374037215, 'colsample_bylevel': 0.922772624451462, 'gamma': 8.893091802712103, 'alpha': 8.443498337910011, 'lambda': 3.355974877484423, 'tweedie_variance_power': 1.7535358515599344}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:43,602] Trial 39 finished with value: 14554297.259259121 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 224, 'learning_rate': 0.8372478260576137, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.3692857125836315, 'colsample_bytree': 0.5217484941463173, 'colsample_bylevel': 0.8410626809939236, 'gamma': 0.1027937533165808, 'alpha': 6.843970286489696, 'lambda': 4.859703799804753, 'tweedie_variance_power': 1.718589737171781}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:50,018] Trial 40 finished with value: 6614.435684535146 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 206, 'learning_rate': 0.07135522754551793, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.307813757114941, 'colsample_bytree': 0.5791253384995544, 'colsample_bylevel': 0.9976702977108884, 'gamma': 8.15129580868164, 'alpha': 8.653952073239697, 'lambda': 5.838636922372097, 'tweedie_variance_power': 1.6171169545006034}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:21:56,218] Trial 41 finished with value: 6613.969728020127 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 209, 'learning_rate': 0.06978621185247895, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.30956961485363377, 'colsample_bytree': 0.580905261302932, 'colsample_bylevel': 0.9679441567590937, 'gamma': 8.253264802066807, 'alpha': 8.445293064226549, 'lambda': 5.888787075468495, 'tweedie_variance_power': 1.6161282483772814}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:22:01,829] Trial 42 finished with value: 6613.915632693939 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 187, 'learning_rate': 0.07255388301608567, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.2971513644154928, 'colsample_bytree': 0.5931344846393416, 'colsample_bylevel': 0.9958730723095893, 'gamma': 8.12872498543771, 'alpha': 8.68002640673402, 'lambda': 5.779027717965564, 'tweedie_variance_power': 1.6135374677627516}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:22:07,494] Trial 43 finished with value: 6616.648818217481 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 189, 'learning_rate': 0.15805811480935056, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.29641700974563845, 'colsample_bytree': 0.5571122170526, 'colsample_bylevel': 0.9980445404830363, 'gamma': 8.144332742375122, 'alpha': 9.957262951943848, 'lambda': 5.76918442418022, 'tweedie_variance_power': 1.6226018243058076}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:22:13,722] Trial 44 finished with value: 6615.988382744411 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 204, 'learning_rate': 0.06401531827772672, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.2201923267967363, 'colsample_bytree': 0.4916217771895718, 'colsample_bylevel': 0.9304432612588187, 'gamma': 9.300523911630576, 'alpha': 8.300007696748851, 'lambda': 2.355906599359759, 'tweedie_variance_power': 1.604550430830386}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:22:19,183] Trial 45 finished with value: 6619.8748054458865 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 167, 'learning_rate': 0.20991212222336714, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.334262496194546, 'colsample_bytree': 0.5930960298820849, 'colsample_bylevel': 0.935522607695293, 'gamma': 7.89678772467928, 'alpha': 8.247265853181304, 'lambda': 3.7464607801214016, 'tweedie_variance_power': 1.663618475458577}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:22:24,895] Trial 46 finished with value: 6614.757981069135 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 140, 'learning_rate': 0.06269120525939273, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.2803978777547215, 'colsample_bytree': 0.6434743889036704, 'colsample_bylevel': 0.8589272759313415, 'gamma': 8.760482158964436, 'alpha': 7.434676188961573, 'lambda': 4.792175322826717, 'tweedie_variance_power': 1.7020512284745977}. Best is trial 29 with value: 6613.521217462371.

[I 2026-08-31 09:22:30,788] Trial 47 finished with value: 6613.231159155801 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 215, 'learning_rate': 0.16989455937569808, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.3913704943113349, 'colsample_bytree': 0.41404229055055275, 'colsample_bylevel': 0.8937379949020605, 'gamma': 8.392865797631526, 'alpha': 8.906578362244055, 'lambda': 3.104509340847616, 'tweedie_variance_power': 1.795469528145628}. Best is trial 47 with value: 6613.231159155801.

[I 2026-08-31 09:22:37,690] Trial 48 finished with value: 675767.1791972956 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 237, 'learning_rate': 0.5972623284925261, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.4257561074495261, 'colsample_bytree': 0.29545565620141584, 'colsample_bylevel': 0.8924560620800543, 'gamma': 8.500703359631501, 'alpha': 8.842143960442158, 'lambda': 3.0275173449767254, 'tweedie_variance_power': 1.799987850374734}. Best is trial 47 with value: 6613.231159155801.

[I 2026-08-31 09:22:45,518] Trial 49 finished with value: 16780.672784502243 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 267, 'learning_rate': 0.38150013432556, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.3950243936292385, 'colsample_bytree': 0.40693761009143503, 'colsample_bylevel': 0.7699938210243377, 'gamma': 9.262684650544253, 'alpha': 6.663140052250579, 'lambda': 2.203645199024452, 'tweedie_variance_power': 1.9022074690749555}. Best is trial 47 with value: 6613.231159155801.

[I 2026-08-31 09:22:53,424] Trial 50 finished with value: 6626.407712309688 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 180, 'learning_rate': 0.22171990297537786, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.48510805360508347, 'colsample_bytree': 0.5266838572536305, 'colsample_bylevel': 0.9593190516075437, 'gamma': 7.8560797669023765, 'alpha': 7.747785785338984, 'lambda': 1.268286594564842, 'tweedie_variance_power': 1.722254589159706}. Best is trial 47 with value: 6613.231159155801.

[I 2026-08-31 09:23:00,720] Trial 51 finished with value: 6619.235338204506 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 214, 'learning_rate': 0.17064391718201383, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.3066251833843894, 'colsample_bytree': 0.49032198093098445, 'colsample_bylevel': 0.9983878477742836, 'gamma': 8.337304105831555, 'alpha': 8.952759957371088, 'lambda': 6.9504008649454, 'tweedie_variance_power': 1.6409617594176888}. Best is trial 47 with value: 6613.231159155801.

[I 2026-08-31 09:23:07,589] Trial 52 finished with value: 6612.228842773278 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 117, 'learning_rate': 0.12649085500761087, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.25058694468060944, 'colsample_bytree': 0.5813607258724345, 'colsample_bylevel': 0.8891421788278686, 'gamma': 9.778701560774575, 'alpha': 9.994528499438175, 'lambda': 3.938270613690259, 'tweedie_variance_power': 1.5823614782370155}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:13,953] Trial 53 finished with value: 6617.486271131473 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 108, 'learning_rate': 0.10883789467325661, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.25683975686645943, 'colsample_bytree': 0.42470153927276755, 'colsample_bylevel': 0.8752308423427116, 'gamma': 9.808956152358345, 'alpha': 9.92381040703994, 'lambda': 4.0694020649796485, 'tweedie_variance_power': 1.566493815243227}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:19,788] Trial 54 finished with value: 6614.36888278533 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 145, 'learning_rate': 0.04500900655833875, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.35868177340138063, 'colsample_bytree': 0.319118615922683, 'colsample_bylevel': 0.7861950711516779, 'gamma': 9.558495389520942, 'alpha': 9.466038690770674, 'lambda': 4.373420429213496, 'tweedie_variance_power': 1.688346657179093}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:25,646] Trial 55 finished with value: 2.8309243687470023e+28 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 164, 'learning_rate': 0.9986876022178239, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.24512047534923026, 'colsample_bytree': 0.3725323248904878, 'colsample_bylevel': 0.9119851934883982, 'gamma': 9.384412417975026, 'alpha': 9.206492896748372, 'lambda': 2.863578578495698, 'tweedie_variance_power': 1.7937852074602927}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:30,911] Trial 56 finished with value: 6614.743099419967 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 130, 'learning_rate': 0.13733549693622296, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4606630434028852, 'colsample_bytree': 0.6149551916747503, 'colsample_bylevel': 0.9442491379894187, 'gamma': 7.51505330618487, 'alpha': 8.059808236008314, 'lambda': 3.298431406144589, 'tweedie_variance_power': 1.5843564106291679}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:36,525] Trial 57 finished with value: 6619.157744593601 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 182, 'learning_rate': 0.17713353057336434, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.2034655435742034, 'colsample_bytree': 0.6624099349469205, 'colsample_bylevel': 0.6812966320279026, 'gamma': 9.981310765067644, 'alpha': 7.2499523575585085, 'lambda': 2.55643128403033, 'tweedie_variance_power': 1.5373279307814085}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:43,283] Trial 58 finished with value: 6640.756073540169 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 258, 'learning_rate': 0.25445771952510193, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.3836706466198087, 'colsample_bytree': 0.49099863704231617, 'colsample_bylevel': 0.969934286257089, 'gamma': 8.845579682047077, 'alpha': 7.81074305436617, 'lambda': 1.8264824831542592, 'tweedie_variance_power': 1.655998828956216}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:49,367] Trial 59 finished with value: 6614.031990860446 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 232, 'learning_rate': 0.04314683803192215, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.3365948095719977, 'colsample_bytree': 0.526768337643706, 'colsample_bylevel': 0.8113811754962043, 'gamma': 9.182825421160947, 'alpha': 9.523544583880287, 'lambda': 3.8550814293035085, 'tweedie_variance_power': 1.4931549715922663}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:23:57,197] Trial 60 finished with value: 6977.054194595703 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 118, 'learning_rate': 0.10806079092988319, 'max_depth': 10, 'min_child_weight': 12, 'subsample': 0.26416000388697647, 'colsample_bytree': 0.26568437922301946, 'colsample_bylevel': 0.8998740212838321, 'gamma': 8.515978981960638, 'alpha': 6.378391612798747, 'lambda': 4.6014072568801145, 'tweedie_variance_power': 1.7856775975955521}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:03,173] Trial 61 finished with value: 6614.122650513854 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 227, 'learning_rate': 0.03578585915471375, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.3240501098779924, 'colsample_bytree': 0.5285045369596846, 'colsample_bylevel': 0.8147614906535854, 'gamma': 9.20735009119341, 'alpha': 9.128023376421261, 'lambda': 3.851713305519888, 'tweedie_variance_power': 1.4889279243658238}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:09,419] Trial 62 finished with value: 6613.583944870252 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 250, 'learning_rate': 0.034257787174315595, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.3373523184118609, 'colsample_bytree': 0.5913029394698279, 'colsample_bylevel': 0.9685680293992699, 'gamma': 9.112436235737588, 'alpha': 9.78372540085052, 'lambda': 5.092033590843123, 'tweedie_variance_power': 1.4499718828690467}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:16,627] Trial 63 finished with value: 6620.550751460857 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 281, 'learning_rate': 0.11447489122302314, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.4191634368887189, 'colsample_bytree': 0.5920544248787476, 'colsample_bylevel': 0.9527847728368739, 'gamma': 7.740077709292949, 'alpha': 9.766270955808361, 'lambda': 5.513840035740863, 'tweedie_variance_power': 1.4334801442974179}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:22,927] Trial 64 finished with value: 6629.50884292578 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 250, 'learning_rate': 0.1505172148643286, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.28162456473001296, 'colsample_bytree': 0.6262806334177042, 'colsample_bylevel': 0.9722590125448279, 'gamma': 6.723009379735553, 'alpha': 8.564200539767507, 'lambda': 5.235388836797457, 'tweedie_variance_power': 1.8640403479608056}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:29,904] Trial 65 finished with value: 6614.597276449975 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 327, 'learning_rate': 0.015152646984676471, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.3455900652283249, 'colsample_bytree': 0.5498012135617916, 'colsample_bylevel': 0.8824980524378412, 'gamma': 8.852201117244965, 'alpha': 8.778661942612738, 'lambda': 4.920813216118352, 'tweedie_variance_power': 1.7382122098860184}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:35,987] Trial 66 finished with value: 6625.187343283402 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 156, 'learning_rate': 0.19479857233678322, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.38035406966657065, 'colsample_bytree': 0.6786432359127256, 'colsample_bylevel': 0.8492068318999337, 'gamma': 9.655959358796647, 'alpha': 9.639885601044785, 'lambda': 4.27599472438854, 'tweedie_variance_power': 1.4144604750097007}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:45,690] Trial 67 finished with value: 6675.247726773787 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 302, 'learning_rate': 0.23909033497894305, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.4506611381063911, 'colsample_bytree': 0.5773362811600584, 'colsample_bylevel': 0.9748650088531705, 'gamma': 8.17824713154844, 'alpha': 9.150402758804079, 'lambda': 3.2183220463198663, 'tweedie_variance_power': 1.3269348774976757}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:24:52,598] Trial 68 finished with value: 6614.282092448552 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 197, 'learning_rate': 0.045061220547140984, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.20005873013848796, 'colsample_bytree': 0.6443015660319951, 'colsample_bylevel': 0.9123041864591765, 'gamma': 8.56479035415509, 'alpha': 5.513976115132605, 'lambda': 7.42052401589888, 'tweedie_variance_power': 1.5157451003128914}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:01,208] Trial 69 finished with value: 6616.686964640553 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 279, 'learning_rate': 0.0017712321843662143, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.5615357739730611, 'colsample_bytree': 0.45226768008544066, 'colsample_bylevel': 0.7349298176581239, 'gamma': 8.992008689882095, 'alpha': 8.005716925202556, 'lambda': 3.5843138344433805, 'tweedie_variance_power': 1.25179058924599}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:08,821] Trial 70 finished with value: 6614.943069825104 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 247, 'learning_rate': 0.10282193235398102, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5177640862461907, 'colsample_bytree': 0.4774920822129016, 'colsample_bylevel': 0.9442922683804148, 'gamma': 7.5771182851749685, 'alpha': 7.008239114581845, 'lambda': 6.633534597977523, 'tweedie_variance_power': 1.587591713111158}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:16,459] Trial 71 finished with value: 6613.794920748434 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 224, 'learning_rate': 0.05196355186657117, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.3272541073226431, 'colsample_bytree': 0.5446004564986251, 'colsample_bylevel': 0.8190875361211046, 'gamma': 9.094602032419225, 'alpha': 9.479673938261238, 'lambda': 4.048283908922464, 'tweedie_variance_power': 1.4764166718534089}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:23,864] Trial 72 finished with value: 6614.916428375044 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 218, 'learning_rate': 0.08809544523467913, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.31067530821848716, 'colsample_bytree': 0.6073899151658728, 'colsample_bylevel': 0.867992367727807, 'gamma': 9.467261463620735, 'alpha': 9.294552867752984, 'lambda': 5.22938991618726, 'tweedie_variance_power': 1.4579190111007059}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:31,865] Trial 73 finished with value: 6620.062629897126 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 298, 'learning_rate': 0.13663958350129654, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.23953143304119734, 'colsample_bytree': 0.5614754234939747, 'colsample_bylevel': 0.9807765739603248, 'gamma': 9.721277096280707, 'alpha': 9.800881087684088, 'lambda': 4.187723094705931, 'tweedie_variance_power': 1.4063759549322863}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:38,499] Trial 74 finished with value: 6614.762224527509 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 173, 'learning_rate': 0.04689069111087729, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.2748694363604556, 'colsample_bytree': 0.6310470612260802, 'colsample_bylevel': 0.9057142007667248, 'gamma': 8.48469110786761, 'alpha': 8.980123835931165, 'lambda': 4.612777541077196, 'tweedie_variance_power': 1.8224903036858335}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:49,766] Trial 75 finished with value: 6623.141504278473 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 189, 'learning_rate': 0.08251241696285525, 'max_depth': 9, 'min_child_weight': 11, 'subsample': 0.35599419442747915, 'colsample_bytree': 0.5432136905070482, 'colsample_bylevel': 0.9254919285857776, 'gamma': 7.924417445070869, 'alpha': 8.421884075283478, 'lambda': 5.9314383955601935, 'tweedie_variance_power': 1.5508005979174364}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:25:56,417] Trial 76 finished with value: 6622.821270938829 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 247, 'learning_rate': 0.19476679105019812, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.39779066225872795, 'colsample_bytree': 0.5047311807775319, 'colsample_bylevel': 0.6195166715297804, 'gamma': 9.104574611171094, 'alpha': 9.996298238442284, 'lambda': 2.6752816418150225, 'tweedie_variance_power': 1.6865967398004957}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:02,858] Trial 77 finished with value: 6615.738187167286 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 220, 'learning_rate': 0.12702403391705724, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.2932821383025061, 'colsample_bytree': 0.5859965739427387, 'colsample_bylevel': 0.833123539992983, 'gamma': 8.206937827342001, 'alpha': 3.5375879944418482, 'lambda': 5.525470396132911, 'tweedie_variance_power': 1.6034551109828625}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:12,111] Trial 78 finished with value: 4483748063.808523 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 273, 'learning_rate': 0.16319849065394892, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.4406184905662992, 'colsample_bytree': 0.6644780611285753, 'colsample_bylevel': 0.9562680310219027, 'gamma': 7.175928398239716, 'alpha': 8.719040990029788, 'lambda': 5.0831880882844604, 'tweedie_variance_power': 1.9524599965150784}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:19,753] Trial 79 finished with value: 6614.1652612999005 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 256, 'learning_rate': 0.02667318090198624, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.4768256213157147, 'colsample_bytree': 0.6090418719205604, 'colsample_bylevel': 0.8886082732075345, 'gamma': 2.474112102708025, 'alpha': 9.567523412511786, 'lambda': 3.4827711574119147, 'tweedie_variance_power': 1.4744898283155408}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:32,764] Trial 80 finished with value: 6618.220690314795 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 600, 'learning_rate': 0.06645854131455296, 'max_depth': 3, 'min_child_weight': 12, 'subsample': 0.3165087269666269, 'colsample_bytree': 0.5085673084497626, 'colsample_bylevel': 0.9849302355362466, 'gamma': 9.987020082333865, 'alpha': 9.28178683377582, 'lambda': 3.1183546507479103, 'tweedie_variance_power': 1.5078088624231423}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:39,847] Trial 81 finished with value: 6613.850199011789 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 228, 'learning_rate': 0.049066724297333233, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.33598661022611925, 'colsample_bytree': 0.5337575165184408, 'colsample_bylevel': 0.8048736552726142, 'gamma': 8.967826342821558, 'alpha': 9.56081911459945, 'lambda': 3.867167407932312, 'tweedie_variance_power': 1.4909524653822945}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:47,536] Trial 82 finished with value: 6617.331066201538 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 239, 'learning_rate': 0.001308896933295875, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.3588119468392448, 'colsample_bytree': 0.5695507296039812, 'colsample_bylevel': 0.7812218176948631, 'gamma': 8.682552177842727, 'alpha': 9.691087908359954, 'lambda': 3.9056573550521856, 'tweedie_variance_power': 1.3488791040942327}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:26:55,004] Trial 83 finished with value: 6613.377878406269 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 208, 'learning_rate': 0.08572282472362516, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.3375302002504021, 'colsample_bytree': 0.5452276186653625, 'colsample_bylevel': 0.751589961413628, 'gamma': 9.013976566349283, 'alpha': 8.94377444942946, 'lambda': 4.728782457613293, 'tweedie_variance_power': 1.4120774174206772}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:02,615] Trial 84 finished with value: 6616.536336852586 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 190, 'learning_rate': 0.0964348628203335, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.3367905515774823, 'colsample_bytree': 0.541678902400825, 'colsample_bylevel': 0.6992214773329974, 'gamma': 9.006045312705007, 'alpha': 8.854722713874047, 'lambda': 4.420018042764309, 'tweedie_variance_power': 1.3920627335545985}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:08,530] Trial 85 finished with value: 6613.972722983894 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 126, 'learning_rate': 0.12220796484677536, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.4121942548250903, 'colsample_bytree': 0.46932228761174877, 'colsample_bylevel': 0.7412590508085495, 'gamma': 9.39157910713198, 'alpha': 4.64773632963319, 'lambda': 4.028975492592921, 'tweedie_variance_power': 1.425794386156884}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:14,304] Trial 86 finished with value: 6614.3772154119715 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 151, 'learning_rate': 0.05556302543442559, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.3768869573040284, 'colsample_bytree': 0.5969847175036872, 'colsample_bylevel': 0.7973529176163183, 'gamma': 4.6375527051818946, 'alpha': 9.426247263217519, 'lambda': 4.724977701091755, 'tweedie_variance_power': 1.4517635304584078}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:21,091] Trial 87 finished with value: 6616.5203808772985 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 231, 'learning_rate': 0.02843487056191573, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.26214073550417627, 'colsample_bytree': 0.4425835998859278, 'colsample_bylevel': 0.20547673408676242, 'gamma': 9.688470017185274, 'alpha': 5.955571015926536, 'lambda': 3.655214182891632, 'tweedie_variance_power': 1.8853602924217276}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:27,593] Trial 88 finished with value: 6618.811282693737 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 314, 'learning_rate': 0.1522847011210136, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.34608459786837953, 'colsample_bytree': 0.5621662086449417, 'colsample_bylevel': 0.7686723672254626, 'gamma': 9.095882249745081, 'alpha': 9.010553997302946, 'lambda': 5.003189773925246, 'tweedie_variance_power': 1.5329222577229917}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:32,594] Trial 89 finished with value: 6614.3087413155345 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 100, 'learning_rate': 0.09416565496785127, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.28802207720088346, 'colsample_bytree': 0.5053055945251849, 'colsample_bylevel': 0.8241067845015845, 'gamma': 1.251502996334052, 'alpha': 8.13901206042503, 'lambda': 4.311526683089382, 'tweedie_variance_power': 1.4722712301168746}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:38,806] Trial 90 finished with value: 1301670.3711671114 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 199, 'learning_rate': 0.7039486784011628, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.2191002936268865, 'colsample_bytree': 0.7037915726662519, 'colsample_bylevel': 0.8609434554218531, 'gamma': 8.566960967612484, 'alpha': 5.110004725431321, 'lambda': 2.9102373027259576, 'tweedie_variance_power': 1.3606913280609314}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:44,710] Trial 91 finished with value: 6613.911934405582 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 215, 'learning_rate': 0.06986129217659023, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.32301532614682443, 'colsample_bytree': 0.37907850774643215, 'colsample_bylevel': 0.9358238139850877, 'gamma': 8.324912750595885, 'alpha': 8.600372197401612, 'lambda': 5.773404693748861, 'tweedie_variance_power': 1.6374228893743104}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:50,695] Trial 92 finished with value: 6613.667547294904 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 216, 'learning_rate': 0.07606856461145026, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.3273503846952301, 'colsample_bytree': 0.36340976633884936, 'colsample_bylevel': 0.9339051406230574, 'gamma': 7.929072928495698, 'alpha': 7.85565908710273, 'lambda': 5.397181444861549, 'tweedie_variance_power': 1.7784350081971474}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:27:57,162] Trial 93 finished with value: 6629.852297768733 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 291, 'learning_rate': 0.1857640524183904, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.32465810300128745, 'colsample_bytree': 0.36832118425183163, 'colsample_bylevel': 0.8439000555263326, 'gamma': 5.989275192894644, 'alpha': 7.7875474251331855, 'lambda': 5.383008591556957, 'tweedie_variance_power': 1.8297423259274899}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:03,171] Trial 94 finished with value: 6614.564853667415 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 215, 'learning_rate': 0.028682495221578924, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.40084087198652346, 'colsample_bytree': 0.3888967200511052, 'colsample_bylevel': 0.925737740085346, 'gamma': 8.680137583523807, 'alpha': 9.316366048489996, 'lambda': 3.3740387358922153, 'tweedie_variance_power': 1.7779652688312768}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:10,851] Trial 95 finished with value: 6613.722383944066 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 263, 'learning_rate': 0.12034933721486588, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.3717532939063985, 'colsample_bytree': 0.3290098446269463, 'colsample_bylevel': 0.8793520263958048, 'gamma': 9.449387822575062, 'alpha': 7.537556148440834, 'lambda': 4.614959807985941, 'tweedie_variance_power': 1.7336587649393476}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:18,892] Trial 96 finished with value: 6614.251470658572 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 265, 'learning_rate': 0.11964598170034735, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.370032146281876, 'colsample_bytree': 0.34399019538440656, 'colsample_bylevel': 0.8800583878776771, 'gamma': 9.469478627958136, 'alpha': 7.507254075461177, 'lambda': 4.506543557880709, 'tweedie_variance_power': 1.8050405612622085}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:27,152] Trial 97 finished with value: 6619.475167714715 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 275, 'learning_rate': 0.14062233414385694, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.4303025506885554, 'colsample_bytree': 0.25434187492176874, 'colsample_bylevel': 0.7522970039399125, 'gamma': 9.282495406724527, 'alpha': 7.165238118756462, 'lambda': 4.12799732900918, 'tweedie_variance_power': 1.7399744360010843}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:35,536] Trial 98 finished with value: 7152.70406343268 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 344, 'learning_rate': 0.30021124967394774, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.24617498648822161, 'colsample_bytree': 0.3095095055725333, 'colsample_bylevel': 0.854443684048107, 'gamma': 9.765053213746974, 'alpha': 7.326037685800404, 'lambda': 4.841836804605524, 'tweedie_variance_power': 1.764903884864184}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:43,098] Trial 99 finished with value: 6628.173006545906 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 257, 'learning_rate': 0.22104135863595264, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.38651778229015904, 'colsample_bytree': 0.33427342729191845, 'colsample_bylevel': 0.8014556656346083, 'gamma': 8.921370462246626, 'alpha': 6.513526468704053, 'lambda': 4.594285063045586, 'tweedie_variance_power': 1.848313675112929}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:52,464] Trial 100 finished with value: 6629.655673549906 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 358, 'learning_rate': 0.16547481073164977, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.3472660325898939, 'colsample_bytree': 0.27683724952262945, 'colsample_bylevel': 0.7016831870248519, 'gamma': 9.502767759794555, 'alpha': 9.792251460474493, 'lambda': 3.707112323042, 'tweedie_variance_power': 1.3924014946431391}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:28:59,601] Trial 101 finished with value: 6612.8475905491205 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 237, 'learning_rate': 0.08179560245618145, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.3286373540132031, 'colsample_bytree': 0.39617784458871746, 'colsample_bylevel': 0.906124716935576, 'gamma': 8.35983975634843, 'alpha': 8.29770881185532, 'lambda': 5.638933138847207, 'tweedie_variance_power': 1.732083440311132}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:06,559] Trial 102 finished with value: 6614.245886062813 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 235, 'learning_rate': 0.10126099471477445, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.3668380655837133, 'colsample_bytree': 0.43572691387014645, 'colsample_bylevel': 0.9073298446501046, 'gamma': 8.759296957525905, 'alpha': 7.922157412984429, 'lambda': 5.189915501975656, 'tweedie_variance_power': 1.7307566303085595}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:13,680] Trial 103 finished with value: 6613.546209216456 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 326, 'learning_rate': 0.05403379903552611, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.2668015388884424, 'colsample_bytree': 0.4288667939959665, 'colsample_bylevel': 0.8964206847669417, 'gamma': 9.120445692999567, 'alpha': 7.5776345001264005, 'lambda': 5.479259953148638, 'tweedie_variance_power': 1.7034713451763213}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:20,180] Trial 104 finished with value: 6612.861969901877 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 308, 'learning_rate': 0.07889879542407445, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.2715536911298633, 'colsample_bytree': 0.40374275356495454, 'colsample_bylevel': 0.8971496590560629, 'gamma': 8.000711378749894, 'alpha': 7.650003189766391, 'lambda': 5.413178810524764, 'tweedie_variance_power': 1.6955597131709452}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:27,035] Trial 105 finished with value: 6614.043886963622 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 329, 'learning_rate': 0.08846223497097136, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.267390862192188, 'colsample_bytree': 0.42159665112558614, 'colsample_bylevel': 0.8897151840370395, 'gamma': 7.626926158879706, 'alpha': 7.646426698853824, 'lambda': 6.191646426698597, 'tweedie_variance_power': 1.7050043448252645}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:35,211] Trial 106 finished with value: 6623.878639814769 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 331, 'learning_rate': 0.1332550726005238, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.2955435747544652, 'colsample_bytree': 0.35106266233455696, 'colsample_bylevel': 0.9172505181157691, 'gamma': 7.9999056069306995, 'alpha': 7.018699354579493, 'lambda': 5.637683065241654, 'tweedie_variance_power': 1.6780954019764482}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:42,496] Trial 107 finished with value: 6616.697710408336 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 307, 'learning_rate': 0.10827797561035549, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.22305508847944383, 'colsample_bytree': 0.39612609879344807, 'colsample_bylevel': 0.9491410444661245, 'gamma': 8.394467718220197, 'alpha': 8.233855045075785, 'lambda': 5.450725756809781, 'tweedie_variance_power': 1.7553571207204233}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:51,140] Trial 108 finished with value: 6615.911109091253 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 292, 'learning_rate': 0.021220589077036695, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.23775515135108027, 'colsample_bytree': 0.41032889795016353, 'colsample_bylevel': 0.4544362081560704, 'gamma': 7.362915128851085, 'alpha': 7.511727505162266, 'lambda': 6.633050387245362, 'tweedie_variance_power': 1.715089777567332}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:29:58,777] Trial 109 finished with value: 6617.419048355332 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 285, 'learning_rate': 0.15324087489300026, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.27292023493204787, 'colsample_bytree': 0.38742558788129156, 'colsample_bylevel': 0.5277448462213092, 'gamma': 7.782400289391296, 'alpha': 7.919151877613479, 'lambda': 6.058254520659, 'tweedie_variance_power': 1.776517867717157}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:07,324] Trial 110 finished with value: 6614.157507866778 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 376, 'learning_rate': 0.08067090685427006, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.30809192326446333, 'colsample_bytree': 0.35997793058940375, 'colsample_bylevel': 0.8721815130382585, 'gamma': 5.345503162195264, 'alpha': 7.306687692118755, 'lambda': 5.006611539273154, 'tweedie_variance_power': 1.7439055579251548}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:16,513] Trial 111 finished with value: 6614.035880986664 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 402, 'learning_rate': 0.05869581638351334, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.2489252589289498, 'colsample_bytree': 0.2979648346431867, 'colsample_bylevel': 0.9030505080279014, 'gamma': 9.12721430592852, 'alpha': 6.827638888859012, 'lambda': 5.324721344527823, 'tweedie_variance_power': 1.7969853919866212}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:24,745] Trial 112 finished with value: 6614.862482582461 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 319, 'learning_rate': 0.04427768121467364, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.9258513937065889, 'colsample_bytree': 0.42917293665168643, 'colsample_bylevel': 0.8371190421709185, 'gamma': 3.2769484303878555, 'alpha': 8.348141052737475, 'lambda': 4.859202023883648, 'tweedie_variance_power': 1.70123067446973}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:32,401] Trial 113 finished with value: 6614.454500289947 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 250, 'learning_rate': 0.08321729782772179, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.6873348443960393, 'colsample_bytree': 0.3320780317034577, 'colsample_bylevel': 0.9409514352684849, 'gamma': 8.712920849721126, 'alpha': 9.046529960909556, 'lambda': 5.619412367643483, 'tweedie_variance_power': 1.80783315921974}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:40,182] Trial 114 finished with value: 6615.225826123032 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 269, 'learning_rate': 0.1240909839278798, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.7810905794537071, 'colsample_bytree': 0.4756518414332362, 'colsample_bylevel': 0.8946923633433073, 'gamma': 6.999741126930447, 'alpha': 6.192509661572183, 'lambda': 4.751157459515884, 'tweedie_variance_power': 1.6541326267146685}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:48,097] Trial 115 finished with value: 101960044.0912181 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 306, 'learning_rate': 0.8654067605453757, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.6028117827048289, 'colsample_bytree': 0.3984454101389452, 'colsample_bylevel': 0.5756290086687348, 'gamma': 9.369515124764643, 'alpha': 7.66303549197516, 'lambda': 4.340476335174244, 'tweedie_variance_power': 1.8314326401502745}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:30:54,401] Trial 116 finished with value: 6616.914431971113 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 244, 'learning_rate': 0.1827096249447001, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.30299611742530763, 'colsample_bytree': 0.44608452187111386, 'colsample_bylevel': 0.8635082497354626, 'gamma': 9.861634197933828, 'alpha': 8.508365112927871, 'lambda': 5.1129829215257425, 'tweedie_variance_power': 1.724368161018591}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:01,126] Trial 117 finished with value: 6614.226108475013 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 335, 'learning_rate': 0.023125395839476297, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.28877575773378017, 'colsample_bytree': 0.2250841532855437, 'colsample_bylevel': 0.9652270498301826, 'gamma': 8.063724993262571, 'alpha': 8.123573674929682, 'lambda': 4.048825377807505, 'tweedie_variance_power': 1.761121129147471}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:08,080] Trial 118 finished with value: 6612.94393629276 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 354, 'learning_rate': 0.05965402146419825, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.3194090767799132, 'colsample_bytree': 0.4130443397453914, 'colsample_bylevel': 0.9252336500476449, 'gamma': 9.554697408936972, 'alpha': 8.848083529642603, 'lambda': 4.543731101331414, 'tweedie_variance_power': 1.6708933591208344}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:16,567] Trial 119 finished with value: 6617.448413301888 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 347, 'learning_rate': 0.00040600807947375334, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.3557293052634797, 'colsample_bytree': 0.4197244649550353, 'colsample_bylevel': 0.986929297564881, 'gamma': 9.210987108180976, 'alpha': 6.882587324337812, 'lambda': 4.572431084809661, 'tweedie_variance_power': 1.673655873665717}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:24,932] Trial 120 finished with value: 6612.230520072797 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 365, 'learning_rate': 0.06984631318888394, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.39209650922242173, 'colsample_bytree': 0.3613852523025228, 'colsample_bylevel': 0.9216963025835146, 'gamma': 9.606241429248044, 'alpha': 7.906888131385783, 'lambda': 5.175618295842006, 'tweedie_variance_power': 1.7883605924921013}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:33,690] Trial 121 finished with value: 6613.61910316502 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 386, 'learning_rate': 0.06963282245898954, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.40500853060220887, 'colsample_bytree': 0.3512428729921669, 'colsample_bylevel': 0.9225348752480951, 'gamma': 9.54113173428474, 'alpha': 7.9668373767358815, 'lambda': 5.349226871334538, 'tweedie_variance_power': 1.7830274860457296}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:42,429] Trial 122 finished with value: 6613.4504100748045 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 358, 'learning_rate': 0.09811673296074169, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.3966318664108838, 'colsample_bytree': 0.37426594647279443, 'colsample_bylevel': 0.930724264252985, 'gamma': 9.652116221006494, 'alpha': 8.303280762090886, 'lambda': 5.699258025426113, 'tweedie_variance_power': 1.7796741648417447}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:50,915] Trial 123 finished with value: 6615.846793638505 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 357, 'learning_rate': 0.10421336839309134, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4108185263484795, 'colsample_bytree': 0.3777761407256611, 'colsample_bylevel': 0.9585434218063991, 'gamma': 9.660963503259316, 'alpha': 8.733969070768422, 'lambda': 5.648169251559023, 'tweedie_variance_power': 1.8640569827457412}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:31:59,586] Trial 124 finished with value: 6612.619247985196 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 390, 'learning_rate': 0.06087457905752745, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.3898794713364516, 'colsample_bytree': 0.41187892769639606, 'colsample_bylevel': 0.9185546432528242, 'gamma': 9.81697822191629, 'alpha': 4.083898419811625, 'lambda': 5.963424565738528, 'tweedie_variance_power': 1.7945753062208334}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:32:08,456] Trial 125 finished with value: 6613.7562854285125 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 367, 'learning_rate': 0.040763181394900386, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.4321743051265294, 'colsample_bytree': 0.40421125708737016, 'colsample_bylevel': 0.9133749230010905, 'gamma': 9.996264540966376, 'alpha': 4.029941310538694, 'lambda': 6.008664587759793, 'tweedie_variance_power': 1.6987113678014232}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:32:17,052] Trial 126 finished with value: 6613.249932076922 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 393, 'learning_rate': 0.05728076384331508, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4544168701781147, 'colsample_bytree': 0.4609071863608804, 'colsample_bylevel': 0.9517000232491567, 'gamma': 9.870326016708708, 'alpha': 3.609932280590124, 'lambda': 6.299442353148907, 'tweedie_variance_power': 1.8149559044498362}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:32:25,539] Trial 127 finished with value: 6614.1296217302615 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 402, 'learning_rate': 0.09700897744639732, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.446110333173684, 'colsample_bytree': 0.46007779429138923, 'colsample_bylevel': 0.41690370676393074, 'gamma': 9.778113458788727, 'alpha': 3.1562260626868373, 'lambda': 6.473923369677563, 'tweedie_variance_power': 1.8201025077050754}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:32:35,053] Trial 128 finished with value: 6631.72088072503 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 429, 'learning_rate': 0.14298925418004801, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.47001863678537675, 'colsample_bytree': 0.4336453107520364, 'colsample_bylevel': 0.9446052792713148, 'gamma': 9.840605018915237, 'alpha': 4.294910181649963, 'lambda': 7.214143245208003, 'tweedie_variance_power': 1.7941828590359954}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:32:43,442] Trial 129 finished with value: 6616.1118675391135 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 401, 'learning_rate': 0.06133766477160422, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5138534068631613, 'colsample_bytree': 0.45302562313020117, 'colsample_bylevel': 0.9034385567540909, 'gamma': 3.703625047237468, 'alpha': 3.548413801444912, 'lambda': 6.268538891886574, 'tweedie_variance_power': 1.2081193159231751}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:32:51,948] Trial 130 finished with value: 6630.515358852127 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 361, 'learning_rate': 0.16096527684657047, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.40035415710883276, 'colsample_bytree': 0.4098418388556358, 'colsample_bylevel': 0.6326729150708268, 'gamma': 9.32349219738845, 'alpha': 3.687675531000863, 'lambda': 5.797483037957762, 'tweedie_variance_power': 1.2912829644307675}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:33:00,672] Trial 131 finished with value: 6614.083751424963 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 375, 'learning_rate': 0.03261543828155799, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.3875339912932918, 'colsample_bytree': 0.38481751232537975, 'colsample_bylevel': 0.9769116755926047, 'gamma': 8.926021190822425, 'alpha': 3.9496228292527578, 'lambda': 6.772312378115292, 'tweedie_variance_power': 1.7506508719883842}. Best is trial 52 with value: 6612.228842773278.

[I 2026-08-31 09:33:08,970] Trial 132 finished with value: 6612.083999344832 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 412, 'learning_rate': 0.05630959786596994, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.34665701278520633, 'colsample_bytree': 0.624878967498229, 'colsample_bylevel': 0.9628944133173251, 'gamma': 9.59301177833398, 'alpha': 4.559837742575986, 'lambda': 6.299178816313253, 'tweedie_variance_power': 1.8445625708851354}. Best is trial 132 with value: 6612.083999344832.

[I 2026-08-31 09:33:17,241] Trial 133 finished with value: 6613.070561264551 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 413, 'learning_rate': 0.059381563873782704, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.4202057547701536, 'colsample_bytree': 0.622956871036712, 'colsample_bylevel': 0.9317615622757941, 'gamma': 9.625967859025119, 'alpha': 4.707793644698915, 'lambda': 5.852025858774356, 'tweedie_variance_power': 1.85155718298554}. Best is trial 132 with value: 6612.083999344832.

[I 2026-08-31 09:33:26,222] Trial 134 finished with value: 6611.054220867645 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 452, 'learning_rate': 0.09076061074489432, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.42002879229206774, 'colsample_bytree': 0.6401168693294862, 'colsample_bylevel': 0.9291125490144647, 'gamma': 9.610832349664369, 'alpha': 4.60847912941864, 'lambda': 6.423622824193021, 'tweedie_variance_power': 1.8499302517679364}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:33:35,132] Trial 135 finished with value: 6612.610203718107 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 444, 'learning_rate': 0.08813186031512756, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.48520552582694704, 'colsample_bytree': 0.6419816106273585, 'colsample_bylevel': 0.9306626278998686, 'gamma': 9.665651972486645, 'alpha': 4.657397676643903, 'lambda': 6.252345531917602, 'tweedie_variance_power': 1.883607652304755}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:33:44,143] Trial 136 finished with value: 6616.7377529782925 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 446, 'learning_rate': 0.11086015844613561, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.4521296085392892, 'colsample_bytree': 0.6526893081381072, 'colsample_bylevel': 0.9316129344855723, 'gamma': 9.681679153971139, 'alpha': 4.763196679442379, 'lambda': 6.3660445400461185, 'tweedie_variance_power': 1.8866707551382367}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:33:53,797] Trial 137 finished with value: 6624.460226235485 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 445, 'learning_rate': 0.08338435502922317, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4680474018932591, 'colsample_bytree': 0.6786057906438946, 'colsample_bylevel': 0.9584092622622359, 'gamma': 9.97158048804472, 'alpha': 4.438090017219006, 'lambda': 7.592042399430069, 'tweedie_variance_power': 1.9322974406220192}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:34:02,841] Trial 138 finished with value: 6614.63814273635 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 472, 'learning_rate': 0.018401666995129892, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.4972549734612674, 'colsample_bytree': 0.6318592558748175, 'colsample_bylevel': 0.9196684085927375, 'gamma': 9.496207486106586, 'alpha': 4.908772055295825, 'lambda': 6.577100490139899, 'tweedie_variance_power': 1.8453034842025393}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:34:18,907] Trial 139 finished with value: 1289273949.3528223 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 411, 'learning_rate': 0.12804004806317013, 'max_depth': 8, 'min_child_weight': 15, 'subsample': 0.4902474725659745, 'colsample_bytree': 0.7218632552664729, 'colsample_bylevel': 0.9454415439075401, 'gamma': 9.63533637692375, 'alpha': 4.144162845643596, 'lambda': 6.147094781877663, 'tweedie_variance_power': 1.8724284018018658}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:34:28,313] Trial 140 finished with value: 6625.321411429046 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 418, 'learning_rate': 0.09408457620437578, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.42286673254007084, 'colsample_bytree': 0.687776532927919, 'colsample_bylevel': 0.9264144051965667, 'gamma': 9.776308524081648, 'alpha': 3.890022333705304, 'lambda': 6.908901937345241, 'tweedie_variance_power': 1.852277335018325}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:34:37,296] Trial 141 finished with value: 6617.469469593685 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 456, 'learning_rate': 0.06822941669157193, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.4390629093418144, 'colsample_bytree': 0.6058446471324068, 'colsample_bylevel': 0.8840748122040445, 'gamma': 9.869854568504845, 'alpha': 4.49823226037082, 'lambda': 5.9314620261975, 'tweedie_variance_power': 1.9053294282385045}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:34:46,028] Trial 142 finished with value: 6612.4015129979325 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 392, 'learning_rate': 0.10439148511189308, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.39171720620274025, 'colsample_bytree': 0.6305873253717751, 'colsample_bylevel': 0.9535787451451885, 'gamma': 9.578378791230225, 'alpha': 4.996426996406123, 'lambda': 6.233542365023118, 'tweedie_variance_power': 1.8331630389814717}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:34:54,878] Trial 143 finished with value: 6613.372533582053 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 396, 'learning_rate': 0.11206845015977315, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.38962828655525134, 'colsample_bytree': 0.6222032068717465, 'colsample_bylevel': 0.9665651292888505, 'gamma': 9.576657326066313, 'alpha': 5.4242163039144025, 'lambda': 6.181653867092108, 'tweedie_variance_power': 1.8158234991840851}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:03,426] Trial 144 finished with value: 6616.458815351068 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 389, 'learning_rate': 0.13759480171814234, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.41745949546774364, 'colsample_bytree': 0.647633347003166, 'colsample_bylevel': 0.9560226823269957, 'gamma': 9.286101697100783, 'alpha': 5.392900055115556, 'lambda': 6.304283101653636, 'tweedie_variance_power': 1.8155006708771644}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:12,360] Trial 145 finished with value: 6613.385774826274 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 431, 'learning_rate': 0.05266445177275355, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.3807687851202461, 'colsample_bytree': 0.6229538551084106, 'colsample_bylevel': 0.9726508715868043, 'gamma': 9.403547783492773, 'alpha': 5.089320395760176, 'lambda': 6.87580711343595, 'tweedie_variance_power': 1.8811773853570666}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:22,045] Trial 146 finished with value: 6620.51109524051 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 516, 'learning_rate': 0.1175741637540669, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5363977532312201, 'colsample_bytree': 0.6286030764726689, 'colsample_bylevel': 0.9087381426077044, 'gamma': 9.560953264853879, 'alpha': 4.902116565556192, 'lambda': 6.098359198320728, 'tweedie_variance_power': 1.9075189855746908}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:30,723] Trial 147 finished with value: 6624.333022477507 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 391, 'learning_rate': 0.17458147011560943, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.3563238187877191, 'colsample_bytree': 0.6604400947676428, 'colsample_bylevel': 0.9876564186582804, 'gamma': 9.903805364745164, 'alpha': 3.3618873260439894, 'lambda': 6.746213431353263, 'tweedie_variance_power': 1.833002433236926}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:39,483] Trial 148 finished with value: 6613.152982314054 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 408, 'learning_rate': 0.08165577573366514, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4560940937550843, 'colsample_bytree': 0.6763347149138894, 'colsample_bylevel': 0.9468979137052072, 'gamma': 9.332724430507405, 'alpha': 4.672567639516559, 'lambda': 6.472306494183224, 'tweedie_variance_power': 1.850130290591835}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:48,143] Trial 149 finished with value: 6612.127484851681 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 412, 'learning_rate': 0.0742969655673929, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.45966531101747554, 'colsample_bytree': 0.6759354222498747, 'colsample_bylevel': 0.9522276533870809, 'gamma': 9.292289866326767, 'alpha': 4.596926112003449, 'lambda': 6.517711232880703, 'tweedie_variance_power': 1.8534564140357188}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:35:57,149] Trial 150 finished with value: 6613.641767572115 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 442, 'learning_rate': 0.045734832226540685, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5043878684934814, 'colsample_bytree': 0.7670418585795064, 'colsample_bylevel': 0.9416786526691331, 'gamma': 9.290751847680305, 'alpha': 4.805424531547262, 'lambda': 7.179909513869026, 'tweedie_variance_power': 1.8548247500196224}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:05,761] Trial 151 finished with value: 6612.771158953928 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 406, 'learning_rate': 0.07164863246989923, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4583385954637134, 'colsample_bytree': 0.6747452576642483, 'colsample_bylevel': 0.9622863730969853, 'gamma': 9.558708716511665, 'alpha': 4.6487192876463705, 'lambda': 6.502703039981423, 'tweedie_variance_power': 1.8375560506612298}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:14,437] Trial 152 finished with value: 6615.501652024277 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 412, 'learning_rate': 0.07041791443920466, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4634537890015335, 'colsample_bytree': 0.6955799793005017, 'colsample_bylevel': 0.9159475339503722, 'gamma': 9.98789696216512, 'alpha': 4.329371001476482, 'lambda': 6.521962711486749, 'tweedie_variance_power': 1.9198180816267856}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:22,972] Trial 153 finished with value: 6614.717267620009 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 426, 'learning_rate': 0.015516288350904704, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.4546291089612015, 'colsample_bytree': 0.6644834891086834, 'colsample_bylevel': 0.9497270996298429, 'gamma': 9.749924685804382, 'alpha': 4.1160321244714435, 'lambda': 6.471801746636155, 'tweedie_variance_power': 1.839446060257054}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:31,678] Trial 154 finished with value: 6612.681662964666 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 409, 'learning_rate': 0.08185254520466194, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4752122872920392, 'colsample_bytree': 0.7359354457413221, 'colsample_bylevel': 0.8975150299399413, 'gamma': 9.416379235220711, 'alpha': 4.624690574272654, 'lambda': 6.984636336454699, 'tweedie_variance_power': 1.8719430216517652}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:40,262] Trial 155 finished with value: 6613.733319112472 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 410, 'learning_rate': 0.08298781723251808, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.47573432068656835, 'colsample_bytree': 0.7228361380408367, 'colsample_bylevel': 0.8887357660574431, 'gamma': 9.406156133391944, 'alpha': 4.58720485466407, 'lambda': 7.06006194930198, 'tweedie_variance_power': 1.8727537018484115}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:50,498] Trial 156 finished with value: 212103716598.6646 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 420, 'learning_rate': 0.14615094963562125, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.4330456457919417, 'colsample_bytree': 0.7508298570750123, 'colsample_bylevel': 0.9003397609985297, 'gamma': 9.249115563555117, 'alpha': 5.101206556706427, 'lambda': 5.917717831953353, 'tweedie_variance_power': 1.9529450450520984}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:36:58,560] Trial 157 finished with value: 6613.695584644297 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 379, 'learning_rate': 0.04065603153468919, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.4945093978535367, 'colsample_bytree': 0.7127877668799226, 'colsample_bylevel': 0.8732137361967002, 'gamma': 8.860644410964703, 'alpha': 4.5897202099395695, 'lambda': 6.783985257440489, 'tweedie_variance_power': 1.8954540385827532}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:37:07,883] Trial 158 finished with value: 6612.729165110299 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 438, 'learning_rate': 0.11184790635058123, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5315217170955739, 'colsample_bytree': 0.6689375268015338, 'colsample_bylevel': 0.9300798350219855, 'gamma': 9.572967220282036, 'alpha': 5.278197656101746, 'lambda': 7.667106775093167, 'tweedie_variance_power': 1.863409629063167}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:37:17,142] Trial 159 finished with value: 6616.011705515272 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 473, 'learning_rate': 0.10501757082088506, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.551461583799467, 'colsample_bytree': 0.6721253171192478, 'colsample_bylevel': 0.9345064773288548, 'gamma': 9.525823838668419, 'alpha': 5.673117504385899, 'lambda': 7.818924601424473, 'tweedie_variance_power': 1.8607850841410456}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:37:26,977] Trial 160 finished with value: 6617.675131513552 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 440, 'learning_rate': 0.07385189585862166, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.5281947813493119, 'colsample_bytree': 0.6358697811894848, 'colsample_bylevel': 0.9193633756482171, 'gamma': 9.105133524309414, 'alpha': 5.272766241292977, 'lambda': 8.525560646216453, 'tweedie_variance_power': 1.8792631184284725}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:37:35,889] Trial 161 finished with value: 6621.650811351766 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 462, 'learning_rate': 0.1196547431119592, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4223414828775969, 'colsample_bytree': 0.8685125218053871, 'colsample_bylevel': 0.8944123808859835, 'gamma': 9.632486330751806, 'alpha': 4.7201790062297935, 'lambda': 7.3422039363646325, 'tweedie_variance_power': 1.8456706761767832}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:37:44,551] Trial 162 finished with value: 8528.971739201641 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 407, 'learning_rate': 0.5439061432212021, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.48718748911369775, 'colsample_bytree': 0.6909150466271842, 'colsample_bylevel': 0.9331283569949936, 'gamma': 9.391487432978943, 'alpha': 4.285681491004003, 'lambda': 7.586609945806889, 'tweedie_variance_power': 1.828942803649383}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:37:53,478] Trial 163 finished with value: 6611.2975312950675 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 419, 'learning_rate': 0.09299281363785922, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5103759850718631, 'colsample_bytree': 0.6593348601713909, 'colsample_bylevel': 0.9111561289212562, 'gamma': 9.234789051089134, 'alpha': 5.124188408833975, 'lambda': 6.661350400751972, 'tweedie_variance_power': 1.864523012300966}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:38:02,334] Trial 164 finished with value: 6614.688445956732 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 421, 'learning_rate': 0.08766397900287971, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5725312545452382, 'colsample_bytree': 0.6791589230170878, 'colsample_bylevel': 0.9168039267003049, 'gamma': 9.191317923155758, 'alpha': 4.923837572463806, 'lambda': 6.670419338263635, 'tweedie_variance_power': 1.8597177789939887}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:38:16,741] Trial 165 finished with value: 10495202.16639968 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 434, 'learning_rate': 0.06315418466477793, 'max_depth': 5, 'min_child_weight': 18, 'subsample': 0.5175551844479391, 'colsample_bytree': 0.6463062426159261, 'colsample_bylevel': 0.9649998641528051, 'gamma': 9.609564524671109, 'alpha': 5.2184076054037485, 'lambda': 6.438928931349862, 'tweedie_variance_power': 1.9178804629924107}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:38:25,104] Trial 166 finished with value: 6616.8578728620105 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 381, 'learning_rate': 0.09527843711501477, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5061645481099653, 'colsample_bytree': 0.7376419162850077, 'colsample_bylevel': 0.861536714515984, 'gamma': 9.428548161925654, 'alpha': 4.483484348145406, 'lambda': 7.106024283195619, 'tweedie_variance_power': 1.8935137563331428}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:38:34,358] Trial 167 finished with value: 6614.1759311223095 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 455, 'learning_rate': 0.03454178629706395, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5420150689291185, 'colsample_bytree': 0.6516056493874623, 'colsample_bylevel': 0.9970275410318813, 'gamma': 9.045415818804525, 'alpha': 4.951786072720403, 'lambda': 8.116355363859896, 'tweedie_variance_power': 1.8634254095251033}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:38:43,282] Trial 168 finished with value: 6611.654279784109 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 419, 'learning_rate': 0.12710540175014928, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.48044124949334316, 'colsample_bytree': 0.6982531655973064, 'colsample_bylevel': 0.9080327337743904, 'gamma': 9.765666921778005, 'alpha': 5.678719032382162, 'lambda': 5.933615516889727, 'tweedie_variance_power': 1.8385485816433598}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:38:53,265] Trial 169 finished with value: 6613.23684405664 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 435, 'learning_rate': 0.14034999404019574, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.4786868746808172, 'colsample_bytree': 0.7082860174133833, 'colsample_bylevel': 0.8807289189551915, 'gamma': 9.73407564111681, 'alpha': 5.607749451196054, 'lambda': 5.94713825201363, 'tweedie_variance_power': 1.8379021833832003}. Best is trial 134 with value: 6611.054220867645.

[I 2026-08-31 09:39:02,809] Trial 170 finished with value: 6610.180799821957 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 451, 'learning_rate': 0.12367934505532757, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5285687569558881, 'colsample_bytree': 0.6129210239832641, 'colsample_bylevel': 0.9066686946400777, 'gamma': 9.79427136046085, 'alpha': 5.12383005995257, 'lambda': 6.177335042978104, 'tweedie_variance_power': 1.877329305208047}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:39:12,191] Trial 171 finished with value: 6616.639492441674 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 452, 'learning_rate': 0.12091188125493527, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5340403378927714, 'colsample_bytree': 0.6183208955708955, 'colsample_bylevel': 0.9079411484947729, 'gamma': 9.81060749538199, 'alpha': 5.697543926936702, 'lambda': 0.0846180982816147, 'tweedie_variance_power': 1.8768134537039949}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:39:20,800] Trial 172 finished with value: 6613.541040172859 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 419, 'learning_rate': 0.10154564135429914, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5023333227571211, 'colsample_bytree': 0.7651853390679475, 'colsample_bylevel': 0.9312655272247472, 'gamma': 9.590520373081622, 'alpha': 5.2541809974260785, 'lambda': 6.127716475355532, 'tweedie_variance_power': 1.805919632155502}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:39:29,848] Trial 173 finished with value: 6614.14264402638 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 427, 'learning_rate': 0.12232568111832601, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5673850202210342, 'colsample_bytree': 0.6398671233436848, 'colsample_bylevel': 0.9002568260170578, 'gamma': 9.996013530310213, 'alpha': 5.043676931697565, 'lambda': 5.806479444015631, 'tweedie_variance_power': 1.8271907310410547}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:39:38,915] Trial 174 finished with value: 6611.818179131538 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 478, 'learning_rate': 0.05997488393207524, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.5216412267422073, 'colsample_bytree': 0.6595460330009448, 'colsample_bylevel': 0.9219206363087747, 'gamma': 9.771991966856415, 'alpha': 4.2912373132839745, 'lambda': 6.296954062475574, 'tweedie_variance_power': 1.8894608627511522}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:39:48,302] Trial 175 finished with value: 6614.165969394692 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 498, 'learning_rate': 0.07650764052283716, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.520436565187295, 'colsample_bytree': 0.6947184249521419, 'colsample_bylevel': 0.8502099571851809, 'gamma': 9.792385884292106, 'alpha': 3.856846023899674, 'lambda': 6.639163257989667, 'tweedie_variance_power': 1.9062869194225491}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:39:57,545] Trial 176 finished with value: 7535.816980719268 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 480, 'learning_rate': 0.15895068014710112, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.4867219056442699, 'colsample_bytree': 0.6648811744522121, 'colsample_bylevel': 0.8713564753688162, 'gamma': 9.481598325521631, 'alpha': 4.240031511178853, 'lambda': 6.251315028502202, 'tweedie_variance_power': 1.9459007399066528}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:40:06,198] Trial 177 finished with value: 6615.113679515401 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 399, 'learning_rate': 0.10235085113898991, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5510608914479507, 'colsample_bytree': 0.6051465745924632, 'colsample_bylevel': 0.9113558081240122, 'gamma': 9.982676183965284, 'alpha': 4.374800253754844, 'lambda': 6.955707580907649, 'tweedie_variance_power': 1.8706991434754852}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:40:15,607] Trial 178 finished with value: 6613.664426245314 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 505, 'learning_rate': 0.04980761583080166, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5899151366067868, 'colsample_bytree': 0.6552587794242182, 'colsample_bylevel': 0.8883357105012248, 'gamma': 9.242816378071172, 'alpha': 5.915834048462578, 'lambda': 6.313978943505975, 'tweedie_variance_power': 1.8906570650622465}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:40:24,732] Trial 179 finished with value: 6624.236303444888 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 369, 'learning_rate': 0.1335189304026523, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.5272186512822024, 'colsample_bytree': 0.7271537583346342, 'colsample_bylevel': 0.9766106372048103, 'gamma': 9.770153253921787, 'alpha': 4.808353713697244, 'lambda': 6.004895337940072, 'tweedie_variance_power': 1.8386860467000847}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:40:33,709] Trial 180 finished with value: 6614.261961079623 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 450, 'learning_rate': 0.023199842808769855, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.47261144735768995, 'colsample_bytree': 0.7050241612589832, 'colsample_bylevel': 0.9214892868182015, 'gamma': 9.521410607913362, 'alpha': 5.350019130667604, 'lambda': 5.631191614841623, 'tweedie_variance_power': 1.798007877657344}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:40:42,973] Trial 181 finished with value: 6612.187116216061 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 464, 'learning_rate': 0.061421770290443906, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.43825301963129515, 'colsample_bytree': 0.6402217732771321, 'colsample_bylevel': 0.9385837804605169, 'gamma': 9.699518314137418, 'alpha': 4.505548662209127, 'lambda': 6.096513804815569, 'tweedie_variance_power': 1.854340836172213}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:40:52,211] Trial 182 finished with value: 6614.756398185296 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 463, 'learning_rate': 0.07278524270338922, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.4395833874877719, 'colsample_bytree': 0.6377551616723215, 'colsample_bylevel': 0.9498826544507274, 'gamma': 9.714209175051666, 'alpha': 4.532173593747369, 'lambda': 6.6002193583567985, 'tweedie_variance_power': 1.870653680935299}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:01,414] Trial 183 finished with value: 6613.704728892324 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 487, 'learning_rate': 0.09551237545324864, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5044583803864573, 'colsample_bytree': 0.6702774487770875, 'colsample_bylevel': 0.9043529274711224, 'gamma': 9.312611107338709, 'alpha': 4.958151523969145, 'lambda': 6.122533201584294, 'tweedie_variance_power': 1.824130926894397}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:10,293] Trial 184 finished with value: 6612.71518203299 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 438, 'learning_rate': 0.0554299947228255, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.48297589474781955, 'colsample_bytree': 0.6904782702814233, 'colsample_bylevel': 0.9396894771226558, 'gamma': 9.490951997624549, 'alpha': 4.151535159336017, 'lambda': 6.40804872189797, 'tweedie_variance_power': 1.884767246366406}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:19,398] Trial 185 finished with value: 6613.619405301734 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 439, 'learning_rate': 0.04065380880481156, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.4811200514944827, 'colsample_bytree': 0.6885525128702562, 'colsample_bylevel': 0.9396394373880474, 'gamma': 8.984954082674788, 'alpha': 4.058023566304515, 'lambda': 6.337464130189004, 'tweedie_variance_power': 1.8925586516964559}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:28,254] Trial 186 finished with value: 6617.6898376770005 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 426, 'learning_rate': 0.1114992768825527, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.46444796989505516, 'colsample_bytree': 0.6583135187499068, 'colsample_bylevel': 0.9605337235357845, 'gamma': 9.999295414515217, 'alpha': 4.404147090539319, 'lambda': 6.836098476010372, 'tweedie_variance_power': 1.9212912530329351}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:37,422] Trial 187 finished with value: 6613.836839551162 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 472, 'learning_rate': 0.08418280240574189, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5137919449234689, 'colsample_bytree': 0.6412028136989403, 'colsample_bylevel': 0.9156701789607833, 'gamma': 9.446764835505277, 'alpha': 4.149356196858952, 'lambda': 6.040256715241821, 'tweedie_variance_power': 1.8804956979996532}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:46,293] Trial 188 finished with value: 6613.387819645917 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 447, 'learning_rate': 0.058830265307813975, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.44334746166305417, 'colsample_bytree': 0.741807604495336, 'colsample_bylevel': 0.8881368658161302, 'gamma': 9.763777727103466, 'alpha': 5.158649967900906, 'lambda': 6.492645927181486, 'tweedie_variance_power': 1.8576755119885302}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:41:55,224] Trial 189 finished with value: 6616.413614285918 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 462, 'learning_rate': 0.0017448850565340013, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.49291266772301995, 'colsample_bytree': 0.6723827956472261, 'colsample_bylevel': 0.9611031473959913, 'gamma': 9.229537979436277, 'alpha': 4.610034592425767, 'lambda': 6.327362925584333, 'tweedie_variance_power': 1.8403976511032691}. Best is trial 170 with value: 6610.180799821957.

[I 2026-08-31 09:42:04,289] Trial 190 finished with value: 6608.046948201771 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 437, 'learning_rate': 0.13799728413245504, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5497532661016888, 'colsample_bytree': 0.6107265591780002, 'colsample_bylevel': 0.9811139234279938, 'gamma': 9.657066888481154, 'alpha': 3.9398059957745954, 'lambda': 6.745397213656747, 'tweedie_variance_power': 1.9078716299336351}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:42:13,304] Trial 191 finished with value: 7434.831726262276 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 437, 'learning_rate': 0.15284615848017696, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.553470594115392, 'colsample_bytree': 0.592849013336143, 'colsample_bylevel': 0.9825636443677522, 'gamma': 9.629369929347085, 'alpha': 3.7610104682102365, 'lambda': 6.769196733026815, 'tweedie_variance_power': 1.9725490903905005}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:42:21,981] Trial 192 finished with value: 6616.598667377564 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 417, 'learning_rate': 0.1347722765298218, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5814799445007618, 'colsample_bytree': 0.6158122711729819, 'colsample_bylevel': 0.9431670648123732, 'gamma': 9.806865329163674, 'alpha': 4.2118581404325806, 'lambda': 7.007095504686553, 'tweedie_variance_power': 1.9039212663888918}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:42:31,096] Trial 193 finished with value: 6611.629792148256 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 457, 'learning_rate': 0.11096484500339125, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5270486563442744, 'colsample_bytree': 0.6544441181819534, 'colsample_bylevel': 0.9752387497025001, 'gamma': 9.430449275544076, 'alpha': 3.9821897149196275, 'lambda': 6.563212869944076, 'tweedie_variance_power': 1.8869026658314412}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:42:39,913] Trial 194 finished with value: 6619.094393375034 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 459, 'learning_rate': 0.10883269630835984, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5393465731954323, 'colsample_bytree': 0.9725047000183282, 'colsample_bylevel': 0.9721456757536203, 'gamma': 9.455468428733921, 'alpha': 3.994389235207546, 'lambda': 6.513473360827446, 'tweedie_variance_power': 1.9152446677853312}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:42:48,294] Trial 195 finished with value: 6615.263674283288 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 448, 'learning_rate': 0.12444677983447029, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5065654986926978, 'colsample_bytree': 0.644667731595049, 'colsample_bylevel': 0.9879915177008419, 'gamma': 9.160305368304204, 'alpha': 3.8449138268347283, 'lambda': 6.661563024527976, 'tweedie_variance_power': 1.8883244722599188}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:42:57,052] Trial 196 finished with value: 6788.005005508102 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 430, 'learning_rate': 0.1984777455176211, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.530626627304672, 'colsample_bytree': 0.6050420199838378, 'colsample_bylevel': 0.9993554264016428, 'gamma': 9.65924833488275, 'alpha': 4.785900020567659, 'lambda': 6.267490725094986, 'tweedie_variance_power': 1.929359560009087}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:43:05,872] Trial 197 finished with value: 6613.315921431718 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 402, 'learning_rate': 0.0948532596842959, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5635654913539543, 'colsample_bytree': 0.6773826477150325, 'colsample_bylevel': 0.9544691218061317, 'gamma': 9.457075848723566, 'alpha': 4.462116123818573, 'lambda': 7.408443030037333, 'tweedie_variance_power': 1.8690555061578593}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:43:15,135] Trial 198 finished with value: 6641.454836782397 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 466, 'learning_rate': 0.16833427478491916, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.46286391550640205, 'colsample_bytree': 0.6965476729548845, 'colsample_bylevel': 0.9329009057896214, 'gamma': 9.793028886206237, 'alpha': 4.278379421493895, 'lambda': 6.0753479241253565, 'tweedie_variance_power': 1.848929794772263}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:43:24,251] Trial 199 finished with value: 6612.362158658074 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 479, 'learning_rate': 0.0716237640157332, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5211307263378943, 'colsample_bytree': 0.6559653829386072, 'colsample_bylevel': 0.9736843784611704, 'gamma': 9.250744959814613, 'alpha': 3.450947960361552, 'lambda': 6.449978834805394, 'tweedie_variance_power': 1.8958430854793116}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:43:33,672] Trial 200 finished with value: 6613.2555600636715 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 479, 'learning_rate': 0.036592535869101536, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5259584533105177, 'colsample_bytree': 0.659805222096155, 'colsample_bylevel': 0.9686940697686858, 'gamma': 9.056200820832963, 'alpha': 3.459937783911469, 'lambda': 6.754066904114639, 'tweedie_variance_power': 1.8819705407996745}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:43:43,027] Trial 201 finished with value: 6614.7488310049475 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 490, 'learning_rate': 0.06987708037638306, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.4853972131192374, 'colsample_bytree': 0.6311610339278981, 'colsample_bylevel': 0.9803140580038018, 'gamma': 9.336591670505229, 'alpha': 3.2554551732074266, 'lambda': 6.4362755000371195, 'tweedie_variance_power': 1.897625580666303}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:43:52,288] Trial 202 finished with value: 6613.090003068627 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 470, 'learning_rate': 0.08659789194971586, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.5490558568323441, 'colsample_bytree': 0.6560870807367982, 'colsample_bylevel': 0.9462335204220647, 'gamma': 9.575670763558293, 'alpha': 2.5179982145989532, 'lambda': 5.843882402689011, 'tweedie_variance_power': 1.863588038109365}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:01,373] Trial 203 finished with value: 6609.267765193797 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 454, 'learning_rate': 0.11305669103653213, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5084219582890444, 'colsample_bytree': 0.6806486696935479, 'colsample_bylevel': 0.926563866011306, 'gamma': 9.306932801188642, 'alpha': 4.008016627238898, 'lambda': 6.2314828129622075, 'tweedie_variance_power': 1.9074017116216413}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:10,318] Trial 204 finished with value: 6611.499003036073 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 441, 'learning_rate': 0.10867853229966365, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5115313531925074, 'colsample_bytree': 0.7115705194020981, 'colsample_bylevel': 0.9583108516824774, 'gamma': 9.186031590634762, 'alpha': 2.80145944884655, 'lambda': 6.571648217849428, 'tweedie_variance_power': 1.9056892710438196}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:19,272] Trial 205 finished with value: 6612.181153819242 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 454, 'learning_rate': 0.14457206319708432, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5148876082293213, 'colsample_bytree': 0.7145678675920214, 'colsample_bylevel': 0.923666059088785, 'gamma': 8.943762221175364, 'alpha': 2.727198122755551, 'lambda': 6.897780950309428, 'tweedie_variance_power': 1.932408933175297}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:28,289] Trial 206 finished with value: 6636.439956014122 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 454, 'learning_rate': 0.13559446165901137, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5159762065539393, 'colsample_bytree': 0.7245791983256662, 'colsample_bylevel': 0.948247994371211, 'gamma': 8.937069372687214, 'alpha': 2.813858777907697, 'lambda': 6.90555759200187, 'tweedie_variance_power': 1.924433793851498}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:37,256] Trial 207 finished with value: 6673.544372752687 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 445, 'learning_rate': 0.1432722368417129, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.49835357211432396, 'colsample_bytree': 0.7117421933219128, 'colsample_bylevel': 0.9203646625529236, 'gamma': 8.836224039790771, 'alpha': 2.968062670698851, 'lambda': 7.162954818981683, 'tweedie_variance_power': 1.9400241379242635}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:46,372] Trial 208 finished with value: 44896.35991026147 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 458, 'learning_rate': 0.16136922072870885, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5073175174397428, 'colsample_bytree': 0.6954046772868364, 'colsample_bylevel': 0.9780633676303756, 'gamma': 8.72714107596308, 'alpha': 2.8010189694294003, 'lambda': 6.70484060424661, 'tweedie_variance_power': 1.9709515088831373}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:44:55,577] Trial 209 finished with value: 6615.923994734942 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 477, 'learning_rate': 0.11803020869772385, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.4932735507471794, 'colsample_bytree': 0.7156217793157199, 'colsample_bylevel': 0.9327391549323324, 'gamma': 9.187266939420894, 'alpha': 3.671358795260584, 'lambda': 6.158245164249678, 'tweedie_variance_power': 1.9066722720986937}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:45:05,479] Trial 210 finished with value: 11459.12678983649 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 565, 'learning_rate': 0.18729135254617366, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.4775505055096265, 'colsample_bytree': 0.7664604920744558, 'colsample_bylevel': 0.9571212517225611, 'gamma': 9.294971939643672, 'alpha': 2.246029719816362, 'lambda': 6.375921008365169, 'tweedie_variance_power': 1.9330617247415895}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:45:14,551] Trial 211 finished with value: 6608.330054115272 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 436, 'learning_rate': 0.1036768334083169, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.529419583259837, 'colsample_bytree': 0.6825990636921023, 'colsample_bylevel': 0.9284834415823915, 'gamma': 9.39805216621682, 'alpha': 3.1286407473470237, 'lambda': 6.598817956697072, 'tweedie_variance_power': 1.8986894334877973}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:45:23,762] Trial 212 finished with value: 6616.348050801228 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 432, 'learning_rate': 0.10156451308669996, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5421862387804531, 'colsample_bytree': 0.6879947866748867, 'colsample_bylevel': 0.9130532128730402, 'gamma': 9.041144964746639, 'alpha': 3.0921739885198316, 'lambda': 6.627174472697842, 'tweedie_variance_power': 1.899761107851784}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:45:33,460] Trial 213 finished with value: 7152.714436729301 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 451, 'learning_rate': 0.12553482502837912, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.5114372112895045, 'colsample_bytree': 0.6149714704798231, 'colsample_bylevel': 0.9401950930801142, 'gamma': 9.344673614037205, 'alpha': 3.3014324568267748, 'lambda': 6.990647429136796, 'tweedie_variance_power': 1.9653021617726134}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:45:42,060] Trial 214 finished with value: 6615.8860484216275 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 425, 'learning_rate': 0.09872675700118372, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5246592884576214, 'colsample_bytree': 0.6379617778896276, 'colsample_bylevel': 0.9225114368037098, 'gamma': 9.339502129481602, 'alpha': 2.6918209351439915, 'lambda': 6.224849267974029, 'tweedie_variance_power': 1.9123398521531738}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:45:50,831] Trial 215 finished with value: 6609.9987912832285 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 438, 'learning_rate': 0.14614918276756708, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5181157247846659, 'colsample_bytree': 0.7341878240935702, 'colsample_bylevel': 0.9657451183590213, 'gamma': 9.819877949590008, 'alpha': 3.958050375840253, 'lambda': 6.534279850488445, 'tweedie_variance_power': 1.8839839851630675}. Best is trial 190 with value: 6608.046948201771.

[I 2026-08-31 09:46:00,192] Trial 216 finished with value: 6607.426054633319 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 500, 'learning_rate': 0.14671853221380152, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5580935564158042, 'colsample_bytree': 0.7554181078749264, 'colsample_bylevel': 0.9737070804955209, 'gamma': 9.869886255692933, 'alpha': 2.324428741036249, 'lambda': 6.7864804214008645, 'tweedie_variance_power': 1.8903203815286416}. Best is trial 216 with value: 6607.426054633319.

[I 2026-08-31 09:46:09,575] Trial 217 finished with value: 6605.558227926169 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 520, 'learning_rate': 0.15294789421529958, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5675797490191806, 'colsample_bytree': 0.7489465387292096, 'colsample_bylevel': 0.9844633165519008, 'gamma': 9.97888073025197, 'alpha': 2.1763146139213125, 'lambda': 6.606378723462408, 'tweedie_variance_power': 1.9136338174742307}. Best is trial 217 with value: 6605.558227926169.

[I 2026-08-31 09:46:19,242] Trial 218 finished with value: 6477.950199572396 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 526, 'learning_rate': 0.17512951721752334, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5711535899445354, 'colsample_bytree': 0.7815959653558312, 'colsample_bylevel': 0.9977778603526434, 'gamma': 9.928320444825609, 'alpha': 2.296710172012551, 'lambda': 6.794902978103159, 'tweedie_variance_power': 1.9219326581434355}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:46:28,582] Trial 219 finished with value: 6963.317620969693 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 490, 'learning_rate': 0.1756875857906849, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5998367965998374, 'colsample_bytree': 0.8106605356488578, 'colsample_bylevel': 0.9997545254695057, 'gamma': 9.980367297634492, 'alpha': 2.317003578519746, 'lambda': 6.851611251910526, 'tweedie_variance_power': 1.9499489449022671}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:46:38,192] Trial 220 finished with value: 6852.147015444661 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 536, 'learning_rate': 0.2078958307666553, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6186757390172735, 'colsample_bytree': 0.7581979319743515, 'colsample_bylevel': 0.9835364132992764, 'gamma': 9.845776037655838, 'alpha': 1.741345772216955, 'lambda': 6.612167530075233, 'tweedie_variance_power': 1.9264378886912161}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:46:47,939] Trial 221 finished with value: 6640.062479277681 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 549, 'learning_rate': 0.15446020057556403, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5718186217072747, 'colsample_bytree': 0.7871790990567701, 'colsample_bylevel': 0.9690164392993253, 'gamma': 9.772875678657321, 'alpha': 1.9174452698409816, 'lambda': 6.561549349974235, 'tweedie_variance_power': 1.9117752103100463}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:46:57,547] Trial 222 finished with value: 6624.087537201373 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 522, 'learning_rate': 0.14927106272600485, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5599628384233454, 'colsample_bytree': 0.7352602955411113, 'colsample_bylevel': 0.9879408777695591, 'gamma': 9.702420916186549, 'alpha': 2.47668112939421, 'lambda': 6.7635606103468575, 'tweedie_variance_power': 1.8921527150755342}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:47:07,083] Trial 223 finished with value: 6672.645277549424 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 514, 'learning_rate': 0.17541354437625392, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5482763060253412, 'colsample_bytree': 0.7748852943664305, 'colsample_bylevel': 0.9766231512152529, 'gamma': 9.980115576652869, 'alpha': 2.0842469823470595, 'lambda': 7.167664472750169, 'tweedie_variance_power': 1.9019993568633502}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:47:16,624] Trial 224 finished with value: 6585.031082199381 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 502, 'learning_rate': 0.13890186751879677, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5876796881323396, 'colsample_bytree': 0.8129372441360619, 'colsample_bylevel': 0.965746237686537, 'gamma': 9.682445944063671, 'alpha': 2.60188149372666, 'lambda': 6.385706008364065, 'tweedie_variance_power': 1.9218311438887141}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:47:26,074] Trial 225 finished with value: 6618.547602372489 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 500, 'learning_rate': 0.14742300594908955, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5824367301084635, 'colsample_bytree': 0.8164218366924282, 'colsample_bylevel': 0.9656579618028758, 'gamma': 9.820335011267588, 'alpha': 2.6210208527724173, 'lambda': 6.574922379643531, 'tweedie_variance_power': 1.927195840923387}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:47:35,816] Trial 226 finished with value: 6646.814116231628 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 508, 'learning_rate': 0.16359929773798998, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.618817963897983, 'colsample_bytree': 0.839870856423115, 'colsample_bylevel': 0.9939348458030082, 'gamma': 9.986721390814582, 'alpha': 2.2504665629494642, 'lambda': 6.850282062856118, 'tweedie_variance_power': 1.9428033901453188}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:47:45,561] Trial 227 finished with value: 6710.124458605937 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 531, 'learning_rate': 0.1908118783797026, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5953528145414888, 'colsample_bytree': 0.7487479966328028, 'colsample_bylevel': 0.9599037446972695, 'gamma': 9.61590649091843, 'alpha': 2.55566268309655, 'lambda': 6.441453617564861, 'tweedie_variance_power': 1.9164361979271647}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:47:55,284] Trial 228 finished with value: 6603.630534607458 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 519, 'learning_rate': 0.12010755301294804, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5683543527035594, 'colsample_bytree': 0.750197914844358, 'colsample_bylevel': 0.9819859937895513, 'gamma': 9.189170979708333, 'alpha': 3.039495658530308, 'lambda': 6.712200067493698, 'tweedie_variance_power': 1.8897952214034126}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:48:04,771] Trial 229 finished with value: 6575.658597513029 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 523, 'learning_rate': 0.1345811484397626, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5705040028630081, 'colsample_bytree': 0.777693217195961, 'colsample_bylevel': 0.9999102713032659, 'gamma': 9.140090794543461, 'alpha': 2.955450963605065, 'lambda': 7.030192842996943, 'tweedie_variance_power': 1.903052650688291}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:48:14,631] Trial 230 finished with value: 6685.746419834484 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 526, 'learning_rate': 0.13561370033957154, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6429002774155288, 'colsample_bytree': 0.7891891943959166, 'colsample_bylevel': 0.9913719487236147, 'gamma': 8.791796004904871, 'alpha': 3.0328764500289913, 'lambda': 7.243354725956149, 'tweedie_variance_power': 1.9583853943526108}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:48:23,996] Trial 231 finished with value: 6608.823521013082 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 515, 'learning_rate': 0.1353314145233165, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5800424989175228, 'colsample_bytree': 0.8000081126689504, 'colsample_bylevel': 0.9798688797110111, 'gamma': 9.169735637333897, 'alpha': 3.016188661850902, 'lambda': 6.748757930392435, 'tweedie_variance_power': 1.8976033015417033}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:48:33,649] Trial 232 finished with value: 6540.42579537984 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 521, 'learning_rate': 0.1359736752312033, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5806917829660163, 'colsample_bytree': 0.8031158315882473, 'colsample_bylevel': 0.9809294725289068, 'gamma': 9.040314917833694, 'alpha': 2.9189857729592568, 'lambda': 6.989775800533259, 'tweedie_variance_power': 1.935364762839042}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:48:43,284] Trial 233 finished with value: 7173.991298459198 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 518, 'learning_rate': 0.2244436234918002, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5801932445824941, 'colsample_bytree': 0.7807907509017183, 'colsample_bylevel': 0.9957399587251352, 'gamma': 9.095792437108837, 'alpha': 2.870685339224333, 'lambda': 7.034258345091329, 'tweedie_variance_power': 1.9325007157607372}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:48:53,024] Trial 234 finished with value: 6591.698010916566 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 534, 'learning_rate': 0.15097953292766683, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5670917863748925, 'colsample_bytree': 0.8059898936733604, 'colsample_bylevel': 0.978927257031856, 'gamma': 8.94257624118385, 'alpha': 2.6871214025854306, 'lambda': 6.781033665774409, 'tweedie_variance_power': 1.9122956849186055}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:49:02,911] Trial 235 finished with value: 6657.596212440515 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 539, 'learning_rate': 0.16246279804107822, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5635738514503507, 'colsample_bytree': 0.8021631354706138, 'colsample_bylevel': 0.9826689827934038, 'gamma': 8.598798338136149, 'alpha': 2.7176524432606706, 'lambda': 6.856194056711825, 'tweedie_variance_power': 1.9126570306956376}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:49:12,672] Trial 236 finished with value: 6670.013436132899 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 547, 'learning_rate': 0.14401601460696062, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6116754133043022, 'colsample_bytree': 0.834436095318414, 'colsample_bylevel': 0.9766039140277686, 'gamma': 9.011376114165925, 'alpha': 2.4224073918962676, 'lambda': 7.089280967096159, 'tweedie_variance_power': 1.939946362853505}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:49:22,176] Trial 237 finished with value: 6686.409482309229 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 511, 'learning_rate': 0.18503677444661126, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5724480401269854, 'colsample_bytree': 0.8084629800632424, 'colsample_bylevel': 0.9972243839624596, 'gamma': 8.799483160866616, 'alpha': 2.9743953225538835, 'lambda': 6.744171462074529, 'tweedie_variance_power': 1.90953150283432}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:49:31,935] Trial 238 finished with value: 6616.761074499471 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 531, 'learning_rate': 0.13089925311387712, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5597297604865928, 'colsample_bytree': 0.8235852443344132, 'colsample_bylevel': 0.9683236502752929, 'gamma': 8.937966927764414, 'alpha': 2.8369342171338485, 'lambda': 7.294667120740384, 'tweedie_variance_power': 1.8836391476796424}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:49:41,570] Trial 239 finished with value: 6641.8573887613375 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 524, 'learning_rate': 0.1535660255362831, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5954914768656407, 'colsample_bytree': 0.7962437229886666, 'colsample_bylevel': 0.9847736158083144, 'gamma': 9.284303942601676, 'alpha': 3.113969552884288, 'lambda': 6.694407308923664, 'tweedie_variance_power': 1.8966963516420636}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:49:51,230] Trial 240 finished with value: 6650.8164584853885 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 501, 'learning_rate': 0.1726240106093893, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5821907900434464, 'colsample_bytree': 0.8722180741463884, 'colsample_bylevel': 0.9574591632718028, 'gamma': 9.053311751374228, 'alpha': 2.1099832425061584, 'lambda': 6.9710653912811305, 'tweedie_variance_power': 1.9218758946483234}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:50:01,041] Trial 241 finished with value: 6594.628352906923 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 552, 'learning_rate': 0.12629732744974828, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5531474337133275, 'colsample_bytree': 0.7727577651217457, 'colsample_bylevel': 0.9706830628419049, 'gamma': 9.151649640385829, 'alpha': 2.5763660975616407, 'lambda': 6.708191119393149, 'tweedie_variance_power': 1.8751695565355806}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:50:10,840] Trial 242 finished with value: 6605.858310320423 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 550, 'learning_rate': 0.12591186598139664, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5444567550772549, 'colsample_bytree': 0.7734411273555313, 'colsample_bylevel': 0.9752296964308115, 'gamma': 9.159623477903567, 'alpha': 2.662532434617445, 'lambda': 6.648236323599314, 'tweedie_variance_power': 1.8786185366966464}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:50:20,518] Trial 243 finished with value: 6619.813784889083 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 557, 'learning_rate': 0.131166717562244, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5438330816963882, 'colsample_bytree': 0.7807638090921105, 'colsample_bylevel': 0.9996744448721577, 'gamma': 9.150124689782645, 'alpha': 2.744884059713268, 'lambda': 6.6678567817952725, 'tweedie_variance_power': 1.8733626925373132}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:50:30,464] Trial 244 finished with value: 6594.708666106846 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 573, 'learning_rate': 0.12567158481726606, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.559988573153641, 'colsample_bytree': 0.7637854699358677, 'colsample_bylevel': 0.9770639114805876, 'gamma': 8.85725796929819, 'alpha': 2.3788952456850345, 'lambda': 6.843034297551974, 'tweedie_variance_power': 1.89701808475051}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:50:40,538] Trial 245 finished with value: 6598.098524553353 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 579, 'learning_rate': 0.12331600394707674, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5664310402738689, 'colsample_bytree': 0.7523189752021785, 'colsample_bylevel': 0.9746109075553191, 'gamma': 8.571412407004352, 'alpha': 2.2448121468930236, 'lambda': 6.608288786140471, 'tweedie_variance_power': 1.8852326140133653}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:50:50,558] Trial 246 finished with value: 6613.624179792166 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 577, 'learning_rate': 0.1206531300686321, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5597274250280331, 'colsample_bytree': 0.7589479033285642, 'colsample_bylevel': 0.974261101422875, 'gamma': 8.473716687702616, 'alpha': 1.8656591170381513, 'lambda': 6.796026189584996, 'tweedie_variance_power': 1.9002724724761042}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:51:00,729] Trial 247 finished with value: 6609.589022087966 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 592, 'learning_rate': 0.12364004288250999, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5701348460816094, 'colsample_bytree': 0.7750677778511113, 'colsample_bylevel': 0.9845897175479634, 'gamma': 8.651743604424784, 'alpha': 2.42097956218598, 'lambda': 7.085502335603587, 'tweedie_variance_power': 1.886215989518548}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:51:10,738] Trial 248 finished with value: 6598.74047957547 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 588, 'learning_rate': 0.11992696479289194, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5780839286396191, 'colsample_bytree': 0.7761591384983487, 'colsample_bylevel': 0.9798221166860507, 'gamma': 8.658686386813017, 'alpha': 2.380911455520948, 'lambda': 7.11005982132017, 'tweedie_variance_power': 1.884969972593991}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:51:20,758] Trial 249 finished with value: 6617.596336208555 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 564, 'learning_rate': 0.12686637588033783, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5782204089772801, 'colsample_bytree': 0.7682980387050863, 'colsample_bylevel': 0.9841100552093632, 'gamma': 8.419746238964704, 'alpha': 2.3967771528954436, 'lambda': 7.520726591742572, 'tweedie_variance_power': 1.8813432103061418}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:51:30,839] Trial 250 finished with value: 6618.65288336173 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 591, 'learning_rate': 0.15535903573850401, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.60441362353552, 'colsample_bytree': 0.7889537772358459, 'colsample_bylevel': 0.9998868389679763, 'gamma': 8.64380908854177, 'alpha': 2.2794498334259226, 'lambda': 7.176853851684091, 'tweedie_variance_power': 1.9081941158317863}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:51:40,820] Trial 251 finished with value: 6614.809277825556 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 587, 'learning_rate': 0.1174660909453053, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.56846636357719, 'colsample_bytree': 0.7462999161208397, 'colsample_bylevel': 0.9784610085190848, 'gamma': 8.693639083577313, 'alpha': 1.478261530474608, 'lambda': 7.100853381322046, 'tweedie_variance_power': 1.8786352044939136}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:51:50,941] Trial 252 finished with value: 6586.502646745831 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 572, 'learning_rate': 0.13779531828688635, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5899527911031275, 'colsample_bytree': 0.8005802999553758, 'colsample_bylevel': 0.9814958232046074, 'gamma': 8.538156889887828, 'alpha': 2.5528480981048296, 'lambda': 7.417305114007396, 'tweedie_variance_power': 1.9027629646972173}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:52:01,037] Trial 253 finished with value: 6625.0631716024545 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 575, 'learning_rate': 0.14206237192825336, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6302551438293285, 'colsample_bytree': 0.8006325437917259, 'colsample_bylevel': 0.9842421611687473, 'gamma': 8.517389195263432, 'alpha': 2.510457702651479, 'lambda': 7.472300779694519, 'tweedie_variance_power': 1.9127202738344797}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:52:11,182] Trial 254 finished with value: 6610.193570402125 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 595, 'learning_rate': 0.17076916998563846, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5989665240455807, 'colsample_bytree': 0.7799686516612137, 'colsample_bylevel': 0.969828695733005, 'gamma': 8.663552257608211, 'alpha': 2.085720950109163, 'lambda': 7.3466740816881835, 'tweedie_variance_power': 1.8943484445730498}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:52:21,227] Trial 255 finished with value: 6597.1855950475 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 593, 'learning_rate': 0.17340465033431168, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.586260348264424, 'colsample_bytree': 0.7763943350117855, 'colsample_bylevel': 0.9677911694217186, 'gamma': 8.25584349332822, 'alpha': 2.153284055836786, 'lambda': 7.35148864240193, 'tweedie_variance_power': 1.8976595769858717}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:52:33,630] Trial 256 finished with value: 401266.2667601308 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 599, 'learning_rate': 0.20401597737110128, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.5950801584485473, 'colsample_bytree': 0.8248328113746035, 'colsample_bylevel': 0.9996478264605682, 'gamma': 8.326602747419308, 'alpha': 2.1563841638730974, 'lambda': 7.337143409623844, 'tweedie_variance_power': 1.8973003336263987}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:52:43,435] Trial 257 finished with value: 6647.890308789566 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 579, 'learning_rate': 0.17395723720968534, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5858744926515337, 'colsample_bytree': 0.7781748219479236, 'colsample_bylevel': 0.9672952218196134, 'gamma': 8.572210447171061, 'alpha': 2.3587586639442275, 'lambda': 7.947973420628966, 'tweedie_variance_power': 1.9256083747008694}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:52:53,454] Trial 258 finished with value: 6585.3547462673105 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 568, 'learning_rate': 0.19156304279059938, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.610421482130631, 'colsample_bytree': 0.7562591020425369, 'colsample_bylevel': 0.9825090137471068, 'gamma': 8.764678829143508, 'alpha': 1.7054120112761035, 'lambda': 7.668682820080748, 'tweedie_variance_power': 1.8730625017061584}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:53:03,176] Trial 259 finished with value: 6673.775069058944 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 559, 'learning_rate': 0.24311386037897503, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6099356030524755, 'colsample_bytree': 0.7577481464545325, 'colsample_bylevel': 0.9869098326684538, 'gamma': 8.278481605627633, 'alpha': 1.6456868863449534, 'lambda': 7.685787797162029, 'tweedie_variance_power': 1.892649799795095}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:53:13,238] Trial 260 finished with value: 6642.60243805582 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 594, 'learning_rate': 0.19324343313233042, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5870981857494819, 'colsample_bytree': 0.7727453074677386, 'colsample_bylevel': 0.9702191127771396, 'gamma': 8.660489078606092, 'alpha': 2.062690810257243, 'lambda': 7.741613922877981, 'tweedie_variance_power': 1.8812464619525842}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:53:23,114] Trial 261 finished with value: 6661.100960487398 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 570, 'learning_rate': 0.20978541130845538, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5680173442376298, 'colsample_bytree': 0.80039131099298, 'colsample_bylevel': 0.9816053400736724, 'gamma': 8.132080118105977, 'alpha': 1.7717070472610752, 'lambda': 7.376592827086062, 'tweedie_variance_power': 1.9178951983243575}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:53:33,207] Trial 262 finished with value: 6599.9555787274 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 586, 'learning_rate': 0.17355179136359922, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6268632230019693, 'colsample_bytree': 0.7510221185216742, 'colsample_bylevel': 0.9643304898859717, 'gamma': 8.693753253462654, 'alpha': 1.1639986643864781, 'lambda': 7.394781507078247, 'tweedie_variance_power': 1.8735696005481013}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:53:43,269] Trial 263 finished with value: 6635.263009452255 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 587, 'learning_rate': 0.17911435765628914, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6350885125794548, 'colsample_bytree': 0.7510947111012921, 'colsample_bylevel': 0.9661501206058362, 'gamma': 8.450184014728585, 'alpha': 1.9900195538483243, 'lambda': 7.384311152822417, 'tweedie_variance_power': 1.9006819760274527}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:53:53,251] Trial 264 finished with value: 6635.075088993232 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 552, 'learning_rate': 0.1642281937343811, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.611188924978813, 'colsample_bytree': 0.7763410292302801, 'colsample_bylevel': 0.9992313065546392, 'gamma': 8.72336754481621, 'alpha': 2.549212632595796, 'lambda': 7.1856164673822125, 'tweedie_variance_power': 1.8705488744786798}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:54:05,818] Trial 265 finished with value: 1033089779.1539395 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 583, 'learning_rate': 0.19469715484346395, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.5524285348932471, 'colsample_bytree': 0.7894916433372702, 'colsample_bylevel': 0.9819383594349163, 'gamma': 8.850079066011542, 'alpha': 2.2081878095511405, 'lambda': 7.866036513602988, 'tweedie_variance_power': 1.9406181252476946}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:54:15,719] Trial 266 finished with value: 6559.510201521346 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 570, 'learning_rate': 0.15546411283637102, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.649639192860246, 'colsample_bytree': 0.7607905996478198, 'colsample_bylevel': 0.9641804954487787, 'gamma': 8.233916617395556, 'alpha': 2.559948425517196, 'lambda': 7.039413440934441, 'tweedie_variance_power': 1.8902772834866224}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:54:32,218] Trial 267 finished with value: 4901581.545656456 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 571, 'learning_rate': 0.1532276383587311, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.6597233763250911, 'colsample_bytree': 0.7681167808044095, 'colsample_bylevel': 0.9558946432467423, 'gamma': 8.299533557811976, 'alpha': 2.561078627728142, 'lambda': 7.033976079197416, 'tweedie_variance_power': 1.920484208362082}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:54:41,609] Trial 268 finished with value: 6617.181478537742 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 542, 'learning_rate': 0.1467396774256513, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6757996806217972, 'colsample_bytree': 0.7432002123914553, 'colsample_bylevel': 0.9847297768748327, 'gamma': 8.062538249283408, 'alpha': 3.0006216974837367, 'lambda': 6.975061782701175, 'tweedie_variance_power': 1.876009043935591}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:54:51,592] Trial 269 finished with value: 6621.104198644824 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 561, 'learning_rate': 0.1784400644986041, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5725556424784453, 'colsample_bytree': 0.7527585003653279, 'colsample_bylevel': 0.9599796913398648, 'gamma': 8.554355322900644, 'alpha': 1.1783678976431866, 'lambda': 7.469644662331797, 'tweedie_variance_power': 1.9080943399646344}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:55:01,541] Trial 270 finished with value: 6541.499502861744 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 580, 'learning_rate': 0.2138037271187636, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.652742244512225, 'colsample_bytree': 0.81240309320408, 'colsample_bylevel': 0.9837657860681367, 'gamma': 8.225543823043305, 'alpha': 0.45592270230117293, 'lambda': 7.202410470193697, 'tweedie_variance_power': 1.886481090603958}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:55:20,510] Trial 271 finished with value: 17964.51963902052 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 582, 'learning_rate': 0.22251009460659876, 'max_depth': 9, 'min_child_weight': 20, 'subsample': 0.6455080804469252, 'colsample_bytree': 0.8586711575245792, 'colsample_bylevel': 0.9992316244203819, 'gamma': 8.200770484082108, 'alpha': 0.5585877589266608, 'lambda': 7.202877649394525, 'tweedie_variance_power': 1.8906165681817193}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:55:30,208] Trial 272 finished with value: 6640.29836902174 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 571, 'learning_rate': 0.22124901803760338, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6233583899631188, 'colsample_bytree': 0.8185127027763737, 'colsample_bylevel': 0.9759838944732943, 'gamma': 7.738360096892473, 'alpha': 0.588482873327902, 'lambda': 7.011596064915713, 'tweedie_variance_power': 1.9191646600014294}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:55:39,830] Trial 273 finished with value: 34836.09206819461 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 541, 'learning_rate': 0.2645691066328459, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.7150547956681567, 'colsample_bytree': 0.800582797430697, 'colsample_bylevel': 0.982415649523612, 'gamma': 8.380738301151068, 'alpha': 0.9929558604417704, 'lambda': 7.558382631295396, 'tweedie_variance_power': 1.9861631528679833}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:55:49,767] Trial 274 finished with value: 6922.752260111235 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 551, 'learning_rate': 0.199836414174676, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6642311923598135, 'colsample_bytree': 0.7621464016022181, 'colsample_bylevel': 0.9637205266158081, 'gamma': 8.742211702906696, 'alpha': 2.4502743545340278, 'lambda': 6.911512306875045, 'tweedie_variance_power': 1.9491246432491345}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:55:59,973] Trial 275 finished with value: 6547.387076581169 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 580, 'learning_rate': 0.1617384873205216, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5864239042926113, 'colsample_bytree': 0.8103078388168412, 'colsample_bylevel': 0.9532152560338236, 'gamma': 8.864978018419949, 'alpha': 2.632644321363548, 'lambda': 7.249485462351662, 'tweedie_variance_power': 1.9007877615669415}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:56:10,234] Trial 276 finished with value: 6634.74395600728 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 580, 'learning_rate': 0.16578716934375926, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5865639165101795, 'colsample_bytree': 0.8144165993293546, 'colsample_bylevel': 0.9523181237134145, 'gamma': 8.856194774176803, 'alpha': 0.11897673871095926, 'lambda': 7.2455154527517385, 'tweedie_variance_power': 1.9348884421754113}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:56:20,340] Trial 277 finished with value: 6624.334551322861 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 565, 'learning_rate': 0.18451381095669875, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.625697388532326, 'colsample_bytree': 0.8451325089712819, 'colsample_bylevel': 0.9840324277875633, 'gamma': 8.547903587038007, 'alpha': 2.6681286834632307, 'lambda': 8.092338284929587, 'tweedie_variance_power': 1.8998644567789968}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:56:30,638] Trial 278 finished with value: 6905.425917478691 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 600, 'learning_rate': 0.1613412185316075, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5549998985590882, 'colsample_bytree': 0.7937685663531746, 'colsample_bylevel': 0.9731882689857181, 'gamma': 8.903131872135113, 'alpha': 1.2679418320379243, 'lambda': 7.526744355562156, 'tweedie_variance_power': 1.913905136441154}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:56:41,266] Trial 279 finished with value: 6668.478807915238 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 530, 'learning_rate': 0.14019557574942323, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.5929694757967682, 'colsample_bytree': 0.803088344079758, 'colsample_bylevel': 0.9497942680257301, 'gamma': 8.065293096349787, 'alpha': 2.3170648716393405, 'lambda': 7.1756525423760955, 'tweedie_variance_power': 1.8672034958596373}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:56:51,177] Trial 280 finished with value: 6693.2151096919615 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 584, 'learning_rate': 0.20367951645527663, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5731213930043828, 'colsample_bytree': 0.83352508312259, 'colsample_bylevel': 0.9986993929935697, 'gamma': 8.837540963616995, 'alpha': 2.903693619559644, 'lambda': 7.051620109550702, 'tweedie_variance_power': 1.9014624453339797}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:57:01,161] Trial 281 finished with value: 6619.794013663822 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 572, 'learning_rate': 0.1359613451767394, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6488812484017149, 'colsample_bytree': 0.7811241029916602, 'colsample_bylevel': 0.9843721486851521, 'gamma': 8.344663361486719, 'alpha': 2.593881919367948, 'lambda': 6.871365808383113, 'tweedie_variance_power': 1.9295431693490603}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:57:10,551] Trial 282 finished with value: 6571.621244236221 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 517, 'learning_rate': 0.23267227907508042, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5528627539792894, 'colsample_bytree': 0.7678962432925056, 'colsample_bylevel': 0.9508785306731686, 'gamma': 8.493796983997285, 'alpha': 0.3746703423141832, 'lambda': 7.693065997317808, 'tweedie_variance_power': 1.8871284278564078}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:57:21,655] Trial 283 finished with value: 2549390260.315563 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 518, 'learning_rate': 0.25177150706418433, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.6093972300821908, 'colsample_bytree': 0.758352683749861, 'colsample_bylevel': 0.9552831084218374, 'gamma': 8.467109321803418, 'alpha': 0.8678088280727909, 'lambda': 7.732983923510747, 'tweedie_variance_power': 1.9107096347151529}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:57:30,957] Trial 284 finished with value: 6654.23802479013 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 508, 'learning_rate': 0.22282253518923084, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5449645806985278, 'colsample_bytree': 0.814955804074748, 'colsample_bylevel': 0.947578572010763, 'gamma': 7.899886484121995, 'alpha': 0.27961822061626473, 'lambda': 7.616811708643451, 'tweedie_variance_power': 1.864877560251796}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:57:46,076] Trial 285 finished with value: 14372610278861.23 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 556, 'learning_rate': 0.23956601915555698, 'max_depth': 7, 'min_child_weight': 19, 'subsample': 0.5524270520938936, 'colsample_bytree': 0.7948003894944005, 'colsample_bylevel': 0.9690847409123086, 'gamma': 8.18093652033269, 'alpha': 3.239243621902667, 'lambda': 7.339471540154118, 'tweedie_variance_power': 1.891553556149269}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:57:55,486] Trial 286 finished with value: 6726.282775204186 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 523, 'learning_rate': 0.1904506622229251, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5871801576233164, 'colsample_bytree': 0.7449023431440249, 'colsample_bylevel': 0.9616906765049927, 'gamma': 8.956728815559327, 'alpha': 1.9512969398719153, 'lambda': 7.421561752148509, 'tweedie_variance_power': 1.9261388785795226}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:58:05,569] Trial 287 finished with value: 6661.283390467377 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 535, 'learning_rate': 0.1601348744985881, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6033034811302384, 'colsample_bytree': 0.7645979744962738, 'colsample_bylevel': 0.9713622796540359, 'gamma': 8.819890106544998, 'alpha': 3.1149012643298915, 'lambda': 9.59706264921072, 'tweedie_variance_power': 1.9545351012099175}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:58:15,449] Trial 288 finished with value: 6641.590104602164 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 550, 'learning_rate': 0.1770603416955772, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5608713626024424, 'colsample_bytree': 0.784067370130306, 'colsample_bylevel': 0.9474902642074412, 'gamma': 8.4890223943587, 'alpha': 0.33655954318368453, 'lambda': 6.815820410601829, 'tweedie_variance_power': 1.877732477425589}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:58:25,420] Trial 289 finished with value: 6644.67595551737 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 565, 'learning_rate': 0.21409457388874456, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5753627768305899, 'colsample_bytree': 0.8279611930171962, 'colsample_bylevel': 0.9875502514206613, 'gamma': 8.999054732407025, 'alpha': 2.7260282257422683, 'lambda': 7.795128262621845, 'tweedie_variance_power': 1.9021983558486326}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:58:34,816] Trial 290 finished with value: 189561.6211587304 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 510, 'learning_rate': 0.6529483478545869, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.538229807467284, 'colsample_bytree': 0.7303306765664543, 'colsample_bylevel': 0.9663698426533825, 'gamma': 8.264908309178695, 'alpha': 2.244563007456087, 'lambda': 7.2202724245097825, 'tweedie_variance_power': 1.9152984012562047}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:58:46,193] Trial 291 finished with value: inf and parameters: {'objective': 'reg:tweedie', 'n_estimators': 542, 'learning_rate': 0.9324779797637617, 'max_depth': 10, 'min_child_weight': 20, 'subsample': 0.630011391078701, 'colsample_bytree': 0.8084839247977466, 'colsample_bylevel': 0.9501620486174001, 'gamma': 8.650731999285195, 'alpha': 1.4867763839222632, 'lambda': 6.8181974694134135, 'tweedie_variance_power': 1.8663803634804321}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:58:56,426] Trial 292 finished with value: 6872.9733523145405 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 577, 'learning_rate': 0.15589733673790707, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.593144703831217, 'colsample_bytree': 0.7637265802493364, 'colsample_bylevel': 0.9878066258996915, 'gamma': 9.086808309234236, 'alpha': 0.4041870872535854, 'lambda': 7.998812230930286, 'tweedie_variance_power': 1.9411889777089253}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:59:07,372] Trial 293 finished with value: 6778.6477382572775 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 525, 'learning_rate': 0.13727856294635837, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.5519183115044909, 'colsample_bytree': 0.7904563826268385, 'colsample_bylevel': 0.9710121505242914, 'gamma': 8.80484939737712, 'alpha': 2.9104798517062744, 'lambda': 6.977127131959256, 'tweedie_variance_power': 1.8912408161977623}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:59:16,680] Trial 294 finished with value: 6678.6415999913015 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 499, 'learning_rate': 0.18667352553173128, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5799459663093901, 'colsample_bytree': 0.7468285971125397, 'colsample_bylevel': 0.9982106250923868, 'gamma': 8.502471227636912, 'alpha': 2.4361378913465384, 'lambda': 7.537339325235841, 'tweedie_variance_power': 1.903588696501627}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:59:26,832] Trial 295 finished with value: 6548.799168491417 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 586, 'learning_rate': 0.15741580182432582, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5633738228870488, 'colsample_bytree': 0.7800416724643288, 'colsample_bylevel': 0.9450621884720709, 'gamma': 9.046089170614177, 'alpha': 2.6765642587790808, 'lambda': 8.295552678241652, 'tweedie_variance_power': 1.883160232034378}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:59:36,813] Trial 296 finished with value: 7401.167988119556 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 587, 'learning_rate': 0.42095499466091213, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.56782468337467, 'colsample_bytree': 0.7699654861799865, 'colsample_bylevel': 0.9488524562293742, 'gamma': 8.997181689092299, 'alpha': 2.631969967481339, 'lambda': 8.525642587605896, 'tweedie_variance_power': 1.8762930318939544}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:59:47,012] Trial 297 finished with value: 6599.108608355872 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 576, 'learning_rate': 0.17080957110280517, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.606080938269245, 'colsample_bytree': 0.8036372785199755, 'colsample_bylevel': 0.9999884333958227, 'gamma': 8.728338342199452, 'alpha': 2.903486601260761, 'lambda': 8.33568700807153, 'tweedie_variance_power': 1.8631132353746767}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 09:59:57,189] Trial 298 finished with value: 6600.161279621847 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 572, 'learning_rate': 0.20278982680592444, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.615239017094277, 'colsample_bytree': 0.8163019074379958, 'colsample_bylevel': 0.9981789817737774, 'gamma': 8.728780967897668, 'alpha': 2.2420052411158946, 'lambda': 8.825298251685636, 'tweedie_variance_power': 1.8554686018061304}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:00:07,325] Trial 299 finished with value: 6666.4142224723855 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 575, 'learning_rate': 0.2728751473750711, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6180884719883764, 'colsample_bytree': 0.8182544148003768, 'colsample_bylevel': 0.9947958740732508, 'gamma': 8.71957460913501, 'alpha': 1.8885001933138672, 'lambda': 8.830542605879744, 'tweedie_variance_power': 1.8578163654970545}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:00:17,410] Trial 300 finished with value: 6624.870176267269 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 561, 'learning_rate': 0.2049264460065842, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6814764990192104, 'colsample_bytree': 0.8415076536539271, 'colsample_bylevel': 0.9986396873478836, 'gamma': 8.377200478951755, 'alpha': 0.032156012112281196, 'lambda': 9.12783018627648, 'tweedie_variance_power': 1.868296765864486}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:00:27,413] Trial 301 finished with value: 6609.035174025924 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 586, 'learning_rate': 0.23542261867190428, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6360046259877655, 'colsample_bytree': 0.7893757712910173, 'colsample_bylevel': 0.9787580541480098, 'gamma': 8.5806458546261, 'alpha': 2.2374280407196343, 'lambda': 8.319639155151473, 'tweedie_variance_power': 1.8595153106993352}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:00:37,574] Trial 302 finished with value: 6627.102501529139 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 570, 'learning_rate': 0.1818988713401659, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6081572889373205, 'colsample_bytree': 0.8109842526937114, 'colsample_bylevel': 0.967207583636531, 'gamma': 8.20580854333355, 'alpha': 2.4419777993198215, 'lambda': 8.781621052679887, 'tweedie_variance_power': 1.8809236889423357}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:00:47,658] Trial 303 finished with value: 6631.105667091718 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 579, 'learning_rate': 0.2028101419812414, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6005175754829257, 'colsample_bytree': 0.8536363045009677, 'colsample_bylevel': 0.9846008802598695, 'gamma': 7.94384075669491, 'alpha': 2.0824880872294265, 'lambda': 8.322740193242526, 'tweedie_variance_power': 1.8537078070996071}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:00:57,469] Trial 304 finished with value: 6610.152368762097 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 555, 'learning_rate': 0.16609214774538916, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6597721033880112, 'colsample_bytree': 0.7755340164264022, 'colsample_bylevel': 0.9998231285955803, 'gamma': 8.804885624895237, 'alpha': 2.6337113388038245, 'lambda': 8.367620025868954, 'tweedie_variance_power': 1.881354239967187}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:01:07,616] Trial 305 finished with value: 6639.407598300109 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 571, 'learning_rate': 0.28745534729861333, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6178745525977551, 'colsample_bytree': 0.755372368218922, 'colsample_bylevel': 0.9631559203530469, 'gamma': 8.596217241456252, 'alpha': 1.7397725450418857, 'lambda': 9.500287459710194, 'tweedie_variance_power': 1.8650710277598745}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:01:17,642] Trial 306 finished with value: 7696.062187957789 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 589, 'learning_rate': 0.22666196473598466, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5621519022984951, 'colsample_bytree': 0.7859916010247041, 'colsample_bylevel': 0.9771599014566309, 'gamma': 8.844288879601, 'alpha': 2.3150058860846294, 'lambda': 8.921579101081324, 'tweedie_variance_power': 1.9284117549921003}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:01:27,134] Trial 307 finished with value: 6628.488117636026 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 544, 'learning_rate': 0.17895017173936462, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5978064081800625, 'colsample_bytree': 0.8321340862175741, 'colsample_bylevel': 0.9561189830998977, 'gamma': 8.412557163780567, 'alpha': 2.7915316631442315, 'lambda': 8.679353893961883, 'tweedie_variance_power': 1.8859294926674612}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:01:36,927] Trial 308 finished with value: 6620.0610386095495 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 563, 'learning_rate': 0.1566706061502256, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5853942132326424, 'colsample_bytree': 0.8091247709171748, 'colsample_bylevel': 0.9833136944174462, 'gamma': 8.67489957568395, 'alpha': 0.7571539711752344, 'lambda': 7.87577901999866, 'tweedie_variance_power': 1.8512559942519007}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:01:47,435] Trial 309 finished with value: 6699.57396185384 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 594, 'learning_rate': 0.19454124149042734, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6359129144193703, 'colsample_bytree': 0.7668179161086555, 'colsample_bylevel': 0.9692099686002472, 'gamma': 8.15045527704444, 'alpha': 2.527882626514896, 'lambda': 8.51096096666549, 'tweedie_variance_power': 1.9175388486645775}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:01:58,227] Trial 310 finished with value: 6788.862393410978 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 532, 'learning_rate': 0.16932774748129947, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.5594250726545509, 'colsample_bytree': 0.7377345176107905, 'colsample_bylevel': 0.9456785657410451, 'gamma': 8.948973961646923, 'alpha': 2.1060001731543267, 'lambda': 7.290365375899436, 'tweedie_variance_power': 1.872603383843079}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:02:08,180] Trial 311 finished with value: 6639.6262491008565 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 580, 'learning_rate': 0.1435887253176286, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5439654110572509, 'colsample_bytree': 0.7983685471403208, 'colsample_bylevel': 0.9843051418092331, 'gamma': 8.527696401772328, 'alpha': 2.844542003764437, 'lambda': 8.199681451209557, 'tweedie_variance_power': 1.891133222427545}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:02:18,317] Trial 312 finished with value: 7532.699209797631 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 599, 'learning_rate': 0.21003210158702393, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5773576003958764, 'colsample_bytree': 0.7814664377948739, 'colsample_bylevel': 0.9610605480351351, 'gamma': 8.934063813663482, 'alpha': 2.313180139608742, 'lambda': 7.7261847660160035, 'tweedie_variance_power': 1.9397052984344811}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:02:29,554] Trial 313 finished with value: 372674.24529174133 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 553, 'learning_rate': 0.2484103234849866, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.6528196114196948, 'colsample_bytree': 0.753006040117134, 'colsample_bylevel': 0.9867337019049054, 'gamma': 8.341174756573396, 'alpha': 1.3301906121992249, 'lambda': 7.107499062253811, 'tweedie_variance_power': 1.9113089522958777}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:02:39,452] Trial 314 finished with value: 6613.674033121133 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 574, 'learning_rate': 0.1537904086527366, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6163215745105708, 'colsample_bytree': 0.8279441448437536, 'colsample_bylevel': 0.9982722809861433, 'gamma': 8.691927328394032, 'alpha': 2.605855038746596, 'lambda': 7.965122215221428, 'tweedie_variance_power': 1.8794418308973302}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:02:49,222] Trial 315 finished with value: 10073.726734091628 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 566, 'learning_rate': 0.18588023081870805, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5924156979832875, 'colsample_bytree': 0.7722474172393881, 'colsample_bylevel': 0.9694403741955168, 'gamma': 9.085045824419389, 'alpha': 1.991718656374729, 'lambda': 7.426104901458656, 'tweedie_variance_power': 1.963825280069266}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:02:59,218] Trial 316 finished with value: 6602.616367073485 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 587, 'learning_rate': 0.16316445394598952, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5640456727870303, 'colsample_bytree': 0.8008029291660462, 'colsample_bylevel': 0.9439876815700406, 'gamma': 0.9404505694308947, 'alpha': 1.610448633865792, 'lambda': 9.276600355411365, 'tweedie_variance_power': 1.8577892691675701}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:03:09,230] Trial 317 finished with value: 6607.713977740453 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 586, 'learning_rate': 0.1640751393295234, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6993523044585566, 'colsample_bytree': 0.735691320076236, 'colsample_bylevel': 0.9418830854118626, 'gamma': 2.359439785601876, 'alpha': 1.8327098710535503, 'lambda': 7.544681439344061, 'tweedie_variance_power': 1.8469492439827149}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:03:19,220] Trial 318 finished with value: 6576.819113043217 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 580, 'learning_rate': 0.19416743779585083, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5717896976502134, 'colsample_bytree': 0.8005487482834918, 'colsample_bylevel': 0.9999543728150833, 'gamma': 6.579840954571075, 'alpha': 1.6273841750835103, 'lambda': 9.190808190661212, 'tweedie_variance_power': 1.8638209916943889}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:03:32,839] Trial 319 finished with value: 279649.39290251414 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 581, 'learning_rate': 0.21869264764681662, 'max_depth': 4, 'min_child_weight': 19, 'subsample': 0.6011358544307697, 'colsample_bytree': 0.8146723075249283, 'colsample_bylevel': 0.9991839660971084, 'gamma': 6.38450678414698, 'alpha': 1.57368356965894, 'lambda': 9.434698758888727, 'tweedie_variance_power': 1.855468013702601}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:03:42,617] Trial 320 finished with value: 6644.430618197798 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 591, 'learning_rate': 0.19469043623256374, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5732332691275652, 'colsample_bytree': 0.8028788155187297, 'colsample_bylevel': 0.9537808136201765, 'gamma': 0.17437069432763463, 'alpha': 1.2085337018581916, 'lambda': 9.156620467761577, 'tweedie_variance_power': 1.8649981556190842}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:03:52,402] Trial 321 finished with value: 6648.860134903671 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 561, 'learning_rate': 0.23903407633273469, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5855175697507341, 'colsample_bytree': 0.7925074241175956, 'colsample_bylevel': 0.9590526641799786, 'gamma': 8.767270693105518, 'alpha': 1.7136699928583448, 'lambda': 9.306425794046763, 'tweedie_variance_power': 1.8416082344739724}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:04:02,335] Trial 322 finished with value: 6615.096217042794 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 575, 'learning_rate': 0.17296289317514377, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6286653785203691, 'colsample_bytree': 0.8212372838848448, 'colsample_bylevel': 0.98330949959295, 'gamma': 6.74876498636742, 'alpha': 1.5106908868366848, 'lambda': 9.012310322086154, 'tweedie_variance_power': 1.8619692137172872}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:04:12,081] Trial 323 finished with value: 6611.059125552838 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 537, 'learning_rate': 0.2130178257990251, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5673289305860278, 'colsample_bytree': 0.775695755407955, 'colsample_bylevel': 0.9417834303941831, 'gamma': 1.1402187178295418, 'alpha': 2.9083821738128517, 'lambda': 9.312193552660993, 'tweedie_variance_power': 1.8723063272879947}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:04:23,535] Trial 324 finished with value: 6641.155727759854 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 598, 'learning_rate': 0.1961278239850801, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.6117456993491215, 'colsample_bytree': 0.8857520551766727, 'colsample_bylevel': 0.9718664324743774, 'gamma': 4.59740793712354, 'alpha': 1.0441366882731784, 'lambda': 8.970164986738414, 'tweedie_variance_power': 1.8291917407074068}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:04:33,239] Trial 325 finished with value: 6595.630460692879 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 568, 'learning_rate': 0.17252376040943754, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5872058801188547, 'colsample_bytree': 0.8021458525578072, 'colsample_bylevel': 0.9977578767347, 'gamma': 8.980254380255472, 'alpha': 2.6748428324720908, 'lambda': 9.791410478137772, 'tweedie_variance_power': 1.8874814071490915}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:04:43,203] Trial 326 finished with value: 6599.580056962623 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 584, 'learning_rate': 0.18226746229135346, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.591679528720765, 'colsample_bytree': 0.8017350980231323, 'colsample_bylevel': 0.9953564834820786, 'gamma': 0.6738182230897155, 'alpha': 3.314801942727688, 'lambda': 9.800236411427154, 'tweedie_variance_power': 1.892633079224677}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:04:53,420] Trial 327 finished with value: 6563.314792344256 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 585, 'learning_rate': 0.18878255784849693, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5991351286690965, 'colsample_bytree': 0.8049008762806232, 'colsample_bylevel': 0.9988160433367756, 'gamma': 8.852068378293877, 'alpha': 3.3348809209986428, 'lambda': 9.573200356273384, 'tweedie_variance_power': 1.8905301121041453}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:05:03,671] Trial 328 finished with value: 6562.000979603467 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 584, 'learning_rate': 0.23010162853351138, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.6039057308185782, 'colsample_bytree': 0.8346675338434167, 'colsample_bylevel': 0.9969276905292949, 'gamma': 0.7774244044624448, 'alpha': 3.345843312009925, 'lambda': 9.838537101257195, 'tweedie_variance_power': 1.8497841103585033}. Best is trial 218 with value: 6477.950199572396.

[I 2026-08-31 10:05:13,795] Trial 329 finished with value: 6469.6972025111745 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 570, 'learning_rate': 0.2595525275491146, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.6064480180480966, 'colsample_bytree': 0.8405603469782187, 'colsample_bylevel': 0.9959895581557628, 'gamma': 5.529890290582709, 'alpha': 3.275010657889333, 'lambda': 9.461731268272077, 'tweedie_variance_power': 1.8914621343096838}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:05:23,704] Trial 330 finished with value: 6648.9976300344915 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 582, 'learning_rate': 0.24258254421988595, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.6012671045462911, 'colsample_bytree': 0.8609934697831693, 'colsample_bylevel': 0.9968590550358273, 'gamma': 0.31704805591318075, 'alpha': 3.439430622040729, 'lambda': 9.954427075080263, 'tweedie_variance_power': 1.8925342968572727}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:05:34,071] Trial 331 finished with value: 6897.602408482422 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 600, 'learning_rate': 0.28656791586077074, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.6362953131461547, 'colsample_bytree': 0.8316337924034118, 'colsample_bylevel': 0.99647216443515, 'gamma': 5.392282594918168, 'alpha': 3.267487416445966, 'lambda': 9.645246184393562, 'tweedie_variance_power': 1.896801390854137}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:05:43,863] Trial 332 finished with value: 8133.439695485678 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 565, 'learning_rate': 0.262577641800607, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5965635884831658, 'colsample_bytree': 0.8423028041590763, 'colsample_bylevel': 0.987656083311353, 'gamma': 0.5983932291602476, 'alpha': 3.460597950197803, 'lambda': 9.76427912118798, 'tweedie_variance_power': 1.9240739933031914}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:05:53,857] Trial 333 finished with value: 6608.487149012357 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 578, 'learning_rate': 0.2611087412103945, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5892794046182365, 'colsample_bytree': 0.8475329548410238, 'colsample_bylevel': 0.9993352647289991, 'gamma': 0.9127083308804904, 'alpha': 3.2864205314434556, 'lambda': 9.56222651665918, 'tweedie_variance_power': 1.8783467052763188}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:06:04,096] Trial 334 finished with value: 6680.331161119833 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 589, 'learning_rate': 0.23757669751270785, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.6075012643557712, 'colsample_bytree': 0.8818394319131739, 'colsample_bylevel': 0.9997781152841232, 'gamma': 5.046417727447666, 'alpha': 3.2058930574154565, 'lambda': 9.679568663586707, 'tweedie_variance_power': 1.9066686825393544}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:06:14,391] Trial 335 finished with value: 6910.492832810373 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 569, 'learning_rate': 0.3155656515944429, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5855285911598875, 'colsample_bytree': 0.8290258704363507, 'colsample_bylevel': 0.969118779869467, 'gamma': 5.925605489189468, 'alpha': 2.9913785428183584, 'lambda': 9.910608565397931, 'tweedie_variance_power': 1.882797643032844}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:06:25,976] Trial 336 finished with value: 34228070832.543594 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 581, 'learning_rate': 0.2210977862248048, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.6467967224011214, 'colsample_bytree': 0.8099315886473544, 'colsample_bylevel': 0.9811936796024973, 'gamma': 6.054240663302399, 'alpha': 2.8112213568692863, 'lambda': 9.758985396552198, 'tweedie_variance_power': 1.9298056550518643}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:06:35,754] Trial 337 finished with value: 6601.3330593757 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 557, 'learning_rate': 0.1873421442676999, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6184655109406296, 'colsample_bytree': 0.7904312877917146, 'colsample_bylevel': 0.9598280736778444, 'gamma': 0.4809583366335657, 'alpha': 3.3494072995547826, 'lambda': 9.454071691054883, 'tweedie_variance_power': 1.8985259510806431}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:06:45,920] Trial 338 finished with value: 6617.126203717862 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 588, 'learning_rate': 0.21681037096347242, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.6260793156800323, 'colsample_bytree': 0.8015974113303891, 'colsample_bylevel': 0.9992569628949735, 'gamma': 7.1860151649423605, 'alpha': 0.44905524978673705, 'lambda': 9.91355407650102, 'tweedie_variance_power': 1.87787801620166}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:06:55,759] Trial 339 finished with value: 6606.301520030719 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 569, 'learning_rate': 0.1846766032435616, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6010310598479875, 'colsample_bytree': 0.8205244425351933, 'colsample_bylevel': 0.9751827382097892, 'gamma': 8.376344753362009, 'alpha': 3.1483616490378026, 'lambda': 9.983083699036653, 'tweedie_variance_power': 1.870370214113013}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:07:05,864] Trial 340 finished with value: 6966.057306977225 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 579, 'learning_rate': 0.23333021794003708, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5821283785063013, 'colsample_bytree': 0.7861660112221134, 'colsample_bylevel': 0.9833305907485536, 'gamma': 1.4242304822032499, 'alpha': 2.7613470000557743, 'lambda': 9.765770178781231, 'tweedie_variance_power': 1.9162702617624123}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:07:15,725] Trial 341 finished with value: 6592.316965367797 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 558, 'learning_rate': 0.1753863838812908, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5908100645691325, 'colsample_bytree': 0.8471340103805973, 'colsample_bylevel': 0.961567727918573, 'gamma': 5.713902792038102, 'alpha': 3.683181400879847, 'lambda': 9.605023021516281, 'tweedie_variance_power': 1.8958750635069195}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:07:25,547] Trial 342 finished with value: 6719.201689955233 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 559, 'learning_rate': 0.20052354672242492, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.583019562895454, 'colsample_bytree': 0.8551550092472898, 'colsample_bylevel': 0.999664167033738, 'gamma': 0.6496622382140181, 'alpha': 3.7121679138755295, 'lambda': 9.38846638536631, 'tweedie_variance_power': 1.9039179444358623}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:07:35,138] Trial 343 finished with value: 45376.596451099365 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 548, 'learning_rate': 0.34266453010821996, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5935423604162144, 'colsample_bytree': 0.8473509080012354, 'colsample_bylevel': 0.958739111099327, 'gamma': 4.803647426793478, 'alpha': 3.5133500985340627, 'lambda': 9.61895947913866, 'tweedie_variance_power': 1.95443941201775}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:07:44,957] Trial 344 finished with value: 6674.298855411942 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 569, 'learning_rate': 0.27507863191216025, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5786037008895359, 'colsample_bytree': 0.8316812423609781, 'colsample_bylevel': 0.9803288339893234, 'gamma': 4.07177603785903, 'alpha': 3.5800904650735785, 'lambda': 9.765087737627567, 'tweedie_variance_power': 1.894053556059175}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:07:54,720] Trial 345 finished with value: 6685.010854257256 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 561, 'learning_rate': 0.17526179045653276, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6050417446841541, 'colsample_bytree': 0.8080135751094578, 'colsample_bylevel': 0.9703160475587801, 'gamma': 6.797434704679265, 'alpha': 3.081625433590721, 'lambda': 9.495184689986903, 'tweedie_variance_power': 1.938987593505912}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:08:04,657] Trial 346 finished with value: 6758.767920441794 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 573, 'learning_rate': 0.21301453489642566, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5702520744701624, 'colsample_bytree': 0.8220372351810955, 'colsample_bylevel': 0.9518200472917558, 'gamma': 6.519705929051878, 'alpha': 2.5805706869575653, 'lambda': 9.801999543921232, 'tweedie_variance_power': 1.9211095319099514}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:08:14,215] Trial 347 finished with value: 6630.748499069859 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 543, 'learning_rate': 0.18942181466429706, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5539894566361627, 'colsample_bytree': 0.7906737660092572, 'colsample_bylevel': 0.9803131286700952, 'gamma': 7.547707981640867, 'alpha': 2.921113287697497, 'lambda': 9.599987964853462, 'tweedie_variance_power': 1.8893415040476014}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:08:24,304] Trial 348 finished with value: 6806.514339536371 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 600, 'learning_rate': 0.253850425383449, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5921076859572774, 'colsample_bytree': 0.8380855798636477, 'colsample_bylevel': 0.9864640704852772, 'gamma': 6.22248589118637, 'alpha': 3.3335503259566046, 'lambda': 9.391273763199239, 'tweedie_variance_power': 1.9061871304801774}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:08:35,710] Trial 349 finished with value: 136206491.89935791 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 554, 'learning_rate': 0.16491240639905455, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.6090669591755852, 'colsample_bytree': 0.8039228118549775, 'colsample_bylevel': 0.9628553602260959, 'gamma': 3.4980877806585005, 'alpha': 2.486832786283688, 'lambda': 9.169595585056923, 'tweedie_variance_power': 1.9247075469124593}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:08:45,720] Trial 350 finished with value: 6635.705351254776 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 589, 'learning_rate': 0.22548978448906182, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.5770330770009972, 'colsample_bytree': 0.8676731623816, 'colsample_bylevel': 0.9992522450678724, 'gamma': 7.758567089809985, 'alpha': 2.7218784075361633, 'lambda': 0.8194946213611676, 'tweedie_variance_power': 1.8415920713856508}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:08:55,632] Trial 351 finished with value: 6614.15111013632 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 575, 'learning_rate': 0.15165043561758026, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5454631687408557, 'colsample_bytree': 0.7805226207998567, 'colsample_bylevel': 0.9384237437926666, 'gamma': 5.758044036814133, 'alpha': 3.15010553908145, 'lambda': 9.984467357725402, 'tweedie_variance_power': 1.8915081340148152}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:09:12,100] Trial 352 finished with value: 489569841102960.3 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 562, 'learning_rate': 0.1987190290691881, 'max_depth': 8, 'min_child_weight': 20, 'subsample': 0.592470707234718, 'colsample_bytree': 0.8182605945585739, 'colsample_bylevel': 0.971279966211619, 'gamma': 5.552083652455751, 'alpha': 2.481124758820161, 'lambda': 9.636560970678616, 'tweedie_variance_power': 1.9068722886062757}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:09:21,966] Trial 353 finished with value: 6539.957742098576 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 583, 'learning_rate': 0.18470137036352052, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5632980405949524, 'colsample_bytree': 0.7956307062364553, 'colsample_bylevel': 0.9864530324005907, 'gamma': 1.4844671819639297, 'alpha': 2.9280448531111865, 'lambda': 9.262882202264802, 'tweedie_variance_power': 1.8659966975090896}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:09:31,908] Trial 354 finished with value: 6612.947426745321 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 567, 'learning_rate': 0.14157797587878446, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5583666615145274, 'colsample_bytree': 0.7799742962311268, 'colsample_bylevel': 0.9550475664904299, 'gamma': 1.854937701797657, 'alpha': 2.9273847908425803, 'lambda': 9.161033837935953, 'tweedie_variance_power': 1.8566074864881614}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:09:41,887] Trial 355 finished with value: 6651.001628023418 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 577, 'learning_rate': 0.17445880654210671, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5391075030993644, 'colsample_bytree': 0.7710489438389008, 'colsample_bylevel': 0.975711190824749, 'gamma': 3.1326110057080063, 'alpha': 2.7302393516955514, 'lambda': 9.332349061657586, 'tweedie_variance_power': 1.866768492562654}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:09:52,091] Trial 356 finished with value: 6612.958591410226 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 533, 'learning_rate': 0.1524484721226511, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5720328140873477, 'colsample_bytree': 0.8427550676620573, 'colsample_bylevel': 0.9508321558881152, 'gamma': 2.6372357962060944, 'alpha': 2.4111910791324775, 'lambda': 9.171970538390193, 'tweedie_variance_power': 1.83600188940012}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:10:02,649] Trial 357 finished with value: 5.165647031192188e+28 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 551, 'learning_rate': 0.20404818319337575, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.6694268375167854, 'colsample_bytree': 0.7944298823450977, 'colsample_bylevel': 0.9844703552664515, 'gamma': 1.5070309304694296, 'alpha': 2.938913572073379, 'lambda': 7.190863438573565, 'tweedie_variance_power': 1.9828673497812042}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:10:12,633] Trial 358 finished with value: 6753.599724635866 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 590, 'learning_rate': 0.22771977088120005, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5580279274142035, 'colsample_bytree': 0.7640627832996825, 'colsample_bylevel': 0.9674230848751386, 'gamma': 5.539115019144897, 'alpha': 2.6431623051189654, 'lambda': 7.713935201462123, 'tweedie_variance_power': 1.8754260854276654}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:10:22,555] Trial 359 finished with value: 6612.720413140244 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 577, 'learning_rate': 0.1358270813320982, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6179288723134503, 'colsample_bytree': 0.8226255033907869, 'colsample_bylevel': 0.9382915234924702, 'gamma': 4.440950642414742, 'alpha': 2.443243662417904, 'lambda': 9.41665882954391, 'tweedie_variance_power': 1.8514955250185543}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:10:32,277] Trial 360 finished with value: 6626.907314783148 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 560, 'learning_rate': 0.16998608779038385, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5769788505663781, 'colsample_bytree': 0.7946094954469793, 'colsample_bylevel': 0.984589705051545, 'gamma': 8.926831073227838, 'alpha': 2.7931525625718923, 'lambda': 8.124119491076444, 'tweedie_variance_power': 1.8780679828715106}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:10:42,365] Trial 361 finished with value: 6607.550450102831 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 593, 'learning_rate': 0.12599621591746954, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6424505223230983, 'colsample_bytree': 0.8099669379006285, 'colsample_bylevel': 0.9637955985236781, 'gamma': 8.063875605201101, 'alpha': 2.1598695074346703, 'lambda': 9.55957798708985, 'tweedie_variance_power': 1.929920119352067}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:10:52,201] Trial 362 finished with value: 8170.185166857555 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 544, 'learning_rate': 0.2916156342758339, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6051312524919609, 'colsample_bytree': 0.7837115797080181, 'colsample_bylevel': 0.9991420017404633, 'gamma': 8.59696598817644, 'alpha': 2.6465670869482754, 'lambda': 7.291057379385421, 'tweedie_variance_power': 1.9427885301524743}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:11:02,198] Trial 363 finished with value: 6603.74784599737 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 569, 'learning_rate': 0.15869754070221823, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5562839359366576, 'colsample_bytree': 0.7715602327319547, 'colsample_bylevel': 0.9744754417174799, 'gamma': 5.24222233044026, 'alpha': 3.0970388571533296, 'lambda': 8.630856676121837, 'tweedie_variance_power': 1.9169740609519645}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:11:12,358] Trial 364 finished with value: 6736.004823161961 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 582, 'learning_rate': 0.2501030904099359, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5390107860968884, 'colsample_bytree': 0.8298186305639569, 'colsample_bylevel': 0.9434220565070027, 'gamma': 3.7718834894964237, 'alpha': 2.357412419766287, 'lambda': 7.047527444430967, 'tweedie_variance_power': 1.865857175542311}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:11:22,223] Trial 365 finished with value: 6645.6930978175105 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 555, 'learning_rate': 0.19044535170505583, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5772720297673598, 'colsample_bytree': 0.9019078666039024, 'colsample_bylevel': 0.9842814137423246, 'gamma': 2.088086374916644, 'alpha': 2.9671737447902578, 'lambda': 7.653786372741318, 'tweedie_variance_power': 1.8907669556108422}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:11:31,859] Trial 366 finished with value: 6634.216948516687 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 531, 'learning_rate': 0.20441580661487438, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.8186403595963133, 'colsample_bytree': 0.8026729132554424, 'colsample_bylevel': 0.9670898985204874, 'gamma': 8.972059352787142, 'alpha': 3.659196613444927, 'lambda': 6.997524496915114, 'tweedie_variance_power': 1.9046232376387822}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:11:42,025] Trial 367 finished with value: 6616.11762112332 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 600, 'learning_rate': 0.1389471158007457, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5654375861609098, 'colsample_bytree': 0.7611533456590304, 'colsample_bylevel': 0.9506344092403374, 'gamma': 6.939012676978734, 'alpha': 1.9338493805253627, 'lambda': 7.289988156438471, 'tweedie_variance_power': 1.8234434213703037}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:11:51,805] Trial 368 finished with value: 6620.315160734298 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 567, 'learning_rate': 0.17669365579246027, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5903241333366221, 'colsample_bytree': 0.8463698323899911, 'colsample_bylevel': 0.9861045176498745, 'gamma': 8.477744060149156, 'alpha': 2.6346142607775374, 'lambda': 7.933652580605334, 'tweedie_variance_power': 1.8487503044327582}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:12:02,752] Trial 369 finished with value: 6644.6552655740725 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 580, 'learning_rate': 0.23186409995266333, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.6236141783528396, 'colsample_bytree': 0.7824640745536402, 'colsample_bylevel': 0.9602852050118251, 'gamma': 8.267224701894179, 'alpha': 2.8469318117883358, 'lambda': 7.508761852874435, 'tweedie_variance_power': 1.8821270587334085}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:12:13,318] Trial 370 finished with value: 6617.591318724647 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 508, 'learning_rate': 0.11692851738616183, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6104304755988589, 'colsample_bytree': 0.810188764297483, 'colsample_bylevel': 0.9859384645752176, 'gamma': 7.413576148045835, 'alpha': 0.6520286454532098, 'lambda': 8.991038558366089, 'tweedie_variance_power': 1.8623829903400555}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:12:25,655] Trial 371 finished with value: 6622.970110247263 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 592, 'learning_rate': 0.15292980036189194, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8754326336946316, 'colsample_bytree': 0.7927986293237037, 'colsample_bylevel': 0.9994156726818205, 'gamma': 8.876884424143643, 'alpha': 3.1739874483705712, 'lambda': 7.107031819971058, 'tweedie_variance_power': 1.9113851726792856}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:12:36,257] Trial 372 finished with value: 6689.589475391561 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 573, 'learning_rate': 0.21415430508675184, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.5798034661116831, 'colsample_bytree': 0.8252385978988536, 'colsample_bylevel': 0.9690836358819311, 'gamma': 8.56198907166884, 'alpha': 2.413327151614114, 'lambda': 9.473674870529921, 'tweedie_variance_power': 1.8868732521539906}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:12:46,603] Trial 373 finished with value: 6567.82832615254 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 543, 'learning_rate': 0.16527488446219823, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.5514665408512355, 'colsample_bytree': 0.7622477495981032, 'colsample_bylevel': 0.9383206312495501, 'gamma': 7.972616591288442, 'alpha': 0.2312162140754968, 'lambda': 9.31233664758459, 'tweedie_variance_power': 1.8960311096402713}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:12:57,039] Trial 374 finished with value: 6523.287889026174 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 542, 'learning_rate': 0.1352313332166145, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5442447159604922, 'colsample_bytree': 0.7315909972706222, 'colsample_bylevel': 0.9390809913712925, 'gamma': 7.913264794069304, 'alpha': 0.13715589021556673, 'lambda': 9.247608621806977, 'tweedie_variance_power': 1.9308452212552432}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:13:07,552] Trial 375 finished with value: 6698.356689700205 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 524, 'learning_rate': 0.14220379326923144, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5427954931392499, 'colsample_bytree': 0.7287627687508429, 'colsample_bylevel': 0.9354009981342134, 'gamma': 4.969515315837196, 'alpha': 0.1840314400088911, 'lambda': 9.179518309377901, 'tweedie_variance_power': 1.9478158667685987}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:13:17,937] Trial 376 finished with value: 7087.976785578467 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 541, 'learning_rate': 0.18326183787103584, 'max_depth': 1, 'min_child_weight': 1, 'subsample': 0.5393623523792686, 'colsample_bytree': 0.7419685150250382, 'colsample_bylevel': 0.9428947637008348, 'gamma': 7.884361437966729, 'alpha': 0.8809318684047491, 'lambda': 9.033112961923198, 'tweedie_variance_power': 1.9364257834672434}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:13:30,173] Trial 377 finished with value: 1981740229.3161807 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 535, 'learning_rate': 0.1581582118134025, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.553969241871327, 'colsample_bytree': 0.8614597328413156, 'colsample_bylevel': 0.9310646960113704, 'gamma': 7.646059169330214, 'alpha': 0.006146823678931879, 'lambda': 9.323408108843516, 'tweedie_variance_power': 1.9579059426086498}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:13:40,301] Trial 378 finished with value: 4800699.973037408 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 549, 'learning_rate': 0.8068935506000685, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5352030549056754, 'colsample_bytree': 0.7600888105683862, 'colsample_bylevel': 0.9499278184047583, 'gamma': 7.93561086783808, 'alpha': 0.2275635080872291, 'lambda': 9.697984613099434, 'tweedie_variance_power': 1.920545827405624}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:13:50,471] Trial 379 finished with value: 6643.094234318758 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 515, 'learning_rate': 0.1951602802807323, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.559068629108603, 'colsample_bytree': 0.7595417684485334, 'colsample_bylevel': 0.9405974862327717, 'gamma': 8.079298081497415, 'alpha': 0.5004540193135335, 'lambda': 9.328342334046246, 'tweedie_variance_power': 1.906312792436642}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:14:00,830] Trial 380 finished with value: 7306.105451788655 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 524, 'learning_rate': 0.2647292054205795, 'max_depth': 1, 'min_child_weight': 1, 'subsample': 0.564638557630144, 'colsample_bytree': 0.7680438704875956, 'colsample_bylevel': 0.9561343828583708, 'gamma': 8.248962201320923, 'alpha': 0.2574434243045467, 'lambda': 9.46113958809347, 'tweedie_variance_power': 1.9314249244234787}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:14:11,778] Trial 381 finished with value: 6611.833257710115 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 542, 'learning_rate': 0.1369327143003406, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5378362105675667, 'colsample_bytree': 0.7327308362206281, 'colsample_bylevel': 0.9342556679062317, 'gamma': 2.899700131213149, 'alpha': 0.33175527501133656, 'lambda': 9.194939385352473, 'tweedie_variance_power': 1.9179025591449468}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:14:29,625] Trial 382 finished with value: 5163478264039.073 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 555, 'learning_rate': 0.1657374252430114, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.5509303182108802, 'colsample_bytree': 0.7429616111021641, 'colsample_bylevel': 0.9569634854625627, 'gamma': 7.841917960850575, 'alpha': 0.1848450374684871, 'lambda': 9.663017872650876, 'tweedie_variance_power': 1.8960530248563336}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:14:38,905] Trial 383 finished with value: 23268.099738803896 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 527, 'learning_rate': 0.21383665706171862, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5712105635672489, 'colsample_bytree': 0.7841182010034257, 'colsample_bylevel': 0.970102092300763, 'gamma': 8.076365071598495, 'alpha': 0.6572742354850039, 'lambda': 8.878373489917077, 'tweedie_variance_power': 1.963555627059636}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:14:48,894] Trial 384 finished with value: 6846.860111804176 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 545, 'learning_rate': 0.18970205392392342, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.5905924248207611, 'colsample_bytree': 0.8300338611716434, 'colsample_bylevel': 0.9528817182207668, 'gamma': 8.251524655959797, 'alpha': 0.38168649002323846, 'lambda': 9.470692768624023, 'tweedie_variance_power': 1.9430424922049314}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:14:58,858] Trial 385 finished with value: 6593.822115607238 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 560, 'learning_rate': 0.11937898658719959, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5636504983515654, 'colsample_bytree': 0.7574220761406645, 'colsample_bylevel': 0.9730821937861915, 'gamma': 7.203330929893174, 'alpha': 2.1150183511146654, 'lambda': 9.708772333017924, 'tweedie_variance_power': 1.9036046527746442}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:15:08,853] Trial 386 finished with value: 6607.1634506566 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 557, 'learning_rate': 0.15159140385925793, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.700271151966756, 'colsample_bytree': 0.8118421336851247, 'colsample_bylevel': 0.9306927146361303, 'gamma': 7.075669015886326, 'alpha': 3.4964593660999825, 'lambda': 9.850139182060282, 'tweedie_variance_power': 1.9257628613118623}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:15:18,721] Trial 387 finished with value: 11284.754302088939 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 536, 'learning_rate': 0.4995789759382976, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5531635057241738, 'colsample_bytree': 0.788011755734421, 'colsample_bylevel': 0.9674529620904867, 'gamma': 7.266568392385027, 'alpha': 0.49906497158562807, 'lambda': 9.607390166776996, 'tweedie_variance_power': 1.9061195015319787}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:15:28,955] Trial 388 finished with value: 6783.553789259131 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 562, 'learning_rate': 0.24413234743118745, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5873873650271072, 'colsample_bytree': 0.7231425922356198, 'colsample_bylevel': 0.982885172604829, 'gamma': 6.277099516536868, 'alpha': 0.06191522416051111, 'lambda': 9.95184206901773, 'tweedie_variance_power': 1.9170761458667005}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:15:38,528] Trial 389 finished with value: 6613.968580923464 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 492, 'learning_rate': 0.1078213072919881, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.6558828669793044, 'colsample_bytree': 0.767612179548256, 'colsample_bylevel': 0.9565821018200793, 'gamma': 6.560634256909081, 'alpha': 2.175364319242879, 'lambda': 9.795943726759816, 'tweedie_variance_power': 1.9008669174938664}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:15:48,550] Trial 390 finished with value: 7535.295776413233 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 552, 'learning_rate': 0.172237335579045, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5306001451909945, 'colsample_bytree': 0.8505452730243726, 'colsample_bylevel': 0.9418168985349398, 'gamma': 7.722571058858597, 'alpha': 1.9846141899062744, 'lambda': 9.04779708117168, 'tweedie_variance_power': 1.9485144475087457}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:15:58,015] Trial 391 finished with value: 6633.565422922364 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 506, 'learning_rate': 0.12835285614657582, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5699576822008334, 'colsample_bytree': 0.7915475893558015, 'colsample_bylevel': 0.9837029381845891, 'gamma': 7.501974613009685, 'alpha': 2.56668429273964, 'lambda': 9.295189216249927, 'tweedie_variance_power': 1.932954585057186}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:16:08,084] Trial 392 finished with value: 6580.0751766865815 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 536, 'learning_rate': 0.20810654716850516, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.595527673338912, 'colsample_bytree': 0.8165861285616286, 'colsample_bylevel': 0.9693837282606305, 'gamma': 1.695190326878756, 'alpha': 3.163969126559289, 'lambda': 9.688333487125865, 'tweedie_variance_power': 1.903351705570701}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:16:21,838] Trial 393 finished with value: 183157196925.5016 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 534, 'learning_rate': 0.22045392793061952, 'max_depth': 5, 'min_child_weight': 18, 'subsample': 0.6358085621313523, 'colsample_bytree': 0.8413712371255485, 'colsample_bylevel': 0.9727236067594711, 'gamma': 1.3951612771199144, 'alpha': 3.3628681494517907, 'lambda': 9.58085226068343, 'tweedie_variance_power': 1.9157081996893695}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:16:33,662] Trial 394 finished with value: 1557012505.3768432 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 543, 'learning_rate': 0.23784668375006668, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.5993504161235844, 'colsample_bytree': 0.8197428579999465, 'colsample_bylevel': 0.9847144643727533, 'gamma': 0.8740061056329419, 'alpha': 3.1415684434549265, 'lambda': 9.960061772407313, 'tweedie_variance_power': 1.8946510826503231}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:16:43,640] Trial 395 finished with value: 6603.703925305714 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 522, 'learning_rate': 0.20558403557234392, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6161535218971691, 'colsample_bytree': 0.8049308187092035, 'colsample_bylevel': 0.9538966393972657, 'gamma': 6.076719187386109, 'alpha': 3.3085927322926065, 'lambda': 9.73373927872407, 'tweedie_variance_power': 1.8729823200858489}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:16:53,331] Trial 396 finished with value: 7217.787306228414 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 516, 'learning_rate': 0.20164533801642653, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.546639278107269, 'colsample_bytree': 0.8288349292203623, 'colsample_bylevel': 0.9237887703637315, 'gamma': 9.126545106312076, 'alpha': 3.520393483234635, 'lambda': 9.52793944357902, 'tweedie_variance_power': 1.9234346279216334}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:17:03,067] Trial 397 finished with value: 7107.9599524926825 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 551, 'learning_rate': 0.2724346328605292, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.564776712112922, 'colsample_bytree': 0.8129201106509075, 'colsample_bylevel': 0.4871555943883151, 'gamma': 1.7447990737630126, 'alpha': 3.0160738712788593, 'lambda': 9.402079314740064, 'tweedie_variance_power': 1.90613695587021}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:17:13,063] Trial 398 finished with value: 6663.860386889451 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 563, 'learning_rate': 0.15640173713142608, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5980614215920356, 'colsample_bytree': 0.7931582683102384, 'colsample_bylevel': 0.3147255582517354, 'gamma': 1.6709607356624983, 'alpha': 3.7112809457664895, 'lambda': 9.232497976263941, 'tweedie_variance_power': 1.9342530631884864}. Best is trial 329 with value: 6469.6972025111745.

[I 2026-08-31 10:17:22,949] Trial 399 finished with value: 6536.4030044101655 and parameters: {'objective': 'reg:tweedie', 'n_estimators': 535, 'learning_rate': 0.1842490626181942, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.5792820241338048, 'colsample_bytree': 0.8745706395939803, 'colsample_bylevel': 0.2527485182744681, 'gamma': 1.9781461923725148, 'alpha': 2.7071256615809554, 'lambda': 9.65283325308684, 'tweedie_variance_power': 1.8874053487899527}. Best is trial 329 with value: 6469.6972025111745.

{'objective': 'reg:tweedie',
 'n_estimators': 570,
 'learning_rate': 0.2595525275491146,
 'max_depth': 1,
 'min_child_weight': 18,
 'subsample': 0.6064480180480966,
 'colsample_bytree': 0.8405603469782187,
 'colsample_bylevel': 0.9959895581557628,
 'gamma': 5.529890290582709,
 'alpha': 3.275010657889333,
 'lambda': 9.461731268272077,
 'tweedie_variance_power': 1.8914621343096838}

In [13]:
from utils.objectives import get_best_regression_model

selected_features, xgb = get_best_regression_model(
    study.best_params,
    x_train[best_features],
    y_transform(y_train),
    x_dev[best_features],
    y_transform(y_dev),
    w_train=w_train,
    w_dev=w_dev,
    train_on_full=False,
)

used features: ['KAPITAL40', 'VOCATION', 'TYPERS', 'KAPITAL41', 'KAPITAL42', 'RISK11', 'DEROG12', 'KAPITAL37', 'ACTIVIT2', 'KAPITAL43', 'NBJFXI3S28_MM_A_NBJFXI3S28_MMAX_A', 'DEROG4', 'DEROG5', 'TXAB_VOR_MM_A_TXAB_VOR_MMAX_A', 'TN_VOR_MM_A_TN_VOR_MMAX_A', 'TAMPLIAB_VOR_MM_A_TAMPLIAB_VOR_MMAX_A', 'NBJTX0_MM_A_NBJTX0_MMAX_A', 'INDEM2', 'TX_VOR_MM_A_TX_VOR_MMAX_A', 'RRAB_VOR_MM_A_RRAB_VOR_MMAX_A', 'TAMPLIM_VOR_MM_A_TAMPLIM_VOR_MMAX_A', 'NBJTXI27_MM_A_NBJTXI27_MMAX_A', 'NBJFF28_MM_A_NBJFF28_MMAX_A', 'EQUIPEMENT2', 'RISK12', 'NBJTXI20_MM_A_NBJTXI20_MMAX_A', 'ZONE', 'NBJTX25_MM_A_NBJTX25_MMAX_A', 'TNAB_VOR_MM_A_TNAB_VOR_MMAX_A', 'TXMIN_VOR_MM_A_TXMIN_VOR_MMAX_A', 'RISK6', 'TM_VOR_MM_A_TM_VOR_MMAX_A', 'NBJRR30_MM_A_NBJRR30_MMAX_A', 'TMMAX_VOR_MM_A_TMMAX_VOR_MMAX_A', 'NBJTNI10_MM_A_NBJTNI10_MMAX_A', 'KAPITAL35', 'IND_REGION', 'NBJRR1_MM_A_NBJRR1_MMAX_A', 'TMMIN_VOR_MM_A_TMMIN_VOR_MMAX_A', 'total_surface_crossed', 'RR_VOR_MM_A_RR_VOR_MMAX_A', 'IND_SNV_REGION', 'NBJTXS32_MM_A_NBJTXS32_MMAX_A', 'NBJTNI20_MM_A_NBJTNI20_MMAX_A', 'NBJTNI15_MM_A_NBJTNI15_MMAX_A', 'ALTITUDE_5_ALT_TOT', 'FXIAB_VOR_MM_A_FXIAB_VOR_MMAX_A', 'ALTITUDE_4_num', 'DEROG2', 'NBJTX35_MM_A_NBJTX35_MMAX_A', 'TNMAX_VOR_MM_A_TNMAX_VOR_MMAX_A', 'AN_EXERC', 'NBJTN5_MM_A_NBJTN5_MMAX_A', 'ZONE_REGION', 'FXI3SAB_VOR_COM_MM_A_Y_FXI3SAB_VOR_COM_MMAX_A_Y', 'MEN_REGION', 'NBJTMS24_MM_A_NBJTMS24_MMAX_A', 'CARACT1', 'MEN_1IND_MEN_TOT', 'LOG_APA3_num', 'NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A', 'NBJTX30_MM_A_NBJTX30_MMAX_A', 'NBJRR100_MM_A_NBJRR100_MMAX_A', 'zone_vent_extinction_rate', 'LOG_AVA1_num', 'FFM_VOR_COM_MM_A_Y_FFM_VOR_COM_MMAX_A_Y', 'MEN_TOT', 'TMM_VOR_MM_A_TMM_VOR_MMAX_A', 'SURFACE4', 'TAILLE1', 'TAILLE2', 'HAUTEUR_MAX', 'BDTOPO_BAT_MAX_HAUTEUR_MAX', 'DISTANCE_213', 'BDTOPO_BAT_MAX_HAUTEUR', 'NBJFXI3S28_MSOM_A', 'CARACT4', 'NBJFF10_MMAX_A', 'PROPORTION_21', 'DISTANCE_323', 'HAUTEUR', 'DISTANCE_335', 'DISTANCE_334', 'NBJTX0_MMAX_A', 'RRAB_VOR_MMAX_A', 'NBJFXY8_MMAX_A', 'DISTANCE_212', 'DISTANCE_422', 'DISTANCE_411', 'TN_VOR_MM_A', 'NBJTXI27_MSOM_A', 'DISTANCE_332', 'RR_VOR_MM_A', 'NBJRR30_MMAX_A', 'DISTANCE_321', 'TAMPLIAB_VOR_MM_A', 'FFM_VOR_MM_A', 'PROPORTION_24', 'NBJRR50_MSOM_A', 'NBJFF28_MSOM_A', 'FXIAB_VOR_MMAX_A', 'NBJTX30_MSOM_A', 'RRAB_VOR_MM_A', 'RR_VOR_MMAX_A', 'ALTITUDE_5', 'NBJRR50_MMAX_A', 'TM_VOR_MMAX_A', 'NBJTX25_MMAX_A', 'TX_VOR_MMAX_A', 'NBJTX25_MSOM_A', 'NBJRR5_MMAX_A', 'NBJTX30_MMAX_A', 'NBJRR10_MSOM_A', 'ALTITUDE_1', 'ALTITUDE_2', 'NBJTNS20_MSOM_A', 'TX_VOR_MM_A', 'TN_VOR_MMAX_A', 'PROPORTION_31', 'NBJTX0_MSOM_A', 'TMMIN_VOR_MM_A', 'NBJTXI20_MSOM_A', 'DISTANCE_242', 'TNAB_VOR_MM_A', 'NBJFF16_MSOM_A', 'FFM_VOR_MMAX_A', 'NBJTX35_MSOM_A', 'DISTANCE_211', 'NBJTXS32_MMAX_A', 'DISTANCE_412', 'NBJTMS24_MMAX_A', 'NBJTN5_MMAX_A', 'NBJTNI15_MSOM_A', 'total_surface_5y', 'NBJFXI3S16_MSOM_A', 'TNMAX_VOR_MM_A', 'NBJTN5_MSOM_A', 'NBJFXY10_MMAX_A', 'NBJTN10_MSOM_A', 'DISTANCE_311', 'FFM_VOR_COM_MM_A_Y', 'DISTANCE_221', 'NBJTNI10_MSOM_A', 'TMMAX_VOR_MMAX_A', 'FXYAB_VOR_MMAX_A', 'DISTANCE_123', 'COEFASS', 'TNAB_VOR_MMAX_A', 'total_surface_2023', 'SURFACE11', 'KAPITAL32', 'SURFACE17', 'KAPITAL_MAX', 'SURFACE10', 'NBBAT1', 'KAPITAL21', 'KAPITAL10', 'CA3_CA_MEAN', 'EQUIPEMENT6', 'CA1_CA_TOT', 'CA_TOT', 'SURFACE7', 'KAPITAL24', 'NBSINSTRT', 'KAPITAL27', 'SURFACE8', 'CA1', 'KAPITAL23', 'KAPITAL3', 'KAPITAL14', 'NBBAT8', 'DEROG11', 'RISK5', 'RISK4', 'RISK1', 'RISK3', 'NBSINCONJ', 'NBBAT6', 'CARACT5', 'DEROG10', 'NBBAT9', 'KAPITAL28', 'CARACT2', 'KAPITAL8', 'SURFACE16', 'EQUIPEMENT1', 'KAPITAL18', 'TAILLE3', 'KAPITAL25', 'KAPITAL30', 'ANCIENNETE', 'DEROG1', 'NBBAT14', 'Naturelle', 'DEROG9', 'KAPITAL17', 'KAPITAL22', 'Accidentelle', 'DEROG6', 'KAPITAL16']

RMSE Train: 6888.927095479314

RMSE Dev:   6469.6972025111745

## Prediction on OOS & challenge submission

In [14]:
# expected cost = frequency x severity
oos["CM"] = xgb.predict(oos[selected_features])

pred = oos.reset_index()[["ID", "ANNEE_ASSURANCE", "pred_sum", "CM"]].rename(
    columns={"pred_sum": "FREQ"}
)
pred["CHARGE"] = pred["FREQ"] * pred["CM"]
# pred.to_csv("predictions/2026_amount_pred.csv", index=False)
pred.head()

       ID  ANNEE_ASSURANCE      FREQ          CM      CHARGE
0  383611         0.813699  0.963831   39.561230   38.130350
1  383612         1.000000  0.694419   91.541489   63.568104
2  383613         0.586301  0.400150  110.509445   44.220392
3  383614         1.000000  0.373611  427.521820  159.726933
4  383615         0.753425  0.495960  322.615326  160.004360

## End-to-end `CHARGE` on train / dev

The challenge metric is `CHARGE`, the **total** claim cost. In the raw target
`CHARGE = CM x (FREQ x ANNEE_ASSURANCE)` -- average claim amount times claim count
(verified on `train_output`: `CHARGE / CM` is exactly `FREQ * ANNEE_ASSURANCE`, an
integer 1..5, on every one of the 2,352 rows with a claim). The frequency model predicts
the claim **count** (`pred_sum`, the `CLASS_MEANS`-weighted expectation), so
`pred_sum * CM_pred` lands on the same scale as the true `CHARGE` -- the same
construction as the OOS submission above and as 2025 (`amount_model.ipynb` cell 65).

**Read the dev number with care.** Optuna selected on this dev set over 400 trials, so
the dev `CHARGE` RMSE is optimistic -- it is a selection-contaminated estimate, not a
held-out one. Train and dev are printed together so the gap is visible.

In [15]:
from sklearn.metrics import root_mean_squared_error

for label, frame in (("Train", x_train), ("Dev", x_dev)):
    # true CHARGE lives in the raw target; fall back to it if the carved frame dropped it
    true_charge = (
        frame["CHARGE"]
        if "CHARGE" in frame.columns
        else target.loc[frame.index, "CHARGE"]
    )
    pred_charge = frame["pred_sum"] * xgb.predict(frame[selected_features])
    print(f"CHARGE RMSE {label}: {root_mean_squared_error(true_charge, pred_charge)}")

CHARGE RMSE Train: 7031.15579812017

CHARGE RMSE Dev: 6482.842161889131