# Claim-Frequency model — 2026 re-run

This notebook re-runs the **2025 winning frequency model** ([CAA / ENS Challenge
Data #161](https://challengedata.ens.fr/challenges/161)) with the **current AutoCarver** (see `pyproject.toml` for the pinned floor).

Everything before the carving step — data loading, the `0/1/2+` target, the
stratified split, inverse-frequency weights, feature engineering and the column
typing — is **identical to `frequency_model.ipynb`** (cells reused verbatim) so
the only thing that changes is the AutoCarver step. That keeps the comparison
honest.

**What changes in 2026:**
1. **`ProcessingConfig(n_jobs=...)`** — per-feature carving runs across a process
   pool. Timed below.
2. **`OrdinalCarver`** instead of `MulticlassCarver` — the claim-count target
   `0 < 1 < 2+` is **ordinal**, so we carve with **Kendall's Tau-c** rather than
   nominal multiclass association. Note the rename: in 7.0.5 `MulticlassCarver`
   carved *one-vs-rest* (several carved columns per raw feature); that behaviour
   is `OneVsRestCarver` today.
3. **`min_freq_alpha`** — bin frequencies are gated by a **Wilson-score CI**, so
   thin bins are merged on statistical grounds (relevant for the rare-claim tail).
4. **Selectors** take a `SelectionConfig` and a single `n_best_features` **total**
   budget, split evenly across feature types.

## Loading data & target  *(reused from 2025)*

In [1]:
import pandas as pd

data_path = "../data/"

# loading x_train
data = pd.read_csv(data_path + "train_input_Z61KlZo.csv", low_memory=False)
data.set_index("ID", inplace=True)
print("x_train", data.shape)

# loading target
target = pd.read_csv(data_path + "train_output_DzPxaPY.csv", low_memory=False)
target.set_index("ID", inplace=True)
print("y_train", target.shape)

# joining x_train and y_train
data = data.join(target.drop("ANNEE_ASSURANCE", axis=1))
print("data", data.shape)

x_train (383610, 373)
y_train (383610, 4)

data (383610, 376)

In [2]:
target_col = "TARGET"
data[target_col] = (data["FREQ"] * data["ANNEE_ASSURANCE"]).astype(int)
data[target_col].value_counts(normalize=False).sort_index()

TARGET
0    381061
1      2458
2        87
3         2
4         1
5         1
Name: count, dtype: int64

## Stratified sampling & inverse-frequency weights  *(reused from 2025)*

In [3]:
import numpy as np

from collections import Counter
from sklearn.model_selection import train_test_split
from utils.data_toolkit import collapse_count

# Compute class frequencies
class_counts = Counter(collapse_count(data[target_col]))
total_samples = len(data[target_col])

# Compute inverse frequency class weights
class_weights = {
    cls: total_samples / (len(class_counts) * count)
    for cls, count in class_counts.items()
}
print("Class weights:", class_weights)

# Assign sample weights based on target values
weights = np.array([class_weights[label] for label in collapse_count(data[target_col])])

# Train-test split
x_train, x_dev, y_train, y_dev, w_train, w_dev = train_test_split(
    data,
    data[target_col],
    weights,
    test_size=0.2,
    random_state=42,
    stratify=collapse_count(data[target_col]),
)
print("y_train mean", y_train.mean(), " observations:", x_train.shape[0])
print("y_dev mean", y_dev.mean(), " observations:", x_dev.shape[0])

Class weights: {0: 0.3355630725789309, 1: 52.0219690805533, 2: 1405.1648351648353}

y_train mean 0.006895023591668622  observations: 306888
y_dev mean 0.006921091733792133  observations: 76722

## Feature engineering  *(reused from 2025)*

In [4]:
from utils.data_toolkit import Processor

proc = Processor()
x_train = proc.fit_transform(x_train)
x_dev = proc.transform(x_dev)
data = proc.transform(data)

## Column typing  *(reused from 2025)*

In [ ]:
from AutoCarver import Features

# sorting columns per type
features = Features.from_dataframe(x_train)

# getting ordinal columns
ordinals = [
    "NB_CASERNES", "BDTOPO_BAT_MAX_HAUTEUR", "HAUTEUR_MAX", "HAUTEUR", "BDTOPO_BAT_MAX_HAUTEUR_MAX", "MEN_SURF", "IND_SNV", "IND_INC", "IND_Y9", "IND_0_Y1", "IND", "LOG_SOC", "LOG_INC", "LOG_APA3", "LOG_AVA1", "MEN_MAIS", "MEN_COLL", "MEN_FMP", "MEN_PROP", "MEN_PAUV", "MEN", "COEFASS", "DISTANCE_111", "DISTANCE_112", "DISTANCE_121", "DISTANCE_122", "DISTANCE_123", "DISTANCE_124", "DISTANCE_131", "DISTANCE_132", "DISTANCE_133", "DISTANCE_141", "DISTANCE_142", "DISTANCE_211", "DISTANCE_212", "DISTANCE_213", "DISTANCE_221", "DISTANCE_222", "DISTANCE_223", "DISTANCE_231", "DISTANCE_242", "DISTANCE_243", "DISTANCE_244", "DISTANCE_311", "DISTANCE_312", "DISTANCE_313", "DISTANCE_321", "DISTANCE_322", "DISTANCE_323", "DISTANCE_324", "DISTANCE_331", "DISTANCE_332", "DISTANCE_333", "DISTANCE_334", "DISTANCE_335", "DISTANCE_411", "DISTANCE_412", "DISTANCE_421", "DISTANCE_422", "DISTANCE_423", "DISTANCE_511", "DISTANCE_512", "DISTANCE_521", "DISTANCE_522", "DISTANCE_523", "PROPORTION_11", "PROPORTION_12", "PROPORTION_13", "PROPORTION_14", "PROPORTION_21", "PROPORTION_22", "PROPORTION_23", "PROPORTION_24", "PROPORTION_31", "PROPORTION_32", "PROPORTION_33", "PROPORTION_41", "PROPORTION_42", "PROPORTION_51", "PROPORTION_52", "MEN_1IND", "MEN_5IND", "LOG_A1_A2", "LOG_A2_A3", "IND_Y1_Y2", "IND_Y2_Y3", "IND_Y3_Y4", "IND_Y4_Y5", "IND_Y5_Y6", "IND_Y6_Y7", "IND_Y7_Y8", "IND_Y8_Y9", "DISTANCE_1", "DISTANCE_2", "ALTITUDE_1", "ALTITUDE_2", "ALTITUDE_3", "ALTITUDE_4", "ALTITUDE_5", "NBJTX25_MM_A", "NBJTX25_MMAX_A", "NBJTX25_MSOM_A", "NBJTX0_MM_A", "NBJTX0_MMAX_A", "NBJTX0_MSOM_A", "NBJTXI27_MM_A", "NBJTXI27_MMAX_A", "NBJTXI27_MSOM_A", "NBJTXS32_MM_A", "NBJTXS32_MMAX_A", "NBJTXS32_MSOM_A", "NBJTXI20_MM_A", "NBJTXI20_MMAX_A", "NBJTXI20_MSOM_A", "NBJTX30_MM_A", "NBJTX30_MMAX_A", "NBJTX30_MSOM_A", "NBJTX35_MM_A", "NBJTX35_MMAX_A", "NBJTX35_MSOM_A", "NBJTN10_MM_A", "NBJTN10_MMAX_A", "NBJTN10_MSOM_A", "NBJTNI10_MM_A", "NBJTNI10_MMAX_A", "NBJTNI10_MSOM_A", "NBJTN5_MM_A", "NBJTN5_MMAX_A", "NBJTN5_MSOM_A", "NBJTNS25_MM_A", "NBJTNS25_MMAX_A", "NBJTNS25_MSOM_A", "NBJTNI15_MM_A", "NBJTNI15_MMAX_A", "NBJTNI15_MSOM_A", "NBJTNI20_MM_A", "NBJTNI20_MMAX_A", "NBJTNI20_MSOM_A", "NBJTNS20_MM_A", "NBJTNS20_MMAX_A", "NBJTNS20_MSOM_A", "NBJTMS24_MM_A", "NBJTMS24_MMAX_A", "NBJTMS24_MSOM_A", "TAMPLIAB_VOR_MM_A", "TAMPLIAB_VOR_MMAX_A", "TAMPLIM_VOR_MM_A", "TAMPLIM_VOR_MMAX_A", "TM_VOR_MM_A", "TM_VOR_MMAX_A", "TMM_VOR_MM_A", "TMM_VOR_MMAX_A", "TMMAX_VOR_MM_A", "TMMAX_VOR_MMAX_A", "TMMIN_VOR_MM_A", "TMMIN_VOR_MMAX_A", "TN_VOR_MM_A", "TN_VOR_MMAX_A", "TNAB_VOR_MM_A", "TNAB_VOR_MMAX_A", "TNMAX_VOR_MM_A", "TNMAX_VOR_MMAX_A", "TX_VOR_MM_A", "TX_VOR_MMAX_A", "TXAB_VOR_MM_A", "TXAB_VOR_MMAX_A", "TXMIN_VOR_MM_A", "TXMIN_VOR_MMAX_A", "NBJFF10_MM_A", "NBJFF10_MMAX_A", "NBJFF10_MSOM_A", "NBJFF16_MM_A", "NBJFF16_MMAX_A", "NBJFF16_MSOM_A", "NBJFF28_MM_A", "NBJFF28_MMAX_A", "NBJFF28_MSOM_A", "NBJFXI3S10_MM_A", "NBJFXI3S10_MMAX_A", "NBJFXI3S10_MSOM_A", "NBJFXI3S16_MM_A", "NBJFXI3S16_MMAX_A", "NBJFXI3S16_MSOM_A", "NBJFXI3S28_MM_A", "NBJFXI3S28_MMAX_A", "NBJFXI3S28_MSOM_A", "NBJFXY8_MM_A", "NBJFXY8_MMAX_A", "NBJFXY8_MSOM_A", "NBJFXY10_MM_A", "NBJFXY10_MMAX_A", "NBJFXY10_MSOM_A", "NBJFXY15_MM_A", "NBJFXY15_MMAX_A", "NBJFXY15_MSOM_A", "FFM_VOR_MM_A", "FFM_VOR_MMAX_A", "FXI3SAB_VOR_MM_A", "FXI3SAB_VOR_MMAX_A", "FXIAB_VOR_MM_A", "FXIAB_VOR_MMAX_A", "FXYAB_VOR_MM_A", "FXYAB_VOR_MMAX_A", "FFM_VOR_COM_MM_A_Y", "FFM_VOR_COM_MMAX_A_Y", "FXI3SAB_VOR_COM_MM_A_Y", "FXI3SAB_VOR_COM_MMAX_A_Y", "NBJRR50_MM_A", "NBJRR50_MMAX_A", "NBJRR50_MSOM_A", "NBJRR1_MM_A", "NBJRR1_MMAX_A", "NBJRR1_MSOM_A", "NBJRR5_MM_A", "NBJRR5_MMAX_A", "NBJRR5_MSOM_A", "NBJRR10_MM_A", "NBJRR10_MMAX_A", "NBJRR10_MSOM_A", "NBJRR30_MM_A", "NBJRR30_MMAX_A", "NBJRR30_MSOM_A", "NBJRR100_MM_A", "NBJRR100_MMAX_A", "NBJRR100_MSOM_A", "RR_VOR_MM_A", "RR_VOR_MMAX_A", "RRAB_VOR_MM_A", "RRAB_VOR_MMAX_A", "TAILLE1", "TAILLE2",
]
ordinal_columns = {
    col: list(data[col].value_counts().sort_index().index)
    for col in ordinals
    if col in data.columns
}
ordinal_columns["PROPORTION_32"] += ["10. > 90"]
ordinal_columns.update(
    {
        "CARACT4": [
            "absence de surface", "Surface de moins d", "Surface entre 501", "Surface entre 1001", "Surface entre 1501", "Surface de plus de",
        ],
        "SURFACE4": [
            "0", "500", "1000", "1500", "2000", "2500", "3000", "3500", "4000", "4500", "5000", "5500", "6000", "6500", "7000", "7000+",
        ],
        "SURFACE6": [
            "0", "500", "1000", "1500", "2000", "2500", "3000", "3500", "4000", "4500", "5000", "5500", "6000", "6500", "7000", "7000+",
        ],
        "total_surface_2023": [
            "Aucun feu", "<10ha", "10-20ha", "20-50ha", "50-100ha", "100-200ha", ">200ha",
        ],
        "total_surface_5y": [
            "Aucun feu", "<10ha", "10-20ha", "20-50ha", "50-100ha", "100-200ha", ">200ha",
        ],
        "surface_over_forest": [
            "Absence de feu", "<0.05", "0.05-0.1", "0.1-0.2", "0.5-2",
        ],
        "fire_extinction_rates": ["Aucun feu", "<50%", "50-70%", "70-85%", ">85%"],
    }
)

# columns that are to be removed (target + no values)
to_remove = target.columns.tolist() + [target_col]
to_remove += [c for c in data.columns if "MMSOM" in c]
to_remove += ["DEROG13", "DEROG14", "DEROG16"]

# removing columns
categorical_columns = [
    col.name
    for col in features.categoricals
    if col not in to_remove and col not in ordinal_columns
]
categorical_columns += ["TYPERS"]
numerical_columns = [
    col.name
    for col in features.numericals
    if col not in to_remove
    and col not in ordinal_columns
    and col not in categorical_columns
]
print(
    len(categorical_columns),
    len(numerical_columns),
    len(ordinal_columns),
    len(categorical_columns) + len(numerical_columns) + len(ordinal_columns),
)

197 120 238 555

## 2026 carving — OrdinalCarver + multiprocessing + Wilson-CI

`n_jobs` parallelises the per-feature combination search; set it to the core
count on the competition machine. `min_freq_alpha=0.05` is the 95% Wilson
interval used to test each bin's frequency.

In [6]:
import time

from AutoCarver import Features, OrdinalCarver
from AutoCarver.discretizers import ProcessingConfig

N_JOBS = 6

# the 0/1/2+ claim-count target is ordinal -> carve with Kendall's Tau-c
y_ord_train = collapse_count(y_train)
y_ord_dev = collapse_count(y_dev)

config = ProcessingConfig(
    dropna=False, copy=False, verbose=False, n_jobs=N_JOBS, min_freq_alpha=0.05
)

### Qualitative + ordinal features

In [7]:
qualitatives = Features(categoricals=categorical_columns, ordinals=ordinal_columns)

carver = OrdinalCarver(features=qualitatives, target_scale="level", config=config)

t0 = time.perf_counter()
x_train = carver.fit_transform(x_train, y_ord_train, X_dev=x_dev, y_dev=y_ord_dev)
print(
    f"[2026] qualitative carving: {time.perf_counter() - t0:.1f}s on {N_JOBS} workers"
)
carver.summary

[OrdinalCarver] Carving:   0%|          | 0/435 [00:00<?, ?feature/s]

[OrdinalCarver] dropped 38/435 feature(s) (no robust train/dev combination): LOG_VETUSTE_REGION, MEN_num, IND_num, IND_0_Y1_num, IND_Y1_Y2_num, IND_Y4_Y5_num, IND_Y6_Y7_num, IND_Y7_Y8_num, IND_INC_num, IND_0_Y1_IND, IND_Y1_Y2_IND, IND_Y2_Y3_IND, IND_Y6_Y7_IND, IND_Y7_Y8_IND, IND_INC_IND, IND_INC, IND_0_Y1, IND, LOG_INC, MEN, PROPORTION_13, PROPORTION_12, PROPORTION_14, PROPORTION_11, PROPORTION_33, PROPORTION_41, PROPORTION_42, PROPORTION_51, PROPORTION_52, IND_Y1_Y2, IND_Y2_Y3, LOG_A1_A2, IND_Y4_Y5, IND_Y6_Y7, IND_Y7_Y8, LOG_APA3_num_LOG_TOT, LOG_AVA1_num_LOG_TOT, LOG_VETUSTE

[2026] qualitative carving: 120.0s on 6 workers

                                                                                                                          content  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                                                        [ACT3, ACT2]
                                                            1                           [ACT8, ACT9, ACT4, ACT6, ACT7, __OTHER__]
                                                            2                                                                ACT1
                                                            3                                                                ACT5
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                   [VOC1, VOC7, VOC5, VOC3, VOC2, __OTHER__, VOC4...
...                                                                                                                           ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686                                 57.926829268292686
                                                            64.02439024390245                                   64.02439024390245
                                                            52.083333333333336                                 52.083333333333336
                                                            43.292682926829265                                 43.292682926829265
                                                            69.63855421686748                                   69.63855421686748

                                                                                target_mean_level  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                            0.002030
                                                            1                            0.005593
                                                            2                            0.006539
                                                            3                            0.010893
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                            0.002050
...                                                                                           ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686           0.007920
                                                            64.02439024390245            0.008269
                                                            52.083333333333336           0.008765
                                                            43.292682926829265           0.008900
                                                            69.63855421686748            0.008993

                                                                                frequency  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                    0.051364
                                                            1                    0.035537
                                                            2                    0.773396
                                                            3                    0.139702
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                    0.362458
...                                                                                   ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686   0.020571
                                                            64.02439024390245    0.048470
                                                            52.083333333333336   0.020076
                                                            43.292682926829265   0.010251
                                                            69.63855421686748    0.014856

                                                                                   count  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                    15763.0
                                                            1                    10906.0
                                                            2                   237346.0
                                                            3                    42873.0
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                   111234.0
...                                                                                  ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686    6313.0
                                                            64.02439024390245    14875.0
                                                            52.083333333333336    6161.0
                                                            43.292682926829265    3146.0
                                                            69.63855421686748     4559.0

                                                                                dropped  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                     False
                                                            1                     False
                                                            2                     False
                                                            3                     False
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                     False
...                                                                                 ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686     True
                                                            64.02439024390245      True
                                                            52.083333333333336     True
                                                            43.292682926829265     True
                                                            69.63855421686748      True

                                                                                                                   dropped_reason
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                                                                None
                                                            1                                                                None
                                                            2                                                                None
                                                            3                                                                None
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                                                                None
...                                                                                                                           ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686  No robust combination (Inversion of target rat...
                                                            64.02439024390245   No robust combination (Inversion of target rat...
                                                            52.083333333333336  No robust combination (Inversion of target rat...
                                                            43.292682926829265  No robust combination (Inversion of target rat...
                                                            69.63855421686748   No robust combination (Inversion of target rat...

[977 rows x 6 columns]

### Apply carver to dev + OOS

In [8]:
x_dev = carver.transform(x_dev)

data_path = "../data/"
oos = pd.read_csv(data_path + "test_input_5qJzHrr.csv", low_memory=False)
oos = proc.transform(oos)
oos = carver.transform(oos)

No processing for continuous features

In [9]:
quantitatives = Features(numericals=numerical_columns)

## Feature selection  *(single selector, one config)*

One `ClassificationSelector` over **both** feature types with a single `SelectionConfig`,
instead of one selector per type. `n_best_features` is a **total** budget, split **evenly**
across feature types (redistributing seats a type cannot fill), so the 100 below buys 50
carved qualitative + 50 raw quantitative features.

The split matters more than the total: on a 0.69 % positive-rate target, tilting the same
budget towards carved qualitatives measurably costs log loss, because each extra carved
feature adds up to 5 mostly-empty buckets to a rare-event stump ensemble. Respect the
pinned dependency floor -- older releases apportion the budget differently and silently
produce a different feature mix.

Filters are the current library defaults plus a redundancy cut (Cramer's V 0.9 on
qualitatives, Spearman 0.9 on quantitatives). The 2025 association thresholds are **not**
reproduced here; that is one of the stated deviations between the two eras.

In [10]:
from AutoCarver.selectors import (
    ClassificationSelector,
    CramervFilter,
    SelectionConfig,
    SpearmanFilter,
)

config = SelectionConfig(
    qualitative_filters=[CramervFilter(threshold=0.9)],
    quantitative_filters=[SpearmanFilter(threshold=0.9)],
)
selector = ClassificationSelector(
    qualitatives + quantitatives, n_best_features=100, config=config
)
selector.fit(x_train, y_ord_train)
print("selected:", len(selector.selected_features))
selector.summary

selected: 100

,feature,Nan,Mode,measure,association,rank,filter,redundancy,redundancy_with,selected
0,Numerical('KAPITAL32'),0.000000,0.347971,KruskalEtaSquared,0.003341,0.0,Spearman,0.000000,itself,True
1,Numerical('KAPITAL_MAX'),0.000000,0.248687,KruskalEtaSquared,0.002912,1.0,Spearman,0.824113,KAPITAL32,True
2,Numerical('SURFACE10'),0.019235,0.523992,KruskalEtaSquared,0.002625,2.0,Spearman,0.611342,KAPITAL32,True
3,Numerical('SURFACE1'),0.000000,0.071573,KruskalEtaSquared,0.002570,3.0,Spearman,0.640521,KAPITAL32,True
4,Numerical('SURFACE7'),0.010479,0.559276,KruskalEtaSquared,0.002430,4.0,Spearman,0.621579,SURFACE10,True
...,...,...,...,...,...,...,...,...,...,...
511,Ordinal('SURFACE4'),0.000000,0.605064,Tschuprowt,0.040019,NaN,Cramerv,0.999993,SURFACE6,False
512,Ordinal('total_surface_2023'),0.000000,0.587276,Tschuprowt,0.003196,NaN,None,NaN,None,False
513,Ordinal('total_surface_5y'),0.000000,0.731602,Tschuprowt,0.008750,NaN,None,NaN,None,False
514,Ordinal('surface_over_forest'),0.000000,0.842874,Tschuprowt,0.003599,NaN,None,NaN,None,False
515,Ordinal('fire_extinction_rates'),0.000000,0.566291,Tschuprowt,0.002325,NaN,None,NaN,None,False

In [11]:
pd.set_option("display.max_rows", None)
selector.summary

,feature,Nan,Mode,measure,association,rank,filter,redundancy,redundancy_with,selected
0,Numerical('KAPITAL32'),0.000000,0.347971,KruskalEtaSquared,3.341446e-03,0.0,Spearman,0.000000,itself,True
1,Numerical('KAPITAL_MAX'),0.000000,0.248687,KruskalEtaSquared,2.912102e-03,1.0,Spearman,0.824113,KAPITAL32,True
2,Numerical('SURFACE10'),0.019235,0.523992,KruskalEtaSquared,2.625000e-03,2.0,Spearman,0.611342,KAPITAL32,True
3,Numerical('SURFACE1'),0.000000,0.071573,KruskalEtaSquared,2.569790e-03,3.0,Spearman,0.640521,KAPITAL32,True
4,Numerical('SURFACE7'),0.010479,0.559276,KruskalEtaSquared,2.429846e-03,4.0,Spearman,0.621579,SURFACE10,True
5,Numerical('KAPITAL21'),0.014090,0.573636,KruskalEtaSquared,1.992941e-03,5.0,Spearman,0.706107,KAPITAL32,True
6,Numerical('NBBAT4'),0.000000,0.121360,KruskalEtaSquared,1.928590e-03,6.0,Spearman,0.834693,SURFACE1,True
7,Numerical('NBSINSTRT'),0.000000,0.727373,KruskalEtaSquared,1.636910e-03,7.0,Spearman,0.379864,KAPITAL32,True
8,Numerical('KAPITAL23'),0.003050,0.834321,KruskalEtaSquared,1.421355e-03,8.0,Spearman,0.422755,SURFACE7,True
9,Numerical('EQUIPEMENT6'),0.000000,0.100607,KruskalEtaSquared,1.197528e-03,9.0,Spearman,0.394208,KAPITAL21,True
10,Numerical('NBSINCONJ'),0.000000,0.857394,KruskalEtaSquared,1.060261e-03,10.0,Spearman,0.678237,NBSINSTRT,True
11,Numerical('SURFACE17'),0.000000,0.831616,KruskalEtaSquared,9.547590e-04,11.0,Spearman,0.479089,SURFACE10,True
12,Numerical('KAPITAL8'),0.000000,0.955847,KruskalEtaSquared,8.972874e-04,12.0,Spearman,0.376848,KAPITAL23,True
13,Numerical('TAILLE3'),0.000000,0.816073,KruskalEtaSquared,8.145976e-04,13.0,Spearman,0.409352,KAPITAL_MAX,True
14,Numerical('KAPITAL14'),0.000000,0.810494,KruskalEtaSquared,7.977501e-04,14.0,Spearman,0.440357,KAPITAL32,True
15,Numerical('KAPITAL24'),0.002209,0.905989,KruskalEtaSquared,6.514318e-04,15.0,Spearman,0.404014,KAPITAL32,True
16,Numerical('KAPITAL27'),0.000000,0.844725,KruskalEtaSquared,6.393106e-04,16.0,Spearman,0.576490,KAPITAL24,True
17,Numerical('KAPITAL3'),0.000000,0.953361,KruskalEtaSquared,5.956810e-04,17.0,Spearman,0.242833,KAPITAL_MAX,True
18,Numerical('KAPITAL10'),0.000000,0.600307,KruskalEtaSquared,5.569936e-04,18.0,Spearman,0.522196,KAPITAL32,True
19,Numerical('CA3_CA_TOT'),0.960080,0.035811,KruskalEtaSquared,5.070386e-04,19.0,Spearman,-0.337415,SURFACE7,True
20,Numerical('NBBAT2'),0.000000,0.921098,KruskalEtaSquared,3.064476e-04,20.0,Spearman,0.277145,SURFACE1,True
21,Numerical('EQUIPEMENT1'),0.000000,0.924891,KruskalEtaSquared,3.044120e-04,21.0,Spearman,0.271899,SURFACE7,True
22,Numerical('CA3'),0.960080,0.015064,KruskalEtaSquared,2.516013e-04,22.0,Spearman,-0.308451,NBBAT4,True
23,Numerical('DEROG1'),0.000000,0.999801,KruskalEtaSquared,2.335854e-04,23.0,Spearman,0.024230,TAILLE3,True
24,Numerical('SURFACE13'),0.000000,0.941816,KruskalEtaSquared,1.871255e-04,24.0,Spearman,-0.274989,KAPITAL_MAX,True
25,Numerical('RISK5'),0.069058,0.414461,KruskalEtaSquared,1.801798e-04,25.0,Spearman,-0.666149,KAPITAL10,True
26,Numerical('CARACT5'),0.000000,0.951494,KruskalEtaSquared,1.795424e-04,26.0,Spearman,-0.276311,CA3,True
27,Numerical('NBBAT7'),0.000000,0.993258,KruskalEtaSquared,1.756540e-04,27.0,Spearman,0.277779,NBBAT2,True
28,Numerical('NBBAT8'),0.000000,0.949288,KruskalEtaSquared,1.480459e-04,28.0,Spearman,0.782825,NBBAT2,True
29,Numerical('ZONE_VENT'),0.048493,0.571179,KruskalEtaSquared,1.383686e-04,29.0,Spearman,0.106681,KAPITAL23,True
30,Numerical('KAPITAL20'),0.000701,0.995321,KruskalEtaSquared,1.372280e-04,30.0,Spearman,0.103333,KAPITAL14,True
31,Numerical('KAPITAL17'),0.002336,0.988768,KruskalEtaSquared,1.211205e-04,31.0,Spearman,0.174275,KAPITAL24,True
32,Numerical('KAPITAL25'),0.000000,0.572323,KruskalEtaSquared,1.163460e-04,32.0,Spearman,-0.322482,CA3,True
33,Numerical('RISK2'),0.069058,0.414461,KruskalEtaSquared,1.102564e-04,33.0,Spearman,0.851601,RISK5,True
34,Numerical('NBBAT6'),0.000000,0.978956,KruskalEtaSquared,9.838665e-05,34.0,Spearman,0.515189,NBBAT2,True
35,Numerical('RISK1'),0.069058,0.414461,KruskalEtaSquared,9.240935e-05,35.0,Spearman,0.885394,RISK2,True
36,Numerical('DEROG11'),0.000000,0.987683,KruskalEtaSquared,8.811951e-05,36.0,Spearman,0.148753,KAPITAL10,True
37,Numerical('NBBAT9'),0.000000,0.522839,KruskalEtaSquared,8.464476e-05,37.0,Spearman,0.428987,NBBAT4,True
38,Numerical('KAPITAL1'),0.000000,0.975939,KruskalEtaSquared,8.198152e-05,38.0,Spearman,0.245992,KAPITAL14,True
39,Numerical('DUREE_REQANEUF'),0.069058,0.863631,KruskalEtaSquared,7.885826e-05,39.0,Spearman,0.232908,KAPITAL_MAX,True
40,Numerical('DEROG10'),0.000000,0.996165,KruskalEtaSquared,7.869706e-05,40.0,Spearman,0.520261,DEROG11,True
41,Numerical('DEROG8_formatted'),0.000000,0.979370,KruskalEtaSquared,7.564088e-05,41.0,Spearman,-0.166884,KAPITAL32,True
42,Numerical('DEROG7'),0.000000,0.998022,KruskalEtaSquared,6.409434e-05,42.0,Spearman,0.056103,KAPITAL23,True
43,Numerical('EQUIPEMENT4'),0.000000,0.899419,KruskalEtaSquared,6.020368e-05,43.0,Spearman,0.522600,EQUIPEMENT6,True
44,Numerical('DEROG6'),0.000000,0.994809,KruskalEtaSquared,5.832720e-05,44.0,Spearman,0.195569,NBBAT2,True
45,Numerical('RISK4'),0.069058,0.414461,KruskalEtaSquared,5.666574e-05,45.0,Spearman,0.894092,RISK2,True
46,Numerical('TYPBAT2'),0.000000,0.377965,KruskalEtaSquared,5.003733e-05,46.0,Spearman,0.549456,RISK1,True
47,Numerical('ANCIENNETE'),0.000000,0.159716,KruskalEtaSquared,4.079280e-05,47.0,Spearman,0.353348,TYPBAT2,True
48,Numerical('KAPITAL19'),0.002933,0.982117,KruskalEtaSquared,3.276541e-05,48.0,Spearman,0.337261,CARACT5,True
49,Numerical('SURFACE21'),0.000000,0.935315,KruskalEtaSquared,3.265618e-05,49.0,Spearman,0.243652,TAILLE3,True
50,Numerical('CARACT2'),0.959888,0.039373,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
51,Numerical('DEROG9'),0.000000,0.994278,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
52,Numerical('DEROG15'),0.000000,0.999896,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
53,Numerical('CA1'),0.927882,0.018326,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
54,Numerical('CA2'),0.999831,0.000098,KruskalEtaSquared,NaN,NaN,None,NaN,None,False
55,Numerical('KAPITAL2'),0.000000,0.997742,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
56,Numerical('KAPITAL4'),0.000000,0.999583,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
57,Numerical('KAPITAL5'),0.000000,0.995852,KruskalEtaSquared,3.945069e-06,NaN,None,NaN,None,False
58,Numerical('KAPITAL6'),0.000000,0.573584,KruskalEtaSquared,1.826409e-03,NaN,Spearman,0.955036,KAPITAL21,False
59,Numerical('KAPITAL7'),0.000000,0.831935,KruskalEtaSquared,1.351722e-03,NaN,Spearman,0.986379,KAPITAL23,False
60,Numerical('KAPITAL9'),0.000000,0.902036,KruskalEtaSquared,6.275249e-04,NaN,Spearman,0.975769,KAPITAL24,False
61,Numerical('KAPITAL11'),0.309846,0.290461,KruskalEtaSquared,6.513004e-05,NaN,Spearman,0.991077,KAPITAL10,False
62,Numerical('KAPITAL12'),0.000000,0.309846,KruskalEtaSquared,2.657781e-03,NaN,Spearman,0.947189,KAPITAL_MAX,False
63,Numerical('KAPITAL13'),0.000000,0.975939,KruskalEtaSquared,8.180338e-05,NaN,Spearman,0.999995,KAPITAL1,False
64,Numerical('KAPITAL15'),0.001619,0.992066,KruskalEtaSquared,3.068810e-05,NaN,None,NaN,None,False
65,Numerical('KAPITAL16'),0.004076,0.981642,KruskalEtaSquared,2.740024e-05,NaN,None,NaN,None,False
66,Numerical('KAPITAL18'),0.000140,0.995735,KruskalEtaSquared,2.668701e-05,NaN,None,NaN,None,False
67,Numerical('KAPITAL22'),0.006843,0.986810,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
68,Numerical('KAPITAL26'),0.000000,0.962833,KruskalEtaSquared,2.502776e-05,NaN,None,NaN,None,False
69,Numerical('KAPITAL28'),0.000000,0.968233,KruskalEtaSquared,3.229668e-05,NaN,None,NaN,None,False
70,Numerical('KAPITAL29'),0.009844,0.983756,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
71,Numerical('KAPITAL30'),0.009844,0.985428,KruskalEtaSquared,1.039729e-05,NaN,None,NaN,None,False
72,Numerical('KAPITAL31'),0.000010,0.981365,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
73,Numerical('KAPITAL33'),0.000010,0.954159,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
74,Numerical('KAPITAL36'),0.000000,0.997742,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
75,Numerical('KAPITAL38'),0.000000,0.999583,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
76,Numerical('KAPITAL39'),0.000000,0.995852,KruskalEtaSquared,3.945069e-06,NaN,None,NaN,None,False
77,Numerical('SURFACE2'),0.000000,0.071573,KruskalEtaSquared,2.569627e-03,NaN,Spearman,0.999999,SURFACE1,False
78,Numerical('SURFACE3'),0.228865,0.049445,KruskalEtaSquared,2.461386e-03,NaN,Spearman,0.976658,SURFACE1,False
79,Numerical('SURFACE5'),0.000000,0.727295,KruskalEtaSquared,2.333192e-06,NaN,None,NaN,None,False
80,Numerical('SURFACE8'),0.228924,0.710803,KruskalEtaSquared,2.619866e-04,NaN,Spearman,0.998956,NBBAT2,False
81,Numerical('SURFACE9'),0.038131,0.928234,KruskalEtaSquared,2.200449e-05,NaN,None,NaN,None,False
82,Numerical('SURFACE11'),0.228865,0.066184,KruskalEtaSquared,2.252028e-03,NaN,Spearman,0.931674,SURFACE1,False
83,Numerical('SURFACE12'),0.000000,0.979478,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
84,Numerical('SURFACE14'),0.000000,0.999928,KruskalEtaSquared,1.067500e-05,NaN,None,NaN,None,False
85,Numerical('SURFACE15'),0.000000,0.999925,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
86,Numerical('SURFACE16'),0.000000,0.928114,KruskalEtaSquared,3.100269e-05,NaN,None,NaN,None,False
87,Numerical('SURFACE18'),0.228865,0.586885,KruskalEtaSquared,1.009588e-05,NaN,None,NaN,None,False
88,Numerical('SURFACE19'),0.228865,0.748791,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
89,Numerical('SURFACE20'),0.000000,0.999954,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
90,Numerical('NBBAT1'),0.000000,0.121328,KruskalEtaSquared,1.926212e-03,NaN,Spearman,0.999839,NBBAT4,False
91,Numerical('NBBAT3'),0.000000,0.998908,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
92,Numerical('NBBAT5'),0.000000,0.997328,KruskalEtaSquared,2.932719e-06,NaN,None,NaN,None,False
93,Numerical('NBBAT10'),0.000000,0.921098,KruskalEtaSquared,3.064474e-04,NaN,Spearman,1.000000,NBBAT2,False
94,Numerical('NBBAT11'),0.000000,0.993920,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
95,Numerical('NBBAT13'),0.000000,0.127291,KruskalEtaSquared,1.783138e-03,NaN,Spearman,0.971032,NBBAT4,False
96,Numerical('NBBAT14'),0.000000,0.727295,KruskalEtaSquared,3.245221e-06,NaN,None,NaN,None,False
97,Numerical('TAILLE4'),0.000000,0.972094,KruskalEtaSquared,5.205504e-07,NaN,None,NaN,None,False
98,Numerical('RISK3'),0.069058,0.414461,KruskalEtaSquared,1.002140e-04,NaN,Spearman,0.968219,RISK2,False
99,Numerical('RISK7'),0.069058,0.495810,KruskalEtaSquared,8.424683e-05,NaN,Spearman,0.949660,RISK2,False
100,Numerical('EQUIPEMENT3'),0.000000,0.976851,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
101,Numerical('EQUIPEMENT7'),0.000000,0.100607,KruskalEtaSquared,1.185308e-03,NaN,Spearman,0.999620,EQUIPEMENT6,False
102,Numerical('CA_TOT'),0.891902,0.030780,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
103,Numerical('CA_MEAN'),0.891902,0.031044,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
104,Numerical('CA1_CA_TOT'),0.927882,0.068178,KruskalEtaSquared,1.017485e-05,NaN,None,NaN,None,False
105,Numerical('CA1_CA_MEAN'),0.927882,0.068442,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
106,Numerical('CA2_CA_TOT'),0.999831,0.000091,KruskalEtaSquared,NaN,NaN,None,NaN,None,False
107,Numerical('CA2_CA_MEAN'),0.999831,0.000091,KruskalEtaSquared,NaN,NaN,None,NaN,None,False
108,Numerical('CA3_CA_MEAN'),0.960080,0.036075,KruskalEtaSquared,2.425823e-05,NaN,None,NaN,None,False
109,Numerical('Unknown'),0.046714,0.058699,KruskalEtaSquared,1.244433e-05,NaN,None,NaN,None,False
110,Numerical('Involontaire (travaux)'),0.046714,0.201197,KruskalEtaSquared,2.025583e-05,NaN,None,NaN,None,False
111,Numerical('Involontaire (particulier)'),0.046714,0.239625,KruskalEtaSquared,4.006896e-06,NaN,None,NaN,None,False
112,Numerical('Accidentelle'),0.046714,0.279939,KruskalEtaSquared,2.681138e-05,NaN,None,NaN,None,False
113,Numerical('Malveillance'),0.046714,0.275733,KruskalEtaSquared,4.357144e-06,NaN,None,NaN,None,False
114,Numerical('Naturelle'),0.046714,0.514699,KruskalEtaSquared,1.864485e-06,NaN,None,NaN,None,False
115,Numerical('KAPITAL_SUM'),0.000000,0.050188,KruskalEtaSquared,2.797287e-03,NaN,Spearman,0.925025,KAPITAL_MAX,False
116,Numerical('DEROG13_formatted'),0.000000,0.996667,KruskalEtaSquared,4.171530e-06,NaN,None,NaN,None,False
117,Numerical('DEROG3_formatted'),0.000000,0.979136,KruskalEtaSquared,7.218467e-05,NaN,Spearman,0.994243,DEROG8_formatted,False
118,Numerical('DEROG16_formatted'),0.000000,0.995634,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
119,Ordinal('SURFACE6'),0.000000,0.605064,Tschuprowt,4.001909e-02,0.0,Cramerv,0.000000,itself,True
120,Ordinal('TAILLE1'),0.000000,0.536202,Tschuprowt,3.790376e-02,1.0,Cramerv,0.784561,SURFACE6,True
121,Ordinal('TAILLE2'),0.000000,0.648250,Tschuprowt,3.716073e-02,2.0,Cramerv,0.791881,TAILLE1,True
122,Categorical('VOCATION'),0.000000,0.637542,Tschuprowt,3.616924e-02,3.0,Cramerv,0.412891,SURFACE6,True
123,Categorical('KAPITAL40'),0.000000,0.573584,Tschuprowt,3.600092e-02,4.0,Cramerv,0.523479,VOCATION,True
124,Categorical('TYPERS'),0.000000,0.665246,Tschuprowt,3.377202e-02,5.0,Cramerv,0.439513,TAILLE2,True
125,Categorical('KAPITAL41'),0.000000,0.831935,Tschuprowt,3.099055e-02,6.0,Cramerv,0.339695,KAPITAL40,True
126,Categorical('KAPITAL42'),0.000000,0.955847,Tschuprowt,2.528007e-02,7.0,Cramerv,0.351962,KAPITAL41,True
127,Categorical('DEROG12'),0.910026,0.069993,Tschuprowt,2.459976e-02,8.0,Cramerv,0.299745,TAILLE2,True
128,Categorical('RISK11'),0.000000,0.590649,Tschuprowt,2.415179e-02,9.0,Cramerv,0.346331,TAILLE2,True
129,Categorical('KAPITAL43'),0.000000,0.902036,Tschuprowt,2.117386e-02,10.0,Cramerv,0.355821,TAILLE2,True
130,Categorical('KAPITAL37'),0.000000,0.953361,Tschuprowt,2.063530e-02,11.0,Cramerv,0.218826,KAPITAL41,True
131,Ordinal('HAUTEUR_MAX'),0.618584,0.268023,Tschuprowt,1.927595e-02,12.0,Cramerv,0.321568,TAILLE1,True
132,Ordinal('BDTOPO_BAT_MAX_HAUTEUR_MAX'),0.618584,0.235939,Tschuprowt,1.772692e-02,13.0,Cramerv,0.657972,HAUTEUR_MAX,True
133,Categorical('DEROG4'),0.000000,0.936260,Tschuprowt,1.768627e-02,14.0,Cramerv,0.187568,KAPITAL40,True
134,Categorical('ZONE'),0.000000,0.503907,Tschuprowt,1.667586e-02,15.0,Cramerv,0.189744,KAPITAL41,True
135,Categorical('RISK10'),0.366860,0.424650,Tschuprowt,1.633163e-02,16.0,Cramerv,0.518069,RISK11,True
136,Categorical('DEROG5'),0.000000,0.951647,Tschuprowt,1.525374e-02,17.0,Cramerv,0.863876,DEROG4,True
137,Categorical('AN_EXERC'),0.000000,0.596126,Tschuprowt,1.471564e-02,18.0,Cramerv,0.202763,RISK10,True
138,Ordinal('BDTOPO_BAT_MAX_HAUTEUR'),0.618584,0.219836,Tschuprowt,1.448520e-02,19.0,Cramerv,0.673177,BDTOPO_BAT_MAX_HAUTEUR_MAX,True
139,Categorical('total_surface_crossed'),0.000000,0.711931,Tschuprowt,1.436602e-02,20.0,Cramerv,0.386196,ZONE,True
140,Categorical('ACTIVIT2'),0.000000,0.773396,Tschuprowt,1.430788e-02,21.0,Cramerv,0.421996,VOCATION,True
141,Categorical('TXAB_VOR_MM_A_TXAB_VOR_MMAX_A'),0.567477,0.272943,Tschuprowt,1.389696e-02,22.0,Cramerv,0.284343,ZONE,True
142,Categorical('NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A'),0.567477,0.231061,Tschuprowt,1.323326e-02,23.0,Cramerv,0.342760,TXAB_VOR_MM_A_TXAB_VOR_MMAX_A,True
143,Categorical('INDEM2'),0.071541,0.636995,Tschuprowt,1.313907e-02,24.0,Cramerv,0.249867,SURFACE6,True
144,Categorical('EQUIPEMENT2'),0.228865,0.448102,Tschuprowt,1.228792e-02,25.0,Cramerv,0.299324,RISK10,True
145,Ordinal('DISTANCE_213'),0.567477,0.228324,Tschuprowt,1.219746e-02,26.0,Cramerv,0.502375,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
146,Categorical('NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A'),0.567477,0.221305,Tschuprowt,1.201703e-02,27.0,Cramerv,0.544836,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
147,Categorical('NBJTX0_MM_A_NBJTX0_MMAX_A'),0.567477,0.236099,Tschuprowt,1.196835e-02,28.0,Cramerv,0.330653,TXAB_VOR_MM_A_TXAB_VOR_MMAX_A,True
148,Ordinal('PROPORTION_21'),0.049653,0.605364,Tschuprowt,1.196445e-02,29.0,Cramerv,0.364817,DISTANCE_213,True
149,Ordinal('HAUTEUR'),0.618584,0.170877,Tschuprowt,1.183648e-02,30.0,Cramerv,0.617213,HAUTEUR_MAX,True
150,Categorical('NBJRR50_MM_A_NBJRR50_MMAX_A'),0.567477,0.234486,Tschuprowt,1.150895e-02,31.0,Cramerv,0.605462,DISTANCE_213,True
151,Categorical('NBJRR10_MM_A_NBJRR10_MMAX_A'),0.567477,0.232329,Tschuprowt,1.147412e-02,32.0,Cramerv,0.305561,NBJRR50_MM_A_NBJRR50_MMAX_A,True
152,Ordinal('CARACT4'),0.000000,0.951494,Tschuprowt,1.142831e-02,33.0,Cramerv,0.205333,DEROG12,True
153,Ordinal('DISTANCE_212'),0.567477,0.225405,Tschuprowt,1.141974e-02,34.0,Cramerv,0.809413,DISTANCE_213,True
154,Categorical('NBJFXI3S28_MM_A_NBJFXI3S28_MMAX_A'),0.567477,0.287466,Tschuprowt,1.138844e-02,35.0,Cramerv,0.494334,DISTANCE_212,True
155,Ordinal('DISTANCE_411'),0.567477,0.237438,Tschuprowt,1.133115e-02,36.0,Cramerv,0.257156,NBJFXI3S28_MM_A_NBJFXI3S28_MMAX_A,True
156,Ordinal('DISTANCE_323'),0.567477,0.227702,Tschuprowt,1.131726e-02,37.0,Cramerv,0.893887,DISTANCE_213,True
157,Categorical('IND_SNV_REGION'),0.048519,0.530360,Tschuprowt,1.125026e-02,38.0,Cramerv,0.246765,ZONE,True
158,Categorical('NBJFF16_MM_A_NBJFF16_MMAX_A'),0.567477,0.218011,Tschuprowt,1.084392e-02,39.0,Cramerv,0.593049,NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A,True
159,Ordinal('DISTANCE_335'),0.567477,0.246047,Tschuprowt,1.073400e-02,40.0,Cramerv,0.798592,DISTANCE_213,True
160,Categorical('RRAB_VOR_MM_A_RRAB_VOR_MMAX_A'),0.567477,0.277932,Tschuprowt,1.067033e-02,41.0,Cramerv,0.589694,DISTANCE_323,True
161,Ordinal('DISTANCE_334'),0.567477,0.290559,Tschuprowt,1.053903e-02,42.0,Cramerv,0.724556,DISTANCE_212,True
162,Categorical('NBJFF10_MM_A_NBJFF10_MMAX_A'),0.567477,0.265569,Tschuprowt,1.052720e-02,43.0,Cramerv,0.393039,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
163,Categorical('NBJFXY8_MM_A_NBJFXY8_MMAX_A'),0.567477,0.244115,Tschuprowt,1.017021e-02,44.0,Cramerv,0.553077,DISTANCE_213,True
164,Categorical('NBJRR30_MM_A_NBJRR30_MMAX_A'),0.567477,0.232306,Tschuprowt,1.006179e-02,45.0,Cramerv,0.605871,NBJRR50_MM_A_NBJRR50_MMAX_A,True
165,Categorical('TAMPLIAB_VOR_MM_A_TAMPLIAB_VOR_MM...,0.567477,0.218774,Tschuprowt,1.005323e-02,46.0,Cramerv,0.259588,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
166,Ordinal('NBJRR10_MSOM_A'),0.567477,0.262747,Tschuprowt,9.991996e-03,47.0,Cramerv,0.800806,NBJRR10_MM_A_NBJRR10_MMAX_A,True
167,Categorical('TAMPLIM_VOR_MM_A_TAMPLIM_VOR_MMAX...,0.567477,0.234845,Tschuprowt,9.944258e-03,48.0,Cramerv,0.630036,TAMPLIAB_VOR_MM_A_TAMPLIAB_VOR_MMAX_A,True
168,Categorical('ALTITUDE_5_ALT_TOT'),0.589994,0.254823,Tschuprowt,9.811223e-03,49.0,Cramerv,0.508038,DISTANCE_335,True
169,Categorical('ADOSS'),0.000000,0.978820,Tschuprowt,6.793098e-04,NaN,None,NaN,None,False
170,Categorical('CARACT1'),0.012027,0.957802,Tschuprowt,5.919150e-03,NaN,None,NaN,None,False
171,Categorical('CARACT3'),0.959888,0.040112,Tschuprowt,0.000000e+00,NaN,None,NaN,None,False
172,Categorical('INDEM1'),0.000000,0.953547,Tschuprowt,4.197765e-03,NaN,None,NaN,None,False
173,Categorical('TYPBAT1'),0.921098,0.049565,Tschuprowt,8.819415e-03,NaN,None,NaN,None,False
174,Categorical('FRCH1'),0.000000,0.962012,Tschuprowt,2.999874e-03,NaN,None,NaN,None,False
175,Categorical('FRCH2'),0.069058,0.468207,Tschuprowt,4.828410e-03,NaN,None,NaN,None,False
176,Categorical('DEROG2'),0.000000,0.965975,Tschuprowt,7.095822e-03,NaN,None,NaN,None,False
177,Categorical('DEROG3'),0.000000,0.979136,Tschuprowt,7.459906e-03,NaN,None,NaN,None,False
178,Categorical('DEROG8'),0.000000,0.979370,Tschuprowt,7.621948e-03,NaN,None,NaN,None,False
179,Categorical('KAPITAL34'),0.000000,0.963909,Tschuprowt,2.322643e-03,NaN,None,NaN,None,False
180,Categorical('KAPITAL35'),0.000000,0.975939,Tschuprowt,7.910598e-03,NaN,None,NaN,None,False
181,Categorical('RISK6'),0.069058,0.516482,Tschuprowt,8.742029e-03,NaN,None,NaN,None,False
182,Categorical('RISK8'),0.069058,0.629226,Tschuprowt,6.204247e-03,NaN,None,NaN,None,False

In [12]:
best_features = selector.selected_features.names

## XGBoost + Optuna  *(unchanged objectives from `utils.objectives`)*

The model search is the same as 2025 so any dev-metric delta is attributable to
the carving step, not the tuner. Drop `N_TRIALS` while iterating.

In [13]:
import optuna

from utils.objectives import get_multiclass_objective

N_TRIALS = 300

objective = get_multiclass_objective(
    x_train[best_features],
    y_ord_train,
    x_dev[best_features],
    y_ord_dev,
    w_train=w_train,
    w_dev=w_dev,
)
# seeded so the tuning is reproducible: the split and every XGBoost estimator
# already use random_state=42, and carving is deterministic, so this is the last
# source of run-to-run variance.
study = optuna.create_study(
    direction="minimize", sampler=optuna.samplers.TPESampler(seed=42)
)
study.optimize(objective, n_trials=N_TRIALS)
study.best_params

[I 2026-08-31 08:27:13,084] A new study created in memory with name: no-name-9480a73f-5280-4ead-adf6-bebffda6d764

C:\Users\defra\Desktop\git\PROJECTS\caa-challenge\.venv\Lib\site-packages\xgboost\core.py:751: UserWarning: [08:27:21] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

[I 2026-08-31 08:27:22,489] Trial 0 finished with value: 11.439976647085183 and parameters: {'objective': 'multi:softprob', 'n_estimators': 287, 'learning_rate': 0.9507192349792751, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.3248149123539492, 'colsample_bytree': 0.32479561626896214, 'colsample_bylevel': 0.24646688973455957, 'gamma': 8.661761457749352, 'alpha': 6.011150117432088, 'lambda': 7.080725777960454}. Best is trial 0 with value: 11.439976647085183.

[I 2026-08-31 08:27:27,128] Trial 1 finished with value: 10.12497945384667 and parameters: {'objective': 'multi:softprob', 'n_estimators': 110, 'learning_rate': 0.9699128611767781, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.3454599737656805, 'colsample_bytree': 0.34672360788274703, 'colsample_bylevel': 0.4433937943676302, 'gamma': 5.247564316322379, 'alpha': 4.319450186421157, 'lambda': 2.9122914019804194}. Best is trial 1 with value: 10.12497945384667.

[I 2026-08-31 08:27:39,780] Trial 2 finished with value: 1.6465574086802413 and parameters: {'objective': 'multi:softprob', 'n_estimators': 406, 'learning_rate': 0.13957991126597663, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.5648559873736287, 'colsample_bytree': 0.8281407691144109, 'colsample_bylevel': 0.3597390257266878, 'gamma': 5.142344384136116, 'alpha': 5.924145688620425, 'lambda': 0.46450412719997725}. Best is trial 2 with value: 1.6465574086802413.

[I 2026-08-31 08:27:48,810] Trial 3 finished with value: 0.9671104569252442 and parameters: {'objective': 'multi:softprob', 'n_estimators': 404, 'learning_rate': 0.17060707127492278, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9725056264596474, 'colsample_bytree': 0.846717878493169, 'colsample_bylevel': 0.4436910153386966, 'gamma': 0.9767211400638387, 'alpha': 6.842330265121569, 'lambda': 4.4015249373960135}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:27:53,910] Trial 4 finished with value: 1.1807535973775525 and parameters: {'objective': 'multi:softprob', 'n_estimators': 161, 'learning_rate': 0.49522739242025904, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.40702398528001354, 'colsample_bytree': 0.7300178274831857, 'colsample_bylevel': 0.4493688608715288, 'gamma': 5.200680211778108, 'alpha': 5.4671027934327965, 'lambda': 1.8485445552552704}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:28:09,220] Trial 5 finished with value: 4.829814121871582 and parameters: {'objective': 'multi:softprob', 'n_estimators': 585, 'learning_rate': 0.7751553100787785, 'max_depth': 10, 'min_child_weight': 18, 'subsample': 0.6783199830488682, 'colsample_bytree': 0.9374993880184934, 'colsample_bylevel': 0.2707940016415356, 'gamma': 1.959828624191452, 'alpha': 0.45227288910538066, 'lambda': 3.2533033076326436}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:28:22,212] Trial 6 finished with value: 3.1206188513099344 and parameters: {'objective': 'multi:softprob', 'n_estimators': 294, 'learning_rate': 0.2714218968707185, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.4247476077499046, 'colsample_bytree': 0.6341568665265989, 'colsample_bylevel': 0.31273937997981016, 'gamma': 8.021969807540398, 'alpha': 0.7455064367977082, 'lambda': 9.868869366005173}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:28:32,894] Trial 7 finished with value: 1.0734385352468034 and parameters: {'objective': 'multi:softprob', 'n_estimators': 486, 'learning_rate': 0.19879580996601898, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7654858750780937, 'colsample_bytree': 0.7832057344327898, 'colsample_bylevel': 0.8170162773487566, 'gamma': 0.7404465173409036, 'alpha': 3.5846572854427263, 'lambda': 1.1586905952512971}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:28:50,435] Trial 8 finished with value: 3.9699475684098813 and parameters: {'objective': 'multi:softprob', 'n_estimators': 532, 'learning_rate': 0.6233357970148752, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.4487858573725298, 'colsample_bytree': 0.46014665762139767, 'colsample_bylevel': 0.7836849426704513, 'gamma': 6.3755747135521315, 'alpha': 8.872127425763265, 'lambda': 4.722149251619493}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:28:57,478] Trial 9 finished with value: 3.8101329892800657 and parameters: {'objective': 'multi:softprob', 'n_estimators': 159, 'learning_rate': 0.7132734627442727, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.8167737439636489, 'colsample_bytree': 0.5950364770915126, 'colsample_bylevel': 0.6181862635055952, 'gamma': 4.275410183585496, 'alpha': 0.2541912674409519, 'lambda': 1.0789142699330445}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:29:16,460] Trial 10 finished with value: 1.0082945601676803 and parameters: {'objective': 'multi:softprob', 'n_estimators': 374, 'learning_rate': 0.006096583237521769, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.9814131532569819, 'colsample_bytree': 0.23098015996894666, 'colsample_bylevel': 0.9678165967563358, 'gamma': 2.8905925958373584, 'alpha': 9.51307795498635, 'lambda': 6.4371273662382364}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:29:33,225] Trial 11 finished with value: 0.9814384031440782 and parameters: {'objective': 'multi:softprob', 'n_estimators': 372, 'learning_rate': 0.008649137766908316, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.9971846460001386, 'colsample_bytree': 0.22145059055877642, 'colsample_bylevel': 0.9909653391662029, 'gamma': 2.1785358383633726, 'alpha': 9.600267336039376, 'lambda': 6.002316298303307}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:29:47,426] Trial 12 finished with value: 3.0379165121357063 and parameters: {'objective': 'multi:softprob', 'n_estimators': 408, 'learning_rate': 0.3744406251821827, 'max_depth': 4, 'min_child_weight': 16, 'subsample': 0.9932801402878824, 'colsample_bytree': 0.9782753057038069, 'colsample_bylevel': 0.6145990427879906, 'gamma': 0.2184630777707024, 'alpha': 7.726591734183185, 'lambda': 5.765954901843468}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:30:03,708] Trial 13 finished with value: 1.011221927809692 and parameters: {'objective': 'multi:softprob', 'n_estimators': 304, 'learning_rate': 0.0025349543919357563, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.8806318315090284, 'colsample_bytree': 0.4883554834611627, 'colsample_bylevel': 0.9760199384988906, 'gamma': 2.1363768556891767, 'alpha': 7.803096238541361, 'lambda': 8.796139267265122}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:30:18,691] Trial 14 finished with value: 1.527628337934203 and parameters: {'objective': 'multi:softprob', 'n_estimators': 468, 'learning_rate': 0.13564255010788662, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.9187069578395135, 'colsample_bytree': 0.22682117975105842, 'colsample_bylevel': 0.6163523606608526, 'gamma': 3.1662617341164774, 'alpha': 7.779304623466966, 'lambda': 4.48548056890076}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:30:34,200] Trial 15 finished with value: 3.174259433230633 and parameters: {'objective': 'multi:softprob', 'n_estimators': 347, 'learning_rate': 0.3184235808607091, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.2037920957224718, 'colsample_bytree': 0.5336117879385596, 'colsample_bylevel': 0.7843238346074204, 'gamma': 1.146517136090952, 'alpha': 9.262177757917913, 'lambda': 7.6054244598531895}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:30:42,614] Trial 16 finished with value: 1.4573836114681011 and parameters: {'objective': 'multi:softprob', 'n_estimators': 255, 'learning_rate': 0.43453267747711666, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.7417619680780085, 'colsample_bytree': 0.8758895902324695, 'colsample_bylevel': 0.8812139089520454, 'gamma': 3.073015616642768, 'alpha': 9.989031619779839, 'lambda': 4.9576906314126745}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:31:03,066] Trial 17 finished with value: 2.457642259028186 and parameters: {'objective': 'multi:softprob', 'n_estimators': 447, 'learning_rate': 0.11162189185775512, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.86169933479121, 'colsample_bytree': 0.38793861986590483, 'colsample_bylevel': 0.5219350868734808, 'gamma': 1.5795130006005613, 'alpha': 7.100822496348982, 'lambda': 3.6572438888867453}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:31:10,742] Trial 18 finished with value: 1.1953973846199766 and parameters: {'objective': 'multi:softprob', 'n_estimators': 222, 'learning_rate': 0.22462916708008454, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.6565767273232013, 'colsample_bytree': 0.691853062570388, 'colsample_bylevel': 0.7162010845839389, 'gamma': 0.2927735600047696, 'alpha': 3.4065288398379314, 'lambda': 7.97152583468206}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:31:24,700] Trial 19 finished with value: 2.015569089242877 and parameters: {'objective': 'multi:softprob', 'n_estimators': 370, 'learning_rate': 0.08197296680943317, 'max_depth': 7, 'min_child_weight': 17, 'subsample': 0.9424822945862977, 'colsample_bytree': 0.41071583329859995, 'colsample_bylevel': 0.697524214362791, 'gamma': 9.813130867582933, 'alpha': 2.390425939608689, 'lambda': 5.814384057023714}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:31:42,064] Trial 20 finished with value: 3.132239637489217 and parameters: {'objective': 'multi:softprob', 'n_estimators': 545, 'learning_rate': 0.4703323451407776, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.8322299350787241, 'colsample_bytree': 0.5700096057213453, 'colsample_bylevel': 0.5226785188938063, 'gamma': 3.918396199941158, 'alpha': 8.624808991805704, 'lambda': 2.3536652308037214}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:31:57,712] Trial 21 finished with value: 1.3226969318436197 and parameters: {'objective': 'multi:softprob', 'n_estimators': 349, 'learning_rate': 0.04447448241620523, 'max_depth': 5, 'min_child_weight': 13, 'subsample': 0.9852963562294018, 'colsample_bytree': 0.20550673835818667, 'colsample_bylevel': 0.9771006573810361, 'gamma': 2.815531632433655, 'alpha': 9.827684441673252, 'lambda': 6.3303861461150985}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:32:17,204] Trial 22 finished with value: 0.9991223363203349 and parameters: {'objective': 'multi:softprob', 'n_estimators': 372, 'learning_rate': 0.004379352099612292, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.9273593939191052, 'colsample_bytree': 0.28113520612000825, 'colsample_bylevel': 0.8659449625788173, 'gamma': 2.3794183111879375, 'alpha': 6.824286003707776, 'lambda': 6.606032986471551}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:32:33,909] Trial 23 finished with value: 2.745407658759802 and parameters: {'objective': 'multi:softprob', 'n_estimators': 413, 'learning_rate': 0.17877794818363188, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.9185322963688836, 'colsample_bytree': 0.28064930362901563, 'colsample_bylevel': 0.9036687282871938, 'gamma': 1.9449438478338206, 'alpha': 6.792111554276067, 'lambda': 4.008784670231632}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:32:52,817] Trial 24 finished with value: 2.1450674175357882 and parameters: {'objective': 'multi:softprob', 'n_estimators': 437, 'learning_rate': 0.08398608775227244, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.7645034784841658, 'colsample_bytree': 0.2679993951093913, 'colsample_bylevel': 0.8853060911656067, 'gamma': 1.1052517439168605, 'alpha': 4.9970107762072224, 'lambda': 5.4009440115916325}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:33:06,961] Trial 25 finished with value: 2.5104545338556115 and parameters: {'objective': 'multi:softprob', 'n_estimators': 498, 'learning_rate': 0.2825337610271432, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.9229185099732528, 'colsample_bytree': 0.3155477576109343, 'colsample_bylevel': 0.8348368312985361, 'gamma': 3.8966826478325496, 'alpha': 6.747851138934437, 'lambda': 6.9232511270529775}. Best is trial 3 with value: 0.9671104569252442.

[I 2026-08-31 08:33:19,132] Trial 26 finished with value: 0.9547311600014009 and parameters: {'objective': 'multi:softprob', 'n_estimators': 325, 'learning_rate': 0.006662544416796225, 'max_depth': 3, 'min_child_weight': 16, 'subsample': 0.8677983793850796, 'colsample_bytree': 0.42577943588597944, 'colsample_bylevel': 0.7052667842368143, 'gamma': 2.312687995488208, 'alpha': 8.362541307915398, 'lambda': 8.15981592450115}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:33:29,047] Trial 27 finished with value: 1.241564594549162 and parameters: {'objective': 'multi:softprob', 'n_estimators': 321, 'learning_rate': 0.21504048832105394, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8095849972626379, 'colsample_bytree': 0.4219739339856825, 'colsample_bylevel': 0.7184208384150417, 'gamma': 0.9202687524542732, 'alpha': 8.398384561816133, 'lambda': 8.38478906753408}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:33:38,579] Trial 28 finished with value: 1.0790772047632815 and parameters: {'objective': 'multi:softprob', 'n_estimators': 248, 'learning_rate': 0.09497133526517057, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 0.6686393872955876, 'colsample_bytree': 0.6719786935893999, 'colsample_bylevel': 0.20431754107970765, 'gamma': 1.4427778458021439, 'alpha': 8.368252581123336, 'lambda': 9.636621778839036}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:33:46,957] Trial 29 finished with value: 1.0309933545052985 and parameters: {'objective': 'multi:softprob', 'n_estimators': 325, 'learning_rate': 0.34210592890212443, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.870521407406145, 'colsample_bytree': 0.3579312337401467, 'colsample_bylevel': 0.3881974298814878, 'gamma': 0.0476125939255021, 'alpha': 7.4937908001419515, 'lambda': 7.5701958529066795}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:33:55,723] Trial 30 finished with value: 1.0482457830743321 and parameters: {'objective': 'multi:softprob', 'n_estimators': 268, 'learning_rate': 0.15516373903794375, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.9979975144361848, 'colsample_bytree': 0.7707310973352647, 'colsample_bylevel': 0.5599563277802153, 'gamma': 3.7510898205991063, 'alpha': 9.00377188676108, 'lambda': 8.729406870710301}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:34:10,826] Trial 31 finished with value: 0.9560597313432097 and parameters: {'objective': 'multi:softprob', 'n_estimators': 374, 'learning_rate': 0.011545939462326373, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.9278590682428197, 'colsample_bytree': 0.29564603476866524, 'colsample_bylevel': 0.9317123393276462, 'gamma': 2.397940269608036, 'alpha': 6.248438657320208, 'lambda': 7.027112071611624}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:34:25,973] Trial 32 finished with value: 1.3243295351057254 and parameters: {'objective': 'multi:softprob', 'n_estimators': 395, 'learning_rate': 0.058112491569279806, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.8781273557055398, 'colsample_bytree': 0.32819572670438124, 'colsample_bylevel': 0.9376777268788379, 'gamma': 2.3545189319145097, 'alpha': 6.008280847882187, 'lambda': 6.9854544095338}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:34:37,812] Trial 33 finished with value: 1.1062257915122569 and parameters: {'objective': 'multi:softprob', 'n_estimators': 338, 'learning_rate': 0.06324508252336107, 'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.9527569622684392, 'colsample_bytree': 0.4992948706066265, 'colsample_bylevel': 0.9332262956529952, 'gamma': 3.4007562659247492, 'alpha': 5.14811071224916, 'lambda': 9.228942548981646}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:34:54,994] Trial 34 finished with value: 2.43103008157233 and parameters: {'objective': 'multi:softprob', 'n_estimators': 419, 'learning_rate': 0.14452090580622023, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.8193953039792914, 'colsample_bytree': 0.3758946015711552, 'colsample_bylevel': 0.9953309357161575, 'gamma': 4.56801325597835, 'alpha': 6.083179281964295, 'lambda': 7.737724168584541}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:35:03,648] Trial 35 finished with value: 1.558363372567472 and parameters: {'objective': 'multi:softprob', 'n_estimators': 217, 'learning_rate': 0.24443861536994965, 'max_depth': 3, 'min_child_weight': 12, 'subsample': 0.7184275537786987, 'colsample_bytree': 0.8601298299071803, 'colsample_bylevel': 0.41701133187002065, 'gamma': 1.6294170533744512, 'alpha': 4.456268117080952, 'lambda': 5.826791199300342}. Best is trial 26 with value: 0.9547311600014009.

[I 2026-08-31 08:35:13,139] Trial 36 finished with value: 0.9393834264284853 and parameters: {'objective': 'multi:softprob', 'n_estimators': 387, 'learning_rate': 0.02429375895887931, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9065099098173286, 'colsample_bytree': 0.3154221568052779, 'colsample_bylevel': 0.6711120297923772, 'gamma': 5.688176998681454, 'alpha': 8.16972250595035, 'lambda': 5.164446735189553}. Best is trial 36 with value: 0.9393834264284853.

[I 2026-08-31 08:35:23,610] Trial 37 finished with value: 1.0362878932259578 and parameters: {'objective': 'multi:softprob', 'n_estimators': 443, 'learning_rate': 0.1744775392559531, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.6062638994220226, 'colsample_bytree': 0.31273951975292275, 'colsample_bylevel': 0.6852018872773838, 'gamma': 6.3635244988812385, 'alpha': 6.443413626490331, 'lambda': 2.8786195383419715}. Best is trial 36 with value: 0.9393834264284853.

[I 2026-08-31 08:35:34,567] Trial 38 finished with value: 0.9602810136897774 and parameters: {'objective': 'multi:softprob', 'n_estimators': 470, 'learning_rate': 0.11052440345560555, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.8937217273033078, 'colsample_bytree': 0.4356591450454178, 'colsample_bylevel': 0.46804664457865974, 'gamma': 6.4708728873365615, 'alpha': 5.612023835486375, 'lambda': 5.037213389802583}. Best is trial 36 with value: 0.9393834264284853.

[I 2026-08-31 08:35:48,767] Trial 39 finished with value: 2.845929413486676 and parameters: {'objective': 'multi:softprob', 'n_estimators': 520, 'learning_rate': 0.9108363943732133, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.7839052303093679, 'colsample_bytree': 0.43820153219495894, 'colsample_bylevel': 0.33286618895461817, 'gamma': 6.314397764009776, 'alpha': 5.4273878860520215, 'lambda': 5.1480801550398}. Best is trial 36 with value: 0.9393834264284853.

[I 2026-08-31 08:35:59,907] Trial 40 finished with value: 0.979503861684825 and parameters: {'objective': 'multi:softprob', 'n_estimators': 475, 'learning_rate': 0.12147006938074287, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.7068397220556542, 'colsample_bytree': 0.45926868552013755, 'colsample_bylevel': 0.4997480561319003, 'gamma': 8.15749000737061, 'alpha': 4.508746567195388, 'lambda': 4.1074994689070286}. Best is trial 36 with value: 0.9393834264284853.

[I 2026-08-31 08:36:09,480] Trial 41 finished with value: 0.9337358762970235 and parameters: {'objective': 'multi:softprob', 'n_estimators': 388, 'learning_rate': 0.04000948290751655, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.895202225531395, 'colsample_bytree': 0.5343450888417697, 'colsample_bylevel': 0.4571927310726275, 'gamma': 7.500761540623417, 'alpha': 5.851068384482421, 'lambda': 3.254766657287886}. Best is trial 41 with value: 0.9337358762970235.

[I 2026-08-31 08:36:22,018] Trial 42 finished with value: 0.9366122064949127 and parameters: {'objective': 'multi:softprob', 'n_estimators': 569, 'learning_rate': 0.04470288582555433, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.8904392629172885, 'colsample_bytree': 0.5244873017365784, 'colsample_bylevel': 0.46471180398610923, 'gamma': 7.269699140664175, 'alpha': 3.7721263878405917, 'lambda': 3.3108446910127047}. Best is trial 41 with value: 0.9337358762970235.

[I 2026-08-31 08:36:27,357] Trial 43 finished with value: 0.9423560295746342 and parameters: {'objective': 'multi:softprob', 'n_estimators': 105, 'learning_rate': 0.04474094239064072, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8424884738837312, 'colsample_bytree': 0.5365075768264496, 'colsample_bylevel': 0.5640492672239824, 'gamma': 7.17756801351587, 'alpha': 2.4485401187710196, 'lambda': 3.081460056860413}. Best is trial 41 with value: 0.9337358762970235.

[I 2026-08-31 08:36:32,700] Trial 44 finished with value: 0.930106261212653 and parameters: {'objective': 'multi:softprob', 'n_estimators': 102, 'learning_rate': 0.05402840486004695, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.839802540853604, 'colsample_bytree': 0.5736885482409473, 'colsample_bylevel': 0.5639234967254032, 'gamma': 7.056351515749528, 'alpha': 1.3372988344326058, 'lambda': 1.777308151858286}. Best is trial 44 with value: 0.930106261212653.

[I 2026-08-31 08:36:37,903] Trial 45 finished with value: 0.9271508933501834 and parameters: {'objective': 'multi:softprob', 'n_estimators': 102, 'learning_rate': 0.0540204139748916, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.7801005599679736, 'colsample_bytree': 0.6099245928959975, 'colsample_bylevel': 0.5595420757038215, 'gamma': 7.3045686195555115, 'alpha': 1.300680995156251, 'lambda': 0.1499550322318821}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:36:43,198] Trial 46 finished with value: 0.94277167806886 and parameters: {'objective': 'multi:softprob', 'n_estimators': 138, 'learning_rate': 0.06184104046749256, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7854286145120223, 'colsample_bytree': 0.6213253426233676, 'colsample_bylevel': 0.6465390644376718, 'gamma': 7.249236276428895, 'alpha': 1.0694167846339768, 'lambda': 0.27755771420225006}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:36:58,736] Trial 47 finished with value: 1.5111138045249173 and parameters: {'objective': 'multi:softprob', 'n_estimators': 585, 'learning_rate': 0.1852115894849957, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.5529303619390562, 'colsample_bytree': 0.586053250037462, 'colsample_bylevel': 0.5731478221021843, 'gamma': 5.702501572705891, 'alpha': 1.849096871236009, 'lambda': 1.020496153628121}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:03,949] Trial 48 finished with value: 0.9366069571400429 and parameters: {'objective': 'multi:softprob', 'n_estimators': 132, 'learning_rate': 0.13851504122734842, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.8013674552438416, 'colsample_bytree': 0.6394124079192219, 'colsample_bylevel': 0.48473438549206466, 'gamma': 9.026505404780599, 'alpha': 1.2958723799984528, 'lambda': 1.7684967985873699}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:09,121] Trial 49 finished with value: 0.9600570293585012 and parameters: {'objective': 'multi:softprob', 'n_estimators': 131, 'learning_rate': 0.2636461308973288, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7583997178790954, 'colsample_bytree': 0.6574326703341147, 'colsample_bylevel': 0.46439170881431663, 'gamma': 9.188658201982548, 'alpha': 1.1028904100933439, 'lambda': 2.033565990834739}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:16,393] Trial 50 finished with value: 0.9794782864071979 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.13528551853529716, 'max_depth': 2, 'min_child_weight': 1, 'subsample': 0.7228794176380874, 'colsample_bytree': 0.729483160428501, 'colsample_bylevel': 0.37779869865787874, 'gamma': 7.538245331297208, 'alpha': 0.08959333504946132, 'lambda': 1.6297593883277088}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:22,125] Trial 51 finished with value: 0.9435945261370307 and parameters: {'objective': 'multi:softprob', 'n_estimators': 173, 'learning_rate': 0.04602845156939711, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.814653332213201, 'colsample_bytree': 0.5515005893343541, 'colsample_bylevel': 0.42525855094019627, 'gamma': 8.542192311064975, 'alpha': 1.8068774351635213, 'lambda': 0.7120288351784032}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:27,228] Trial 52 finished with value: 0.9410114805091234 and parameters: {'objective': 'multi:softprob', 'n_estimators': 123, 'learning_rate': 0.10066769566504576, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.8941978906085138, 'colsample_bytree': 0.6238471778561395, 'colsample_bylevel': 0.519384535155348, 'gamma': 7.798325928374531, 'alpha': 3.1204298685939675, 'lambda': 1.515713498545245}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:33,729] Trial 53 finished with value: 1.043055221738251 and parameters: {'objective': 'multi:softprob', 'n_estimators': 155, 'learning_rate': 0.20105993301983324, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8383493652449545, 'colsample_bytree': 0.718167081892685, 'colsample_bylevel': 0.49062536124680584, 'gamma': 6.707530905398825, 'alpha': 0.7664533674432594, 'lambda': 0.014103614369467138}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:37:46,109] Trial 54 finished with value: 0.9329680835520405 and parameters: {'objective': 'multi:softprob', 'n_estimators': 561, 'learning_rate': 0.038776702881911956, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.7969378029148891, 'colsample_bytree': 0.4827189001653904, 'colsample_bylevel': 0.5872147573444768, 'gamma': 5.734935887215398, 'alpha': 1.6557201404228348, 'lambda': 2.4203829101025267}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:38:05,332] Trial 55 finished with value: 2.3168174399601793 and parameters: {'objective': 'multi:softprob', 'n_estimators': 561, 'learning_rate': 0.0811049626229011, 'max_depth': 10, 'min_child_weight': 17, 'subsample': 0.7849163306530307, 'colsample_bytree': 0.4999879628643558, 'colsample_bylevel': 0.5854541603713075, 'gamma': 8.777878713753095, 'alpha': 1.5907690143216981, 'lambda': 2.444981801274589}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:38:20,694] Trial 56 finished with value: 1.3277972777767995 and parameters: {'objective': 'multi:softprob', 'n_estimators': 563, 'learning_rate': 0.15656370322458985, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7977127494971691, 'colsample_bytree': 0.6015452515084878, 'colsample_bylevel': 0.5320848092612679, 'gamma': 6.91729655221768, 'alpha': 2.859292058340209, 'lambda': 3.392108702129235}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:38:34,612] Trial 57 finished with value: 1.0184767855359131 and parameters: {'objective': 'multi:softprob', 'n_estimators': 600, 'learning_rate': 0.11516940977576731, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.6877537094657055, 'colsample_bytree': 0.5223550950147646, 'colsample_bylevel': 0.596533181767269, 'gamma': 5.822479878266586, 'alpha': 3.899311505710783, 'lambda': 2.690403275261297}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:38:40,612] Trial 58 finished with value: 1.9978897489254963 and parameters: {'objective': 'multi:softprob', 'n_estimators': 106, 'learning_rate': 0.6432370938968858, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 0.6311797291015999, 'colsample_bytree': 0.5681465159055006, 'colsample_bylevel': 0.43317645428086676, 'gamma': 8.231504332344945, 'alpha': 1.4096199441057082, 'lambda': 2.0792994627482693}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:38:55,169] Trial 59 finished with value: 0.9532045150330092 and parameters: {'objective': 'multi:softprob', 'n_estimators': 523, 'learning_rate': 0.02916834484561033, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7452878692834515, 'colsample_bytree': 0.6477291157344522, 'colsample_bylevel': 0.6354999799271766, 'gamma': 9.707380801139022, 'alpha': 2.1148428648387636, 'lambda': 3.5025094296304897}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:00,640] Trial 60 finished with value: 0.9393498910553404 and parameters: {'objective': 'multi:softprob', 'n_estimators': 146, 'learning_rate': 0.07876564915694323, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9584156329344485, 'colsample_bytree': 0.4745015694970971, 'colsample_bylevel': 0.5481061353720869, 'gamma': 4.762470087571536, 'alpha': 2.7113119264014465, 'lambda': 1.5477620435595836}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:06,651] Trial 61 finished with value: 0.9363702521675621 and parameters: {'objective': 'multi:softprob', 'n_estimators': 173, 'learning_rate': 0.07679714765019578, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9576965801378199, 'colsample_bytree': 0.4634189123008959, 'colsample_bylevel': 0.5531808353341999, 'gamma': 4.817111056957323, 'alpha': 2.687810515384366, 'lambda': 1.3074235518010933}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:12,814] Trial 62 finished with value: 0.9478250877699548 and parameters: {'objective': 'multi:softprob', 'n_estimators': 181, 'learning_rate': 0.038898829632224706, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.8401337440146975, 'colsample_bytree': 0.5167896812033893, 'colsample_bylevel': 0.4909345198001282, 'gamma': 7.774339839427266, 'alpha': 0.3500046517276765, 'lambda': 0.7619611706969835}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:18,470] Trial 63 finished with value: 0.9620653582265393 and parameters: {'objective': 'multi:softprob', 'n_estimators': 122, 'learning_rate': 0.13646261758822142, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.8504578107677399, 'colsample_bytree': 0.5551559902819915, 'colsample_bylevel': 0.45938664340471536, 'gamma': 5.974783353938079, 'alpha': 0.7917654303159919, 'lambda': 1.2401664446667906}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:23,406] Trial 64 finished with value: 1.0960976550236396 and parameters: {'objective': 'multi:softprob', 'n_estimators': 119, 'learning_rate': 0.0002198783719907782, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.9622833010570966, 'colsample_bytree': 0.6942625676885575, 'colsample_bylevel': 0.40191958968000063, 'gamma': 5.333260942075399, 'alpha': 1.2421352403249966, 'lambda': 2.389297695272039}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:37,067] Trial 65 finished with value: 1.5234784065443463 and parameters: {'objective': 'multi:softprob', 'n_estimators': 504, 'learning_rate': 0.22309063418846373, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8641141620800522, 'colsample_bytree': 0.5917400503039549, 'colsample_bylevel': 0.6006274908600255, 'gamma': 7.275825258596374, 'alpha': 2.099792180416412, 'lambda': 3.740594265084738}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:42,832] Trial 66 finished with value: 0.9387318525964922 and parameters: {'objective': 'multi:softprob', 'n_estimators': 164, 'learning_rate': 0.09120497102089524, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.9041358749245796, 'colsample_bytree': 0.45910974324434406, 'colsample_bylevel': 0.5391378366002314, 'gamma': 5.326437191743171, 'alpha': 3.841282400580457, 'lambda': 1.9416185877206187}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:39:50,218] Trial 67 finished with value: 2.2462595001855017 and parameters: {'objective': 'multi:softprob', 'n_estimators': 198, 'learning_rate': 0.2983966411889889, 'max_depth': 9, 'min_child_weight': 16, 'subsample': 0.9432668877946587, 'colsample_bytree': 0.6114522961675175, 'colsample_bylevel': 0.5101517141912082, 'gamma': 8.990742634923851, 'alpha': 3.2743842950029554, 'lambda': 2.7245863925716516}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:05,114] Trial 68 finished with value: 1.3723324145105062 and parameters: {'objective': 'multi:softprob', 'n_estimators': 547, 'learning_rate': 0.17070596393150883, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.3873234336991951, 'colsample_bytree': 0.38959090094581816, 'colsample_bylevel': 0.3288322254764543, 'gamma': 6.88623345598616, 'alpha': 0.5718673775746359, 'lambda': 1.3042868805455239}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:11,900] Trial 69 finished with value: 0.9719998438499022 and parameters: {'objective': 'multi:softprob', 'n_estimators': 141, 'learning_rate': 0.06219389562733881, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7449371215598133, 'colsample_bytree': 0.5131333943494587, 'colsample_bylevel': 0.6475257847382465, 'gamma': 9.461273459228584, 'alpha': 2.4029910384609336, 'lambda': 0.8041655267932948}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:19,682] Trial 70 finished with value: 0.9463900014658965 and parameters: {'objective': 'multi:softprob', 'n_estimators': 287, 'learning_rate': 0.11502397597006019, 'max_depth': 1, 'min_child_weight': 20, 'subsample': 0.8210383543659473, 'colsample_bytree': 0.48210805231627024, 'colsample_bylevel': 0.7354353304405604, 'gamma': 4.99096278266582, 'alpha': 1.6028453368702928, 'lambda': 0.3840812122796917}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:25,494] Trial 71 finished with value: 0.9357449114897257 and parameters: {'objective': 'multi:softprob', 'n_estimators': 171, 'learning_rate': 0.08242860965908519, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.8891450617849816, 'colsample_bytree': 0.4523118257841152, 'colsample_bylevel': 0.5409265496174762, 'gamma': 5.439646787042686, 'alpha': 3.730074278907322, 'lambda': 1.9584918384844479}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:30,162] Trial 72 finished with value: 0.9908826525129267 and parameters: {'objective': 'multi:softprob', 'n_estimators': 101, 'learning_rate': 0.028149549224701267, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.21684129047225809, 'colsample_bytree': 0.541200396095686, 'colsample_bylevel': 0.47678594634420957, 'gamma': 4.4289619525479065, 'alpha': 3.65277027167095, 'lambda': 3.096963821137006}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:37,902] Trial 73 finished with value: 0.9578302505958889 and parameters: {'objective': 'multi:softprob', 'n_estimators': 224, 'learning_rate': 0.07050818567094945, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8892152363622662, 'colsample_bytree': 0.7683615173984115, 'colsample_bylevel': 0.44560968459613925, 'gamma': 6.096017532405225, 'alpha': 2.19804370747782, 'lambda': 1.7084273579069071}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:43,554] Trial 74 finished with value: 0.944483352439241 and parameters: {'objective': 'multi:softprob', 'n_estimators': 156, 'learning_rate': 0.14052449023029218, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9729239855669378, 'colsample_bytree': 0.5811726501669188, 'colsample_bylevel': 0.6146954070663843, 'gamma': 7.596529860537736, 'alpha': 4.080771674332742, 'lambda': 2.2562762190358154}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:49,896] Trial 75 finished with value: 0.9380590534126153 and parameters: {'objective': 'multi:softprob', 'n_estimators': 200, 'learning_rate': 0.0914783163825679, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.8004218493911118, 'colsample_bytree': 0.6390822271944345, 'colsample_bylevel': 0.5562778870661601, 'gamma': 8.393104249273645, 'alpha': 2.7881284990722204, 'lambda': 2.66769394503829}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:40:56,798] Trial 76 finished with value: 0.9311755451118715 and parameters: {'objective': 'multi:softprob', 'n_estimators': 174, 'learning_rate': 0.037559815030588625, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.9302082884518176, 'colsample_bytree': 0.45143436249665736, 'colsample_bylevel': 0.583255345641105, 'gamma': 6.696583979372038, 'alpha': 3.053429081204346, 'lambda': 1.858299464227226}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:03,576] Trial 77 finished with value: 1.0205089828344813 and parameters: {'objective': 'multi:softprob', 'n_estimators': 181, 'learning_rate': 0.1979830397239546, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.9199775761413271, 'colsample_bytree': 0.4622312781204813, 'colsample_bylevel': 0.5806833888615928, 'gamma': 5.587426120897522, 'alpha': 0.9732897153347593, 'lambda': 1.8667561726465134}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:12,841] Trial 78 finished with value: 1.6801042412492206 and parameters: {'objective': 'multi:softprob', 'n_estimators': 245, 'learning_rate': 0.24441444730657608, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 0.8644177479992695, 'colsample_bytree': 0.49436776014276307, 'colsample_bylevel': 0.6305615867273504, 'gamma': 6.664997948204913, 'alpha': 3.1071589411485427, 'lambda': 1.0351987133682208}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:18,458] Trial 79 finished with value: 1.0929217453196471 and parameters: {'objective': 'multi:softprob', 'n_estimators': 115, 'learning_rate': 0.00037081332053551935, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.9446216160208967, 'colsample_bytree': 0.4132241013102655, 'colsample_bylevel': 0.5383927462247715, 'gamma': 4.1508133268246965, 'alpha': 1.894423642104625, 'lambda': 1.4657511252653732}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:24,325] Trial 80 finished with value: 0.9420024668069195 and parameters: {'objective': 'multi:softprob', 'n_estimators': 130, 'learning_rate': 0.02945716340499873, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.7721058077784035, 'colsample_bytree': 0.4043587587335625, 'colsample_bylevel': 0.67458897258886, 'gamma': 4.9255239999375, 'alpha': 1.4331518942028745, 'lambda': 2.217555308969515}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:30,262] Trial 81 finished with value: 0.9435940123930098 and parameters: {'objective': 'multi:softprob', 'n_estimators': 169, 'learning_rate': 0.04792630879380477, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.88148157587441, 'colsample_bytree': 0.44495247985854597, 'colsample_bylevel': 0.510010603492894, 'gamma': 6.1306924781630805, 'alpha': 4.796140624351336, 'lambda': 3.863158725979681}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:35,921] Trial 82 finished with value: 0.9415617572373528 and parameters: {'objective': 'multi:softprob', 'n_estimators': 149, 'learning_rate': 0.07060959313384849, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.9790318736057262, 'colsample_bytree': 0.5637995503050243, 'colsample_bylevel': 0.5670418183605314, 'gamma': 7.468010058613484, 'alpha': 3.538440484516948, 'lambda': 3.20914344570007}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:42,134] Trial 83 finished with value: 0.9419330876994686 and parameters: {'objective': 'multi:softprob', 'n_estimators': 182, 'learning_rate': 0.10813778448854063, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9180214717718759, 'colsample_bytree': 0.5184478738415969, 'colsample_bylevel': 0.47974175622680465, 'gamma': 7.024168153145741, 'alpha': 4.246611644689346, 'lambda': 4.530113006084807}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:48,337] Trial 84 finished with value: 0.9421013419418315 and parameters: {'objective': 'multi:softprob', 'n_estimators': 137, 'learning_rate': 0.03128757976202707, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8520110091280528, 'colsample_bytree': 0.3658653986719689, 'colsample_bylevel': 0.5989097799729266, 'gamma': 5.538266659573599, 'alpha': 2.649403986967787, 'lambda': 2.541683729488695}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:53,151] Trial 85 finished with value: 0.9299249215267961 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.1631126216906091, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.8305608764351593, 'colsample_bytree': 0.6699377856979207, 'colsample_bylevel': 0.5321705119417153, 'gamma': 8.040825179503182, 'alpha': 2.9629228776863688, 'lambda': 2.891443885922011}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:41:58,786] Trial 86 finished with value: 0.9497175589358184 and parameters: {'objective': 'multi:softprob', 'n_estimators': 114, 'learning_rate': 0.15992193293439994, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.8186190718499158, 'colsample_bytree': 0.6890864920522611, 'colsample_bylevel': 0.5229432549167858, 'gamma': 6.629718109034782, 'alpha': 2.971805070340302, 'lambda': 0.5991816928165304}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:04,691] Trial 87 finished with value: 0.9861913254099867 and parameters: {'objective': 'multi:softprob', 'n_estimators': 104, 'learning_rate': 0.1307268874380415, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 0.8328109263663491, 'colsample_bytree': 0.6738901146405214, 'colsample_bylevel': 0.5469088524493814, 'gamma': 7.790425355737957, 'alpha': 2.5543667866769013, 'lambda': 2.917957203084304}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:11,435] Trial 88 finished with value: 0.9334656075277263 and parameters: {'objective': 'multi:softprob', 'n_estimators': 214, 'learning_rate': 0.09718069622104925, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.7610617010058935, 'colsample_bytree': 0.6075216312067393, 'colsample_bylevel': 0.5808009372682333, 'gamma': 8.583687522284011, 'alpha': 1.6935409621466797, 'lambda': 0.0783211038309896}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:19,134] Trial 89 finished with value: 2.334523653573768 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.874934894573735, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.7069446402048625, 'colsample_bytree': 0.6043524306494253, 'colsample_bylevel': 0.6533379076888095, 'gamma': 7.922242287575295, 'alpha': 3.379632238707481, 'lambda': 0.002839534897746132}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:25,918] Trial 90 finished with value: 0.9331896261912136 and parameters: {'objective': 'multi:softprob', 'n_estimators': 210, 'learning_rate': 0.06608704127947806, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7633664511992754, 'colsample_bytree': 0.4778835201755166, 'colsample_bylevel': 0.5838503607955211, 'gamma': 8.066113387567059, 'alpha': 1.6344483827461482, 'lambda': 0.19010274844813832}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:33,009] Trial 91 finished with value: 0.9357723952221872 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.09395622147759873, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.7644273578390915, 'colsample_bytree': 0.4722101555849771, 'colsample_bylevel': 0.5890323874927597, 'gamma': 8.12079774731082, 'alpha': 1.729940004617593, 'lambda': 0.42870470806193667}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:40,018] Trial 92 finished with value: 0.930736304924611 and parameters: {'objective': 'multi:softprob', 'n_estimators': 224, 'learning_rate': 0.10054306227194744, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7748565013873625, 'colsample_bytree': 0.4881238727739213, 'colsample_bylevel': 0.5812898090912009, 'gamma': 8.111969785476951, 'alpha': 1.6866777148336818, 'lambda': 0.10950149121384639}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:48,599] Trial 93 finished with value: 0.9291072986105743 and parameters: {'objective': 'multi:softprob', 'n_estimators': 303, 'learning_rate': 0.054780936733621936, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.7421577060403689, 'colsample_bytree': 0.49524559692017417, 'colsample_bylevel': 0.6075277731715806, 'gamma': 8.628029776144201, 'alpha': 2.06031742724035, 'lambda': 0.25369855863170965}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:42:56,238] Trial 94 finished with value: 0.9325372167241756 and parameters: {'objective': 'multi:softprob', 'n_estimators': 269, 'learning_rate': 0.055798906810867244, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7275806321768528, 'colsample_bytree': 0.5419301387052169, 'colsample_bylevel': 0.6176302864181016, 'gamma': 8.680937973843328, 'alpha': 2.2097510890455503, 'lambda': 0.1304257953022646}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:04,159] Trial 95 finished with value: 0.9486895824133993 and parameters: {'objective': 'multi:softprob', 'n_estimators': 287, 'learning_rate': 0.020991046361209215, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7418384689610497, 'colsample_bytree': 0.5023195776261117, 'colsample_bylevel': 0.6080238266686472, 'gamma': 8.635276312706898, 'alpha': 2.040503232702588, 'lambda': 0.3013860502220311}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:13,026] Trial 96 finished with value: 0.9487560710555276 and parameters: {'objective': 'multi:softprob', 'n_estimators': 269, 'learning_rate': 0.053842765869542744, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.6857831949833687, 'colsample_bytree': 0.5718388540493886, 'colsample_bylevel': 0.6214420980623846, 'gamma': 8.391018965622274, 'alpha': 2.2654086342036575, 'lambda': 0.8843589230773259}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:20,451] Trial 97 finished with value: 0.9709114825851273 and parameters: {'objective': 'multi:softprob', 'n_estimators': 265, 'learning_rate': 0.18364652523927194, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.7260414539828557, 'colsample_bytree': 0.549713340035062, 'colsample_bylevel': 0.6618199739636716, 'gamma': 9.260757440946984, 'alpha': 1.6040598200605793, 'lambda': 0.06347637954476193}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:30,060] Trial 98 finished with value: 1.0525145405003482 and parameters: {'objective': 'multi:softprob', 'n_estimators': 307, 'learning_rate': 0.11992595156702604, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6618472769872088, 'colsample_bytree': 0.4310587064944327, 'colsample_bylevel': 0.5777099037510823, 'gamma': 8.836849656534973, 'alpha': 1.9206203671111863, 'lambda': 0.27409410313012483}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:38,851] Trial 99 finished with value: 1.1846431522282304 and parameters: {'objective': 'multi:softprob', 'n_estimators': 228, 'learning_rate': 0.10436178223412615, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.706141933593343, 'colsample_bytree': 0.6253147725640731, 'colsample_bylevel': 0.6274263335838907, 'gamma': 8.377999352059101, 'alpha': 0.9538703429811259, 'lambda': 0.5588615618664992}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:45,719] Trial 100 finished with value: 0.9593755567249993 and parameters: {'objective': 'multi:softprob', 'n_estimators': 237, 'learning_rate': 0.1544955315046309, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.7824362212610695, 'colsample_bytree': 0.4852766380509711, 'colsample_bylevel': 0.6934419362645761, 'gamma': 8.069561238203224, 'alpha': 1.2733849703476112, 'lambda': 0.18736966503575367}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:52,291] Trial 101 finished with value: 0.9362956233527462 and parameters: {'objective': 'multi:softprob', 'n_estimators': 211, 'learning_rate': 0.05732057016686277, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.758423271519025, 'colsample_bytree': 0.5283191332944511, 'colsample_bylevel': 0.5691307629576846, 'gamma': 7.4354823494071525, 'alpha': 1.4914043448325833, 'lambda': 0.46014604087410893}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:43:59,731] Trial 102 finished with value: 0.9418909108703196 and parameters: {'objective': 'multi:softprob', 'n_estimators': 258, 'learning_rate': 0.026875113285596754, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.7291653721300368, 'colsample_bytree': 0.9011197234306604, 'colsample_bylevel': 0.6089183824500853, 'gamma': 8.592987228588902, 'alpha': 0.668915901787649, 'lambda': 1.040816182161433}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:44:07,435] Trial 103 finished with value: 0.9669085835775605 and parameters: {'objective': 'multi:softprob', 'n_estimators': 277, 'learning_rate': 0.013862759844646244, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7968653742286081, 'colsample_bytree': 0.580784340016847, 'colsample_bylevel': 0.5900635407172116, 'gamma': 7.657751999968006, 'alpha': 2.316999364772242, 'lambda': 0.16179451752954502}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:44:18,077] Trial 104 finished with value: 0.9899425318800562 and parameters: {'objective': 'multi:softprob', 'n_estimators': 354, 'learning_rate': 0.06111976084765705, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.7750520452801815, 'colsample_bytree': 0.5393868326525632, 'colsample_bylevel': 0.6386955408680013, 'gamma': 7.886609951638589, 'alpha': 1.1465321218348832, 'lambda': 0.6299227157682035}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:44:26,151] Trial 105 finished with value: 1.2623951845135415 and parameters: {'objective': 'multi:softprob', 'n_estimators': 305, 'learning_rate': 0.5326741626650364, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.6329205192292578, 'colsample_bytree': 0.6588784957182494, 'colsample_bylevel': 0.5031930390156563, 'gamma': 7.037319336092073, 'alpha': 1.694715589510448, 'lambda': 0.9491370154557169}. Best is trial 45 with value: 0.9271508933501834.

[I 2026-08-31 08:44:32,535] Trial 106 finished with value: 0.9257644497105022 and parameters: {'objective': 'multi:softprob', 'n_estimators': 202, 'learning_rate': 0.0899256907102241, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.7494339049454449, 'colsample_bytree': 0.507545193992142, 'colsample_bylevel': 0.5625107141349684, 'gamma': 8.227480423971393, 'alpha': 2.020058424345263, 'lambda': 0.581099977406907}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:44:39,789] Trial 107 finished with value: 0.9741238662408562 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.09905086009083505, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.7014201620270086, 'colsample_bytree': 0.5062493927123305, 'colsample_bylevel': 0.563448926939248, 'gamma': 8.8424150718216, 'alpha': 2.0006487485573112, 'lambda': 0.7389234966469922}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:44:46,172] Trial 108 finished with value: 0.9298096118254227 and parameters: {'objective': 'multi:softprob', 'n_estimators': 205, 'learning_rate': 0.12293879115409921, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.7475081664643407, 'colsample_bytree': 0.4869489872749526, 'colsample_bylevel': 0.5256530387955504, 'gamma': 8.250615990013454, 'alpha': 2.9890256021428003, 'lambda': 0.4986985650348724}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:44:54,714] Trial 109 finished with value: 1.0171633165512046 and parameters: {'objective': 'multi:softprob', 'n_estimators': 249, 'learning_rate': 0.12356138467593601, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.7358058827858123, 'colsample_bytree': 0.4820822499495073, 'colsample_bylevel': 0.5255511170281767, 'gamma': 9.982026786180521, 'alpha': 2.4849143218342737, 'lambda': 1.158443200316139}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:01,528] Trial 110 finished with value: 0.9748046639177247 and parameters: {'objective': 'multi:softprob', 'n_estimators': 227, 'learning_rate': 0.2006988462582892, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7510847022436768, 'colsample_bytree': 0.43832829477882934, 'colsample_bylevel': 0.5520748168033749, 'gamma': 8.082212523559114, 'alpha': 2.857941212796413, 'lambda': 0.4583212009720788}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:08,093] Trial 111 finished with value: 0.9373267735851487 and parameters: {'objective': 'multi:softprob', 'n_estimators': 205, 'learning_rate': 0.14694888003321682, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.7679788702735518, 'colsample_bytree': 0.5600020259611694, 'colsample_bylevel': 0.5891854414409834, 'gamma': 8.324791110857026, 'alpha': 3.137483951433647, 'lambda': 0.23111703015117768}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:15,250] Trial 112 finished with value: 0.941548755688636 and parameters: {'objective': 'multi:softprob', 'n_estimators': 239, 'learning_rate': 0.08409000228314761, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.7951673088234151, 'colsample_bytree': 0.4869136375727377, 'colsample_bylevel': 0.6126424917115135, 'gamma': 9.10632969273328, 'alpha': 1.3977983256696132, 'lambda': 0.04197690129853107}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:21,468] Trial 113 finished with value: 0.9339890598499833 and parameters: {'objective': 'multi:softprob', 'n_estimators': 189, 'learning_rate': 0.06913789109418991, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.717703639422337, 'colsample_bytree': 0.5095558666623053, 'colsample_bylevel': 0.5672647611461379, 'gamma': 9.478552417996362, 'alpha': 2.1932040252727685, 'lambda': 0.5973302983284903}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:28,020] Trial 114 finished with value: 0.9631896843361664 and parameters: {'objective': 'multi:softprob', 'n_estimators': 189, 'learning_rate': 0.17472604598410404, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.814616836350804, 'colsample_bytree': 0.5998878053325855, 'colsample_bylevel': 0.530277041792222, 'gamma': 8.540697594467462, 'alpha': 0.8890747451649105, 'lambda': 0.9109593151484875}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:35,744] Trial 115 finished with value: 0.9928199837299073 and parameters: {'objective': 'multi:softprob', 'n_estimators': 215, 'learning_rate': 0.11029196372363242, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.7533670017197476, 'colsample_bytree': 0.3987289359887148, 'colsample_bylevel': 0.5773670989012467, 'gamma': 8.7440435116675, 'alpha': 1.7610327784353206, 'lambda': 1.325453036267945}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:40,788] Trial 116 finished with value: 0.9501900600348961 and parameters: {'objective': 'multi:softprob', 'n_estimators': 125, 'learning_rate': 0.050811685888954294, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.6744840285209378, 'colsample_bytree': 0.9862546452932996, 'colsample_bylevel': 0.5996494166849968, 'gamma': 8.234072603450263, 'alpha': 2.490095797561551, 'lambda': 0.36504280080945506}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:53,240] Trial 117 finished with value: 1.2081356812855935 and parameters: {'objective': 'multi:softprob', 'n_estimators': 426, 'learning_rate': 0.13115726490724494, 'max_depth': 2, 'min_child_weight': 1, 'subsample': 0.6925753303247393, 'colsample_bytree': 0.4237476866887774, 'colsample_bylevel': 0.6628519124371999, 'gamma': 7.983144961211697, 'alpha': 1.9680904776679953, 'lambda': 0.7514890239401122}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:45:59,482] Trial 118 finished with value: 0.9324816213927031 and parameters: {'objective': 'multi:softprob', 'n_estimators': 188, 'learning_rate': 0.0811017042063074, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.7822900663908613, 'colsample_bytree': 0.4696344150134765, 'colsample_bylevel': 0.5080086982444351, 'gamma': 7.286127144897378, 'alpha': 2.255677203641664, 'lambda': 0.180397679145271}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:05,088] Trial 119 finished with value: 0.9885421699368282 and parameters: {'objective': 'multi:softprob', 'n_estimators': 158, 'learning_rate': 0.016358763566189344, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.7850960511256446, 'colsample_bytree': 0.46955269090940993, 'colsample_bylevel': 0.5060690139044838, 'gamma': 7.232136634242451, 'alpha': 2.310415798855363, 'lambda': 0.5248845836063765}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:12,398] Trial 120 finished with value: 0.93000641369324 and parameters: {'objective': 'multi:softprob', 'n_estimators': 190, 'learning_rate': 0.040437790304921034, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.8286060180320494, 'colsample_bytree': 0.4467841307148225, 'colsample_bylevel': 0.5396389337220999, 'gamma': 7.693968668904301, 'alpha': 2.9840877795708813, 'lambda': 1.4412994857507537}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:19,471] Trial 121 finished with value: 0.9311364521245341 and parameters: {'objective': 'multi:softprob', 'n_estimators': 185, 'learning_rate': 0.0403969113348145, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.828171287686941, 'colsample_bytree': 0.44640931165081155, 'colsample_bylevel': 0.5416251386184735, 'gamma': 7.670324704292169, 'alpha': 3.0861590340172693, 'lambda': 1.628398208716128}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:26,673] Trial 122 finished with value: 0.937901361245244 and parameters: {'objective': 'multi:softprob', 'n_estimators': 189, 'learning_rate': 0.04025546640014015, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.8306356171795701, 'colsample_bytree': 0.4505824598338193, 'colsample_bylevel': 0.5410035549485289, 'gamma': 7.670870645029428, 'alpha': 2.872175017617628, 'lambda': 2.1129047715653275}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:33,873] Trial 123 finished with value: 0.9650788839685558 and parameters: {'objective': 'multi:softprob', 'n_estimators': 149, 'learning_rate': 0.012256284808749313, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.8048558013574114, 'colsample_bytree': 0.49595402874019856, 'colsample_bylevel': 0.5163146277383706, 'gamma': 6.823837888095534, 'alpha': 3.2120567634700268, 'lambda': 1.4331792709447781}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:46,572] Trial 124 finished with value: 1.0113037633276003 and parameters: {'objective': 'multi:softprob', 'n_estimators': 458, 'learning_rate': 0.0784604803999798, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.8570762161233327, 'colsample_bytree': 0.42253263741228664, 'colsample_bylevel': 0.49440151127148596, 'gamma': 6.465958638174094, 'alpha': 3.52418139040888, 'lambda': 1.7088126393201568}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:46:53,207] Trial 125 finished with value: 0.9478431114864457 and parameters: {'objective': 'multi:softprob', 'n_estimators': 166, 'learning_rate': 0.05575993581717786, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.5183669926653306, 'colsample_bytree': 0.4556901264588942, 'colsample_bylevel': 0.5548732538485043, 'gamma': 7.33167747555196, 'alpha': 2.941391918370912, 'lambda': 1.2112123179833436}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:01,001] Trial 126 finished with value: 0.9330120608694661 and parameters: {'objective': 'multi:softprob', 'n_estimators': 179, 'learning_rate': 0.03181381846321028, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.8216249286970986, 'colsample_bytree': 0.38096123360162965, 'colsample_bylevel': 0.5233180930355894, 'gamma': 7.6148336690273934, 'alpha': 2.6454339638901287, 'lambda': 1.581827084881405}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:06,431] Trial 127 finished with value: 0.9438048850249254 and parameters: {'objective': 'multi:softprob', 'n_estimators': 113, 'learning_rate': 0.08035023226444482, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.7877467879579125, 'colsample_bytree': 0.3381888383774765, 'colsample_bylevel': 0.26153849505161164, 'gamma': 7.028839331735719, 'alpha': 3.034413937821729, 'lambda': 1.7788856504487136}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:14,301] Trial 128 finished with value: 1.003721525053832 and parameters: {'objective': 'multi:softprob', 'n_estimators': 224, 'learning_rate': 0.11374616082319607, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.8445328862997326, 'colsample_bytree': 0.5214381543818386, 'colsample_bylevel': 0.5396557213679981, 'gamma': 7.853357827056389, 'alpha': 2.123112774424781, 'lambda': 2.4691988808710468}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:21,443] Trial 129 finished with value: 0.9284029703699744 and parameters: {'objective': 'multi:softprob', 'n_estimators': 190, 'learning_rate': 0.04226624480657108, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.7376339701420369, 'colsample_bytree': 0.44000352049645897, 'colsample_bylevel': 0.554391763991193, 'gamma': 7.420125491396343, 'alpha': 3.4149262280831802, 'lambda': 1.074750191330141}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:29,487] Trial 130 finished with value: 1.254911681050121 and parameters: {'objective': 'multi:softprob', 'n_estimators': 192, 'learning_rate': 0.16040303821390606, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.7338731248150949, 'colsample_bytree': 0.4117578593958861, 'colsample_bylevel': 0.478458371225689, 'gamma': 7.419694693335592, 'alpha': 3.3635039082396925, 'lambda': 1.1095727428553368}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:37,103] Trial 131 finished with value: 1.070049700569608 and parameters: {'objective': 'multi:softprob', 'n_estimators': 200, 'learning_rate': 0.001165008035137187, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.807693164841879, 'colsample_bytree': 0.4421838252613113, 'colsample_bylevel': 0.5575808901933613, 'gamma': 7.166301958509928, 'alpha': 2.6558919437939417, 'lambda': 0.8467585288981413}. Best is trial 106 with value: 0.9257644497105022.

[I 2026-08-31 08:47:44,082] Trial 132 finished with value: 0.9249131061974062 and parameters: {'objective': 'multi:softprob', 'n_estimators': 176, 'learning_rate': 0.04322626351327087, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.7740793256703574, 'colsample_bytree': 0.47150404257119993, 'colsample_bylevel': 0.5084933148168244, 'gamma': 7.695681767705847, 'alpha': 3.4656210028676155, 'lambda': 1.410396354164317}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:47:54,070] Trial 133 finished with value: 0.9480391187143691 and parameters: {'objective': 'multi:softprob', 'n_estimators': 318, 'learning_rate': 0.04239280107403366, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.773175115160682, 'colsample_bytree': 0.46704532100903073, 'colsample_bylevel': 0.5072651719316502, 'gamma': 7.746528532881515, 'alpha': 3.9994632149271974, 'lambda': 1.3218791877887437}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:00,898] Trial 134 finished with value: 0.9547984398577729 and parameters: {'objective': 'multi:softprob', 'n_estimators': 180, 'learning_rate': 0.0877671992818838, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.7226897233554193, 'colsample_bytree': 0.5343931575254527, 'colsample_bylevel': 0.5261275289088924, 'gamma': 6.748486919733129, 'alpha': 3.4681582763019745, 'lambda': 0.38655908542308925}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:08,107] Trial 135 finished with value: 0.9809300134708481 and parameters: {'objective': 'multi:softprob', 'n_estimators': 161, 'learning_rate': 0.06564263602265283, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.7449906696076735, 'colsample_bytree': 0.44545919749447505, 'colsample_bylevel': 0.49022803368396095, 'gamma': 7.54068105357887, 'alpha': 3.2588457276792093, 'lambda': 0.6992882974950025}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:15,704] Trial 136 finished with value: 0.9453778142759705 and parameters: {'objective': 'multi:softprob', 'n_estimators': 208, 'learning_rate': 0.019266639046262822, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.8344138376554157, 'colsample_bytree': 0.4976538809441833, 'colsample_bylevel': 0.5413178035370175, 'gamma': 7.098158670686848, 'alpha': 3.639487111030175, 'lambda': 1.05887385778029}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:21,838] Trial 137 finished with value: 0.95598433393278 and parameters: {'objective': 'multi:softprob', 'n_estimators': 145, 'learning_rate': 0.09589153216983179, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.7769026444653472, 'colsample_bytree': 0.5478009863508497, 'colsample_bylevel': 0.5678628081947416, 'gamma': 8.22174473920655, 'alpha': 4.126605149175066, 'lambda': 1.9058161505715414}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:28,559] Trial 138 finished with value: 0.9351018327909183 and parameters: {'objective': 'multi:softprob', 'n_estimators': 170, 'learning_rate': 0.044487750764047373, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.7158136858518062, 'colsample_bytree': 0.4243469631902239, 'colsample_bylevel': 0.6250859425477302, 'gamma': 8.473725533413495, 'alpha': 2.431376403196882, 'lambda': 1.4817403205765014}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:37,178] Trial 139 finished with value: 0.9544833349435782 and parameters: {'objective': 'multi:softprob', 'n_estimators': 337, 'learning_rate': 0.13512391439170068, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.8747878687756234, 'colsample_bytree': 0.45773102490767636, 'colsample_bylevel': 0.44275634451054074, 'gamma': 7.882693871460774, 'alpha': 3.0477969508762635, 'lambda': 0.9155133234554145}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:43,330] Trial 140 finished with value: 0.9369582993351614 and parameters: {'objective': 'multi:softprob', 'n_estimators': 189, 'learning_rate': 0.07238487282817847, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.7532735335624454, 'colsample_bytree': 0.3987528252243135, 'colsample_bylevel': 0.6051829691990656, 'gamma': 6.905198771985251, 'alpha': 2.7666348215947356, 'lambda': 0.2514085018525396}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:49,641] Trial 141 finished with value: 1.2433125308630868 and parameters: {'objective': 'multi:softprob', 'n_estimators': 204, 'learning_rate': 0.9916746407752492, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.8006515897473513, 'colsample_bytree': 0.48256237070435987, 'colsample_bylevel': 0.5528932007469428, 'gamma': 7.3698552036126745, 'alpha': 3.8643238174655483, 'lambda': 2.233383228430636}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:48:59,740] Trial 142 finished with value: 1.2876874792807114 and parameters: {'objective': 'multi:softprob', 'n_estimators': 132, 'learning_rate': 0.03433696772878543, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.8258322128614948, 'colsample_bytree': 0.5122848272576104, 'colsample_bylevel': 0.5748228799653916, 'gamma': 8.947964509145956, 'alpha': 3.260522765764822, 'lambda': 2.8471798664960737}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:05,693] Trial 143 finished with value: 0.9434969023833267 and parameters: {'objective': 'multi:softprob', 'n_estimators': 180, 'learning_rate': 0.051440727300833274, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.7352513023616759, 'colsample_bytree': 0.46812511194464546, 'colsample_bylevel': 0.5167616827968239, 'gamma': 7.967075124802569, 'alpha': 1.8956001149665826, 'lambda': 1.5465212358967455}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:10,520] Trial 144 finished with value: 0.9359894528667485 and parameters: {'objective': 'multi:softprob', 'n_estimators': 111, 'learning_rate': 0.09953945689521393, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.7850105223066268, 'colsample_bytree': 0.4844251189830957, 'colsample_bylevel': 0.5315024866705761, 'gamma': 6.283566408335734, 'alpha': 1.2818406965349733, 'lambda': 2.002309543447269}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:15,935] Trial 145 finished with value: 0.9633153368465356 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.02548326385881953, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.8081020435976896, 'colsample_bytree': 0.4363125612108345, 'colsample_bylevel': 0.5893208725222912, 'gamma': 8.183793511245206, 'alpha': 2.207990116509464, 'lambda': 0.4612416943523632}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:22,735] Trial 146 finished with value: 0.9313218345397132 and parameters: {'objective': 'multi:softprob', 'n_estimators': 217, 'learning_rate': 0.06746726594474804, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.8501094262427544, 'colsample_bytree': 0.5024538335996267, 'colsample_bylevel': 0.6410061143112568, 'gamma': 7.593875682722036, 'alpha': 2.543102873920991, 'lambda': 0.6326682157127692}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:29,407] Trial 147 finished with value: 0.9380167711288213 and parameters: {'objective': 'multi:softprob', 'n_estimators': 219, 'learning_rate': 0.12455850198748714, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.8734773470802455, 'colsample_bytree': 0.5232623351540701, 'colsample_bylevel': 0.6496973753786891, 'gamma': 7.626099811703484, 'alpha': 2.8972229686202593, 'lambda': 0.6080499771035156}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:38,865] Trial 148 finished with value: 0.9605912278488543 and parameters: {'objective': 'multi:softprob', 'n_estimators': 293, 'learning_rate': 0.06118619658379768, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.8503480348688803, 'colsample_bytree': 0.5042972841240241, 'colsample_bylevel': 0.6083931112556629, 'gamma': 6.585858676524397, 'alpha': 2.600250847394986, 'lambda': 0.028100760258181673}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:45,663] Trial 149 finished with value: 0.931549156038947 and parameters: {'objective': 'multi:softprob', 'n_estimators': 231, 'learning_rate': 0.0809740470617637, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.6969070893675181, 'colsample_bytree': 0.5394631429738248, 'colsample_bylevel': 0.6318612776477254, 'gamma': 7.389467295598373, 'alpha': 2.457101603292575, 'lambda': 0.7707819328963372}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:49:53,718] Trial 150 finished with value: 0.987518791758989 and parameters: {'objective': 'multi:softprob', 'n_estimators': 230, 'learning_rate': 0.10872856482774641, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.7692965798901104, 'colsample_bytree': 0.7507325642706202, 'colsample_bylevel': 0.6772339374346059, 'gamma': 7.263020300934081, 'alpha': 3.1817549371110756, 'lambda': 1.215325944317057}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:50:00,805] Trial 151 finished with value: 0.938539350018863 and parameters: {'objective': 'multi:softprob', 'n_estimators': 246, 'learning_rate': 0.07934423251965798, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.6451697661609133, 'colsample_bytree': 0.5514973506945398, 'colsample_bylevel': 0.6356503573136072, 'gamma': 7.477085096956102, 'alpha': 2.42367797995383, 'lambda': 0.7560306512584746}. Best is trial 132 with value: 0.9249131061974062.

[I 2026-08-31 08:50:07,207] Trial 152 finished with value: 0.9223102665231168 and parameters: {'objective': 'multi:softprob', 'n_estimators': 199, 'learning_rate': 0.08613770388249281, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7494546856639388, 'colsample_bytree': 0.4986811957253001, 'colsample_bylevel': 0.6187475108664386, 'gamma': 7.775725004779108, 'alpha': 2.7004562587392624, 'lambda': 0.25880302491777907}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:13,676] Trial 153 finished with value: 0.9336586996294178 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.08454973028248035, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.6888993110755304, 'colsample_bytree': 0.4920572081416373, 'colsample_bylevel': 0.559879808964834, 'gamma': 7.750208309859042, 'alpha': 2.8200111417999345, 'lambda': 0.4105272629545512}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:20,463] Trial 154 finished with value: 1.0842792450069738 and parameters: {'objective': 'multi:softprob', 'n_estimators': 220, 'learning_rate': 0.0007311471746598644, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7061788956720921, 'colsample_bytree': 0.4652366396054295, 'colsample_bylevel': 0.6295154155109755, 'gamma': 7.107553111405031, 'alpha': 3.4715339268385805, 'lambda': 1.0700782337938617}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:27,015] Trial 155 finished with value: 1.2850096746192072 and parameters: {'objective': 'multi:softprob', 'n_estimators': 207, 'learning_rate': 0.7888771531436956, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.744534735144662, 'colsample_bytree': 0.7093220064250285, 'colsample_bylevel': 0.5958194731388031, 'gamma': 8.001916898549407, 'alpha': 3.02913154521448, 'lambda': 0.6367427843318965}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:33,909] Trial 156 finished with value: 0.9564715636444606 and parameters: {'objective': 'multi:softprob', 'n_estimators': 175, 'learning_rate': 0.11419969902377136, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.760153554972796, 'colsample_bytree': 0.5690924287041126, 'colsample_bylevel': 0.5027306443138546, 'gamma': 7.434401667404725, 'alpha': 2.58612261700446, 'lambda': 0.2723140763862103}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:39,597] Trial 157 finished with value: 0.9916549181799584 and parameters: {'objective': 'multi:softprob', 'n_estimators': 156, 'learning_rate': 0.14757068398147727, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.2820712724664769, 'colsample_bytree': 0.513103659386098, 'colsample_bylevel': 0.7190765930039227, 'gamma': 7.703169437976527, 'alpha': 2.7609950120892663, 'lambda': 0.8895606241925536}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:46,021] Trial 158 finished with value: 0.9356769996955042 and parameters: {'objective': 'multi:softprob', 'n_estimators': 193, 'learning_rate': 0.097898199419192, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.8145756998230814, 'colsample_bytree': 0.44231610799881105, 'colsample_bylevel': 0.5446939201510722, 'gamma': 6.946541542098958, 'alpha': 2.3287998776886445, 'lambda': 1.3641718837541872}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:50:54,261] Trial 159 finished with value: 0.946722714402129 and parameters: {'objective': 'multi:softprob', 'n_estimators': 232, 'learning_rate': 0.06731822884855376, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.8391999870084231, 'colsample_bytree': 0.4727415825959705, 'colsample_bylevel': 0.4690113762191102, 'gamma': 8.259456067460553, 'alpha': 3.648793056318648, 'lambda': 0.0022675952544920497}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:00,387] Trial 160 finished with value: 0.9496280158683975 and parameters: {'objective': 'multi:softprob', 'n_estimators': 186, 'learning_rate': 0.03330296948917545, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.7916539362306465, 'colsample_bytree': 0.5319077758677043, 'colsample_bylevel': 0.5751502148008878, 'gamma': 7.811315932327327, 'alpha': 1.9311365072025235, 'lambda': 1.72680618285086}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:08,211] Trial 161 finished with value: 0.9332071788432643 and parameters: {'objective': 'multi:softprob', 'n_estimators': 281, 'learning_rate': 0.05093119119374465, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.726535912279617, 'colsample_bytree': 0.5322598296335164, 'colsample_bylevel': 0.608108218475678, 'gamma': 8.422849564261032, 'alpha': 2.2303570605164964, 'lambda': 0.27545025760275255}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:14,988] Trial 162 finished with value: 0.9329651987337627 and parameters: {'objective': 'multi:softprob', 'n_estimators': 220, 'learning_rate': 0.06298061217270412, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.7426116677820465, 'colsample_bytree': 0.58492212728828, 'colsample_bylevel': 0.6420919642852995, 'gamma': 8.692704809070104, 'alpha': 2.478611724844776, 'lambda': 0.5861497306479158}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:22,486] Trial 163 finished with value: 0.9579676121692896 and parameters: {'objective': 'multi:softprob', 'n_estimators': 260, 'learning_rate': 0.018588922337822576, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.672604965820659, 'colsample_bytree': 0.4966275958651474, 'colsample_bylevel': 0.6194123891295108, 'gamma': 7.317777793496332, 'alpha': 2.040046755250616, 'lambda': 0.45116354228637906}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:29,911] Trial 164 finished with value: 0.9611401666883698 and parameters: {'objective': 'multi:softprob', 'n_estimators': 203, 'learning_rate': 0.08417130781489862, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.771665330283021, 'colsample_bytree': 0.5451080791268534, 'colsample_bylevel': 0.5325887471784454, 'gamma': 8.08466177405904, 'alpha': 3.0168586519893466, 'lambda': 0.23876694974336704}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:37,114] Trial 165 finished with value: 0.9342370355405406 and parameters: {'objective': 'multi:softprob', 'n_estimators': 251, 'learning_rate': 0.1163491571256958, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7109514502927348, 'colsample_bytree': 0.45661418803028375, 'colsample_bylevel': 0.6559882048727681, 'gamma': 7.5946836570641425, 'alpha': 3.2632797233340196, 'lambda': 0.7970065561276857}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:45,348] Trial 166 finished with value: 0.9296329825824947 and parameters: {'objective': 'multi:softprob', 'n_estimators': 237, 'learning_rate': 0.04293998716764686, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6980372440129755, 'colsample_bytree': 0.5130373302858537, 'colsample_bylevel': 0.5667543334055355, 'gamma': 7.865743479941186, 'alpha': 2.7857781758614006, 'lambda': 0.9857020047873375}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:51:53,525] Trial 167 finished with value: 0.9364506912419157 and parameters: {'objective': 'multi:softprob', 'n_estimators': 242, 'learning_rate': 0.03909856680588382, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.6905228583996681, 'colsample_bytree': 0.8164532058165839, 'colsample_bylevel': 0.5607886581538655, 'gamma': 7.91423486751169, 'alpha': 2.705874485795616, 'lambda': 1.1757099434363272}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:00,061] Trial 168 finished with value: 0.9586302742288683 and parameters: {'objective': 'multi:softprob', 'n_estimators': 167, 'learning_rate': 0.07605313232698531, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.8244940458863477, 'colsample_bytree': 0.5043245773769254, 'colsample_bylevel': 0.5748260757438335, 'gamma': 7.166133113357645, 'alpha': 3.3980246285180664, 'lambda': 0.9950903672613928}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:07,829] Trial 169 finished with value: 0.946099181304033 and parameters: {'objective': 'multi:softprob', 'n_estimators': 209, 'learning_rate': 0.017060651841098534, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.8582061775882187, 'colsample_bytree': 0.4786580230531333, 'colsample_bylevel': 0.5922073929690106, 'gamma': 7.524287703926704, 'alpha': 2.8893796642143244, 'lambda': 0.7290607166649977}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:13,926] Trial 170 finished with value: 1.0665807563297331 and parameters: {'objective': 'multi:softprob', 'n_estimators': 122, 'learning_rate': 0.1319952719574838, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7555475408051969, 'colsample_bytree': 0.5139115974677976, 'colsample_bylevel': 0.5155293405276388, 'gamma': 8.200379529633336, 'alpha': 3.0795495983947387, 'lambda': 1.534957839512676}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:21,018] Trial 171 finished with value: 0.9380304060644131 and parameters: {'objective': 'multi:softprob', 'n_estimators': 234, 'learning_rate': 0.05214757258980285, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7320567037127778, 'colsample_bytree': 0.4893607478343151, 'colsample_bylevel': 0.54931256173102, 'gamma': 7.782865868063818, 'alpha': 2.355121776917765, 'lambda': 0.18460272485416854}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:28,461] Trial 172 finished with value: 0.9554635285944805 and parameters: {'objective': 'multi:softprob', 'n_estimators': 267, 'learning_rate': 0.09518919786976669, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.656310654566813, 'colsample_bytree': 0.5598974303127214, 'colsample_bylevel': 0.5824127339059069, 'gamma': 8.427406368765418, 'alpha': 2.5619474835950147, 'lambda': 0.4795291960208432}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:35,674] Trial 173 finished with value: 0.9332460153299442 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.056652394165400896, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.6985621436152615, 'colsample_bytree': 0.5273927221806154, 'colsample_bylevel': 0.6130253258886934, 'gamma': 7.384204982796976, 'alpha': 1.4632400636651148, 'lambda': 0.5794430662748355}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:42,243] Trial 174 finished with value: 0.9424075180652244 and parameters: {'objective': 'multi:softprob', 'n_estimators': 217, 'learning_rate': 0.037644751808418364, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.7249359249931804, 'colsample_bytree': 0.45365519183789205, 'colsample_bylevel': 0.537055429641176, 'gamma': 6.785831184810132, 'alpha': 1.794787351012339, 'lambda': 0.9310059972310147}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:49,195] Trial 175 finished with value: 1.3245969303463083 and parameters: {'objective': 'multi:softprob', 'n_estimators': 184, 'learning_rate': 0.406736147327067, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.7815025971492171, 'colsample_bytree': 0.4977860039452233, 'colsample_bylevel': 0.5609278027817909, 'gamma': 8.036236392459537, 'alpha': 2.054974745929565, 'lambda': 0.0248484803524799}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:52:56,529] Trial 176 finished with value: 1.0759390738700243 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.0010907248727093366, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.7443541809534965, 'colsample_bytree': 0.43161413588800007, 'colsample_bylevel': 0.4945136844251304, 'gamma': 7.594912967761292, 'alpha': 2.8144348876645564, 'lambda': 0.3739577651531082}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:05,601] Trial 177 finished with value: 0.9603924136676623 and parameters: {'objective': 'multi:softprob', 'n_estimators': 275, 'learning_rate': 0.06913855941909952, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.7109569623703195, 'colsample_bytree': 0.41203929803166794, 'colsample_bylevel': 0.6253016141392701, 'gamma': 7.154864532111723, 'alpha': 3.2537191962113856, 'lambda': 1.3058050424071916}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:12,274] Trial 178 finished with value: 0.9474300877948479 and parameters: {'objective': 'multi:softprob', 'n_estimators': 226, 'learning_rate': 0.1006599660297021, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.7967400110374504, 'colsample_bytree': 0.47860294212922516, 'colsample_bylevel': 0.6001680471379957, 'gamma': 8.62402764064447, 'alpha': 1.1111850899933144, 'lambda': 1.8131297155584507}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:18,777] Trial 179 finished with value: 0.9507562020806285 and parameters: {'objective': 'multi:softprob', 'n_estimators': 204, 'learning_rate': 0.030179178090104047, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.7757580630341318, 'colsample_bytree': 0.573226695767008, 'colsample_bylevel': 0.5223616535391202, 'gamma': 7.899242168862106, 'alpha': 2.1676265498230425, 'lambda': 0.17471517122322236}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:25,511] Trial 180 finished with value: 0.9433538082291678 and parameters: {'objective': 'multi:softprob', 'n_estimators': 173, 'learning_rate': 0.0822588997183834, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.7569064882900257, 'colsample_bytree': 0.618848259810043, 'colsample_bylevel': 0.5469881356367441, 'gamma': 8.27838009684636, 'alpha': 2.4904887772314397, 'lambda': 0.7683101719545946}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:32,098] Trial 181 finished with value: 0.933657234491324 and parameters: {'objective': 'multi:softprob', 'n_estimators': 210, 'learning_rate': 0.0532925380187278, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.7372750755589552, 'colsample_bytree': 0.5985626580497975, 'colsample_bylevel': 0.6389254337063438, 'gamma': 8.636543851976834, 'alpha': 2.679031026836699, 'lambda': 0.5928739837780169}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:38,822] Trial 182 finished with value: 0.931314835307494 and parameters: {'objective': 'multi:softprob', 'n_estimators': 218, 'learning_rate': 0.06457659985634094, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.7531437099809465, 'colsample_bytree': 0.5441980389955138, 'colsample_bylevel': 0.6693845084037304, 'gamma': 8.814861657730379, 'alpha': 2.41468447938193, 'lambda': 0.5259553808598425}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:45,958] Trial 183 finished with value: 0.9342660820410125 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.07036650491981485, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7635395362513249, 'colsample_bytree': 0.5483495196605774, 'colsample_bylevel': 0.5749757094524351, 'gamma': 8.989171270037717, 'alpha': 2.98927636506757, 'lambda': 0.30905599129248246}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:52,344] Trial 184 finished with value: 0.9398226904807722 and parameters: {'objective': 'multi:softprob', 'n_estimators': 194, 'learning_rate': 0.04031743381555261, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.727251675016949, 'colsample_bytree': 0.5240916519547844, 'colsample_bylevel': 0.6819187791689855, 'gamma': 9.321458988508594, 'alpha': 2.3096354848349208, 'lambda': 0.9106886398693794}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:53:57,156] Trial 185 finished with value: 0.9405963967664877 and parameters: {'objective': 'multi:softprob', 'n_estimators': 101, 'learning_rate': 0.093616707974362, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.7866734216897318, 'colsample_bytree': 0.5368709682443451, 'colsample_bylevel': 0.6586970384270636, 'gamma': 8.844259013989424, 'alpha': 1.6622347201457477, 'lambda': 1.1706092764520648}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:05,140] Trial 186 finished with value: 0.9369129376089373 and parameters: {'objective': 'multi:softprob', 'n_estimators': 217, 'learning_rate': 0.02100815238206166, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.8096506527569342, 'colsample_bytree': 0.5117199244992088, 'colsample_bylevel': 0.7013901439662674, 'gamma': 7.716153892603923, 'alpha': 1.8949481367313399, 'lambda': 0.4559727188267598}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:12,273] Trial 187 finished with value: 0.937365813161235 and parameters: {'objective': 'multi:softprob', 'n_estimators': 227, 'learning_rate': 0.11898067040302238, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.9086770198799187, 'colsample_bytree': 0.46821110671451316, 'colsample_bylevel': 0.5919616745341184, 'gamma': 7.382239088691238, 'alpha': 3.4540007382788125, 'lambda': 1.6416443437560762}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:21,559] Trial 188 finished with value: 0.9420349019909914 and parameters: {'objective': 'multi:softprob', 'n_estimators': 243, 'learning_rate': 0.052436081757076876, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.7657960094488349, 'colsample_bytree': 0.4915956210357664, 'colsample_bylevel': 0.563925841697535, 'gamma': 8.04547447131958, 'alpha': 2.566843178321464, 'lambda': 0.16606984656730722}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:28,161] Trial 189 finished with value: 0.9546768492065261 and parameters: {'objective': 'multi:softprob', 'n_estimators': 184, 'learning_rate': 0.15106711809910023, 'max_depth': 1, 'min_child_weight': 10, 'subsample': 0.6744513143533926, 'colsample_bytree': 0.4495856655221204, 'colsample_bylevel': 0.667182762972329, 'gamma': 6.955507573850276, 'alpha': 2.8458987232610538, 'lambda': 1.0639744412359613}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:36,325] Trial 190 finished with value: 0.9591006845439125 and parameters: {'objective': 'multi:softprob', 'n_estimators': 199, 'learning_rate': 0.07550206361520569, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.8395967126058725, 'colsample_bytree': 0.5093542830926587, 'colsample_bylevel': 0.5093415662124792, 'gamma': 8.298173241173926, 'alpha': 3.7862672736012426, 'lambda': 0.009480043512275077}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:43,215] Trial 191 finished with value: 0.9326364652765226 and parameters: {'objective': 'multi:softprob', 'n_estimators': 219, 'learning_rate': 0.06236813043405613, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.7485567217644026, 'colsample_bytree': 0.5832930641216845, 'colsample_bylevel': 0.6369252113864301, 'gamma': 8.760569299360114, 'alpha': 2.443962813133922, 'lambda': 0.611508058127381}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:50,008] Trial 192 finished with value: 0.9327626318717656 and parameters: {'objective': 'multi:softprob', 'n_estimators': 215, 'learning_rate': 0.05154105855353593, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.7485951631473786, 'colsample_bytree': 0.5652635575226448, 'colsample_bylevel': 0.6265520596747801, 'gamma': 8.792523454617017, 'alpha': 2.32464686565172, 'lambda': 0.6545509446599591}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:54:56,500] Trial 193 finished with value: 0.9300006748294872 and parameters: {'objective': 'multi:softprob', 'n_estimators': 204, 'learning_rate': 0.09903032609703694, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.7180515343278089, 'colsample_bytree': 0.5826296975446589, 'colsample_bylevel': 0.6152946439605274, 'gamma': 8.41366028203408, 'alpha': 2.131750680819676, 'lambda': 0.3604010016182484}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:03,109] Trial 194 finished with value: 0.9373029422191278 and parameters: {'objective': 'multi:softprob', 'n_estimators': 204, 'learning_rate': 0.09502476763044072, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.713027054068994, 'colsample_bytree': 0.6504280422410309, 'colsample_bylevel': 0.6102582606509377, 'gamma': 8.126047646118137, 'alpha': 2.0997222006224527, 'lambda': 0.3780486144293422}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:09,520] Trial 195 finished with value: 0.9409196699663399 and parameters: {'objective': 'multi:softprob', 'n_estimators': 193, 'learning_rate': 0.11527759542312344, 'max_depth': 1, 'min_child_weight': 16, 'subsample': 0.6885937309208177, 'colsample_bytree': 0.5508528975196025, 'colsample_bylevel': 0.5392939683513515, 'gamma': 8.483602937684363, 'alpha': 1.4924356502233107, 'lambda': 0.3420192823668623}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:19,258] Trial 196 finished with value: 0.9331987235584233 and parameters: {'objective': 'multi:softprob', 'n_estimators': 300, 'learning_rate': 0.033352289478010874, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.7233689988476528, 'colsample_bytree': 0.6777684246623658, 'colsample_bylevel': 0.5867282951262257, 'gamma': 7.696702343960465, 'alpha': 3.1252226129937624, 'lambda': 0.8371341552570789}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:25,064] Trial 197 finished with value: 0.9488728533489248 and parameters: {'objective': 'multi:softprob', 'n_estimators': 178, 'learning_rate': 0.13368453977956898, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7001416639890372, 'colsample_bytree': 0.6297476351943051, 'colsample_bylevel': 0.6175075833699317, 'gamma': 7.263772808472512, 'alpha': 1.7887451570296529, 'lambda': 0.172061978999756}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:30,625] Trial 198 finished with value: 0.9295288913170315 and parameters: {'objective': 'multi:softprob', 'n_estimators': 111, 'learning_rate': 0.07410865363078081, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7366101120673292, 'colsample_bytree': 0.4788559020125324, 'colsample_bylevel': 0.5669575662592331, 'gamma': 7.923971819141295, 'alpha': 2.0795813096391704, 'lambda': 1.4321824989645526}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:36,066] Trial 199 finished with value: 0.9630699627568996 and parameters: {'objective': 'multi:softprob', 'n_estimators': 106, 'learning_rate': 0.1646811218472012, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7753956136215665, 'colsample_bytree': 0.478785621563107, 'colsample_bylevel': 0.5568886423785887, 'gamma': 7.858991451634406, 'alpha': 2.6871319805974374, 'lambda': 1.401862460442446}. Best is trial 152 with value: 0.9223102665231168.

[I 2026-08-31 08:55:41,555] Trial 200 finished with value: 0.9199100734725815 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.07854518144874091, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8218094537436436, 'colsample_bytree': 0.46189056451948923, 'colsample_bylevel': 0.5315954872997546, 'gamma': 7.480450837106385, 'alpha': 1.9495990790032933, 'lambda': 1.9602840460106754}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:55:47,157] Trial 201 finished with value: 0.9273690998316427 and parameters: {'objective': 'multi:softprob', 'n_estimators': 115, 'learning_rate': 0.07833861845207324, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8026141435670169, 'colsample_bytree': 0.4668417853256279, 'colsample_bylevel': 0.5239515590359151, 'gamma': 7.602734727852379, 'alpha': 2.0460251917582544, 'lambda': 2.076407579864222}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:55:52,879] Trial 202 finished with value: 0.9562953463307118 and parameters: {'objective': 'multi:softprob', 'n_estimators': 120, 'learning_rate': 0.10028484457243318, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.826458892752917, 'colsample_bytree': 0.43454939476530663, 'colsample_bylevel': 0.5332966764995246, 'gamma': 7.480327418367681, 'alpha': 1.9889352022617497, 'lambda': 2.065288567738501}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:55:58,342] Trial 203 finished with value: 0.9215142951869273 and parameters: {'objective': 'multi:softprob', 'n_estimators': 111, 'learning_rate': 0.07183568309870976, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.809933896281119, 'colsample_bytree': 0.4685165841876858, 'colsample_bylevel': 0.569630260665105, 'gamma': 7.974125268621916, 'alpha': 1.628760208618193, 'lambda': 2.0268312418777774}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:04,172] Trial 204 finished with value: 0.9362110174414625 and parameters: {'objective': 'multi:softprob', 'n_estimators': 115, 'learning_rate': 0.06704531013243051, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.808996487354878, 'colsample_bytree': 0.4585992718708683, 'colsample_bylevel': 0.5696683381012003, 'gamma': 8.042764075403438, 'alpha': 1.5892873502429699, 'lambda': 1.8804984317234907}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:09,813] Trial 205 finished with value: 0.9652472832012583 and parameters: {'objective': 'multi:softprob', 'n_estimators': 110, 'learning_rate': 0.020772984426235243, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8500282505208361, 'colsample_bytree': 0.4408242487261377, 'colsample_bylevel': 0.5492050840425744, 'gamma': 7.888758858342304, 'alpha': 1.196304266752505, 'lambda': 2.20489851744448}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:15,761] Trial 206 finished with value: 0.9317856529902298 and parameters: {'objective': 'multi:softprob', 'n_estimators': 131, 'learning_rate': 0.10784827127780067, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8225843082586979, 'colsample_bytree': 0.46775747263862294, 'colsample_bylevel': 0.5289739143140811, 'gamma': 7.638671669847452, 'alpha': 1.35728604481328, 'lambda': 1.6969643822399998}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:21,655] Trial 207 finished with value: 0.9452266043923907 and parameters: {'objective': 'multi:softprob', 'n_estimators': 101, 'learning_rate': 0.039222347565056756, 'max_depth': 3, 'min_child_weight': 15, 'subsample': 0.7951778616352017, 'colsample_bytree': 0.4899816536763036, 'colsample_bylevel': 0.5720939156598762, 'gamma': 8.252020537384977, 'alpha': 1.8030876095879123, 'lambda': 1.9118297624487044}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:27,392] Trial 208 finished with value: 0.9445918653061064 and parameters: {'objective': 'multi:softprob', 'n_estimators': 122, 'learning_rate': 0.08278198352987719, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.860911111604927, 'colsample_bytree': 0.4221982304842846, 'colsample_bylevel': 0.5242972655799498, 'gamma': 8.42078324840965, 'alpha': 1.5098939791124937, 'lambda': 2.3454519220345658}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:33,595] Trial 209 finished with value: 0.9437722414889081 and parameters: {'objective': 'multi:softprob', 'n_estimators': 139, 'learning_rate': 0.06372399952635685, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8300247134892267, 'colsample_bytree': 0.4507177511197605, 'colsample_bylevel': 0.5496141426169424, 'gamma': 7.804906361935959, 'alpha': 2.0193143734743244, 'lambda': 1.5171412805432258}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:39,236] Trial 210 finished with value: 0.970766804046086 and parameters: {'objective': 'multi:softprob', 'n_estimators': 114, 'learning_rate': 0.12779331589621432, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8079762995973825, 'colsample_bytree': 0.49729494318425443, 'colsample_bylevel': 0.5854236001291259, 'gamma': 7.992699069515601, 'alpha': 1.7128854261584607, 'lambda': 1.945714991613577}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:44,775] Trial 211 finished with value: 0.9323197474101286 and parameters: {'objective': 'multi:softprob', 'n_estimators': 107, 'learning_rate': 0.08510304652318332, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8426367772796768, 'colsample_bytree': 0.4728853566497476, 'colsample_bylevel': 0.5579039208448168, 'gamma': 7.539724708691321, 'alpha': 2.2108388221395185, 'lambda': 2.089118449793506}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:50,904] Trial 212 finished with value: 0.9392060997518699 and parameters: {'objective': 'multi:softprob', 'n_estimators': 132, 'learning_rate': 0.04493845418964372, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7938783251866361, 'colsample_bytree': 0.5162493452480618, 'colsample_bylevel': 0.5990981826578444, 'gamma': 7.62330679174541, 'alpha': 2.9617614775863688, 'lambda': 1.628679658285465}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:56:56,539] Trial 213 finished with value: 0.9242150745122953 and parameters: {'objective': 'multi:softprob', 'n_estimators': 115, 'learning_rate': 0.07367086815021329, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7630601134065551, 'colsample_bytree': 0.48286173562657236, 'colsample_bylevel': 0.5406340259531304, 'gamma': 7.3968678836384365, 'alpha': 2.01496744853788, 'lambda': 1.3749495851808262}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:02,270] Trial 214 finished with value: 0.9306199930623517 and parameters: {'objective': 'multi:softprob', 'n_estimators': 120, 'learning_rate': 0.06928290110455623, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.7662251118326424, 'colsample_bytree': 0.4601322381100294, 'colsample_bylevel': 0.5369064366152371, 'gamma': 8.152565633737122, 'alpha': 1.845220439132843, 'lambda': 1.4154299713597056}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:08,093] Trial 215 finished with value: 0.9346868401169534 and parameters: {'objective': 'multi:softprob', 'n_estimators': 122, 'learning_rate': 0.09665929151269209, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7632162679826359, 'colsample_bytree': 0.4531011257692173, 'colsample_bylevel': 0.7510253753147876, 'gamma': 8.133958581034474, 'alpha': 1.8208944464000871, 'lambda': 1.374050727138203}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:13,764] Trial 216 finished with value: 0.9757981187143278 and parameters: {'objective': 'multi:softprob', 'n_estimators': 117, 'learning_rate': 0.015969256284396993, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.7518537196530469, 'colsample_bytree': 0.4644853627180576, 'colsample_bylevel': 0.5346160938880059, 'gamma': 8.402133584808514, 'alpha': 1.325941418076646, 'lambda': 1.7716897989933873}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:19,744] Trial 217 finished with value: 0.9361764863654275 and parameters: {'objective': 'multi:softprob', 'n_estimators': 110, 'learning_rate': 0.04104204026878129, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7730105981185055, 'colsample_bytree': 0.4810910037037247, 'colsample_bylevel': 0.5059695698256241, 'gamma': 7.894702559127828, 'alpha': 1.9551790698715454, 'lambda': 2.56438943008023}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:25,305] Trial 218 finished with value: 0.9382417629073748 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.06770954165329524, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.7412198413417668, 'colsample_bytree': 0.43403966623399304, 'colsample_bylevel': 0.5214076207133436, 'gamma': 8.208764964467074, 'alpha': 1.5841104057690467, 'lambda': 1.4729505931427056}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:32,029] Trial 219 finished with value: 0.9580281163687153 and parameters: {'objective': 'multi:softprob', 'n_estimators': 144, 'learning_rate': 0.11366149381699339, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7874095859773143, 'colsample_bytree': 0.4556486658029864, 'colsample_bylevel': 0.5464419554058664, 'gamma': 7.806413267587054, 'alpha': 2.0747339109435745, 'lambda': 1.5647848336644754}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:37,960] Trial 220 finished with value: 0.9342253857757635 and parameters: {'objective': 'multi:softprob', 'n_estimators': 126, 'learning_rate': 0.05081464871155285, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.7611171986840881, 'colsample_bytree': 0.46947661051181827, 'colsample_bylevel': 0.49041433104254595, 'gamma': 7.16844006568647, 'alpha': 1.7903882603303378, 'lambda': 1.2383282842135321}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:43,422] Trial 221 finished with value: 0.9439689917164475 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.07485812730852091, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8090730884831658, 'colsample_bytree': 0.49012385888820836, 'colsample_bylevel': 0.564459467209433, 'gamma': 7.4737402986272805, 'alpha': 3.3840046283565965, 'lambda': 1.8078130973873718}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:49,242] Trial 222 finished with value: 0.9367600729204097 and parameters: {'objective': 'multi:softprob', 'n_estimators': 119, 'learning_rate': 0.0627765443915763, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.735954900083244, 'colsample_bytree': 0.5008699566878165, 'colsample_bylevel': 0.5413563030219654, 'gamma': 7.667081521875065, 'alpha': 2.116660975035525, 'lambda': 1.3100292149967134}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:57:54,966] Trial 223 finished with value: 0.9513997669273665 and parameters: {'objective': 'multi:softprob', 'n_estimators': 114, 'learning_rate': 0.08783269307954712, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8171945214411181, 'colsample_bytree': 0.48127065500518906, 'colsample_bylevel': 0.21217599589651737, 'gamma': 8.074138992568974, 'alpha': 3.128623354690808, 'lambda': 2.17194627972905}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:00,390] Trial 224 finished with value: 0.9723192413147118 and parameters: {'objective': 'multi:softprob', 'n_estimators': 101, 'learning_rate': 0.02045252682576331, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7792535298750688, 'colsample_bytree': 0.500708365761099, 'colsample_bylevel': 0.5622395433468684, 'gamma': 7.922954472467688, 'alpha': 1.865624865975747, 'lambda': 1.0975679926716322}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:06,477] Trial 225 finished with value: 0.9424411867666023 and parameters: {'objective': 'multi:softprob', 'n_estimators': 133, 'learning_rate': 0.04098890799910838, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.7532173278161507, 'colsample_bytree': 0.44686222419867216, 'colsample_bylevel': 0.5187420423428785, 'gamma': 8.306609271224152, 'alpha': 2.313311334305149, 'lambda': 3.5808616805309623}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:12,874] Trial 226 finished with value: 0.9602704749227229 and parameters: {'objective': 'multi:softprob', 'n_estimators': 154, 'learning_rate': 0.10321612300733007, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.7914287904077397, 'colsample_bytree': 0.4145785306582937, 'colsample_bylevel': 0.5781612103639762, 'gamma': 7.711089508221945, 'alpha': 0.9752609723562053, 'lambda': 9.97377714827891}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:18,790] Trial 227 finished with value: 0.9314633839615806 and parameters: {'objective': 'multi:softprob', 'n_estimators': 128, 'learning_rate': 0.06079119680616137, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8374439478491609, 'colsample_bytree': 0.4788780951059008, 'colsample_bylevel': 0.5491723470076196, 'gamma': 7.329733487407552, 'alpha': 2.7488657178819618, 'lambda': 1.6813129803291167}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:24,417] Trial 228 finished with value: 0.9314270113906016 and parameters: {'objective': 'multi:softprob', 'n_estimators': 112, 'learning_rate': 0.07441656316374456, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8712257768204512, 'colsample_bytree': 0.5210825576442594, 'colsample_bylevel': 0.5778395139079072, 'gamma': 7.491459924211432, 'alpha': 1.5603334537483047, 'lambda': 1.409088432712722}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:29,922] Trial 229 finished with value: 0.9463615677176587 and parameters: {'objective': 'multi:softprob', 'n_estimators': 108, 'learning_rate': 0.031042414874634515, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.7686725579613564, 'colsample_bytree': 0.4620397011193665, 'colsample_bylevel': 0.5252238801315655, 'gamma': 6.945870381445426, 'alpha': 2.5715280999073875, 'lambda': 1.980249876667238}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:39,375] Trial 230 finished with value: 2.4022765894264473 and parameters: {'objective': 'multi:softprob', 'n_estimators': 140, 'learning_rate': 0.14452655114563823, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.7216269522717881, 'colsample_bytree': 0.43771312636662923, 'colsample_bylevel': 0.5360278916400704, 'gamma': 8.570563049046715, 'alpha': 2.1259084858173587, 'lambda': 2.3434025396931815}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:44,947] Trial 231 finished with value: 0.9400044705682706 and parameters: {'objective': 'multi:softprob', 'n_estimators': 115, 'learning_rate': 0.07950814823370356, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.8688101136386613, 'colsample_bytree': 0.5194430444496686, 'colsample_bylevel': 0.5771060505876995, 'gamma': 7.519546009964948, 'alpha': 1.5934430460112887, 'lambda': 1.4358718968874813}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:50,786] Trial 232 finished with value: 0.9385168421638304 and parameters: {'objective': 'multi:softprob', 'n_estimators': 123, 'learning_rate': 0.059865131441195686, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8829042735322103, 'colsample_bytree': 0.49932149188481284, 'colsample_bylevel': 0.596708063800223, 'gamma': 7.086800902212482, 'alpha': 1.421708065293872, 'lambda': 1.0874345657332358}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:58:56,147] Trial 233 finished with value: 0.9537208981408243 and parameters: {'objective': 'multi:softprob', 'n_estimators': 101, 'learning_rate': 0.0896450470292747, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.4689626502633958, 'colsample_bytree': 0.48540677019063716, 'colsample_bylevel': 0.5647915561492168, 'gamma': 7.740681209958434, 'alpha': 1.6793679223250186, 'lambda': 1.6393573065040745}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:01,826] Trial 234 finished with value: 0.9354240127905997 and parameters: {'objective': 'multi:softprob', 'n_estimators': 113, 'learning_rate': 0.07365502001545063, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8521996440434046, 'colsample_bytree': 0.5227411872756677, 'colsample_bylevel': 0.554398048320865, 'gamma': 7.986487111734038, 'alpha': 1.8926489432368407, 'lambda': 1.3133377328737112}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:07,256] Trial 235 finished with value: 0.9450008226656708 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.0445484578469242, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8253353689996394, 'colsample_bytree': 0.5130365847388187, 'colsample_bylevel': 0.5793860908793215, 'gamma': 7.448447275860735, 'alpha': 1.1306078703770166, 'lambda': 1.5281299476952355}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:15,799] Trial 236 finished with value: 1.1670740429097244 and parameters: {'objective': 'multi:softprob', 'n_estimators': 207, 'learning_rate': 0.11068321187285199, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7393819536920168, 'colsample_bytree': 0.9550804622836758, 'colsample_bylevel': 0.5398136734711092, 'gamma': 6.587027704604809, 'alpha': 3.239748275992606, 'lambda': 1.7767814139706948}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:22,966] Trial 237 finished with value: 0.9321718883507052 and parameters: {'objective': 'multi:softprob', 'n_estimators': 190, 'learning_rate': 0.053998008120352256, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.8077968102333917, 'colsample_bytree': 0.4678601928701551, 'colsample_bylevel': 0.597916743938673, 'gamma': 7.294083791331142, 'alpha': 2.9022409783901595, 'lambda': 1.1784165158638256}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:29,540] Trial 238 finished with value: 0.9624201609197602 and parameters: {'objective': 'multi:softprob', 'n_estimators': 163, 'learning_rate': 0.09140201385117185, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.8379772717384371, 'colsample_bytree': 0.49165878643154576, 'colsample_bylevel': 0.5061222070246328, 'gamma': 8.086079519445438, 'alpha': 1.2925037668514625, 'lambda': 1.4241897306162212}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:35,307] Trial 239 finished with value: 0.9504234733534371 and parameters: {'objective': 'multi:softprob', 'n_estimators': 127, 'learning_rate': 0.027919295938651688, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7554658350545366, 'colsample_bytree': 0.44959964256737406, 'colsample_bylevel': 0.5697237106332609, 'gamma': 7.558607084168103, 'alpha': 2.0126269090770523, 'lambda': 2.000643125464136}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:42,868] Trial 240 finished with value: 0.9423314348002062 and parameters: {'objective': 'multi:softprob', 'n_estimators': 201, 'learning_rate': 0.07270487847833022, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.8613206471145358, 'colsample_bytree': 0.4760167893797159, 'colsample_bylevel': 0.5533866873423677, 'gamma': 7.819339925956009, 'alpha': 3.5754725458549257, 'lambda': 0.9230587022951771}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:48,867] Trial 241 finished with value: 0.9356037737274052 and parameters: {'objective': 'multi:softprob', 'n_estimators': 129, 'learning_rate': 0.05758033319005193, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.839373812997796, 'colsample_bytree': 0.4791262666127359, 'colsample_bylevel': 0.5487308735862029, 'gamma': 7.320265953815581, 'alpha': 2.6749721062283722, 'lambda': 1.6764840115993744}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 08:59:54,460] Trial 242 finished with value: 0.9389711855756097 and parameters: {'objective': 'multi:softprob', 'n_estimators': 114, 'learning_rate': 0.06641973335333973, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8250493400688628, 'colsample_bytree': 0.4936939558002913, 'colsample_bylevel': 0.5312852072939146, 'gamma': 7.152921165741099, 'alpha': 2.8637611650679275, 'lambda': 1.7863744198398441}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:00,208] Trial 243 finished with value: 0.9410235849446565 and parameters: {'objective': 'multi:softprob', 'n_estimators': 120, 'learning_rate': 0.04517603735318105, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7993116300757789, 'colsample_bytree': 0.5100549837508426, 'colsample_bylevel': 0.5821723902390865, 'gamma': 7.409280747614108, 'alpha': 3.066212678241249, 'lambda': 1.5310629815512051}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:05,728] Trial 244 finished with value: 0.9301352806114065 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.09600665138003034, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.8478447661346096, 'colsample_bytree': 0.46302970571198715, 'colsample_bylevel': 0.5472578088878653, 'gamma': 7.701496655182508, 'alpha': 2.300955159745849, 'lambda': 1.23821273649729}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:10,970] Trial 245 finished with value: 0.9391800997659094 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.12400705606348147, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.8731736852108227, 'colsample_bytree': 0.4282588443323047, 'colsample_bylevel': 0.5648744767204993, 'gamma': 7.685500488428733, 'alpha': 2.3482612040231925, 'lambda': 1.2604040721753775}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:16,392] Trial 246 finished with value: 0.9424349050626868 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.10467406615113115, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.9015276078322333, 'colsample_bytree': 0.45389608463683556, 'colsample_bylevel': 0.5909050669084623, 'gamma': 8.229401463413417, 'alpha': 2.2287555518603583, 'lambda': 1.0239904805137225}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:23,943] Trial 247 finished with value: 0.9534093407871432 and parameters: {'objective': 'multi:softprob', 'n_estimators': 210, 'learning_rate': 0.083544208529916, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.8523906963606458, 'colsample_bytree': 0.4647274479427601, 'colsample_bylevel': 0.5158280513948486, 'gamma': 7.909163841009565, 'alpha': 1.559006009988829, 'lambda': 0.5241132307692279}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:28,879] Trial 248 finished with value: 0.9321228977937122 and parameters: {'objective': 'multi:softprob', 'n_estimators': 111, 'learning_rate': 0.0897008478384825, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.7741930416703109, 'colsample_bytree': 0.5343806102649529, 'colsample_bylevel': 0.5368638984625325, 'gamma': 8.430789541775908, 'alpha': 1.9331666672895684, 'lambda': 0.7337999875304526}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:36,031] Trial 249 finished with value: 0.9415437270282295 and parameters: {'objective': 'multi:softprob', 'n_estimators': 182, 'learning_rate': 0.10642912362206516, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.7343894681872923, 'colsample_bytree': 0.4435385490309301, 'colsample_bylevel': 0.5549470896755561, 'gamma': 7.670157474835232, 'alpha': 2.4777379680221294, 'lambda': 1.289062429752188}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:42,401] Trial 250 finished with value: 1.0501623369416877 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.0034477876536707086, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.8111840249293837, 'colsample_bytree': 0.4646391394806596, 'colsample_bylevel': 0.519613356322273, 'gamma': 8.131468531896658, 'alpha': 1.797066060963695, 'lambda': 1.4181115498861139}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:50,718] Trial 251 finished with value: 1.0546900291417092 and parameters: {'objective': 'multi:softprob', 'n_estimators': 122, 'learning_rate': 0.0306003599854884, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.7516865964866586, 'colsample_bytree': 0.5894050657496039, 'colsample_bylevel': 0.6068129781285745, 'gamma': 7.911886531906584, 'alpha': 2.2188538142941656, 'lambda': 0.44491840068901967}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:00:57,437] Trial 252 finished with value: 0.950451806697236 and parameters: {'objective': 'multi:softprob', 'n_estimators': 170, 'learning_rate': 0.07368054230683214, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.7164214167551622, 'colsample_bytree': 0.4931564825023471, 'colsample_bylevel': 0.568053867984723, 'gamma': 7.598888307050908, 'alpha': 2.0448302317196587, 'lambda': 0.9225407366156224}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:02,849] Trial 253 finished with value: 0.9501136529981892 and parameters: {'objective': 'multi:softprob', 'n_estimators': 137, 'learning_rate': 0.05015285155430184, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7846537138036652, 'colsample_bytree': 0.5049868797002793, 'colsample_bylevel': 0.4893702429817735, 'gamma': 7.841795069345938, 'alpha': 1.4428261924388146, 'lambda': 1.9288598672764015}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:11,634] Trial 254 finished with value: 2.2554833180234173 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.12259228043178517, 'max_depth': 10, 'min_child_weight': 17, 'subsample': 0.8298979025723282, 'colsample_bytree': 0.42558129206146417, 'colsample_bylevel': 0.5364380914616125, 'gamma': 7.522421926323155, 'alpha': 2.42993305157851, 'lambda': 0.3770964122390412}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:19,374] Trial 255 finished with value: 1.5694777559254736 and parameters: {'objective': 'multi:softprob', 'n_estimators': 222, 'learning_rate': 0.5213336230596103, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.7670459650803919, 'colsample_bytree': 0.6116343448844946, 'colsample_bylevel': 0.5856130988233779, 'gamma': 6.8484310358699, 'alpha': 3.205838148186217, 'lambda': 2.1987151464258834}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:27,528] Trial 256 finished with value: 1.7039378837101247 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.09262484527131179, 'max_depth': 8, 'min_child_weight': 18, 'subsample': 0.9259614552299912, 'colsample_bytree': 0.48204646704321696, 'colsample_bylevel': 0.5499321530267209, 'gamma': 8.023360416196704, 'alpha': 7.070011343966172, 'lambda': 1.1295665929732737}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:35,692] Trial 257 finished with value: 0.9882101588321117 and parameters: {'objective': 'multi:softprob', 'n_estimators': 192, 'learning_rate': 0.06326109879907386, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.8031719388384019, 'colsample_bytree': 0.45743288493491174, 'colsample_bylevel': 0.5072255996459494, 'gamma': 8.340793942357097, 'alpha': 1.7916184091901597, 'lambda': 0.6046889050059943}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:42,417] Trial 258 finished with value: 0.9272715322860099 and parameters: {'objective': 'multi:softprob', 'n_estimators': 212, 'learning_rate': 0.13863727035919735, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7424775263984799, 'colsample_bytree': 0.5697036291484303, 'colsample_bylevel': 0.5696547195658874, 'gamma': 8.503322523350148, 'alpha': 2.621928949300878, 'lambda': 1.6034682872229278}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:49,118] Trial 259 finished with value: 0.9297696932826105 and parameters: {'objective': 'multi:softprob', 'n_estimators': 212, 'learning_rate': 0.12614209718350095, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7468929681887069, 'colsample_bytree': 0.5892743754756412, 'colsample_bylevel': 0.524400991283676, 'gamma': 8.546964484685363, 'alpha': 2.6887863391121765, 'lambda': 1.821609054576094}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:01:55,646] Trial 260 finished with value: 0.9320114787134676 and parameters: {'objective': 'multi:softprob', 'n_estimators': 208, 'learning_rate': 0.16273759352002803, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.7372805319445941, 'colsample_bytree': 0.5744804326084519, 'colsample_bylevel': 0.5175123754481257, 'gamma': 8.621384777232716, 'alpha': 2.7660770958732424, 'lambda': 1.8292526983017068}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:04,787] Trial 261 finished with value: 0.9683101938455964 and parameters: {'objective': 'multi:softprob', 'n_estimators': 359, 'learning_rate': 0.14489503914258792, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7233989821463472, 'colsample_bytree': 0.607189144801506, 'colsample_bylevel': 0.5318622263366548, 'gamma': 9.13109326124215, 'alpha': 2.9719144638927455, 'lambda': 2.1298736226007695}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:13,260] Trial 262 finished with value: 1.6195639527151875 and parameters: {'objective': 'multi:softprob', 'n_estimators': 178, 'learning_rate': 0.18116045127952252, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.7524638849680778, 'colsample_bytree': 0.4384973797618751, 'colsample_bylevel': 0.5596547013807515, 'gamma': 8.962359563617845, 'alpha': 2.6419721168667576, 'lambda': 1.6512225189172416}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:19,645] Trial 263 finished with value: 0.9338099057867109 and parameters: {'objective': 'multi:softprob', 'n_estimators': 205, 'learning_rate': 0.13720612606525648, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.7450151065291237, 'colsample_bytree': 0.5882055682121483, 'colsample_bylevel': 0.5435157440622661, 'gamma': 8.278739423806137, 'alpha': 3.3402738724262613, 'lambda': 1.9277629045068647}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:25,992] Trial 264 finished with value: 0.9356082783723154 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.13119921136390816, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.7659072761279321, 'colsample_bytree': 0.5691520004702201, 'colsample_bylevel': 0.49998317966657546, 'gamma': 8.550298265054373, 'alpha': 2.2020381482881466, 'lambda': 1.5893524436247697}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:32,709] Trial 265 finished with value: 0.9327213259570053 and parameters: {'objective': 'multi:softprob', 'n_estimators': 214, 'learning_rate': 0.16379035788742505, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.7276831345128296, 'colsample_bytree': 0.599572559362371, 'colsample_bylevel': 0.5248596807250232, 'gamma': 8.754449850566466, 'alpha': 2.9417497541381206, 'lambda': 1.721734259255935}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:39,685] Trial 266 finished with value: 0.9405499782833889 and parameters: {'objective': 'multi:softprob', 'n_estimators': 225, 'learning_rate': 0.10097345851077061, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.9964151911989196, 'colsample_bytree': 0.5593578380163138, 'colsample_bylevel': 0.5653197326997359, 'gamma': 8.467594339796618, 'alpha': 2.4536100950011477, 'lambda': 2.3201772884043645}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:45,871] Trial 267 finished with value: 0.9344436412519067 and parameters: {'objective': 'multi:softprob', 'n_estimators': 186, 'learning_rate': 0.12522190059665284, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.7084256867223733, 'colsample_bytree': 0.586005466487763, 'colsample_bylevel': 0.5517292028036469, 'gamma': 8.17299555163663, 'alpha': 3.1293500748716547, 'lambda': 4.000868087496638}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:53,289] Trial 268 finished with value: 0.9947262613646138 and parameters: {'objective': 'multi:softprob', 'n_estimators': 201, 'learning_rate': 0.11439118829722415, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.7802524534234839, 'colsample_bytree': 0.5642062015096682, 'colsample_bylevel': 0.4792415658504572, 'gamma': 8.49649079105947, 'alpha': 2.7364267790753183, 'lambda': 2.9711032009069065}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:02:59,536] Trial 269 finished with value: 0.9705981038727449 and parameters: {'objective': 'multi:softprob', 'n_estimators': 188, 'learning_rate': 0.0187398131805633, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.7620576779156722, 'colsample_bytree': 0.47270602727200745, 'colsample_bylevel': 0.8442219450608631, 'gamma': 8.19498316878527, 'alpha': 2.066927016562179, 'lambda': 2.110673880069201}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:05,916] Trial 270 finished with value: 1.061767637658537 and parameters: {'objective': 'multi:softprob', 'n_estimators': 148, 'learning_rate': 0.2013199093195218, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.7437637617077032, 'colsample_bytree': 0.6400387073544581, 'colsample_bylevel': 0.5344197725500354, 'gamma': 8.746984387200323, 'alpha': 2.296461978093154, 'lambda': 2.564169990311504}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:11,936] Trial 271 finished with value: 0.9493235335374187 and parameters: {'objective': 'multi:softprob', 'n_estimators': 174, 'learning_rate': 0.03675479955931624, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.7952124600000858, 'colsample_bytree': 0.7002175388903675, 'colsample_bylevel': 0.5782177432139116, 'gamma': 8.003774426913493, 'alpha': 3.461555399272292, 'lambda': 9.476976701330125}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:19,791] Trial 272 finished with value: 0.9973692141574155 and parameters: {'objective': 'multi:softprob', 'n_estimators': 217, 'learning_rate': 0.13979818339712963, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.7331631738192754, 'colsample_bytree': 0.4056392591878695, 'colsample_bylevel': 0.5182966941498677, 'gamma': 8.371066838567549, 'alpha': 2.798356313720534, 'lambda': 1.5262302846581466}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:24,874] Trial 273 finished with value: 0.9310573462202861 and parameters: {'objective': 'multi:softprob', 'n_estimators': 122, 'learning_rate': 0.10138628418426798, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.7108614673280156, 'colsample_bytree': 0.7415522895151943, 'colsample_bylevel': 0.5455628724886629, 'gamma': 8.901898564854504, 'alpha': 1.9653429881537914, 'lambda': 1.229059804293219}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:30,895] Trial 274 finished with value: 0.9636010312555016 and parameters: {'objective': 'multi:softprob', 'n_estimators': 132, 'learning_rate': 0.11056890217197332, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.7147711794161558, 'colsample_bytree': 0.7360501290226021, 'colsample_bylevel': 0.5545552746615293, 'gamma': 7.826380039909283, 'alpha': 1.830909931443289, 'lambda': 1.2435315499470845}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:35,974] Trial 275 finished with value: 0.933569207304688 and parameters: {'objective': 'multi:softprob', 'n_estimators': 120, 'learning_rate': 0.14851861068535388, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.7017595802261478, 'colsample_bytree': 0.7601933407118941, 'colsample_bylevel': 0.5405722769054254, 'gamma': 8.023518081239196, 'alpha': 1.9605391657880393, 'lambda': 1.3836613054747435}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:41,649] Trial 276 finished with value: 0.9523091493128969 and parameters: {'objective': 'multi:softprob', 'n_estimators': 118, 'learning_rate': 0.09564379997159947, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.7783358753259805, 'colsample_bytree': 0.7924856493641415, 'colsample_bylevel': 0.5693668711227703, 'gamma': 7.01975100197395, 'alpha': 1.6420030958246254, 'lambda': 1.1457798119193334}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:47,241] Trial 277 finished with value: 0.9946942782818707 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.1782009011077642, 'max_depth': 2, 'min_child_weight': 2, 'subsample': 0.7142720442509243, 'colsample_bytree': 0.8353878874070105, 'colsample_bylevel': 0.49795124492022114, 'gamma': 8.307918198693454, 'alpha': 3.6905663065590866, 'lambda': 1.845046331628287}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:03:57,044] Trial 278 finished with value: 0.9455755977981495 and parameters: {'objective': 'multi:softprob', 'n_estimators': 400, 'learning_rate': 0.08858463803558025, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.7326053530990743, 'colsample_bytree': 0.6619238370019661, 'colsample_bylevel': 0.5998643257251483, 'gamma': 8.59752834751243, 'alpha': 2.158345481704464, 'lambda': 1.6319416880208313}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:02,865] Trial 279 finished with value: 0.9716535212213077 and parameters: {'objective': 'multi:softprob', 'n_estimators': 126, 'learning_rate': 0.126650782550402, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.6944165211863981, 'colsample_bytree': 0.6313828231242243, 'colsample_bylevel': 0.5248429990725065, 'gamma': 7.765779590064621, 'alpha': 3.280981329740287, 'lambda': 1.413628420660297}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:11,295] Trial 280 finished with value: 1.2627323684802871 and parameters: {'objective': 'multi:softprob', 'n_estimators': 316, 'learning_rate': 0.6147080193606288, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.7908995854486346, 'colsample_bytree': 0.7343239405752903, 'colsample_bylevel': 0.5436565320640658, 'gamma': 6.383455520122881, 'alpha': 2.5598425134720744, 'lambda': 1.088054524122949}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:17,227] Trial 281 finished with value: 0.936427949431032 and parameters: {'objective': 'multi:softprob', 'n_estimators': 106, 'learning_rate': 0.047422046112376715, 'max_depth': 3, 'min_child_weight': 15, 'subsample': 0.8159743863891061, 'colsample_bytree': 0.6829300515626583, 'colsample_bylevel': 0.5877481504215486, 'gamma': 7.217159946357856, 'alpha': 3.0744345171052685, 'lambda': 1.9807902368377655}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:23,236] Trial 282 finished with value: 0.9356211260199059 and parameters: {'objective': 'multi:softprob', 'n_estimators': 138, 'learning_rate': 0.08459926628924685, 'max_depth': 2, 'min_child_weight': 17, 'subsample': 0.7725592053695055, 'colsample_bytree': 0.44469534133024846, 'colsample_bylevel': 0.5643293427440507, 'gamma': 8.937904263233124, 'alpha': 1.7513949699935316, 'lambda': 0.021470031011721458}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:29,855] Trial 283 finished with value: 1.2685269828870729 and parameters: {'objective': 'multi:softprob', 'n_estimators': 100, 'learning_rate': 0.11004572530424099, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.757455401037524, 'colsample_bytree': 0.781030591306521, 'colsample_bylevel': 0.5103399186889921, 'gamma': 8.115758991310074, 'alpha': 1.9792851548185912, 'lambda': 6.235769234283692}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:36,525] Trial 284 finished with value: 0.9427888999777432 and parameters: {'objective': 'multi:softprob', 'n_estimators': 163, 'learning_rate': 0.022844236017265297, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.7427850632839836, 'colsample_bytree': 0.4610457359352168, 'colsample_bylevel': 0.5459551572532945, 'gamma': 7.749708019399298, 'alpha': 1.4061916530853558, 'lambda': 0.9128120166614943}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:41,504] Trial 285 finished with value: 0.9542742188251929 and parameters: {'objective': 'multi:softprob', 'n_estimators': 120, 'learning_rate': 0.04946113301545246, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.7167092057375396, 'colsample_bytree': 0.4260116884827965, 'colsample_bylevel': 0.6108462885015254, 'gamma': 9.341166596733432, 'alpha': 2.9193241222391206, 'lambda': 1.2610623736475686}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:51,926] Trial 286 finished with value: 1.02440545918301 and parameters: {'objective': 'multi:softprob', 'n_estimators': 336, 'learning_rate': 0.07444952789360362, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6781697700861609, 'colsample_bytree': 0.47494212924221696, 'colsample_bylevel': 0.5739416894073932, 'gamma': 7.937172400691054, 'alpha': 2.261320173774265, 'lambda': 1.7359557009145208}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:04:58,283] Trial 287 finished with value: 0.9351067756958178 and parameters: {'objective': 'multi:softprob', 'n_estimators': 199, 'learning_rate': 0.10334456265051428, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7647759903156225, 'colsample_bytree': 0.2571670304136294, 'colsample_bylevel': 0.535329387179525, 'gamma': 6.803814876283961, 'alpha': 2.6601954135184838, 'lambda': 5.406647882436377}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:05,334] Trial 288 finished with value: 2.2323932530885324 and parameters: {'objective': 'multi:softprob', 'n_estimators': 185, 'learning_rate': 0.9244954873271525, 'max_depth': 2, 'min_child_weight': 8, 'subsample': 0.7963628418151225, 'colsample_bytree': 0.7185723305907084, 'colsample_bylevel': 0.5584721017653025, 'gamma': 7.3565082271751, 'alpha': 2.089104922864746, 'lambda': 0.25916026892498384}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:10,166] Trial 289 finished with value: 0.9331885576581694 and parameters: {'objective': 'multi:softprob', 'n_estimators': 109, 'learning_rate': 0.15618754889752917, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.8193589477944233, 'colsample_bytree': 0.4503061548535454, 'colsample_bylevel': 0.5929793933242551, 'gamma': 8.272500066052123, 'alpha': 1.688896438299345, 'lambda': 1.5224102744335664}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:21,537] Trial 290 finished with value: 1.0908931049285862 and parameters: {'objective': 'multi:softprob', 'n_estimators': 382, 'learning_rate': 0.12204642473855262, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.7295547961422065, 'colsample_bytree': 0.48537188198241193, 'colsample_bylevel': 0.5261662621515973, 'gamma': 8.442333082500674, 'alpha': 1.244806831969392, 'lambda': 2.046514549620912}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:27,248] Trial 291 finished with value: 0.9334739250290507 and parameters: {'objective': 'multi:softprob', 'n_estimators': 129, 'learning_rate': 0.03520997249715062, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.7485881297220249, 'colsample_bytree': 0.6206409716609824, 'colsample_bylevel': 0.5075593334826419, 'gamma': 7.657408630731432, 'alpha': 3.469203269851404, 'lambda': 1.3678788009408205}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:33,575] Trial 292 finished with value: 0.9898599180337647 and parameters: {'objective': 'multi:softprob', 'n_estimators': 117, 'learning_rate': 0.009637167785118299, 'max_depth': 3, 'min_child_weight': 12, 'subsample': 0.7834191328166068, 'colsample_bytree': 0.46316715436030587, 'colsample_bylevel': 0.5768724236568936, 'gamma': 8.091622005358762, 'alpha': 2.363907510671947, 'lambda': 1.8589283783070336}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:39,932] Trial 293 finished with value: 0.9374263639643728 and parameters: {'objective': 'multi:softprob', 'n_estimators': 193, 'learning_rate': 0.07861450762739468, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.7647957071695571, 'colsample_bytree': 0.4398717565307934, 'colsample_bylevel': 0.5532453562735948, 'gamma': 7.4917298563931105, 'alpha': 1.9130071409271863, 'lambda': 0.9402267810660507}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:46,400] Trial 294 finished with value: 0.9435349587867129 and parameters: {'objective': 'multi:softprob', 'n_estimators': 152, 'learning_rate': 0.060885471360320645, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7018622230022239, 'colsample_bytree': 0.41656644651467745, 'colsample_bylevel': 0.528120652333956, 'gamma': 7.897303380161154, 'alpha': 3.0575401851787154, 'lambda': 0.22958203117567433}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:05:52,407] Trial 295 finished with value: 0.9674072736797381 and parameters: {'objective': 'multi:softprob', 'n_estimators': 175, 'learning_rate': 0.09407424413734804, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.33611572099428216, 'colsample_bytree': 0.4726923715605718, 'colsample_bylevel': 0.4887134764712947, 'gamma': 7.196019419299613, 'alpha': 2.5593682607050576, 'lambda': 3.398022672793324}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:06:00,587] Trial 296 finished with value: 0.940700757879865 and parameters: {'objective': 'multi:softprob', 'n_estimators': 233, 'learning_rate': 0.049320600661835454, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.8116902041021831, 'colsample_bytree': 0.49185866603227346, 'colsample_bylevel': 0.5660958994612664, 'gamma': 8.608232088187506, 'alpha': 2.8285831588924304, 'lambda': 1.5773969992047154}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:06:07,114] Trial 297 finished with value: 0.9427259175639068 and parameters: {'objective': 'multi:softprob', 'n_estimators': 211, 'learning_rate': 0.13863251963552914, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.7372630407694911, 'colsample_bytree': 0.39143464644206, 'colsample_bylevel': 0.29121669364275793, 'gamma': 7.722169050118028, 'alpha': 0.8732676440280366, 'lambda': 2.789646148030148}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:06:13,299] Trial 298 finished with value: 0.9401014551059885 and parameters: {'objective': 'multi:softprob', 'n_estimators': 142, 'learning_rate': 0.07767465411802069, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.8348984823768036, 'colsample_bytree': 0.45959416394189095, 'colsample_bylevel': 0.5443470210520026, 'gamma': 8.154095892819353, 'alpha': 3.314752769394603, 'lambda': 1.1443864302075002}. Best is trial 200 with value: 0.9199100734725815.

[I 2026-08-31 09:06:18,250] Trial 299 finished with value: 0.9382513591656048 and parameters: {'objective': 'multi:softprob', 'n_estimators': 111, 'learning_rate': 0.10879655064021972, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.798474782661936, 'colsample_bytree': 0.5997017230476283, 'colsample_bylevel': 0.5894879496514682, 'gamma': 7.384532027671357, 'alpha': 9.19389317846425, 'lambda': 2.4253190802419327}. Best is trial 200 with value: 0.9199100734725815.

{'objective': 'multi:softprob',
 'n_estimators': 109,
 'learning_rate': 0.07854518144874091,
 'max_depth': 2,
 'min_child_weight': 17,
 'subsample': 0.8218094537436436,
 'colsample_bytree': 0.46189056451948923,
 'colsample_bylevel': 0.5315954872997546,
 'gamma': 7.480450837106385,
 'alpha': 1.9495990790032933,
 'lambda': 1.9602840460106754}

In [14]:
from utils.objectives import get_best_multiclass_model

# 7.0.5-era helper, unchanged: prints Log Loss Train / Dev (the article's dev metric)
selected_features, model = get_best_multiclass_model(
    study.best_params,
    x_train[best_features],
    y_ord_train,
    x_dev[best_features],
    y_ord_dev,
    w_train=w_train,
    w_dev=w_dev,
    train_on_full=False,
)

used features: ['VOCATION', 'KAPITAL40', 'TYPERS', 'KAPITAL41', 'KAPITAL42', 'DEROG12', 'RISK11', 'KAPITAL43', 'KAPITAL37', 'DEROG4', 'ZONE', 'RISK10', 'DEROG5', 'AN_EXERC', 'total_surface_crossed', 'ACTIVIT2', 'TXAB_VOR_MM_A_TXAB_VOR_MMAX_A', 'NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A', 'INDEM2', 'EQUIPEMENT2', 'NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A', 'NBJTX0_MM_A_NBJTX0_MMAX_A', 'NBJRR50_MM_A_NBJRR50_MMAX_A', 'NBJRR10_MM_A_NBJRR10_MMAX_A', 'NBJFXI3S28_MM_A_NBJFXI3S28_MMAX_A', 'IND_SNV_REGION', 'NBJFF16_MM_A_NBJFF16_MMAX_A', 'RRAB_VOR_MM_A_RRAB_VOR_MMAX_A', 'NBJFF10_MM_A_NBJFF10_MMAX_A', 'NBJFXY8_MM_A_NBJFXY8_MMAX_A', 'NBJRR30_MM_A_NBJRR30_MMAX_A', 'TAMPLIAB_VOR_MM_A_TAMPLIAB_VOR_MMAX_A', 'TAMPLIM_VOR_MM_A_TAMPLIM_VOR_MMAX_A', 'ALTITUDE_5_ALT_TOT', 'SURFACE6', 'TAILLE1', 'TAILLE2', 'HAUTEUR_MAX', 'BDTOPO_BAT_MAX_HAUTEUR_MAX', 'BDTOPO_BAT_MAX_HAUTEUR', 'DISTANCE_213', 'PROPORTION_21', 'HAUTEUR', 'CARACT4', 'DISTANCE_212', 'DISTANCE_411', 'DISTANCE_323', 'DISTANCE_335', 'DISTANCE_334', 'NBJRR10_MSOM_A', 'KAPITAL32', 'KAPITAL_MAX', 'SURFACE10', 'SURFACE1', 'SURFACE7', 'KAPITAL21', 'NBBAT4', 'NBSINSTRT', 'KAPITAL23', 'EQUIPEMENT6', 'NBSINCONJ', 'SURFACE17', 'KAPITAL8', 'TAILLE3', 'KAPITAL14', 'KAPITAL24', 'KAPITAL27', 'KAPITAL3', 'KAPITAL10', 'CA3_CA_TOT', 'NBBAT2', 'EQUIPEMENT1', 'CA3', 'DEROG1', 'SURFACE13', 'RISK5', 'CARACT5', 'NBBAT7', 'NBBAT8', 'ZONE_VENT', 'KAPITAL20', 'KAPITAL17', 'KAPITAL25', 'RISK2', 'NBBAT6', 'RISK1', 'DEROG11', 'NBBAT9', 'KAPITAL1', 'DUREE_REQANEUF', 'DEROG10', 'DEROG8_formatted', 'DEROG7', 'EQUIPEMENT4', 'DEROG6', 'RISK4', 'TYPBAT2', 'ANCIENNETE', 'KAPITAL19', 'SURFACE21']

Log Loss Train: 0.7819988979524337

Log Loss Dev:   0.9199100734725815

### Hand-off to `amount_model_2026.ipynb` — train + dev

The severity model weights each observation by the **absolute error of the
frequency model** (`|pred_sum - FREQ|`), so it needs this model's predictions on
train, dev and OOS. Written with the index (`ID`), as in 2025.

In [15]:
# hand-off to the severity model: train + dev frequency predictions
# (mirrors the 2025 notebook, which wrote frequency_012.csv)
FREQ_VERSION = "2026"
CLASS_MEANS = np.array([0, 1, 2.076923076923077])


def frequency_predictions(frame):
    """P(1), P(2+) and the expected claim count, built as one block.

    Assigning the three columns one at a time inserts into a ~560-column frame
    three times over and pandas warns that the result is highly fragmented; one
    concat is both quieter and cheaper.
    """
    proba = model.predict_proba(frame[selected_features])
    return pd.DataFrame(
        {
            "pred_1": proba[:, 1],
            "pred_2": proba[:, 2],
            "pred_sum": (proba * CLASS_MEANS).sum(axis=1),
        },
        index=frame.index,
    )


def with_predictions(frame):
    """Attach the block, replacing the columns if the cell is re-run."""
    block = frequency_predictions(frame)
    return pd.concat(
        [frame.drop(columns=block.columns, errors="ignore"), block], axis=1
    )


x_train = with_predictions(x_train)
x_dev = with_predictions(x_dev)

merged = pd.concat([x_train, x_dev], axis=0)
merged.to_csv(data_path + f"frequency_{FREQ_VERSION}.csv")
print("wrote", data_path + f"frequency_{FREQ_VERSION}.csv", merged.shape)

wrote ../data/frequency_2026.csv (383610, 566)

## Prediction — law of total expectation

In [16]:
# E[Y] = P(1)*E[Y|1] + P(2+)*E[Y|2+]; second-class mean carried over from 2025
oos_proba = model.predict_proba(oos[selected_features])
oos_expected_count = (oos_proba * CLASS_MEANS).sum(axis=1)

# one block, one concat -- same reason as the train/dev hand-off above.
# FREQ and pred_sum are the same quantity: 2025 named it FREQ for the submission
# and pred_sum for the severity hand-off, and both names are consumed downstream.
oos_block = pd.DataFrame(
    {
        "FREQ": oos_expected_count,
        "pred_1": oos_proba[:, 1],
        "pred_2": oos_proba[:, 2],
        "pred_sum": oos_expected_count,
    },
    index=oos.index,
)
oos = pd.concat(
    [oos.drop(columns=oos_block.columns, errors="ignore"), oos_block], axis=1
)

pred = oos[["ID", "ANNEE_ASSURANCE", "FREQ"]]
# pred.to_csv("predictions/2026_pred.csv", index=False)
pred.head()

       ID  ANNEE_ASSURANCE      FREQ
0  383611         0.813699  0.963831
1  383612         1.000000  0.694419
2  383613         0.586301  0.400150
3  383614         1.000000  0.373611
4  383615         0.753425  0.495960

### Hand-off to `amount_model_2026.ipynb` — OOS

In [17]:
# hand-off to the severity model: OOS frequency predictions
# (mirrors the 2025 notebook, which wrote oos_frequency_012.csv)
# pred_1 / pred_2 / pred_sum were built with FREQ in the cell above, in one block
oos.to_csv(data_path + f"oos_frequency_{FREQ_VERSION}.csv", index=False)
print("wrote", data_path + f"oos_frequency_{FREQ_VERSION}.csv", oos.shape)

wrote ../data/oos_frequency_2026.csv (95852, 564)

### Target encoding for the severity model  *(re-added from 2025)*

`amount_model_2026.ipynb` stratifies its train/dev split on a **discretized `CM`**, and
that discretization is itself a carving: **feature = `CM` (severity), target = frequency**.
2025 built it here, in the frequency notebook (`frequency_model.ipynb` cell 61), and the
severity notebook only ever *loaded* the artifact.

It lives here rather than in the severity notebook for a reason: the recipe fits on
`x_train` / `x_dev`, so putting it in the severity notebook would need a split that does
not exist yet -- the split it is meant to stratify. Fitting it here breaks the circle.

Recipe, unchanged from 2025:

* fit on rows that **actually have a claim** (`y > 0`), not the full frame -- otherwise
  the 99.4 % of rows with `CM == 0` swamp every bucket;
* binary target = **more than one claim** (`collapse_count(y) - 1`, so 0 = exactly one
  claim, 1 = two or more);
* `min_freq=0.05`, `max_n_mod=5`, `dropna=False`, Tschuprow's T (the 7.6 `BinaryCarver`
  default, matching the 2025 `..._tschuprowt` artifact).

Saved in **light mode** -- the 2025 artifact was 56 MB because it persisted the full
combination history; light mode drops it and lands at ~1.6 kB, small enough to commit.

In [18]:
from pathlib import Path

from AutoCarver import BinaryCarver

# feature = CM (severity), target = frequency (binary: more than one claim)
target_carver = BinaryCarver(
    features=Features(numericals=["CM"]),
    min_freq=0.05,
    max_n_mod=5,
    config=ProcessingConfig(dropna=False, copy=True, verbose=False),
)
target_carver.fit(
    x_train[y_train > 0],
    collapse_count(y_train)[y_train > 0] - 1,
    X_dev=x_dev[y_dev > 0],
    y_dev=collapse_count(y_dev)[y_dev > 0] - 1,
)

TARGET_CARVER_PATH = Path("model/cm_carver_freq_tschuprowt_2026.json")
target_carver.save(TARGET_CARVER_PATH, light_mode=True)
print(
    "wrote", TARGET_CARVER_PATH, f"({TARGET_CARVER_PATH.stat().st_size / 1024:.1f} kB)"
)
target_carver.summary

[BinaryCarver] Carving:   0%|          | 0/1 [00:00<?, ?feature/s]

wrote model\cm_carver_freq_tschuprowt_2026.json (1.7 kB)

                                                              content  \
feature         cramerv  tschuprowt n_mod label
Numerical('CM') 0.070898 0.050132   5     0          (-inf, 6.01e+02]
                                          1      (6.01e+02, 8.69e+02]
                                          2      (8.69e+02, 1.49e+03]
                                          3      (1.49e+03, 5.14e+04]
                                          4           (5.14e+04, inf)

                                                 target_mean  frequency  \
feature         cramerv  tschuprowt n_mod label
Numerical('CM') 0.070898 0.050132   5     0         0.026403   0.445807
                                          1         0.067961   0.050515
                                          2         0.025974   0.075527
                                          3         0.049475   0.327121
                                          4         0.024272   0.101030

                                                 count  dropped dropped_reason
feature         cramerv  tschuprowt n_mod label
Numerical('CM') 0.070898 0.050132   5     0      909.0    False           None
                                          1      103.0    False           None
                                          2      154.0    False           None
                                          3      667.0    False           None
                                          4      206.0    False           None