# Claim-Frequency model — A/B arm: `OrdinalSelector`

Copy of `frequency_model_2026.ipynb` with **one variable changed**: feature selection runs
through `OrdinalSelector` instead of `ClassificationSelector`. Everything else — data
prep, split, carving config, `n_best_features=100`, redundancy filters, `N_TRIALS=300`
and the Optuna seed — is identical, so the difference in dev log loss is attributable.

**Result: this arm is worse — 0.95366 dev log loss**, against the shipped arm's
**0.91991** and the 2025 winner's **0.91936**. It ships as the negative result it is.

Two cautions on how far that may be read. The gap sits ~8 standard deviations above the
seed spread measured by `tools/seed_variance.py`, so it is probably not noise — but it is
one draw on this feature set compared against a four-draw distribution on another, which
is not a rigorous comparison. And it is unexplained: `tools/cmp_selectors.py` and
`tools/measure_grid.py` show the two selectors agreeing at 0.96 rank correlation with 93
of 100 features in common. Supported: *did not improve the frequency arm*. Not supported:
any figure for what it costs.

**Export cells are removed** so this arm cannot overwrite the measured hand-off files
(`data/frequency_2026.csv`, `data/oos_frequency_2026.csv`) or the severity target carver.

## Loading data & target  *(reused from 2025)*

In [1]:
import pandas as pd

data_path = "../data/"

# loading x_train
data = pd.read_csv(data_path + "train_input_Z61KlZo.csv", low_memory=False)
data.set_index("ID", inplace=True)
print("x_train", data.shape)

# loading target
target = pd.read_csv(data_path + "train_output_DzPxaPY.csv", low_memory=False)
target.set_index("ID", inplace=True)
print("y_train", target.shape)

# joining x_train and y_train
data = data.join(target.drop("ANNEE_ASSURANCE", axis=1))
print("data", data.shape)

x_train (383610, 373)
y_train (383610, 4)

data (383610, 376)

In [2]:
target_col = "TARGET"
data[target_col] = (data["FREQ"] * data["ANNEE_ASSURANCE"]).astype(int)
data[target_col].value_counts(normalize=False).sort_index()

TARGET
0    381061
1      2458
2        87
3         2
4         1
5         1
Name: count, dtype: int64

## Stratified sampling & inverse-frequency weights  *(reused from 2025)*

In [3]:
import numpy as np

from collections import Counter
from sklearn.model_selection import train_test_split
from data_toolkit import collapse_count

# Compute class frequencies
class_counts = Counter(collapse_count(data[target_col]))
total_samples = len(data[target_col])

# Compute inverse frequency class weights
class_weights = {
    cls: total_samples / (len(class_counts) * count)
    for cls, count in class_counts.items()
}
print("Class weights:", class_weights)

# Assign sample weights based on target values
weights = np.array([class_weights[label] for label in collapse_count(data[target_col])])

# Train-test split
x_train, x_dev, y_train, y_dev, w_train, w_dev = train_test_split(
    data,
    data[target_col],
    weights,
    test_size=0.2,
    random_state=42,
    stratify=collapse_count(data[target_col]),
)
print("y_train mean", y_train.mean(), " observations:", x_train.shape[0])
print("y_dev mean", y_dev.mean(), " observations:", x_dev.shape[0])

Class weights: {0: 0.3355630725789309, 1: 52.0219690805533, 2: 1405.1648351648353}

y_train mean 0.006895023591668622  observations: 306888
y_dev mean 0.006921091733792133  observations: 76722

## Feature engineering  *(reused from 2025)*

In [4]:
from data_toolkit import Processor

proc = Processor()
x_train = proc.fit_transform(x_train)
x_dev = proc.transform(x_dev)
data = proc.transform(data)

## Column typing  *(reused from 2025)*

In [5]:
from AutoCarver import Features

# sorting columns per type
features = Features.from_dataframe(x_train)

# getting ordinal columns
ordinals = [
    "NB_CASERNES",
    "BDTOPO_BAT_MAX_HAUTEUR",
    "HAUTEUR_MAX",
    "HAUTEUR",
    "BDTOPO_BAT_MAX_HAUTEUR_MAX",
    "MEN_SURF",
    "IND_SNV",
    "IND_INC",
    "IND_Y9",
    "IND_0_Y1",
    "IND",
    "LOG_SOC",
    "LOG_INC",
    "LOG_APA3",
    "LOG_AVA1",
    "MEN_MAIS",
    "MEN_COLL",
    "MEN_FMP",
    "MEN_PROP",
    "MEN_PAUV",
    "MEN",
    "COEFASS",
]
ordinals += [
    "DISTANCE_111",
    "DISTANCE_112",
    "DISTANCE_121",
    "DISTANCE_122",
    "DISTANCE_123",
    "DISTANCE_124",
    "DISTANCE_131",
    "DISTANCE_132",
    "DISTANCE_133",
    "DISTANCE_141",
    "DISTANCE_142",
    "DISTANCE_211",
    "DISTANCE_212",
    "DISTANCE_213",
    "DISTANCE_221",
    "DISTANCE_222",
    "DISTANCE_223",
    "DISTANCE_231",
    "DISTANCE_242",
    "DISTANCE_243",
    "DISTANCE_244",
    "DISTANCE_311",
    "DISTANCE_312",
    "DISTANCE_313",
    "DISTANCE_321",
    "DISTANCE_322",
    "DISTANCE_323",
    "DISTANCE_324",
    "DISTANCE_331",
    "DISTANCE_332",
    "DISTANCE_333",
    "DISTANCE_334",
    "DISTANCE_335",
    "DISTANCE_411",
    "DISTANCE_412",
    "DISTANCE_421",
    "DISTANCE_422",
    "DISTANCE_423",
    "DISTANCE_511",
    "DISTANCE_512",
    "DISTANCE_521",
    "DISTANCE_522",
    "DISTANCE_523",
    "PROPORTION_11",
    "PROPORTION_12",
    "PROPORTION_13",
    "PROPORTION_14",
    "PROPORTION_21",
    "PROPORTION_22",
    "PROPORTION_23",
    "PROPORTION_24",
    "PROPORTION_31",
    "PROPORTION_32",
    "PROPORTION_33",
    "PROPORTION_41",
    "PROPORTION_42",
    "PROPORTION_51",
    "PROPORTION_52",
    "MEN_1IND",
    "MEN_5IND",
    "LOG_A1_A2",
    "LOG_A2_A3",
    "IND_Y1_Y2",
    "IND_Y2_Y3",
    "IND_Y3_Y4",
    "IND_Y4_Y5",
    "IND_Y5_Y6",
    "IND_Y6_Y7",
    "IND_Y7_Y8",
    "IND_Y8_Y9",
    "DISTANCE_1",
    "DISTANCE_2",
    "ALTITUDE_1",
    "ALTITUDE_2",
    "ALTITUDE_3",
    "ALTITUDE_4",
    "ALTITUDE_5",
    "NBJTX25_MM_A",
    "NBJTX25_MMAX_A",
    "NBJTX25_MSOM_A",
    "NBJTX0_MM_A",
    "NBJTX0_MMAX_A",
    "NBJTX0_MSOM_A",
    "NBJTXI27_MM_A",
    "NBJTXI27_MMAX_A",
    "NBJTXI27_MSOM_A",
    "NBJTXS32_MM_A",
    "NBJTXS32_MMAX_A",
    "NBJTXS32_MSOM_A",
    "NBJTXI20_MM_A",
    "NBJTXI20_MMAX_A",
    "NBJTXI20_MSOM_A",
    "NBJTX30_MM_A",
    "NBJTX30_MMAX_A",
    "NBJTX30_MSOM_A",
    "NBJTX35_MM_A",
    "NBJTX35_MMAX_A",
    "NBJTX35_MSOM_A",
    "NBJTN10_MM_A",
    "NBJTN10_MMAX_A",
    "NBJTN10_MSOM_A",
    "NBJTNI10_MM_A",
    "NBJTNI10_MMAX_A",
    "NBJTNI10_MSOM_A",
    "NBJTN5_MM_A",
    "NBJTN5_MMAX_A",
    "NBJTN5_MSOM_A",
    "NBJTNS25_MM_A",
    "NBJTNS25_MMAX_A",
    "NBJTNS25_MSOM_A",
    "NBJTNI15_MM_A",
    "NBJTNI15_MMAX_A",
    "NBJTNI15_MSOM_A",
    "NBJTNI20_MM_A",
    "NBJTNI20_MMAX_A",
    "NBJTNI20_MSOM_A",
    "NBJTNS20_MM_A",
    "NBJTNS20_MMAX_A",
    "NBJTNS20_MSOM_A",
    "NBJTMS24_MM_A",
    "NBJTMS24_MMAX_A",
    "NBJTMS24_MSOM_A",
    "TAMPLIAB_VOR_MM_A",
    "TAMPLIAB_VOR_MMAX_A",
    "TAMPLIM_VOR_MM_A",
    "TAMPLIM_VOR_MMAX_A",
    "TM_VOR_MM_A",
    "TM_VOR_MMAX_A",
    "TMM_VOR_MM_A",
    "TMM_VOR_MMAX_A",
    "TMMAX_VOR_MM_A",
    "TMMAX_VOR_MMAX_A",
    "TMMIN_VOR_MM_A",
    "TMMIN_VOR_MMAX_A",
    "TN_VOR_MM_A",
    "TN_VOR_MMAX_A",
    "TNAB_VOR_MM_A",
    "TNAB_VOR_MMAX_A",
    "TNMAX_VOR_MM_A",
    "TNMAX_VOR_MMAX_A",
    "TX_VOR_MM_A",
    "TX_VOR_MMAX_A",
    "TXAB_VOR_MM_A",
    "TXAB_VOR_MMAX_A",
    "TXMIN_VOR_MM_A",
    "TXMIN_VOR_MMAX_A",
    "NBJFF10_MM_A",
    "NBJFF10_MMAX_A",
    "NBJFF10_MSOM_A",
    "NBJFF16_MM_A",
    "NBJFF16_MMAX_A",
    "NBJFF16_MSOM_A",
    "NBJFF28_MM_A",
    "NBJFF28_MMAX_A",
    "NBJFF28_MSOM_A",
    "NBJFXI3S10_MM_A",
    "NBJFXI3S10_MMAX_A",
    "NBJFXI3S10_MSOM_A",
    "NBJFXI3S16_MM_A",
    "NBJFXI3S16_MMAX_A",
    "NBJFXI3S16_MSOM_A",
    "NBJFXI3S28_MM_A",
    "NBJFXI3S28_MMAX_A",
    "NBJFXI3S28_MSOM_A",
    "NBJFXY8_MM_A",
    "NBJFXY8_MMAX_A",
    "NBJFXY8_MSOM_A",
    "NBJFXY10_MM_A",
    "NBJFXY10_MMAX_A",
    "NBJFXY10_MSOM_A",
    "NBJFXY15_MM_A",
    "NBJFXY15_MMAX_A",
    "NBJFXY15_MSOM_A",
    "FFM_VOR_MM_A",
    "FFM_VOR_MMAX_A",
    "FXI3SAB_VOR_MM_A",
    "FXI3SAB_VOR_MMAX_A",
    "FXIAB_VOR_MM_A",
    "FXIAB_VOR_MMAX_A",
    "FXYAB_VOR_MM_A",
    "FXYAB_VOR_MMAX_A",
    "FFM_VOR_COM_MM_A_Y",
    "FFM_VOR_COM_MMAX_A_Y",
    "FXI3SAB_VOR_COM_MM_A_Y",
    "FXI3SAB_VOR_COM_MMAX_A_Y",
    "NBJRR50_MM_A",
    "NBJRR50_MMAX_A",
    "NBJRR50_MSOM_A",
    "NBJRR1_MM_A",
    "NBJRR1_MMAX_A",
    "NBJRR1_MSOM_A",
    "NBJRR5_MM_A",
    "NBJRR5_MMAX_A",
    "NBJRR5_MSOM_A",
    "NBJRR10_MM_A",
    "NBJRR10_MMAX_A",
    "NBJRR10_MSOM_A",
    "NBJRR30_MM_A",
    "NBJRR30_MMAX_A",
    "NBJRR30_MSOM_A",
    "NBJRR100_MM_A",
    "NBJRR100_MMAX_A",
    "NBJRR100_MSOM_A",
    "RR_VOR_MM_A",
    "RR_VOR_MMAX_A",
    "RRAB_VOR_MM_A",
    "RRAB_VOR_MMAX_A",
]
ordinals += ["TAILLE1", "TAILLE2"]
ordinal_columns = {
    col: list(data[col].value_counts().sort_index().index)
    for col in ordinals
    if col in data.columns
}
ordinal_columns["PROPORTION_32"] += ["10. > 90"]
ordinal_columns.update(
    {
        "CARACT4": [
            "absence de surface",
            "Surface de moins d",
            "Surface entre 501",
            "Surface entre 1001",
            "Surface entre 1501",
            "Surface de plus de",
        ],
        "SURFACE4": [
            "0",
            "500",
            "1000",
            "1500",
            "2000",
            "2500",
            "3000",
            "3500",
            "4000",
            "4500",
            "5000",
            "5500",
            "6000",
            "6500",
            "7000",
            "7000+",
        ],
        "SURFACE6": [
            "0",
            "500",
            "1000",
            "1500",
            "2000",
            "2500",
            "3000",
            "3500",
            "4000",
            "4500",
            "5000",
            "5500",
            "6000",
            "6500",
            "7000",
            "7000+",
        ],
        "total_surface_2023": [
            "Aucun feu",
            "<10ha",
            "10-20ha",
            "20-50ha",
            "50-100ha",
            "100-200ha",
            ">200ha",
        ],
        "total_surface_5y": [
            "Aucun feu",
            "<10ha",
            "10-20ha",
            "20-50ha",
            "50-100ha",
            "100-200ha",
            ">200ha",
        ],
        "surface_over_forest": [
            "Absence de feu",
            "<0.05",
            "0.05-0.1",
            "0.1-0.2",
            "0.5-2",
        ],
        "fire_extinction_rates": ["Aucun feu", "<50%", "50-70%", "70-85%", ">85%"],
    }
)

# columns that are to be removed (target + no values)
to_remove = target.columns.tolist() + [target_col]
to_remove += [c for c in data.columns if "MMSOM" in c]
to_remove += ["DEROG13", "DEROG14", "DEROG16"]

# removing columns
categorical_columns = [
    col.name
    for col in features.categoricals
    if col not in to_remove and col not in ordinal_columns
]
categorical_columns += ["TYPERS"]
numerical_columns = [
    col.name
    for col in features.numericals
    if col not in to_remove
    and col not in ordinal_columns
    and col not in categorical_columns
]
print(
    len(categorical_columns),
    len(numerical_columns),
    len(ordinal_columns),
    len(categorical_columns) + len(numerical_columns) + len(ordinal_columns),
)

197 120 238 555

## 2026 carving — OrdinalCarver + multiprocessing + Wilson-CI

`n_jobs` parallelises the per-feature combination search; set it to the core
count on the competition machine. `min_freq_alpha=0.05` is the 95% Wilson
interval used to test each bin's frequency.

In [6]:
import time

from AutoCarver import Features, OrdinalCarver
from AutoCarver.discretizers import ProcessingConfig

N_JOBS = 6

# the 0/1/2+ claim-count target is ordinal -> carve with Kendall's Tau-c
y_ord_train = collapse_count(y_train)
y_ord_dev = collapse_count(y_dev)

config = ProcessingConfig(
    dropna=False, copy=False, verbose=False, n_jobs=N_JOBS, min_freq_alpha=0.05
)

### Qualitative + ordinal features

In [7]:
qualitatives = Features(categoricals=categorical_columns, ordinals=ordinal_columns)

carver = OrdinalCarver(features=qualitatives, target_scale="level", config=config)

t0 = time.perf_counter()
x_train = carver.fit_transform(x_train, y_ord_train, X_dev=x_dev, y_dev=y_ord_dev)
print(
    f"[2026] qualitative carving: {time.perf_counter() - t0:.1f}s on {N_JOBS} workers"
)
carver.summary

[OrdinalCarver] Carving:   0%|          | 0/435 [00:00<?, ?feature/s]

[OrdinalCarver] dropped 38/435 feature(s) (no robust train/dev combination): LOG_VETUSTE_REGION, MEN_num, IND_num, IND_0_Y1_num, IND_Y1_Y2_num, IND_Y4_Y5_num, IND_Y6_Y7_num, IND_Y7_Y8_num, IND_INC_num, IND_0_Y1_IND, IND_Y1_Y2_IND, IND_Y2_Y3_IND, IND_Y6_Y7_IND, IND_Y7_Y8_IND, IND_INC_IND, IND_INC, IND_0_Y1, IND, LOG_INC, MEN, PROPORTION_13, PROPORTION_12, PROPORTION_14, PROPORTION_11, PROPORTION_33, PROPORTION_41, PROPORTION_51, PROPORTION_42, PROPORTION_52, IND_Y1_Y2, IND_Y2_Y3, LOG_A1_A2, IND_Y4_Y5, IND_Y6_Y7, IND_Y7_Y8, LOG_APA3_num_LOG_TOT, LOG_AVA1_num_LOG_TOT, LOG_VETUSTE

[2026] qualitative carving: 121.5s on 6 workers

                                                                                                                          content  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                                                        [ACT3, ACT2]
                                                            1                           [ACT8, ACT9, ACT4, ACT6, ACT7, __OTHER__]
                                                            2                                                                ACT1
                                                            3                                                                ACT5
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                   [VOC1, VOC7, VOC5, VOC3, VOC2, __OTHER__, VOC4...
...                                                                                                                           ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686                                 57.926829268292686
                                                            64.02439024390245                                   64.02439024390245
                                                            52.083333333333336                                 52.083333333333336
                                                            43.292682926829265                                 43.292682926829265
                                                            69.63855421686748                                   69.63855421686748

                                                                                target_mean_level  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                            0.002030
                                                            1                            0.005593
                                                            2                            0.006539
                                                            3                            0.010893
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                            0.002050
...                                                                                           ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686           0.007920
                                                            64.02439024390245            0.008269
                                                            52.083333333333336           0.008765
                                                            43.292682926829265           0.008900
                                                            69.63855421686748            0.008993

                                                                                frequency  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                    0.051364
                                                            1                    0.035537
                                                            2                    0.773396
                                                            3                    0.139702
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                    0.362458
...                                                                                   ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686   0.020571
                                                            64.02439024390245    0.048470
                                                            52.083333333333336   0.020076
                                                            43.292682926829265   0.010251
                                                            69.63855421686748    0.014856

                                                                                   count  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                    15763.0
                                                            1                    10906.0
                                                            2                   237346.0
                                                            3                    42873.0
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                   111234.0
...                                                                                  ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686    6313.0
                                                            64.02439024390245    14875.0
                                                            52.083333333333336    6161.0
                                                            43.292682926829265    3146.0
                                                            69.63855421686748     4559.0

                                                                                dropped  \
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                     False
                                                            1                     False
                                                            2                     False
                                                            3                     False
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                     False
...                                                                                 ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686     True
                                                            64.02439024390245      True
                                                            52.083333333333336     True
                                                            43.292682926829265     True
                                                            69.63855421686748      True

                                                                                                                   dropped_reason
feature                    tau_b    tau_c    somersd  n_mod label
Categorical('ACTIVIT2')    0.020905 0.002217 0.003905 4.0   0                                                                None
                                                            1                                                                None
                                                            2                                                                None
                                                            3                                                                None
Categorical('VOCATION')    0.042972 0.006714 0.007263 2.0   0                                                                None
...                                                                                                                           ...
Categorical('LOG_VETUSTE') NaN      NaN      NaN      NaN   57.926829268292686  No robust combination (Inversion of target rat...
                                                            64.02439024390245   No robust combination (Inversion of target rat...
                                                            52.083333333333336  No robust combination (Inversion of target rat...
                                                            43.292682926829265  No robust combination (Inversion of target rat...
                                                            69.63855421686748   No robust combination (Inversion of target rat...

[977 rows x 6 columns]

### Apply carver to dev + OOS

In [8]:
x_dev = carver.transform(x_dev)

data_path = "../data/"
oos = pd.read_csv(data_path + "test_input_5qJzHrr.csv", low_memory=False)
oos = proc.transform(oos)
oos = carver.transform(oos)

No processing for continuous features

In [9]:
quantitatives = Features(numericals=numerical_columns)

## Feature selection  *(A/B arm — `OrdinalSelector`)*

`OrdinalSelector` in place of `ClassificationSelector`, and **nothing else changed**:
same carved features, same `n_best_features=100`, same redundancy filters, same seeded
300-trial search.

The two rank features differently. `ClassificationSelector` scores qualitative candidates
with Tschuprow's T, which treats `0 / 1 / 2+` as three unordered labels — a feature that
separates "0 from 1 and 2+" scores the same as one that separates "0 and 1 from 2+".
`OrdinalSelector` treats the integer-encoded target as a rank and scores with Spearman's
rho on quantitatives and a reversed Kruskal-eta-squared on qualitatives, so a feature that
moves *with* the claim count outranks one that merely splits it.

That is the selector-side version of the argument §3.2 makes about the carver: the target
is ordered, and a tool that ignores the order is leaving that information unused.

In [10]:
from AutoCarver.selectors import (
    CramervFilter,
    OrdinalSelector,
    SelectionConfig,
    SpearmanFilter,
)

config = SelectionConfig(
    qualitative_filters=[CramervFilter(threshold=0.9)],
    quantitative_filters=[SpearmanFilter(threshold=0.9)],
)
selector = OrdinalSelector(
    qualitatives + quantitatives, n_best_features=100, config=config
)
selector.fit(x_train, y_ord_train)
print("selected:", len(selector.selected_features))
selector.summary

selected: 100

,feature,Nan,Mode,measure,association,rank,filter,redundancy,redundancy_with,selected
0,Numerical('KAPITAL32'),0.000000,0.347971,Spearman,0.057794,0.0,Spearman,0.000000,itself,True
1,Numerical('KAPITAL_MAX'),0.000000,0.248687,Spearman,0.053906,1.0,Spearman,0.824113,KAPITAL32,True
2,Numerical('SURFACE10'),0.019235,0.523992,Spearman,0.051294,2.0,Spearman,0.611342,KAPITAL32,True
3,Numerical('SURFACE1'),0.000000,0.071573,Spearman,0.050736,3.0,Spearman,0.640521,KAPITAL32,True
4,Numerical('SURFACE7'),0.010479,0.559276,Spearman,0.049353,4.0,Spearman,0.621579,SURFACE10,True
...,...,...,...,...,...,...,...,...,...,...
511,Ordinal('SURFACE4'),0.000000,0.605064,KruskalEtaSquared,0.002260,NaN,Cramerv,0.999993,SURFACE6,False
512,Ordinal('total_surface_2023'),0.000000,0.587276,KruskalEtaSquared,0.000011,NaN,None,NaN,None,False
513,Ordinal('total_surface_5y'),0.000000,0.731602,KruskalEtaSquared,0.000064,NaN,None,NaN,None,False
514,Ordinal('surface_over_forest'),0.000000,0.842874,KruskalEtaSquared,0.000015,NaN,None,NaN,None,False
515,Ordinal('fire_extinction_rates'),0.000000,0.566291,KruskalEtaSquared,0.000003,NaN,None,NaN,None,False

In [11]:
pd.set_option("display.max_rows", None)
selector.summary

,feature,Nan,Mode,measure,association,rank,filter,redundancy,redundancy_with,selected
0,Numerical('KAPITAL32'),0.000000,0.347971,Spearman,5.779430e-02,0.0,Spearman,0.000000,itself,True
1,Numerical('KAPITAL_MAX'),0.000000,0.248687,Spearman,5.390646e-02,1.0,Spearman,0.824113,KAPITAL32,True
2,Numerical('SURFACE10'),0.019235,0.523992,Spearman,5.129417e-02,2.0,Spearman,0.611342,KAPITAL32,True
3,Numerical('SURFACE1'),0.000000,0.071573,Spearman,5.073559e-02,3.0,Spearman,0.640521,KAPITAL32,True
4,Numerical('SURFACE7'),0.010479,0.559276,Spearman,4.935349e-02,4.0,Spearman,0.621579,SURFACE10,True
5,Numerical('KAPITAL21'),0.014090,0.573636,Spearman,4.465265e-02,5.0,Spearman,0.706107,KAPITAL32,True
6,Numerical('NBBAT4'),0.000000,0.121360,Spearman,4.398885e-02,6.0,Spearman,0.834693,SURFACE1,True
7,Numerical('NBSINSTRT'),0.000000,0.727373,Spearman,4.015080e-02,7.0,Spearman,0.379864,KAPITAL32,True
8,Numerical('KAPITAL23'),0.003050,0.834321,Spearman,3.762247e-02,8.0,Spearman,0.422755,SURFACE7,True
9,Numerical('EQUIPEMENT6'),0.000000,0.100607,Spearman,3.447416e-02,9.0,Spearman,0.394208,KAPITAL21,True
10,Numerical('NBSINCONJ'),0.000000,0.857394,Spearman,3.230802e-02,10.0,Spearman,0.678237,NBSINSTRT,True
11,Numerical('SURFACE17'),0.000000,0.831616,Spearman,3.098793e-02,11.0,Spearman,0.479089,SURFACE10,True
12,Numerical('KAPITAL8'),0.000000,0.955847,Spearman,3.006229e-02,12.0,Spearman,0.376848,KAPITAL23,True
13,Numerical('KAPITAL14'),0.000000,0.810494,Spearman,2.835174e-02,13.0,Spearman,0.440357,KAPITAL32,True
14,Numerical('TAILLE3'),0.000000,0.816073,Spearman,2.830057e-02,14.0,Spearman,0.409352,KAPITAL_MAX,True
15,Numerical('KAPITAL24'),0.002209,0.905989,Spearman,2.556681e-02,15.0,Spearman,0.404014,KAPITAL32,True
16,Numerical('KAPITAL27'),0.000000,0.844725,Spearman,2.500207e-02,16.0,Spearman,0.576490,KAPITAL24,True
17,Numerical('KAPITAL3'),0.000000,0.953361,Spearman,2.452047e-02,17.0,Spearman,0.242833,KAPITAL_MAX,True
18,Numerical('CA3_CA_TOT'),0.960080,0.035811,Spearman,-2.297527e-02,18.0,Spearman,-0.337415,SURFACE7,True
19,Numerical('KAPITAL10'),0.000000,0.600307,Spearman,2.291511e-02,19.0,Spearman,0.522196,KAPITAL32,True
20,Numerical('EQUIPEMENT1'),0.000000,0.924891,Spearman,1.763091e-02,20.0,Spearman,0.271899,SURFACE7,True
21,Numerical('NBBAT2'),0.000000,0.921098,Spearman,1.761296e-02,21.0,Spearman,0.277145,SURFACE1,True
22,Numerical('SURFACE13'),0.000000,0.941816,Spearman,-1.391219e-02,22.0,Spearman,-0.274989,KAPITAL_MAX,True
23,Numerical('CARACT5'),0.000000,0.951494,Spearman,1.331636e-02,23.0,Spearman,0.182484,SURFACE1,True
24,Numerical('RISK5'),0.069058,0.414461,Spearman,-1.322828e-02,24.0,Spearman,-0.666149,KAPITAL10,True
25,Numerical('NBBAT8'),0.000000,0.949288,Spearman,1.206160e-02,25.0,Spearman,0.782825,NBBAT2,True
26,Numerical('ZONE_VENT'),0.048493,0.571179,Spearman,1.203212e-02,26.0,Spearman,0.106681,KAPITAL23,True
27,Numerical('CA3_CA_MEAN'),0.960080,0.036075,Spearman,1.186019e-02,27.0,Spearman,-0.574153,CA3_CA_TOT,True
28,Numerical('KAPITAL20'),0.000701,0.995321,Spearman,1.141782e-02,28.0,Spearman,0.103333,KAPITAL14,True
29,Numerical('KAPITAL25'),0.000000,0.572323,Spearman,-1.107941e-02,29.0,Spearman,-0.306696,KAPITAL32,True
30,Numerical('KAPITAL17'),0.002336,0.988768,Spearman,1.071835e-02,30.0,Spearman,0.174275,KAPITAL24,True
31,Numerical('RISK2'),0.069058,0.414461,Spearman,-1.030462e-02,31.0,Spearman,0.851601,RISK5,True
32,Numerical('NBBAT6'),0.000000,0.978956,Spearman,9.880596e-03,32.0,Spearman,0.515189,NBBAT2,True
33,Numerical('NBBAT9'),0.000000,0.522839,Spearman,9.545151e-03,33.0,Spearman,0.428987,NBBAT4,True
34,Numerical('KAPITAL1'),0.000000,0.975939,Spearman,9.407062e-03,34.0,Spearman,0.245992,KAPITAL14,True
35,Numerical('DEROG10'),0.000000,0.996165,Spearman,9.202385e-03,35.0,Spearman,0.106730,TAILLE3,True
36,Numerical('RISK1'),0.069058,0.414461,Spearman,-9.069743e-03,36.0,Spearman,0.885394,RISK2,True
37,Numerical('DEROG8_formatted'),0.000000,0.979370,Spearman,-9.048523e-03,37.0,Spearman,-0.166884,KAPITAL32,True
38,Numerical('DUREE_REQANEUF'),0.069058,0.863631,Spearman,8.983360e-03,38.0,Spearman,0.232908,KAPITAL_MAX,True
39,Numerical('NBBAT7'),0.000000,0.993258,Spearman,8.949512e-03,39.0,Spearman,0.277779,NBBAT2,True
40,Numerical('DEROG11'),0.000000,0.987683,Spearman,8.691299e-03,40.0,Spearman,0.520261,DEROG10,True
41,Numerical('EQUIPEMENT4'),0.000000,0.899419,Spearman,8.145125e-03,41.0,Spearman,0.522600,EQUIPEMENT6,True
42,Numerical('DEROG7'),0.000000,0.998022,Spearman,8.092311e-03,42.0,Spearman,0.056103,KAPITAL23,True
43,Numerical('DEROG6'),0.000000,0.994809,Spearman,8.046819e-03,43.0,Spearman,0.195569,NBBAT2,True
44,Numerical('CA3'),0.960080,0.015064,Spearman,7.993882e-03,44.0,Spearman,-0.322482,KAPITAL25,True
45,Numerical('DEROG1'),0.000000,0.999801,Spearman,7.399408e-03,45.0,Spearman,0.025669,DEROG11,True
46,Numerical('TYPBAT2'),0.000000,0.377965,Spearman,7.385687e-03,46.0,Spearman,0.549456,RISK1,True
47,Numerical('RISK4'),0.069058,0.414461,Spearman,-6.985833e-03,47.0,Spearman,0.894092,RISK2,True
48,Numerical('KAPITAL28'),0.000000,0.968233,Spearman,6.172994e-03,48.0,Spearman,0.478263,CARACT5,True
49,Numerical('KAPITAL19'),0.002933,0.982117,Spearman,6.132568e-03,49.0,Spearman,0.603264,KAPITAL28,True
50,Numerical('ANCIENNETE'),0.000000,0.159716,Spearman,6.071834e-03,NaN,None,NaN,None,False
51,Numerical('CARACT2'),0.959888,0.039373,Spearman,-7.622550e-04,NaN,None,NaN,None,False
52,Numerical('DEROG9'),0.000000,0.994278,Spearman,7.106983e-04,NaN,None,NaN,None,False
53,Numerical('DEROG15'),0.000000,0.999896,Spearman,8.351675e-04,NaN,None,NaN,None,False
54,Numerical('CA1'),0.927882,0.018326,Spearman,4.829725e-03,NaN,None,NaN,None,False
55,Numerical('CA2'),0.999831,0.000098,Spearman,NaN,NaN,None,NaN,None,False
56,Numerical('KAPITAL2'),0.000000,0.997742,Spearman,-5.115070e-04,NaN,None,NaN,None,False
57,Numerical('KAPITAL4'),0.000000,0.999583,Spearman,2.257218e-03,NaN,None,NaN,None,False
58,Numerical('KAPITAL5'),0.000000,0.995852,Spearman,2.832579e-03,NaN,None,NaN,None,False
59,Numerical('KAPITAL6'),0.000000,0.573584,Spearman,4.270720e-02,NaN,Spearman,0.955036,KAPITAL21,False
60,Numerical('KAPITAL7'),0.000000,0.831935,Spearman,3.672312e-02,NaN,Spearman,0.986379,KAPITAL23,False
61,Numerical('KAPITAL9'),0.000000,0.902036,Spearman,2.513253e-02,NaN,Spearman,0.975769,KAPITAL24,False
62,Numerical('KAPITAL11'),0.309846,0.290461,Spearman,6.098225e-03,NaN,None,NaN,None,False
63,Numerical('KAPITAL12'),0.000000,0.309846,Spearman,5.150982e-02,NaN,Spearman,0.947189,KAPITAL_MAX,False
64,Numerical('KAPITAL13'),0.000000,0.975939,Spearman,9.397590e-03,NaN,Spearman,0.999995,KAPITAL1,False
65,Numerical('KAPITAL15'),0.001619,0.992066,Spearman,5.650889e-03,NaN,None,NaN,None,False
66,Numerical('KAPITAL16'),0.004076,0.981642,Spearman,5.094329e-03,NaN,None,NaN,None,False
67,Numerical('KAPITAL18'),0.000140,0.995735,Spearman,5.389481e-03,NaN,None,NaN,None,False
68,Numerical('KAPITAL22'),0.006843,0.986810,Spearman,-1.964694e-03,NaN,None,NaN,None,False
69,Numerical('KAPITAL26'),0.000000,0.962833,Spearman,5.405350e-03,NaN,None,NaN,None,False
70,Numerical('KAPITAL29'),0.009844,0.983756,Spearman,-1.561478e-03,NaN,None,NaN,None,False
71,Numerical('KAPITAL30'),0.009844,0.985428,Spearman,3.701103e-03,NaN,None,NaN,None,False
72,Numerical('KAPITAL31'),0.000010,0.981365,Spearman,-2.698242e-04,NaN,None,NaN,None,False
73,Numerical('KAPITAL33'),0.000010,0.954159,Spearman,-1.158249e-03,NaN,None,NaN,None,False
74,Numerical('KAPITAL36'),0.000000,0.997742,Spearman,-5.115070e-04,NaN,None,NaN,None,False
75,Numerical('KAPITAL38'),0.000000,0.999583,Spearman,2.257218e-03,NaN,None,NaN,None,False
76,Numerical('KAPITAL39'),0.000000,0.995852,Spearman,2.832579e-03,NaN,None,NaN,None,False
77,Numerical('SURFACE2'),0.000000,0.071573,Spearman,5.073397e-02,NaN,Spearman,0.999999,SURFACE1,False
78,Numerical('SURFACE3'),0.228865,0.049445,Spearman,4.959340e-02,NaN,Spearman,0.976658,SURFACE1,False
79,Numerical('SURFACE5'),0.000000,0.727295,Spearman,2.748204e-03,NaN,None,NaN,None,False
80,Numerical('SURFACE8'),0.228924,0.710803,Spearman,1.631506e-02,NaN,Spearman,0.998956,NBBAT2,False
81,Numerical('SURFACE9'),0.038131,0.928234,Spearman,4.909153e-03,NaN,None,NaN,None,False
82,Numerical('SURFACE11'),0.228865,0.066184,Spearman,4.747484e-02,NaN,Spearman,0.931674,SURFACE1,False
83,Numerical('SURFACE12'),0.000000,0.979478,Spearman,2.019824e-03,NaN,None,NaN,None,False
84,Numerical('SURFACE14'),0.000000,0.999928,Spearman,4.044124e-03,NaN,None,NaN,None,False
85,Numerical('SURFACE15'),0.000000,0.999925,Spearman,-7.080373e-04,NaN,None,NaN,None,False
86,Numerical('SURFACE16'),0.000000,0.928114,Spearman,5.816790e-03,NaN,None,NaN,None,False
87,Numerical('SURFACE18'),0.228865,0.586885,Spearman,3.380797e-03,NaN,None,NaN,None,False
88,Numerical('SURFACE19'),0.228865,0.748791,Spearman,-8.216507e-04,NaN,None,NaN,None,False
89,Numerical('SURFACE20'),0.000000,0.999954,Spearman,-5.523952e-04,NaN,None,NaN,None,False
90,Numerical('SURFACE21'),0.000000,0.935315,Spearman,5.981277e-03,NaN,None,NaN,None,False
91,Numerical('NBBAT1'),0.000000,0.121328,Spearman,4.396181e-02,NaN,Spearman,0.999839,NBBAT4,False
92,Numerical('NBBAT3'),0.000000,0.998908,Spearman,-1.489047e-03,NaN,None,NaN,None,False
93,Numerical('NBBAT5'),0.000000,0.997328,Spearman,2.763026e-03,NaN,None,NaN,None,False
94,Numerical('NBBAT10'),0.000000,0.921098,Spearman,1.761295e-02,NaN,Spearman,1.000000,NBBAT2,False
95,Numerical('NBBAT11'),0.000000,0.993920,Spearman,-7.203027e-04,NaN,None,NaN,None,False
96,Numerical('NBBAT13'),0.000000,0.127291,Spearman,4.230364e-02,NaN,Spearman,0.971032,NBBAT4,False
97,Numerical('NBBAT14'),0.000000,0.727295,Spearman,2.920215e-03,NaN,None,NaN,None,False
98,Numerical('TAILLE4'),0.000000,0.972094,Spearman,-9.450088e-04,NaN,None,NaN,None,False
99,Numerical('RISK3'),0.069058,0.414461,Spearman,-9.800538e-03,NaN,Spearman,0.968219,RISK2,False
100,Numerical('RISK7'),0.069058,0.495810,Spearman,-9.000341e-03,NaN,Spearman,0.949660,RISK2,False
101,Numerical('EQUIPEMENT3'),0.000000,0.976851,Spearman,-4.706199e-05,NaN,None,NaN,None,False
102,Numerical('EQUIPEMENT7'),0.000000,0.100607,Spearman,3.430692e-02,NaN,Spearman,0.999620,EQUIPEMENT6,False
103,Numerical('CA_TOT'),0.891902,0.030780,Spearman,2.937134e-04,NaN,None,NaN,None,False
104,Numerical('CA_MEAN'),0.891902,0.031044,Spearman,-1.693449e-03,NaN,None,NaN,None,False
105,Numerical('CA1_CA_TOT'),0.927882,0.068178,Spearman,-7.261453e-03,NaN,Spearman,-0.999815,CA3_CA_TOT,False
106,Numerical('CA1_CA_MEAN'),0.927882,0.068442,Spearman,-3.184277e-03,NaN,None,NaN,None,False
107,Numerical('CA2_CA_TOT'),0.999831,0.000091,Spearman,NaN,NaN,None,NaN,None,False
108,Numerical('CA2_CA_MEAN'),0.999831,0.000091,Spearman,NaN,NaN,None,NaN,None,False
109,Numerical('Unknown'),0.046714,0.058699,Spearman,1.147255e-03,NaN,None,NaN,None,False
110,Numerical('Involontaire (travaux)'),0.046714,0.201197,Spearman,-2.719481e-03,NaN,None,NaN,None,False
111,Numerical('Involontaire (particulier)'),0.046714,0.239625,Spearman,-1.676862e-03,NaN,None,NaN,None,False
112,Numerical('Accidentelle'),0.046714,0.279939,Spearman,1.293638e-03,NaN,None,NaN,None,False
113,Numerical('Malveillance'),0.046714,0.275733,Spearman,-1.360950e-03,NaN,None,NaN,None,False
114,Numerical('Naturelle'),0.046714,0.514699,Spearman,-1.100153e-03,NaN,None,NaN,None,False
115,Numerical('KAPITAL_SUM'),0.000000,0.050188,Spearman,5.281130e-02,NaN,Spearman,0.925025,KAPITAL_MAX,False
116,Numerical('DEROG13_formatted'),0.000000,0.996667,Spearman,2.918759e-03,NaN,None,NaN,None,False
117,Numerical('DEROG3_formatted'),0.000000,0.979136,Spearman,-8.852269e-03,NaN,Spearman,0.994243,DEROG8_formatted,False
118,Numerical('DEROG16_formatted'),0.000000,0.995634,Spearman,-1.158729e-03,NaN,None,NaN,None,False
119,Ordinal('SURFACE6'),0.000000,0.605064,KruskalEtaSquared,2.259566e-03,0.0,Cramerv,0.000000,itself,True
120,Ordinal('TAILLE1'),0.000000,0.536202,KruskalEtaSquared,2.027832e-03,1.0,Cramerv,0.784561,SURFACE6,True
121,Ordinal('TAILLE2'),0.000000,0.648250,KruskalEtaSquared,1.947348e-03,2.0,Cramerv,0.791881,TAILLE1,True
122,Categorical('VOCATION'),0.000000,0.637542,KruskalEtaSquared,1.843793e-03,3.0,Cramerv,0.412891,SURFACE6,True
123,Categorical('KAPITAL40'),0.000000,0.573584,KruskalEtaSquared,1.820653e-03,4.0,Cramerv,0.523479,VOCATION,True
124,Categorical('TYPERS'),0.000000,0.665246,KruskalEtaSquared,1.609234e-03,5.0,Cramerv,0.439513,TAILLE2,True
125,Categorical('KAPITAL41'),0.000000,0.831935,KruskalEtaSquared,1.345333e-03,6.0,Cramerv,0.339695,KAPITAL40,True
126,Categorical('KAPITAL42'),0.000000,0.955847,KruskalEtaSquared,9.004856e-04,7.0,Cramerv,0.351962,KAPITAL41,True
127,Categorical('RISK11'),0.000000,0.590649,KruskalEtaSquared,8.135928e-04,8.0,Cramerv,0.346331,TAILLE2,True
128,Categorical('DEROG12'),0.910026,0.069993,KruskalEtaSquared,8.087761e-04,9.0,Cramerv,0.299745,TAILLE2,True
129,Categorical('KAPITAL43'),0.000000,0.902036,KruskalEtaSquared,6.283878e-04,10.0,Cramerv,0.355821,TAILLE2,True
130,Categorical('KAPITAL37'),0.000000,0.953361,KruskalEtaSquared,5.979967e-04,11.0,Cramerv,0.218826,KAPITAL41,True
131,Ordinal('HAUTEUR_MAX'),0.618584,0.268023,KruskalEtaSquared,5.038433e-04,12.0,Cramerv,0.321568,TAILLE1,True
132,Categorical('ACTIVIT2'),0.000000,0.773396,KruskalEtaSquared,4.880599e-04,13.0,Cramerv,0.421996,VOCATION,True
133,Categorical('DEROG4'),0.000000,0.936260,KruskalEtaSquared,4.386973e-04,14.0,Cramerv,0.187568,KAPITAL40,True
134,Ordinal('BDTOPO_BAT_MAX_HAUTEUR_MAX'),0.618584,0.235939,KruskalEtaSquared,4.112134e-04,15.0,Cramerv,0.657972,HAUTEUR_MAX,True
135,Categorical('ZONE'),0.000000,0.503907,KruskalEtaSquared,3.879580e-04,16.0,Cramerv,0.189744,KAPITAL41,True
136,Categorical('RISK10'),0.366860,0.424650,KruskalEtaSquared,3.692199e-04,17.0,Cramerv,0.518069,RISK11,True
137,Categorical('DEROG5'),0.000000,0.951647,KruskalEtaSquared,3.217873e-04,18.0,Cramerv,0.863876,DEROG4,True
138,Categorical('AN_EXERC'),0.000000,0.596126,KruskalEtaSquared,2.874004e-04,19.0,Cramerv,0.202763,RISK10,True
139,Categorical('total_surface_crossed'),0.000000,0.711931,KruskalEtaSquared,2.848793e-04,20.0,Cramerv,0.386196,ZONE,True
140,Categorical('INDEM2'),0.071541,0.636995,KruskalEtaSquared,2.402262e-04,21.0,Cramerv,0.249867,SURFACE6,True
141,Categorical('NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A'),0.567477,0.231061,KruskalEtaSquared,2.378131e-04,22.0,Cramerv,0.216871,KAPITAL41,True
142,Ordinal('HAUTEUR'),0.618584,0.170877,KruskalEtaSquared,2.291758e-04,23.0,Cramerv,0.617213,HAUTEUR_MAX,True
143,Ordinal('BDTOPO_BAT_MAX_HAUTEUR'),0.618584,0.219836,KruskalEtaSquared,2.279839e-04,24.0,Cramerv,0.673177,BDTOPO_BAT_MAX_HAUTEUR_MAX,True
144,Categorical('TXAB_VOR_MM_A_TXAB_VOR_MMAX_A'),0.567477,0.272943,KruskalEtaSquared,2.262552e-04,25.0,Cramerv,0.342760,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
145,Categorical('zone_vent_extinction_rate'),0.000000,0.377871,KruskalEtaSquared,2.150810e-04,26.0,Cramerv,0.373309,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
146,Ordinal('DISTANCE_213'),0.567477,0.228324,KruskalEtaSquared,1.974910e-04,27.0,Cramerv,0.502375,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
147,Ordinal('PROPORTION_21'),0.049653,0.605364,KruskalEtaSquared,1.925659e-04,28.0,Cramerv,0.364817,DISTANCE_213,True
148,Categorical('NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A'),0.567477,0.221305,KruskalEtaSquared,1.921855e-04,29.0,Cramerv,0.544836,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
149,Categorical('NBJTX0_MM_A_NBJTX0_MMAX_A'),0.567477,0.236099,KruskalEtaSquared,1.891952e-04,30.0,Cramerv,0.330653,TXAB_VOR_MM_A_TXAB_VOR_MMAX_A,True
150,Categorical('NBJRR50_MM_A_NBJRR50_MMAX_A'),0.567477,0.234486,KruskalEtaSquared,1.791375e-04,31.0,Cramerv,0.605462,DISTANCE_213,True
151,Ordinal('DISTANCE_411'),0.567477,0.237438,KruskalEtaSquared,1.733335e-04,32.0,Cramerv,0.242728,NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A,True
152,Ordinal('CARACT4'),0.000000,0.951494,KruskalEtaSquared,1.730273e-04,33.0,Cramerv,0.205333,DEROG12,True
153,Categorical('NBJRR10_MM_A_NBJRR10_MMAX_A'),0.567477,0.232329,KruskalEtaSquared,1.718095e-04,34.0,Cramerv,0.305561,NBJRR50_MM_A_NBJRR50_MMAX_A,True
154,Ordinal('DISTANCE_323'),0.567477,0.227702,KruskalEtaSquared,1.717891e-04,35.0,Cramerv,0.893887,DISTANCE_213,True
155,Categorical('NBJFXI3S28_MM_A_NBJFXI3S28_MMAX_A'),0.567477,0.287466,KruskalEtaSquared,1.679782e-04,36.0,Cramerv,0.492812,DISTANCE_323,True
156,Categorical('IND_REGION'),0.048519,0.330322,KruskalEtaSquared,1.673898e-04,37.0,Cramerv,0.236582,ZONE,True
157,Ordinal('DISTANCE_212'),0.567477,0.225405,KruskalEtaSquared,1.672684e-04,38.0,Cramerv,0.880310,DISTANCE_323,True
158,Categorical('IND_SNV_REGION'),0.048519,0.530360,KruskalEtaSquared,1.661646e-04,39.0,Cramerv,0.495098,IND_REGION,True
159,Categorical('LOG_REGION'),0.048519,0.385303,KruskalEtaSquared,1.607844e-04,40.0,Cramerv,0.396958,IND_SNV_REGION,True
160,Categorical('TN_VOR_MM_A_TN_VOR_MMAX_A'),0.567477,0.202729,KruskalEtaSquared,1.588151e-04,41.0,Cramerv,0.320212,NBJTX0_MM_A_NBJTX0_MMAX_A,True
161,Categorical('NBJFF16_MM_A_NBJFF16_MMAX_A'),0.567477,0.218011,KruskalEtaSquared,1.585929e-04,42.0,Cramerv,0.593049,NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A,True
162,Categorical('NBJTN5_MM_A_NBJTN5_MMAX_A'),0.567477,0.171701,KruskalEtaSquared,1.563590e-04,43.0,Cramerv,0.605600,NBJTX0_MM_A_NBJTX0_MMAX_A,True
163,Ordinal('DISTANCE_335'),0.567477,0.246047,KruskalEtaSquared,1.538005e-04,44.0,Cramerv,0.798592,DISTANCE_213,True
164,Categorical('RRAB_VOR_MM_A_RRAB_VOR_MMAX_A'),0.567477,0.277932,KruskalEtaSquared,1.500816e-04,45.0,Cramerv,0.589694,DISTANCE_323,True
165,Categorical('NBJFF10_MM_A_NBJFF10_MMAX_A'),0.567477,0.265569,KruskalEtaSquared,1.442555e-04,46.0,Cramerv,0.393039,NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A,True
166,Categorical('NBJFXY8_MM_A_NBJFXY8_MMAX_A'),0.567477,0.244115,KruskalEtaSquared,1.370522e-04,47.0,Cramerv,0.553077,DISTANCE_213,True
167,Ordinal('DISTANCE_334'),0.567477,0.290559,KruskalEtaSquared,1.367943e-04,48.0,Cramerv,0.724556,DISTANCE_212,True
168,Categorical('NBJRR30_MM_A_NBJRR30_MMAX_A'),0.567477,0.232306,KruskalEtaSquared,1.356326e-04,49.0,Cramerv,0.605871,NBJRR50_MM_A_NBJRR50_MMAX_A,True
169,Categorical('ADOSS'),0.000000,0.978820,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
170,Categorical('CARACT1'),0.012027,0.957802,KruskalEtaSquared,3.349533e-05,NaN,None,NaN,None,False
171,Categorical('CARACT3'),0.959888,0.040112,KruskalEtaSquared,NaN,NaN,None,NaN,None,False
172,Categorical('INDEM1'),0.000000,0.953547,KruskalEtaSquared,1.321980e-05,NaN,None,NaN,None,False
173,Categorical('TYPBAT1'),0.921098,0.049565,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
174,Categorical('FRCH1'),0.000000,0.962012,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
175,Categorical('FRCH2'),0.069058,0.468207,KruskalEtaSquared,2.300918e-05,NaN,None,NaN,None,False
176,Categorical('DEROG2'),0.000000,0.965975,KruskalEtaSquared,6.605135e-05,NaN,None,NaN,None,False
177,Categorical('DEROG3'),0.000000,0.979136,KruskalEtaSquared,7.510439e-05,NaN,None,NaN,None,False
178,Categorical('DEROG8'),0.000000,0.979370,KruskalEtaSquared,7.861749e-05,NaN,None,NaN,None,False
179,Categorical('KAPITAL34'),0.000000,0.963909,KruskalEtaSquared,0.000000e+00,NaN,None,NaN,None,False
180,Categorical('KAPITAL35'),0.000000,0.975939,KruskalEtaSquared,8.523457e-05,NaN,None,NaN,None,False
181,Categorical('RISK6'),0.069058,0.516482,KruskalEtaSquared,8.276585e-05,NaN,None,NaN,None,False
182,Categorical('RISK8'),0.069058,0.629226,KruskalEtaSquared,3.378335e-05,NaN,None,NaN,None,False
183,Categorical('RISK9'),0.069058,0.903691,KruskalEtaSquared,7.446206e-05,NaN,None,NaN,None,False
184,Categorical('RISK12'),0.069058,0.837491,KruskalEtaSquared,9.149855e-05,NaN,None,NaN,None,False
185,Categorical('RISK13'),0.407406,0.330560,KruskalEtaSquared,2.949253e-05,NaN,None,NaN,None,False
186,Categorical('EQUIPEMENT2'),0.228865,0.448102,KruskalEtaSquared,1.045231e-04,NaN,None,NaN,None,False
187,Categorical('EQUIPEMENT5'),0.394167,0.605833,KruskalEtaSquared,NaN,NaN,None,NaN,None,False
188,Categorical('ESPINSEE'),0.394167,0.605833,KruskalEtaSquared,NaN,NaN,None,NaN,None,False

In [12]:
best_features = selector.selected_features.names

## XGBoost + Optuna  *(unchanged objectives from `objectives.py`)*

The model search is the same as 2025 so any dev-metric delta is attributable to
the carving step, not the tuner. Drop `N_TRIALS` while iterating.

In [13]:
import optuna

from objectives import get_multiclass_objective

N_TRIALS = 300

objective = get_multiclass_objective(
    x_train[best_features],
    y_ord_train,
    x_dev[best_features],
    y_ord_dev,
    w_train=w_train,
    w_dev=w_dev,
)
# seeded so the tuning is reproducible: the split and every XGBoost estimator
# already use random_state=42, and carving is deterministic, so this is the last
# source of run-to-run variance.
study = optuna.create_study(
    direction="minimize", sampler=optuna.samplers.TPESampler(seed=42)
)
study.optimize(objective, n_trials=N_TRIALS)
study.best_params

[I 2026-09-01 09:11:17,187] A new study created in memory with name: no-name-146e93e7-4fc9-48cd-ab48-2f5601581d21

<repo>/.venv\Lib\site-packages\xgboost\core.py:751: UserWarning: [09:11:25] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

[I 2026-09-01 09:11:26,392] Trial 0 finished with value: 10.641719669532819 and parameters: {'objective': 'multi:softprob', 'n_estimators': 287, 'learning_rate': 0.9507192349792751, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.3248149123539492, 'colsample_bytree': 0.32479561626896214, 'colsample_bylevel': 0.24646688973455957, 'gamma': 8.661761457749352, 'alpha': 6.011150117432088, 'lambda': 7.080725777960454}. Best is trial 0 with value: 10.641719669532819.

[I 2026-09-01 09:11:30,938] Trial 1 finished with value: 10.42722139295433 and parameters: {'objective': 'multi:softprob', 'n_estimators': 110, 'learning_rate': 0.9699128611767781, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.3454599737656805, 'colsample_bytree': 0.34672360788274703, 'colsample_bylevel': 0.4433937943676302, 'gamma': 5.247564316322379, 'alpha': 4.319450186421157, 'lambda': 2.9122914019804194}. Best is trial 1 with value: 10.42722139295433.

[I 2026-09-01 09:11:43,480] Trial 2 finished with value: 1.7506374451340678 and parameters: {'objective': 'multi:softprob', 'n_estimators': 406, 'learning_rate': 0.13957991126597663, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.5648559873736287, 'colsample_bytree': 0.8281407691144109, 'colsample_bylevel': 0.3597390257266878, 'gamma': 5.142344384136116, 'alpha': 5.924145688620425, 'lambda': 0.46450412719997725}. Best is trial 2 with value: 1.7506374451340678.

[I 2026-09-01 09:11:52,448] Trial 3 finished with value: 1.0305912453564567 and parameters: {'objective': 'multi:softprob', 'n_estimators': 404, 'learning_rate': 0.17060707127492278, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.9725056264596474, 'colsample_bytree': 0.846717878493169, 'colsample_bylevel': 0.4436910153386966, 'gamma': 0.9767211400638387, 'alpha': 6.842330265121569, 'lambda': 4.4015249373960135}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:11:57,526] Trial 4 finished with value: 1.0870017473478817 and parameters: {'objective': 'multi:softprob', 'n_estimators': 161, 'learning_rate': 0.49522739242025904, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.40702398528001354, 'colsample_bytree': 0.7300178274831857, 'colsample_bylevel': 0.4493688608715288, 'gamma': 5.200680211778108, 'alpha': 5.4671027934327965, 'lambda': 1.8485445552552704}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:12:12,823] Trial 5 finished with value: 5.114531520808638 and parameters: {'objective': 'multi:softprob', 'n_estimators': 585, 'learning_rate': 0.7751553100787785, 'max_depth': 10, 'min_child_weight': 18, 'subsample': 0.6783199830488682, 'colsample_bytree': 0.9374993880184934, 'colsample_bylevel': 0.2707940016415356, 'gamma': 1.959828624191452, 'alpha': 0.45227288910538066, 'lambda': 3.2533033076326436}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:12:26,008] Trial 6 finished with value: 3.195961735261897 and parameters: {'objective': 'multi:softprob', 'n_estimators': 294, 'learning_rate': 0.2714218968707185, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.4247476077499046, 'colsample_bytree': 0.6341568665265989, 'colsample_bylevel': 0.31273937997981016, 'gamma': 8.021969807540398, 'alpha': 0.7455064367977082, 'lambda': 9.868869366005173}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:12:36,641] Trial 7 finished with value: 1.1344555863145522 and parameters: {'objective': 'multi:softprob', 'n_estimators': 486, 'learning_rate': 0.19879580996601898, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.7654858750780937, 'colsample_bytree': 0.7832057344327898, 'colsample_bylevel': 0.8170162773487566, 'gamma': 0.7404465173409036, 'alpha': 3.5846572854427263, 'lambda': 1.1586905952512971}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:12:54,131] Trial 8 finished with value: 3.94458120355032 and parameters: {'objective': 'multi:softprob', 'n_estimators': 532, 'learning_rate': 0.6233357970148752, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.4487858573725298, 'colsample_bytree': 0.46014665762139767, 'colsample_bylevel': 0.7836849426704513, 'gamma': 6.3755747135521315, 'alpha': 8.872127425763265, 'lambda': 4.722149251619493}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:13:01,209] Trial 9 finished with value: 4.184697326741896 and parameters: {'objective': 'multi:softprob', 'n_estimators': 159, 'learning_rate': 0.7132734627442727, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.8167737439636489, 'colsample_bytree': 0.5950364770915126, 'colsample_bylevel': 0.6181862635055952, 'gamma': 4.275410183585496, 'alpha': 0.2541912674409519, 'lambda': 1.0789142699330445}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:13:20,045] Trial 10 finished with value: 1.0327348311302014 and parameters: {'objective': 'multi:softprob', 'n_estimators': 374, 'learning_rate': 0.006096583237521769, 'max_depth': 6, 'min_child_weight': 14, 'subsample': 0.9814131532569819, 'colsample_bytree': 0.23098015996894666, 'colsample_bylevel': 0.9678165967563358, 'gamma': 2.8905925958373584, 'alpha': 9.51307795498635, 'lambda': 6.4371273662382364}. Best is trial 3 with value: 1.0305912453564567.

[I 2026-09-01 09:13:36,655] Trial 11 finished with value: 1.0154633555700099 and parameters: {'objective': 'multi:softprob', 'n_estimators': 372, 'learning_rate': 0.008649137766908316, 'max_depth': 5, 'min_child_weight': 14, 'subsample': 0.9971846460001386, 'colsample_bytree': 0.22145059055877642, 'colsample_bylevel': 0.9909653391662029, 'gamma': 2.1785358383633726, 'alpha': 9.600267336039376, 'lambda': 6.002316298303307}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:13:50,847] Trial 12 finished with value: 3.2362318196414077 and parameters: {'objective': 'multi:softprob', 'n_estimators': 408, 'learning_rate': 0.3744406251821827, 'max_depth': 4, 'min_child_weight': 16, 'subsample': 0.9932801402878824, 'colsample_bytree': 0.9782753057038069, 'colsample_bylevel': 0.6145990427879906, 'gamma': 0.2184630777707024, 'alpha': 7.726591734183185, 'lambda': 5.765954901843468}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:14:07,035] Trial 13 finished with value: 1.036190435062365 and parameters: {'objective': 'multi:softprob', 'n_estimators': 304, 'learning_rate': 0.0025349543919357563, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.8806318315090284, 'colsample_bytree': 0.4883554834611627, 'colsample_bylevel': 0.9760199384988906, 'gamma': 2.1363768556891767, 'alpha': 7.803096238541361, 'lambda': 8.796139267265122}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:14:21,918] Trial 14 finished with value: 1.6091268304080821 and parameters: {'objective': 'multi:softprob', 'n_estimators': 468, 'learning_rate': 0.13564255010788662, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.9187069578395135, 'colsample_bytree': 0.22682117975105842, 'colsample_bylevel': 0.6163523606608526, 'gamma': 3.1662617341164774, 'alpha': 7.779304623466966, 'lambda': 4.48548056890076}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:14:37,360] Trial 15 finished with value: 3.9630205473686733 and parameters: {'objective': 'multi:softprob', 'n_estimators': 347, 'learning_rate': 0.3184235808607091, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.2037920957224718, 'colsample_bytree': 0.5336117879385596, 'colsample_bylevel': 0.7843238346074204, 'gamma': 1.146517136090952, 'alpha': 9.262177757917913, 'lambda': 7.6054244598531895}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:14:45,711] Trial 16 finished with value: 1.7127945961030755 and parameters: {'objective': 'multi:softprob', 'n_estimators': 255, 'learning_rate': 0.43453267747711666, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.7417619680780085, 'colsample_bytree': 0.8758895902324695, 'colsample_bylevel': 0.8812139089520454, 'gamma': 3.073015616642768, 'alpha': 9.989031619779839, 'lambda': 4.9576906314126745}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:15:06,334] Trial 17 finished with value: 2.6573530773163196 and parameters: {'objective': 'multi:softprob', 'n_estimators': 447, 'learning_rate': 0.11162189185775512, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.86169933479121, 'colsample_bytree': 0.38793861986590483, 'colsample_bylevel': 0.5219350868734808, 'gamma': 1.5795130006005613, 'alpha': 7.100822496348982, 'lambda': 3.6572438888867453}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:15:14,126] Trial 18 finished with value: 1.2186695975916875 and parameters: {'objective': 'multi:softprob', 'n_estimators': 222, 'learning_rate': 0.22462916708008454, 'max_depth': 2, 'min_child_weight': 9, 'subsample': 0.6565767273232013, 'colsample_bytree': 0.691853062570388, 'colsample_bylevel': 0.7162010845839389, 'gamma': 0.2927735600047696, 'alpha': 3.4065288398379314, 'lambda': 7.97152583468206}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:15:28,367] Trial 19 finished with value: 2.116564124011974 and parameters: {'objective': 'multi:softprob', 'n_estimators': 370, 'learning_rate': 0.08197296680943317, 'max_depth': 7, 'min_child_weight': 17, 'subsample': 0.9424822945862977, 'colsample_bytree': 0.41071583329859995, 'colsample_bylevel': 0.697524214362791, 'gamma': 9.813130867582933, 'alpha': 2.390425939608689, 'lambda': 5.814384057023714}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:15:45,593] Trial 20 finished with value: 3.1292463543686058 and parameters: {'objective': 'multi:softprob', 'n_estimators': 545, 'learning_rate': 0.4703323451407776, 'max_depth': 4, 'min_child_weight': 14, 'subsample': 0.8322299350787241, 'colsample_bytree': 0.5700096057213453, 'colsample_bylevel': 0.5226785188938063, 'gamma': 3.918396199941158, 'alpha': 8.624808991805704, 'lambda': 2.3536652308037214}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:16:01,200] Trial 21 finished with value: 1.4351170259852115 and parameters: {'objective': 'multi:softprob', 'n_estimators': 349, 'learning_rate': 0.04447448241620523, 'max_depth': 5, 'min_child_weight': 13, 'subsample': 0.9852963562294018, 'colsample_bytree': 0.20550673835818667, 'colsample_bylevel': 0.9771006573810361, 'gamma': 2.815531632433655, 'alpha': 9.827684441673252, 'lambda': 6.3303861461150985}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:16:20,467] Trial 22 finished with value: 1.0255564176538838 and parameters: {'objective': 'multi:softprob', 'n_estimators': 372, 'learning_rate': 0.004379352099612292, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.9273593939191052, 'colsample_bytree': 0.28113520612000825, 'colsample_bylevel': 0.8659449625788173, 'gamma': 2.3794183111879375, 'alpha': 6.824286003707776, 'lambda': 6.606032986471551}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:16:37,023] Trial 23 finished with value: 2.9846428932345996 and parameters: {'objective': 'multi:softprob', 'n_estimators': 413, 'learning_rate': 0.17877794818363188, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.9185322963688836, 'colsample_bytree': 0.28064930362901563, 'colsample_bylevel': 0.9036687282871938, 'gamma': 1.9449438478338206, 'alpha': 6.792111554276067, 'lambda': 4.008784670231632}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:16:55,905] Trial 24 finished with value: 2.3177758264702124 and parameters: {'objective': 'multi:softprob', 'n_estimators': 437, 'learning_rate': 0.08398608775227244, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.7645034784841658, 'colsample_bytree': 0.2679993951093913, 'colsample_bylevel': 0.8853060911656067, 'gamma': 1.1052517439168605, 'alpha': 4.9970107762072224, 'lambda': 5.4009440115916325}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:17:10,167] Trial 25 finished with value: 2.6863627660305927 and parameters: {'objective': 'multi:softprob', 'n_estimators': 498, 'learning_rate': 0.2825337610271432, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.9229185099732528, 'colsample_bytree': 0.3155477576109343, 'colsample_bylevel': 0.8348368312985361, 'gamma': 3.8966826478325496, 'alpha': 6.747851138934437, 'lambda': 6.9232511270529775}. Best is trial 11 with value: 1.0154633555700099.

[I 2026-09-01 09:17:22,348] Trial 26 finished with value: 0.9820816019988591 and parameters: {'objective': 'multi:softprob', 'n_estimators': 325, 'learning_rate': 0.006662544416796225, 'max_depth': 3, 'min_child_weight': 16, 'subsample': 0.8677983793850796, 'colsample_bytree': 0.42577943588597944, 'colsample_bylevel': 0.7052667842368143, 'gamma': 2.312687995488208, 'alpha': 8.362541307915398, 'lambda': 8.15981592450115}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:17:34,825] Trial 27 finished with value: 1.0161888202067533 and parameters: {'objective': 'multi:softprob', 'n_estimators': 329, 'learning_rate': 0.002845291415089093, 'max_depth': 3, 'min_child_weight': 16, 'subsample': 0.8095849972626379, 'colsample_bytree': 0.4069972238430617, 'colsample_bylevel': 0.7184208384150417, 'gamma': 2.4253720290285474, 'alpha': 8.398384561816133, 'lambda': 8.429855559572378}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:17:44,130] Trial 28 finished with value: 1.131144145474233 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.07353194694367211, 'max_depth': 3, 'min_child_weight': 16, 'subsample': 0.6686821543915429, 'colsample_bytree': 0.4517185811466944, 'colsample_bylevel': 0.6995355368549305, 'gamma': 3.7195034331262784, 'alpha': 8.452443477951755, 'lambda': 8.549257553944926}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:17:54,276] Trial 29 finished with value: 1.396486855621277 and parameters: {'objective': 'multi:softprob', 'n_estimators': 329, 'learning_rate': 0.22917975319942097, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.5724425338482402, 'colsample_bytree': 0.366784777674934, 'colsample_bylevel': 0.6698815297775653, 'gamma': 7.285146928910762, 'alpha': 8.388958856285123, 'lambda': 9.397414913804228}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:18:05,700] Trial 30 finished with value: 1.44787366455573 and parameters: {'objective': 'multi:softprob', 'n_estimators': 268, 'learning_rate': 0.07483565448035713, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.8131416903881815, 'colsample_bytree': 0.5130159587857631, 'colsample_bylevel': 0.7403884492796042, 'gamma': 4.3954095574574525, 'alpha': 8.89869382191918, 'lambda': 7.6729090097394534}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:18:21,157] Trial 31 finished with value: 1.0427956061246193 and parameters: {'objective': 'multi:softprob', 'n_estimators': 328, 'learning_rate': 0.011344660966307825, 'max_depth': 5, 'min_child_weight': 12, 'subsample': 0.876430966439472, 'colsample_bytree': 0.3031123203765251, 'colsample_bylevel': 0.9468930786484895, 'gamma': 2.484419122378271, 'alpha': 7.7968498268020054, 'lambda': 7.0697420417902554}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:18:34,453] Trial 32 finished with value: 1.0020909888060894 and parameters: {'objective': 'multi:softprob', 'n_estimators': 378, 'learning_rate': 0.01591622366152602, 'max_depth': 3, 'min_child_weight': 15, 'subsample': 0.7270130448512133, 'colsample_bytree': 0.41918723986836204, 'colsample_bylevel': 0.8516419701896377, 'gamma': 1.710227055636151, 'alpha': 7.4166124950139425, 'lambda': 8.632305102278734}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:18:44,003] Trial 33 finished with value: 1.186976459892315 and parameters: {'objective': 'multi:softprob', 'n_estimators': 301, 'learning_rate': 0.1363637255592323, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.7205560301739306, 'colsample_bytree': 0.42345620105579584, 'colsample_bylevel': 0.9235608814198608, 'gamma': 1.5883660380298494, 'alpha': 5.976909425138048, 'lambda': 8.794356312992281}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:18:57,198] Trial 34 finished with value: 1.234701189535219 and parameters: {'objective': 'multi:softprob', 'n_estimators': 385, 'learning_rate': 0.067035728675896, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 0.5753937115927947, 'colsample_bytree': 0.3400258226895042, 'colsample_bylevel': 0.7608484710017734, 'gamma': 3.428663371923009, 'alpha': 9.196683068285257, 'lambda': 8.178472129610368}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:08,861] Trial 35 finished with value: 1.6185400686354567 and parameters: {'objective': 'multi:softprob', 'n_estimators': 330, 'learning_rate': 0.1443548238930789, 'max_depth': 3, 'min_child_weight': 13, 'subsample': 0.8111433079596064, 'colsample_bytree': 0.3694086313280093, 'colsample_bylevel': 0.8197560865497734, 'gamma': 1.5163107685464783, 'alpha': 8.349543700833484, 'lambda': 9.742567256988687}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:17,763] Trial 36 finished with value: 1.1581789216105627 and parameters: {'objective': 'multi:softprob', 'n_estimators': 187, 'learning_rate': 0.056392042949337126, 'max_depth': 4, 'min_child_weight': 18, 'subsample': 0.6095484182965927, 'colsample_bytree': 0.4566146258250779, 'colsample_bylevel': 0.6456685444720514, 'gamma': 4.897498272646908, 'alpha': 6.318780113863379, 'lambda': 9.315426420999806}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:32,460] Trial 37 finished with value: 1.8227498584494255 and parameters: {'objective': 'multi:softprob', 'n_estimators': 440, 'learning_rate': 0.17143649575741804, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7055358492164046, 'colsample_bytree': 0.5480145949321694, 'colsample_bylevel': 0.20116000943420292, 'gamma': 2.5516115377310538, 'alpha': 7.281680726123749, 'lambda': 7.486665046576807}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:40,048] Trial 38 finished with value: 0.9901573550910219 and parameters: {'objective': 'multi:softprob', 'n_estimators': 265, 'learning_rate': 0.10634136206233005, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.7821246391730631, 'colsample_bytree': 0.6459760973311839, 'colsample_bylevel': 0.8542426114883723, 'gamma': 0.8373841912706976, 'alpha': 8.106119023291692, 'lambda': 8.304916325089117}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:46,694] Trial 39 finished with value: 1.420651185054577 and parameters: {'objective': 'multi:softprob', 'n_estimators': 208, 'learning_rate': 0.9108363943732133, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.5189891799573453, 'colsample_bytree': 0.6499583189231988, 'colsample_bylevel': 0.9977129126227249, 'gamma': 0.5298938273521214, 'alpha': 5.4689352045947714, 'lambda': 9.155488721691487}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:51,640] Trial 40 finished with value: 0.9923635980016833 and parameters: {'objective': 'multi:softprob', 'n_estimators': 111, 'learning_rate': 0.2563678919645983, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.7702508337261109, 'colsample_bytree': 0.7801210053283885, 'colsample_bylevel': 0.8478729401628087, 'gamma': 0.09829525750239787, 'alpha': 7.394232124602217, 'lambda': 7.378612208717888}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:19:57,196] Trial 41 finished with value: 1.0316753379451076 and parameters: {'objective': 'multi:softprob', 'n_estimators': 137, 'learning_rate': 0.2657628427499037, 'max_depth': 1, 'min_child_weight': 13, 'subsample': 0.7756876314612403, 'colsample_bytree': 0.7694324995664807, 'colsample_bylevel': 0.8477914302673861, 'gamma': 0.8584088880567915, 'alpha': 7.63241961323501, 'lambda': 7.945381264564716}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:02,691] Trial 42 finished with value: 1.0290666600078027 and parameters: {'objective': 'multi:softprob', 'n_estimators': 131, 'learning_rate': 0.3410477139732795, 'max_depth': 1, 'min_child_weight': 14, 'subsample': 0.6391103894176287, 'colsample_bytree': 0.8833030221387619, 'colsample_bylevel': 0.9253032192654113, 'gamma': 0.13400264238889384, 'alpha': 6.394243434714844, 'lambda': 7.303359726073222}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:08,306] Trial 43 finished with value: 1.0555879409163231 and parameters: {'objective': 'multi:softprob', 'n_estimators': 105, 'learning_rate': 0.2155717677214283, 'max_depth': 2, 'min_child_weight': 1, 'subsample': 0.7076848312950103, 'colsample_bytree': 0.7885094238307878, 'colsample_bylevel': 0.7811281624045852, 'gamma': 1.3812320090765287, 'alpha': 7.368578953499391, 'lambda': 6.822286925605219}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:16,304] Trial 44 finished with value: 0.9974903727895291 and parameters: {'objective': 'multi:softprob', 'n_estimators': 275, 'learning_rate': 0.11407943055147295, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.8443815936395486, 'colsample_bytree': 0.7180126498133422, 'colsample_bylevel': 0.8098171429602001, 'gamma': 0.7187592285545388, 'alpha': 9.520418226022468, 'lambda': 6.140818226258726}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:24,050] Trial 45 finished with value: 1.0019435322872545 and parameters: {'objective': 'multi:softprob', 'n_estimators': 257, 'learning_rate': 0.12500205254525754, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.7810081350844731, 'colsample_bytree': 0.710017300401372, 'colsample_bylevel': 0.8000083388449306, 'gamma': 0.007685883296506227, 'alpha': 8.045533100925452, 'lambda': 8.237587505552346}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:32,046] Trial 46 finished with value: 1.1237389522739292 and parameters: {'objective': 'multi:softprob', 'n_estimators': 277, 'learning_rate': 0.4003206138948437, 'max_depth': 1, 'min_child_weight': 19, 'subsample': 0.8603956302779461, 'colsample_bytree': 0.7044057518877908, 'colsample_bylevel': 0.8056023369135932, 'gamma': 0.6715609554866433, 'alpha': 9.017104583190722, 'lambda': 5.381878273124078}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:38,625] Trial 47 finished with value: 1.0254868114484017 and parameters: {'objective': 'multi:softprob', 'n_estimators': 194, 'learning_rate': 0.25219348527510055, 'max_depth': 1, 'min_child_weight': 18, 'subsample': 0.7674305744296311, 'colsample_bytree': 0.7481744258711538, 'colsample_bylevel': 0.5620502780529941, 'gamma': 0.5614458825252681, 'alpha': 9.522270266122437, 'lambda': 7.264553857403258}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:47,363] Trial 48 finished with value: 1.1519301653381093 and parameters: {'objective': 'multi:softprob', 'n_estimators': 253, 'learning_rate': 0.12856792861657246, 'max_depth': 2, 'min_child_weight': 19, 'subsample': 0.8492901502609798, 'colsample_bytree': 0.6339538130413742, 'colsample_bylevel': 0.756185558864476, 'gamma': 0.9884493201062937, 'alpha': 8.023526540084065, 'lambda': 8.156302448246626}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:20:53,364] Trial 49 finished with value: 1.0237687868500065 and parameters: {'objective': 'multi:softprob', 'n_estimators': 165, 'learning_rate': 0.30867339722978826, 'max_depth': 1, 'min_child_weight': 17, 'subsample': 0.8888801756535604, 'colsample_bytree': 0.8284292730007585, 'colsample_bylevel': 0.7933015033568666, 'gamma': 0.20443359746669507, 'alpha': 8.107404052831292, 'lambda': 9.991688193136508}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:21:02,764] Trial 50 finished with value: 1.2640933426391796 and parameters: {'objective': 'multi:softprob', 'n_estimators': 287, 'learning_rate': 0.1889373234102309, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.7878200017478411, 'colsample_bytree': 0.6607469346094093, 'colsample_bylevel': 0.37779869865787874, 'gamma': 0.14101438355819168, 'alpha': 8.734265695863751, 'lambda': 6.24332419454011}. Best is trial 26 with value: 0.9820816019988591.

[I 2026-09-01 09:21:09,981] Trial 51 finished with value: 0.9788304075998752 and parameters: {'objective': 'multi:softprob', 'n_estimators': 238, 'learning_rate': 0.10785845219339571, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.7331976768154526, 'colsample_bytree': 0.6040016521154984, 'colsample_bylevel': 0.8248575065036738, 'gamma': 1.7333936601912399, 'alpha': 7.354557728978877, 'lambda': 8.71248000919956}. Best is trial 51 with value: 0.9788304075998752.

[I 2026-09-01 09:21:17,740] Trial 52 finished with value: 0.9795323033427071 and parameters: {'objective': 'multi:softprob', 'n_estimators': 239, 'learning_rate': 0.1232222148924969, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.7451639828485886, 'colsample_bytree': 0.6114715116279893, 'colsample_bylevel': 0.8234188059225703, 'gamma': 1.1914582184587152, 'alpha': 8.075439708733203, 'lambda': 9.033770343500096}. Best is trial 51 with value: 0.9788304075998752.

[I 2026-09-01 09:21:25,085] Trial 53 finished with value: 0.9724958080913599 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.10073784604700614, 'max_depth': 1, 'min_child_weight': 15, 'subsample': 0.6874732195007909, 'colsample_bytree': 0.6105301035513465, 'colsample_bylevel': 0.8906081395622552, 'gamma': 1.229862677333415, 'alpha': 6.36489080046559, 'lambda': 9.07093101733085}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:21:33,426] Trial 54 finished with value: 1.2135186415890191 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.17077776493507013, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.6936816278795849, 'colsample_bytree': 0.6124732416285608, 'colsample_bylevel': 0.8998805885203006, 'gamma': 1.9165600282812116, 'alpha': 5.181252232378258, 'lambda': 8.942248368205206}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:21:39,703] Trial 55 finished with value: 1.0137996052743086 and parameters: {'objective': 'multi:softprob', 'n_estimators': 176, 'learning_rate': 0.20862751077538255, 'max_depth': 1, 'min_child_weight': 12, 'subsample': 0.6172151681767948, 'colsample_bytree': 0.5954459726929793, 'colsample_bylevel': 0.9464262529505721, 'gamma': 1.25164632874083, 'alpha': 6.318209494567758, 'lambda': 9.555676253608667}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:21:47,950] Trial 56 finished with value: 1.7759996324411493 and parameters: {'objective': 'multi:softprob', 'n_estimators': 219, 'learning_rate': 0.5210854060035117, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.7416942965155885, 'colsample_bytree': 0.6747348742765199, 'colsample_bylevel': 0.8513255874960332, 'gamma': 1.8665897283806507, 'alpha': 7.053838301236865, 'lambda': 9.090600400095271}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:22:10,783] Trial 57 finished with value: 3.35997165974615 and parameters: {'objective': 'multi:softprob', 'n_estimators': 303, 'learning_rate': 0.10199419086552335, 'max_depth': 10, 'min_child_weight': 14, 'subsample': 0.6740327693265394, 'colsample_bytree': 0.5469755698852781, 'colsample_bylevel': 0.8785945574183919, 'gamma': 1.2190276322735802, 'alpha': 5.767796272289665, 'lambda': 7.853080833461051}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:22:15,964] Trial 58 finished with value: 0.9779089578265266 and parameters: {'objective': 'multi:softprob', 'n_estimators': 136, 'learning_rate': 0.040962096583213314, 'max_depth': 1, 'min_child_weight': 11, 'subsample': 0.3114005749101698, 'colsample_bytree': 0.5041463344475374, 'colsample_bylevel': 0.7421138594900131, 'gamma': 2.8170566044900696, 'alpha': 4.473465278212537, 'lambda': 8.44050769951842}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:22:24,137] Trial 59 finished with value: 1.0014763203555666 and parameters: {'objective': 'multi:softprob', 'n_estimators': 232, 'learning_rate': 0.03622233032137148, 'max_depth': 2, 'min_child_weight': 11, 'subsample': 0.25744863783646366, 'colsample_bytree': 0.5750792181624897, 'colsample_bylevel': 0.733695525775369, 'gamma': 2.894575608953611, 'alpha': 3.1540421767083235, 'lambda': 8.49260235026669}. Best is trial 53 with value: 0.9724958080913599.

[I 2026-09-01 09:22:30,516] Trial 60 finished with value: 0.9701966486927402 and parameters: {'objective': 'multi:softprob', 'n_estimators': 201, 'learning_rate': 0.04284531868686589, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.47530106316638343, 'colsample_bytree': 0.504790005952271, 'colsample_bylevel': 0.6570226296435215, 'gamma': 3.2804529858396068, 'alpha': 4.49631177546976, 'lambda': 9.53021883493181}. Best is trial 60 with value: 0.9701966486927402.

[I 2026-09-01 09:22:37,217] Trial 61 finished with value: 0.9697747381475696 and parameters: {'objective': 'multi:softprob', 'n_estimators': 208, 'learning_rate': 0.04152655904456754, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.3773434019382587, 'colsample_bytree': 0.5088249670613089, 'colsample_bylevel': 0.6775796717297176, 'gamma': 3.3371955349507063, 'alpha': 4.45482655263148, 'lambda': 9.47144710067213}. Best is trial 61 with value: 0.9697747381475696.

[I 2026-09-01 09:22:43,946] Trial 62 finished with value: 0.9691094221425417 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.03997959017957966, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.3881075132661084, 'colsample_bytree': 0.4991920409474703, 'colsample_bylevel': 0.5836283148839861, 'gamma': 3.3012307996553654, 'alpha': 4.409719373853973, 'lambda': 9.63628618024613}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:22:50,541] Trial 63 finished with value: 0.9717023558782057 and parameters: {'objective': 'multi:softprob', 'n_estimators': 204, 'learning_rate': 0.03941443620528893, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.37469192375491217, 'colsample_bytree': 0.4920792630052554, 'colsample_bylevel': 0.5710735242646948, 'gamma': 3.3648526294246732, 'alpha': 4.369822933042578, 'lambda': 9.645213217554609}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:22:57,148] Trial 64 finished with value: 0.9728990447059346 and parameters: {'objective': 'multi:softprob', 'n_estimators': 198, 'learning_rate': 0.04213573758866206, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.3693147216285625, 'colsample_bytree': 0.4975491017846484, 'colsample_bylevel': 0.5383009783968378, 'gamma': 3.267217416657076, 'alpha': 4.198407036782236, 'lambda': 9.714095989289774}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:04,700] Trial 65 finished with value: 0.9982056731560647 and parameters: {'objective': 'multi:softprob', 'n_estimators': 203, 'learning_rate': 0.04454211043591181, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.342364683730998, 'colsample_bytree': 0.4936712276363771, 'colsample_bylevel': 0.5605865621357388, 'gamma': 3.399376111523956, 'alpha': 3.8086325346924976, 'lambda': 9.567310123335169}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:10,345] Trial 66 finished with value: 0.9702136919904946 and parameters: {'objective': 'multi:softprob', 'n_estimators': 145, 'learning_rate': 0.04309191357637303, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.404092357103359, 'colsample_bytree': 0.5099989920325451, 'colsample_bylevel': 0.5688855116938982, 'gamma': 4.701196185393253, 'alpha': 4.560324544916568, 'lambda': 9.865450388460621}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:17,141] Trial 67 finished with value: 1.0124046517478693 and parameters: {'objective': 'multi:softprob', 'n_estimators': 159, 'learning_rate': 0.07414024274152853, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.3795329145041807, 'colsample_bytree': 0.47603037152354066, 'colsample_bylevel': 0.4663392731088878, 'gamma': 4.59833483541244, 'alpha': 4.481334187013998, 'lambda': 9.769976010101118}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:23,241] Trial 68 finished with value: 1.0034903008613136 and parameters: {'objective': 'multi:softprob', 'n_estimators': 176, 'learning_rate': 0.15020820952108888, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.43876771951489035, 'colsample_bytree': 0.5248822890310485, 'colsample_bylevel': 0.5709475734324736, 'gamma': 5.733531394840584, 'alpha': 3.9830613031088715, 'lambda': 9.353660907755033}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:30,051] Trial 69 finished with value: 0.9903356884622506 and parameters: {'objective': 'multi:softprob', 'n_estimators': 151, 'learning_rate': 0.04260114025321803, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.49836842388031966, 'colsample_bytree': 0.4734187939095989, 'colsample_bylevel': 0.5094591497821648, 'gamma': 5.7811442902266865, 'alpha': 2.8994826853019933, 'lambda': 9.934199815932269}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:36,782] Trial 70 finished with value: 0.9788851386531549 and parameters: {'objective': 'multi:softprob', 'n_estimators': 206, 'learning_rate': 0.08170781633312904, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.37363075834684223, 'colsample_bytree': 0.5718334543142957, 'colsample_bylevel': 0.5923927376043184, 'gamma': 4.183542159111628, 'alpha': 1.777452692245896, 'lambda': 9.662930954184386}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:42,268] Trial 71 finished with value: 0.98522940893399 and parameters: {'objective': 'multi:softprob', 'n_estimators': 137, 'learning_rate': 0.03598584393102784, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.29388455672875896, 'colsample_bytree': 0.5065277000865984, 'colsample_bylevel': 0.6590946259421605, 'gamma': 3.3424814396452027, 'alpha': 4.522686142551513, 'lambda': 9.292363348687164}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:48,621] Trial 72 finished with value: 0.9744774827205941 and parameters: {'objective': 'multi:softprob', 'n_estimators': 183, 'learning_rate': 0.03770951915359518, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.40091250666033595, 'colsample_bytree': 0.5438979676760627, 'colsample_bylevel': 0.6274677912542587, 'gamma': 3.64154257724885, 'alpha': 4.852850950619228, 'lambda': 9.524633802244896}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:23:55,087] Trial 73 finished with value: 0.9759061396005208 and parameters: {'objective': 'multi:softprob', 'n_estimators': 186, 'learning_rate': 0.08948912176490394, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.46615536041778227, 'colsample_bytree': 0.5427538386952301, 'colsample_bylevel': 0.6336157357098284, 'gamma': 3.7504886389808316, 'alpha': 4.888617261684437, 'lambda': 9.957614139148792}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:03,111] Trial 74 finished with value: 0.9797157157683563 and parameters: {'objective': 'multi:softprob', 'n_estimators': 217, 'learning_rate': 0.026270792974161752, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.41081757697153515, 'colsample_bytree': 0.44024726887573745, 'colsample_bylevel': 0.5962916216212201, 'gamma': 4.902451124370252, 'alpha': 3.936948024802263, 'lambda': 9.561747239620455}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:09,220] Trial 75 finished with value: 0.9748702876177117 and parameters: {'objective': 'multi:softprob', 'n_estimators': 177, 'learning_rate': 0.056621717645448336, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.3758552766501922, 'colsample_bytree': 0.5572112894189177, 'colsample_bylevel': 0.6815144309631689, 'gamma': 4.180041329397054, 'alpha': 4.937280419177934, 'lambda': 8.922572469270376}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:17,113] Trial 76 finished with value: 1.1591894725210055 and parameters: {'objective': 'multi:softprob', 'n_estimators': 194, 'learning_rate': 0.15850517979860754, 'max_depth': 2, 'min_child_weight': 2, 'subsample': 0.47394887119094564, 'colsample_bytree': 0.518493574132973, 'colsample_bylevel': 0.4982450697753637, 'gamma': 3.137608329096387, 'alpha': 4.159215313805136, 'lambda': 9.260223487277349}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:24,250] Trial 77 finished with value: 1.065258913602258 and parameters: {'objective': 'multi:softprob', 'n_estimators': 219, 'learning_rate': 0.0020472006446866364, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.3929668133272599, 'colsample_bytree': 0.4715824153444201, 'colsample_bylevel': 0.5326022269597372, 'gamma': 3.565397842696301, 'alpha': 3.5822938448631474, 'lambda': 9.591556721707647}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:30,008] Trial 78 finished with value: 0.9836281743585691 and parameters: {'objective': 'multi:softprob', 'n_estimators': 148, 'learning_rate': 0.06878149944187832, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.25081882769452357, 'colsample_bytree': 0.38658660342427414, 'colsample_bylevel': 0.3898724141241397, 'gamma': 4.038564609465335, 'alpha': 5.386820296181217, 'lambda': 8.782367791267076}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:35,831] Trial 79 finished with value: 0.9968111604049987 and parameters: {'objective': 'multi:softprob', 'n_estimators': 116, 'learning_rate': 0.09423366120277565, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.35755478183509976, 'colsample_bytree': 0.48776509559468395, 'colsample_bylevel': 0.4837028913182816, 'gamma': 4.686161265343925, 'alpha': 4.682609012723676, 'lambda': 9.11558468125877}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:43,122] Trial 80 finished with value: 0.9740064014891386 and parameters: {'objective': 'multi:softprob', 'n_estimators': 249, 'learning_rate': 0.025612546736316494, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.42603162757613, 'colsample_bytree': 0.44177176873542856, 'colsample_bylevel': 0.5411456172410194, 'gamma': 5.4551472024028165, 'alpha': 4.198845986705965, 'lambda': 0.3120445725745382}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:50,575] Trial 81 finished with value: 0.9748515034674715 and parameters: {'objective': 'multi:softprob', 'n_estimators': 254, 'learning_rate': 0.02577679700806757, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.41977291853033916, 'colsample_bytree': 0.4452149517685928, 'colsample_bylevel': 0.5404437368801515, 'gamma': 6.732864269651007, 'alpha': 4.157233006903935, 'lambda': 0.2677050842131039}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:24:56,610] Trial 82 finished with value: 0.9836315011070489 and parameters: {'objective': 'multi:softprob', 'n_estimators': 167, 'learning_rate': 0.026051086279141197, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.33038056361756973, 'colsample_bytree': 0.5324183098711428, 'colsample_bylevel': 0.5990309001286493, 'gamma': 5.357552398022053, 'alpha': 3.469606888249721, 'lambda': 0.8108509125315475}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:03,229] Trial 83 finished with value: 0.9757811809719099 and parameters: {'objective': 'multi:softprob', 'n_estimators': 202, 'learning_rate': 0.07423942807815785, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.5229854309476016, 'colsample_bytree': 0.5795296733015057, 'colsample_bylevel': 0.6317623894565173, 'gamma': 5.403509290738967, 'alpha': 4.755811202116994, 'lambda': 9.996034601426198}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:10,280] Trial 84 finished with value: 0.9703434878885061 and parameters: {'objective': 'multi:softprob', 'n_estimators': 228, 'learning_rate': 0.05532211236129478, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.4424268905976165, 'colsample_bytree': 0.4901568185816916, 'colsample_bylevel': 0.4385379624387963, 'gamma': 2.626540102237877, 'alpha': 5.614874634251147, 'lambda': 2.481768595451073}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:18,636] Trial 85 finished with value: 1.0951213506046154 and parameters: {'objective': 'multi:softprob', 'n_estimators': 228, 'learning_rate': 0.0001312799209029214, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.43906141000168386, 'colsample_bytree': 0.4010908818221801, 'colsample_bylevel': 0.42576051873065407, 'gamma': 2.149889486743043, 'alpha': 5.6074821875152745, 'lambda': 1.8508394222442055}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:25,882] Trial 86 finished with value: 0.9768224986248153 and parameters: {'objective': 'multi:softprob', 'n_estimators': 246, 'learning_rate': 0.0609363185680144, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.47377229438600443, 'colsample_bytree': 0.4382565733113884, 'colsample_bylevel': 0.4407711730716082, 'gamma': 2.6802712091152197, 'alpha': 5.256630971747361, 'lambda': 2.6100669385289303}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:41,923] Trial 87 finished with value: 1.4646702327432193 and parameters: {'objective': 'multi:softprob', 'n_estimators': 600, 'learning_rate': 0.14034839113652053, 'max_depth': 2, 'min_child_weight': 1, 'subsample': 0.35542109124781696, 'colsample_bytree': 0.4610721827815553, 'colsample_bylevel': 0.5461193354476147, 'gamma': 6.028338219243936, 'alpha': 3.769675298995354, 'lambda': 0.05707030044075978}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:49,031] Trial 88 finished with value: 10.73575796214809 and parameters: {'objective': 'multi:softprob', 'n_estimators': 211, 'learning_rate': 0.7386050417448909, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.2921574648900813, 'colsample_bytree': 0.4878939912421105, 'colsample_bylevel': 0.336310406614874, 'gamma': 3.054687082084225, 'alpha': 4.221443888949616, 'lambda': 3.289554115678003}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:25:55,745] Trial 89 finished with value: 0.9735335314182916 and parameters: {'objective': 'multi:softprob', 'n_estimators': 198, 'learning_rate': 0.10120430071461545, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.4556318828160096, 'colsample_bytree': 0.3692912569663017, 'colsample_bylevel': 0.467573357127099, 'gamma': 3.2338984106944864, 'alpha': 3.0285762980899777, 'lambda': 4.345499382692672}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:02,860] Trial 90 finished with value: 1.0510586169212814 and parameters: {'objective': 'multi:softprob', 'n_estimators': 225, 'learning_rate': 0.18983650124448656, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.45800380683413705, 'colsample_bytree': 0.36608421455610185, 'colsample_bylevel': 0.5798536449739813, 'gamma': 3.2659918286055665, 'alpha': 2.8954302572507022, 'lambda': 1.096273054274099}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:09,351] Trial 91 finished with value: 0.9791687123923534 and parameters: {'objective': 'multi:softprob', 'n_estimators': 197, 'learning_rate': 0.09369657197840808, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.5032896684690097, 'colsample_bytree': 0.5174425559746092, 'colsample_bylevel': 0.4232222478935569, 'gamma': 3.888931932283642, 'alpha': 2.1984165624090783, 'lambda': 1.8205683453186665}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:16,990] Trial 92 finished with value: 0.9758108034560838 and parameters: {'objective': 'multi:softprob', 'n_estimators': 263, 'learning_rate': 0.05593066165955539, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.42613163407528276, 'colsample_bytree': 0.4331989046552416, 'colsample_bylevel': 0.47921759740407216, 'gamma': 3.0117992908549334, 'alpha': 3.2388284658880826, 'lambda': 1.5390963835820413}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:24,888] Trial 93 finished with value: 0.9935706346658779 and parameters: {'objective': 'multi:softprob', 'n_estimators': 276, 'learning_rate': 0.10224506797635446, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.3942683619497764, 'colsample_bytree': 0.39138312564974254, 'colsample_bylevel': 0.5494872484699271, 'gamma': 2.745057901492249, 'alpha': 5.092198129354665, 'lambda': 0.7845479767145479}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:33,398] Trial 94 finished with value: 1.1113409230703766 and parameters: {'objective': 'multi:softprob', 'n_estimators': 248, 'learning_rate': 0.12344732705169112, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.4253457050851878, 'colsample_bytree': 0.45835399122313214, 'colsample_bylevel': 0.5172982691559168, 'gamma': 4.469077124705209, 'alpha': 5.943156543423227, 'lambda': 4.070670936244785}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:40,098] Trial 95 finished with value: 0.9830444511541749 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.018730044061097118, 'max_depth': 1, 'min_child_weight': 9, 'subsample': 0.5483870096052821, 'colsample_bytree': 0.33896400464135706, 'colsample_bylevel': 0.4573894564139257, 'gamma': 8.567003655271597, 'alpha': 0.9002582809335586, 'lambda': 3.07556585712574}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:46,584] Trial 96 finished with value: 0.9732068932255894 and parameters: {'objective': 'multi:softprob', 'n_estimators': 195, 'learning_rate': 0.05641027833880399, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4876490893270826, 'colsample_bytree': 0.4145449907387509, 'colsample_bylevel': 0.6116456182449044, 'gamma': 5.032656924513951, 'alpha': 4.379307788880574, 'lambda': 2.6095319732672326}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:52,994] Trial 97 finished with value: 1.0011257412793118 and parameters: {'objective': 'multi:softprob', 'n_estimators': 192, 'learning_rate': 0.16403188143024353, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4927609781578043, 'colsample_bytree': 0.4124302457245189, 'colsample_bylevel': 0.6078941469747297, 'gamma': 2.3213127246507987, 'alpha': 4.654847412271138, 'lambda': 2.2863719447815374}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:26:59,452] Trial 98 finished with value: 0.9883596460428902 and parameters: {'objective': 'multi:softprob', 'n_estimators': 152, 'learning_rate': 0.05839712202794888, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.5483640431930203, 'colsample_bytree': 0.4994038185270657, 'colsample_bylevel': 0.5786627615168204, 'gamma': 3.491323094149801, 'alpha': 6.5754874819508755, 'lambda': 3.4518206969998637}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:05,488] Trial 99 finished with value: 0.9840447635535515 and parameters: {'objective': 'multi:softprob', 'n_estimators': 170, 'learning_rate': 0.10886984546577884, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.44675308372392175, 'colsample_bytree': 0.6265267934108454, 'colsample_bylevel': 0.6822202332550801, 'gamma': 5.15128516324548, 'alpha': 4.350655149828526, 'lambda': 2.6280734244587665}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:13,673] Trial 100 finished with value: 4.731930608777353 and parameters: {'objective': 'multi:softprob', 'n_estimators': 229, 'learning_rate': 0.9575899090834346, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.31127352443723677, 'colsample_bytree': 0.311890678850788, 'colsample_bylevel': 0.4967024008332929, 'gamma': 4.878308427490066, 'alpha': 5.539050329878138, 'lambda': 9.771837567374853}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:20,912] Trial 101 finished with value: 0.9798440334459413 and parameters: {'objective': 'multi:softprob', 'n_estimators': 244, 'learning_rate': 0.019981558011496793, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.36288255019339205, 'colsample_bytree': 0.5587114712181847, 'colsample_bylevel': 0.6158815311779489, 'gamma': 6.245593690598635, 'alpha': 3.7424881100134995, 'lambda': 4.380089295383282}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:27,504] Trial 102 finished with value: 0.9857093506881123 and parameters: {'objective': 'multi:softprob', 'n_estimators': 203, 'learning_rate': 0.08266656628876462, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.38445681339888327, 'colsample_bytree': 0.47914996574110497, 'colsample_bylevel': 0.4027535536896162, 'gamma': 5.663942695884801, 'alpha': 3.9852476481215793, 'lambda': 4.698135377526902}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:33,832] Trial 103 finished with value: 0.971100965796024 and parameters: {'objective': 'multi:softprob', 'n_estimators': 185, 'learning_rate': 0.05163162001959127, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4082842408848367, 'colsample_bytree': 0.4204893514004766, 'colsample_bylevel': 0.5261783875504226, 'gamma': 2.550108285145349, 'alpha': 6.169732119660892, 'lambda': 5.253498120754642}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:39,185] Trial 104 finished with value: 1.2455691762818855 and parameters: {'objective': 'multi:softprob', 'n_estimators': 123, 'learning_rate': 0.8453981449365808, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.33350309816347085, 'colsample_bytree': 0.3503806112030309, 'colsample_bylevel': 0.6529648780980053, 'gamma': 3.8082356447120906, 'alpha': 6.134652949193324, 'lambda': 5.4275558265945545}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:45,667] Trial 105 finished with value: 0.9698697353310263 and parameters: {'objective': 'multi:softprob', 'n_estimators': 189, 'learning_rate': 0.05670933997508011, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.40507065489125227, 'colsample_bytree': 0.37507588998133146, 'colsample_bylevel': 0.5225297058152892, 'gamma': 2.533451272361318, 'alpha': 5.068111611944229, 'lambda': 9.444110263951531}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:52,754] Trial 106 finished with value: 0.9835116089818035 and parameters: {'objective': 'multi:softprob', 'n_estimators': 183, 'learning_rate': 0.05073524487181104, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.3989101011480686, 'colsample_bytree': 0.42131751665039224, 'colsample_bylevel': 0.5664997259200281, 'gamma': 2.628386270401005, 'alpha': 5.226650413343535, 'lambda': 8.935039641403717}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:27:58,475] Trial 107 finished with value: 1.001861045752559 and parameters: {'objective': 'multi:softprob', 'n_estimators': 158, 'learning_rate': 0.13860803473947894, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.3478592310735463, 'colsample_bytree': 0.5263833691768475, 'colsample_bylevel': 0.5245521368431856, 'gamma': 2.1237380642184034, 'alpha': 4.402339971485399, 'lambda': 9.305727192406616}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:28:04,063] Trial 108 finished with value: 0.9756965525424325 and parameters: {'objective': 'multi:softprob', 'n_estimators': 144, 'learning_rate': 0.06811251831430375, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4851224940656126, 'colsample_bytree': 0.5054209930458275, 'colsample_bylevel': 0.2775534441789394, 'gamma': 2.939035878105286, 'alpha': 5.772126213351326, 'lambda': 9.438697044397783}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:28:11,774] Trial 109 finished with value: 1.1095457427248434 and parameters: {'objective': 'multi:softprob', 'n_estimators': 211, 'learning_rate': 0.12004704723837206, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.3717688249899887, 'colsample_bytree': 0.4676123774762927, 'colsample_bylevel': 0.6401857041451017, 'gamma': 9.982026786180521, 'alpha': 5.028283447290019, 'lambda': 9.20209197882818}. Best is trial 62 with value: 0.9691094221425417.

[I 2026-09-01 09:28:17,774] Trial 110 finished with value: 0.9665792569374773 and parameters: {'objective': 'multi:softprob', 'n_estimators': 172, 'learning_rate': 0.04979113674997246, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.41109303120760865, 'colsample_bytree': 0.39192487751533667, 'colsample_bylevel': 0.5823093431875775, 'gamma': 2.511008300275491, 'alpha': 4.625403597561898, 'lambda': 9.700171954612498}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:28:23,966] Trial 111 finished with value: 0.9717481540724944 and parameters: {'objective': 'multi:softprob', 'n_estimators': 171, 'learning_rate': 0.04618824412696254, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.4097866134376458, 'colsample_bytree': 0.3874016749926605, 'colsample_bylevel': 0.5511453455426734, 'gamma': 2.498639719007139, 'alpha': 6.174420704031799, 'lambda': 9.707870434302032}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:28:30,116] Trial 112 finished with value: 0.9883349307651282 and parameters: {'objective': 'multi:softprob', 'n_estimators': 176, 'learning_rate': 0.08368744222383488, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.4099047330690907, 'colsample_bytree': 0.39886598392579004, 'colsample_bylevel': 0.5033967353316056, 'gamma': 2.50565392307142, 'alpha': 6.558045802248037, 'lambda': 9.772461521624523}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:28:36,087] Trial 113 finished with value: 1.0960793777882483 and parameters: {'objective': 'multi:softprob', 'n_estimators': 163, 'learning_rate': 0.00017749300683771868, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.31815862372090764, 'colsample_bytree': 0.35525075820840196, 'colsample_bylevel': 0.5900321771775652, 'gamma': 2.03985434392748, 'alpha': 6.077753451914224, 'lambda': 9.798690515131295}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:28:42,392] Trial 114 finished with value: 1.1780545158508409 and parameters: {'objective': 'multi:softprob', 'n_estimators': 183, 'learning_rate': 0.617839188859559, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.3896555577652052, 'colsample_bytree': 0.3840648143011838, 'colsample_bylevel': 0.5585957494705883, 'gamma': 2.590353853456967, 'alpha': 5.71013834237358, 'lambda': 9.498678490903279}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:28:49,353] Trial 115 finished with value: 0.9703132366379394 and parameters: {'objective': 'multi:softprob', 'n_estimators': 222, 'learning_rate': 0.04045728569172229, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.4370903816001164, 'colsample_bytree': 0.28204191868264195, 'colsample_bylevel': 0.5287650138458632, 'gamma': 2.307315247833589, 'alpha': 4.647070506510153, 'lambda': 8.668606472065024}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:28:57,207] Trial 116 finished with value: 0.9925284429355977 and parameters: {'objective': 'multi:softprob', 'n_estimators': 221, 'learning_rate': 0.04085548917340012, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.43837812416868627, 'colsample_bytree': 0.27038454461484224, 'colsample_bylevel': 0.48908420853884327, 'gamma': 2.3139360111886424, 'alpha': 5.3875919015394915, 'lambda': 8.556081491079535}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:02,591] Trial 117 finished with value: 1.003980841306457 and parameters: {'objective': 'multi:softprob', 'n_estimators': 129, 'learning_rate': 0.018270199267449494, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.41155211484797527, 'colsample_bytree': 0.32947678130895264, 'colsample_bylevel': 0.5177971613251421, 'gamma': 2.8051509777815724, 'alpha': 6.253127056609503, 'lambda': 9.004425565537135}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:08,763] Trial 118 finished with value: 0.9744368770260635 and parameters: {'objective': 'multi:softprob', 'n_estimators': 172, 'learning_rate': 0.07425177353805426, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.43224118914714504, 'colsample_bytree': 0.29562026095360094, 'colsample_bylevel': 0.5706509603666037, 'gamma': 1.787065563524337, 'alpha': 4.638620847702626, 'lambda': 8.71842420377439}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:15,759] Trial 119 finished with value: 0.9807792263394854 and parameters: {'objective': 'multi:softprob', 'n_estimators': 230, 'learning_rate': 0.0873941435090925, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.4618302873168762, 'colsample_bytree': 0.5883013145245797, 'colsample_bylevel': 0.5840306939624252, 'gamma': 1.4632907041083907, 'alpha': 4.84178226221612, 'lambda': 9.21038355314039}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:22,458] Trial 120 finished with value: 0.9752060870024465 and parameters: {'objective': 'multi:softprob', 'n_estimators': 210, 'learning_rate': 0.03387471721854344, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.4085776705436278, 'colsample_bytree': 0.2394148655509779, 'colsample_bylevel': 0.5534846971187614, 'gamma': 2.4783291114224597, 'alpha': 5.267605156890855, 'lambda': 9.45680206142472}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:28,731] Trial 121 finished with value: 0.979938596425256 and parameters: {'objective': 'multi:softprob', 'n_estimators': 186, 'learning_rate': 0.0509004001811219, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.3451341688787956, 'colsample_bytree': 0.4927752427664592, 'colsample_bylevel': 0.5307512187589991, 'gamma': 3.1572531919387776, 'alpha': 6.914898916257778, 'lambda': 9.731878905252625}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:34,667] Trial 122 finished with value: 0.9879829887552272 and parameters: {'objective': 'multi:softprob', 'n_estimators': 158, 'learning_rate': 0.021794466922961407, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.3666200875477273, 'colsample_bytree': 0.5370695031101749, 'colsample_bylevel': 0.5352640445400837, 'gamma': 3.5311923229228404, 'alpha': 4.022679665963134, 'lambda': 9.647575206816315}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:42,150] Trial 123 finished with value: 0.9712671166825408 and parameters: {'objective': 'multi:softprob', 'n_estimators': 237, 'learning_rate': 0.0461868892023634, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4466667531414053, 'colsample_bytree': 0.2504552936097417, 'colsample_bylevel': 0.5990158758744112, 'gamma': 2.9798641367076826, 'alpha': 5.845802799968576, 'lambda': 9.963861724375777}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:49,189] Trial 124 finished with value: 0.9701304098571376 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.06508174840017683, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.44833271839831373, 'colsample_bytree': 0.2556206010590613, 'colsample_bylevel': 0.6652492692086049, 'gamma': 2.2729687246749863, 'alpha': 5.842666505608391, 'lambda': 9.951755157541733}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:29:57,135] Trial 125 finished with value: 0.9998048970761894 and parameters: {'objective': 'multi:softprob', 'n_estimators': 220, 'learning_rate': 0.06366732463462052, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.5129175926089522, 'colsample_bytree': 0.20689144573922968, 'colsample_bylevel': 0.6638230382048226, 'gamma': 2.2903864774604354, 'alpha': 5.834740559662209, 'lambda': 9.971080630824266}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:04,345] Trial 126 finished with value: 1.0712983072121303 and parameters: {'objective': 'multi:softprob', 'n_estimators': 237, 'learning_rate': 0.0016431938411235122, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4755943516497681, 'colsample_bytree': 0.2428048539198836, 'colsample_bylevel': 0.6929480482003598, 'gamma': 2.9444995625474553, 'alpha': 5.500645797670448, 'lambda': 9.369665468808437}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:17,154] Trial 127 finished with value: 1.0500229510237078 and parameters: {'objective': 'multi:softprob', 'n_estimators': 549, 'learning_rate': 0.11691095394671727, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.450477902370011, 'colsample_bytree': 0.2593349530922178, 'colsample_bylevel': 0.7126222153574113, 'gamma': 2.0034003554850544, 'alpha': 4.9735226212442045, 'lambda': 9.852984580757393}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:25,924] Trial 128 finished with value: 0.9979935465005528 and parameters: {'objective': 'multi:softprob', 'n_estimators': 262, 'learning_rate': 0.03815742756072699, 'max_depth': 2, 'min_child_weight': 7, 'subsample': 0.3872748815935868, 'colsample_bytree': 0.28114341252791264, 'colsample_bylevel': 0.6260168248451183, 'gamma': 2.7226241740613113, 'alpha': 4.521415210827085, 'lambda': 9.584615067433166}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:33,828] Trial 129 finished with value: 0.969548315361723 and parameters: {'objective': 'multi:softprob', 'n_estimators': 290, 'learning_rate': 0.0881834763378166, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.41532658591842864, 'colsample_bytree': 0.25470297762587735, 'colsample_bylevel': 0.6040723390282956, 'gamma': 2.218961017003073, 'alpha': 5.077114774274233, 'lambda': 8.880652532864756}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:41,851] Trial 130 finished with value: 0.967812600401538 and parameters: {'objective': 'multi:softprob', 'n_estimators': 290, 'learning_rate': 0.08958978198598504, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.44645777943827525, 'colsample_bytree': 0.25221845894560996, 'colsample_bylevel': 0.6738506723082197, 'gamma': 1.6426507762919667, 'alpha': 5.103901425439548, 'lambda': 8.831754805728101}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:50,189] Trial 131 finished with value: 0.9684524941578836 and parameters: {'objective': 'multi:softprob', 'n_estimators': 300, 'learning_rate': 0.08299701545109174, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.44219886792794444, 'colsample_bytree': 0.21876731779170686, 'colsample_bylevel': 0.6770397985080735, 'gamma': 1.7806407673184939, 'alpha': 5.110076922961956, 'lambda': 8.89373890260176}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:30:59,090] Trial 132 finished with value: 1.015491408705447 and parameters: {'objective': 'multi:softprob', 'n_estimators': 342, 'learning_rate': 0.1490153702930211, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.4461803641849935, 'colsample_bytree': 0.2275730145608597, 'colsample_bylevel': 0.6738514193298151, 'gamma': 1.6198392332712714, 'alpha': 5.1106581467618195, 'lambda': 8.665932567894862}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:31:08,114] Trial 133 finished with value: 0.9800394201233219 and parameters: {'objective': 'multi:softprob', 'n_estimators': 315, 'learning_rate': 0.0875063222981666, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.42363552696647094, 'colsample_bytree': 0.20946138700548406, 'colsample_bylevel': 0.6466683587907853, 'gamma': 1.9124617022840764, 'alpha': 4.674544269638208, 'lambda': 8.32075924071121}. Best is trial 110 with value: 0.9665792569374773.

[I 2026-09-01 09:31:16,104] Trial 134 finished with value: 0.9600055575937119 and parameters: {'objective': 'multi:softprob', 'n_estimators': 282, 'learning_rate': 0.06927980349829926, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.46523287138193353, 'colsample_bytree': 0.2559416088641604, 'colsample_bylevel': 0.6618318137120507, 'gamma': 2.2120312041912915, 'alpha': 5.636624538374258, 'lambda': 8.857581659514329}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:31:24,196] Trial 135 finished with value: 0.9984647507507093 and parameters: {'objective': 'multi:softprob', 'n_estimators': 291, 'learning_rate': 0.12171722825496352, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.4691383844638339, 'colsample_bytree': 0.2903824702155826, 'colsample_bylevel': 0.7217543785668176, 'gamma': 2.27649995756243, 'alpha': 5.351872209378934, 'lambda': 8.991623902366486}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:31:32,511] Trial 136 finished with value: 0.9632536651206163 and parameters: {'objective': 'multi:softprob', 'n_estimators': 310, 'learning_rate': 0.07086542417244207, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5221274521285145, 'colsample_bytree': 0.21978357852250707, 'colsample_bylevel': 0.7008148142961584, 'gamma': 1.7645522882044133, 'alpha': 5.560802995159291, 'lambda': 8.095104077293906}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:31:42,423] Trial 137 finished with value: 1.1303608149479074 and parameters: {'objective': 'multi:softprob', 'n_estimators': 315, 'learning_rate': 0.10128463374982517, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.5216661329950083, 'colsample_bytree': 0.2620334857096552, 'colsample_bylevel': 0.7037561939622116, 'gamma': 1.7322262267020023, 'alpha': 4.860321624200678, 'lambda': 8.834727631042258}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:31:50,350] Trial 138 finished with value: 0.969459848007783 and parameters: {'objective': 'multi:softprob', 'n_estimators': 289, 'learning_rate': 0.07352700740673343, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5400633526456421, 'colsample_bytree': 0.21977807839630098, 'colsample_bylevel': 0.6648155377834749, 'gamma': 1.6094144951153693, 'alpha': 5.166826161325751, 'lambda': 7.956659963083645}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:31:58,571] Trial 139 finished with value: 0.9693583978138898 and parameters: {'objective': 'multi:softprob', 'n_estimators': 298, 'learning_rate': 0.06987128203085906, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5554550579099198, 'colsample_bytree': 0.2208312225804267, 'colsample_bylevel': 0.694044788288251, 'gamma': 1.2850520806599146, 'alpha': 5.108462807573758, 'lambda': 8.212386846455203}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:06,366] Trial 140 finished with value: 0.9992708259964429 and parameters: {'objective': 'multi:softprob', 'n_estimators': 284, 'learning_rate': 0.13585533671440223, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.6052372089391942, 'colsample_bytree': 0.21759816246870511, 'colsample_bylevel': 0.6867799482078772, 'gamma': 1.4239260917042604, 'alpha': 5.044338293097153, 'lambda': 7.705106680117441}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:14,426] Trial 141 finished with value: 0.9654922187868209 and parameters: {'objective': 'multi:softprob', 'n_estimators': 297, 'learning_rate': 0.07647470135181517, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5902260582901931, 'colsample_bytree': 0.2277608206123411, 'colsample_bylevel': 0.6674365062392548, 'gamma': 1.5739931292320457, 'alpha': 4.728848299807454, 'lambda': 8.472627826341668}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:22,537] Trial 142 finished with value: 0.9700715609132393 and parameters: {'objective': 'multi:softprob', 'n_estimators': 299, 'learning_rate': 0.07519312348232829, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5357297254856126, 'colsample_bytree': 0.2012349387285899, 'colsample_bylevel': 0.6638081966415541, 'gamma': 1.0053200113795155, 'alpha': 5.219509609546049, 'lambda': 8.00895664524495}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:30,685] Trial 143 finished with value: 0.9674048724197211 and parameters: {'objective': 'multi:softprob', 'n_estimators': 299, 'learning_rate': 0.0773776291314214, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.541585444475293, 'colsample_bytree': 0.20172185684005878, 'colsample_bylevel': 0.6601256107532675, 'gamma': 1.0374039088992482, 'alpha': 5.185676220502827, 'lambda': 8.016536489080485}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:38,868] Trial 144 finished with value: 0.9669917903428046 and parameters: {'objective': 'multi:softprob', 'n_estimators': 306, 'learning_rate': 0.08180439025611778, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5811817773476325, 'colsample_bytree': 0.22891949646072846, 'colsample_bylevel': 0.6693538683381518, 'gamma': 1.5726468015337471, 'alpha': 5.472838285950191, 'lambda': 7.9632028434049005}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:47,100] Trial 145 finished with value: 0.9705991830529235 and parameters: {'objective': 'multi:softprob', 'n_estimators': 309, 'learning_rate': 0.09349046697950636, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5828187504945358, 'colsample_bytree': 0.2323138317773608, 'colsample_bylevel': 0.7496505093867907, 'gamma': 1.0125825739563128, 'alpha': 5.176996921195698, 'lambda': 7.865780453524309}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:32:55,190] Trial 146 finished with value: 0.9784966453627735 and parameters: {'objective': 'multi:softprob', 'n_estimators': 299, 'learning_rate': 0.1156154906442029, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5510992987611081, 'colsample_bytree': 0.22153533162338887, 'colsample_bylevel': 0.673853482313789, 'gamma': 1.31479080900472, 'alpha': 5.4635921255750475, 'lambda': 8.118581567078378}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:33:03,942] Trial 147 finished with value: 1.0365514875049402 and parameters: {'objective': 'multi:softprob', 'n_estimators': 342, 'learning_rate': 0.18009000620057175, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.5334664740604643, 'colsample_bytree': 0.20100688635985448, 'colsample_bylevel': 0.7183923273349615, 'gamma': 0.4149595697642394, 'alpha': 5.292391498811826, 'lambda': 8.04792088445849}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:33:13,063] Trial 148 finished with value: 1.0138904124128958 and parameters: {'objective': 'multi:softprob', 'n_estimators': 358, 'learning_rate': 0.1525370267822764, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5828891323465704, 'colsample_bytree': 0.2393970393247404, 'colsample_bylevel': 0.6983789116745922, 'gamma': 1.5844945542852669, 'alpha': 4.841996136537803, 'lambda': 7.590944122305679}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:33:32,773] Trial 149 finished with value: 2.5329821970213304 and parameters: {'objective': 'multi:softprob', 'n_estimators': 318, 'learning_rate': 0.07594136481540283, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.5679228756748941, 'colsample_bytree': 0.2220618916965316, 'colsample_bylevel': 0.7680497529880382, 'gamma': 0.9407830941292834, 'alpha': 5.535738961475588, 'lambda': 8.345462618753363}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:33:41,687] Trial 150 finished with value: 1.0601573286538242 and parameters: {'objective': 'multi:softprob', 'n_estimators': 286, 'learning_rate': 0.10425373533066873, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6304769971094012, 'colsample_bytree': 0.20559467458648972, 'colsample_bylevel': 0.6455269702883535, 'gamma': 1.250474050414119, 'alpha': 5.08699782766528, 'lambda': 7.985583986792156}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:33:49,599] Trial 151 finished with value: 0.9656773609813577 and parameters: {'objective': 'multi:softprob', 'n_estimators': 298, 'learning_rate': 0.06981029922767555, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5589409517187565, 'colsample_bytree': 0.2526690691644274, 'colsample_bylevel': 0.6660266895988703, 'gamma': 0.8160465437066936, 'alpha': 5.719551439345646, 'lambda': 8.43576877753875}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:33:57,705] Trial 152 finished with value: 0.977074348426365 and parameters: {'objective': 'multi:softprob', 'n_estimators': 304, 'learning_rate': 0.0854599633314332, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5575268003514336, 'colsample_bytree': 0.267605981893308, 'colsample_bylevel': 0.7355004892401255, 'gamma': 0.7519679529690678, 'alpha': 5.395740829300668, 'lambda': 8.477907152561809}. Best is trial 134 with value: 0.9600055575937119.

[I 2026-09-01 09:34:05,818] Trial 153 finished with value: 0.9582422865647776 and parameters: {'objective': 'multi:softprob', 'n_estimators': 296, 'learning_rate': 0.07062340261661293, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5954235886071667, 'colsample_bytree': 0.2446170729252112, 'colsample_bylevel': 0.6839565992542864, 'gamma': 1.0517227070653667, 'alpha': 5.602055838339061, 'lambda': 7.790076697395317}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:34:13,611] Trial 154 finished with value: 0.9706292853569574 and parameters: {'objective': 'multi:softprob', 'n_estimators': 273, 'learning_rate': 0.13078011499379116, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.6031696279886012, 'colsample_bytree': 0.2495855292066118, 'colsample_bylevel': 0.6915684450321277, 'gamma': 1.5305328310929132, 'alpha': 5.618077969482624, 'lambda': 7.199303427216302}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:34:22,171] Trial 155 finished with value: 0.9881391219901208 and parameters: {'objective': 'multi:softprob', 'n_estimators': 325, 'learning_rate': 0.10396534782391828, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.5933227121180056, 'colsample_bytree': 0.2330806606200502, 'colsample_bylevel': 0.6385011700421207, 'gamma': 1.8107327383747602, 'alpha': 4.822296728543272, 'lambda': 7.719426673717084}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:34:30,251] Trial 156 finished with value: 0.9697822688421509 and parameters: {'objective': 'multi:softprob', 'n_estimators': 292, 'learning_rate': 0.06573370846747709, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.6227160825059164, 'colsample_bytree': 0.3057018046452362, 'colsample_bylevel': 0.7267290232817837, 'gamma': 0.5983246029994359, 'alpha': 5.697802622363446, 'lambda': 8.298281964612018}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:34:38,148] Trial 157 finished with value: 0.974818292157275 and parameters: {'objective': 'multi:softprob', 'n_estimators': 281, 'learning_rate': 0.0746834458261155, 'max_depth': 1, 'min_child_weight': 1, 'subsample': 0.6205337039833764, 'colsample_bytree': 0.30140537522563243, 'colsample_bylevel': 0.7244055657691563, 'gamma': 0.7008107775763206, 'alpha': 5.6588173012923475, 'lambda': 7.433969213785077}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:34:46,388] Trial 158 finished with value: 0.9935007911386546 and parameters: {'objective': 'multi:softprob', 'n_estimators': 295, 'learning_rate': 0.12438814064598441, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.6468940425100179, 'colsample_bytree': 0.2758778367226422, 'colsample_bylevel': 0.6831957896869855, 'gamma': 1.0811012681627528, 'alpha': 5.898971655307523, 'lambda': 8.270506904277926}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:34:55,006] Trial 159 finished with value: 0.9658490215736799 and parameters: {'objective': 'multi:softprob', 'n_estimators': 333, 'learning_rate': 0.01993131497501357, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5675361486478067, 'colsample_bytree': 0.24567195737857828, 'colsample_bylevel': 0.7096071566691315, 'gamma': 0.5036082376687128, 'alpha': 5.962875228232065, 'lambda': 8.490764039405745}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:05,305] Trial 160 finished with value: 0.9765403854607673 and parameters: {'objective': 'multi:softprob', 'n_estimators': 333, 'learning_rate': 0.024923601407523643, 'max_depth': 2, 'min_child_weight': 2, 'subsample': 0.5646674015209795, 'colsample_bytree': 0.22464022759427466, 'colsample_bylevel': 0.7007568834275121, 'gamma': 1.2851621069034913, 'alpha': 6.034621912965901, 'lambda': 8.52666287418533}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:13,473] Trial 161 finished with value: 0.9596487508475675 and parameters: {'objective': 'multi:softprob', 'n_estimators': 311, 'learning_rate': 0.06771097535771602, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5941767580079726, 'colsample_bytree': 0.24560357855665693, 'colsample_bylevel': 0.6762600427672024, 'gamma': 0.4322861551217746, 'alpha': 5.653385039646135, 'lambda': 7.825573772482094}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:21,607] Trial 162 finished with value: 0.9804302355777114 and parameters: {'objective': 'multi:softprob', 'n_estimators': 307, 'learning_rate': 0.1000181694072709, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.536087041919031, 'colsample_bytree': 0.2471063124106223, 'colsample_bylevel': 0.6560649166883201, 'gamma': 0.8348114837850182, 'alpha': 5.281218932009482, 'lambda': 7.764571538017822}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:30,242] Trial 163 finished with value: 0.9775034210173801 and parameters: {'objective': 'multi:softprob', 'n_estimators': 322, 'learning_rate': 0.0848859929210583, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.588306039042114, 'colsample_bytree': 0.25680580155714117, 'colsample_bylevel': 0.6701932834261548, 'gamma': 0.3562310447529761, 'alpha': 5.460771440295911, 'lambda': 8.12081977353313}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:38,599] Trial 164 finished with value: 0.9744557946804806 and parameters: {'objective': 'multi:softprob', 'n_estimators': 310, 'learning_rate': 0.015884183996916247, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5691051272438769, 'colsample_bytree': 0.2329826769997994, 'colsample_bylevel': 0.7073085373681558, 'gamma': 0.4411563860672626, 'alpha': 4.986582981087133, 'lambda': 7.449912023979729}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:46,301] Trial 165 finished with value: 0.9649460467194453 and parameters: {'objective': 'multi:softprob', 'n_estimators': 272, 'learning_rate': 0.06679002886119034, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5437739057296876, 'colsample_bytree': 0.22057537530486135, 'colsample_bylevel': 0.6258759550871688, 'gamma': 1.4130798642871358, 'alpha': 5.970067295024601, 'lambda': 8.466851942867152}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:35:54,439] Trial 166 finished with value: 0.9625057574605846 and parameters: {'objective': 'multi:softprob', 'n_estimators': 271, 'learning_rate': 0.0675354497897538, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5074030472690816, 'colsample_bytree': 0.21712227568262404, 'colsample_bylevel': 0.6201202070685199, 'gamma': 1.642758429356813, 'alpha': 6.043172360136208, 'lambda': 7.86318997264196}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:02,235] Trial 167 finished with value: 0.9609156940967152 and parameters: {'objective': 'multi:softprob', 'n_estimators': 272, 'learning_rate': 0.06282527683782814, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.508536680128132, 'colsample_bytree': 0.21740621102231372, 'colsample_bylevel': 0.6235793348955528, 'gamma': 1.524177362752751, 'alpha': 5.986986212759495, 'lambda': 6.814610930649299}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:10,324] Trial 168 finished with value: 0.9658174917918514 and parameters: {'objective': 'multi:softprob', 'n_estimators': 272, 'learning_rate': 0.02444966566406124, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5167377064405092, 'colsample_bytree': 0.2401753125892624, 'colsample_bylevel': 0.6295617807878566, 'gamma': 1.4250965715902035, 'alpha': 5.984464285437124, 'lambda': 7.600755245030736}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:18,295] Trial 169 finished with value: 0.9648282846545639 and parameters: {'objective': 'multi:softprob', 'n_estimators': 268, 'learning_rate': 0.025909340553594604, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5158046628928067, 'colsample_bytree': 0.23993861268031116, 'colsample_bylevel': 0.622925252230335, 'gamma': 1.0620129868977297, 'alpha': 6.515122468107554, 'lambda': 6.522199236347021}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:25,960] Trial 170 finished with value: 0.9807521625645038 and parameters: {'objective': 'multi:softprob', 'n_estimators': 271, 'learning_rate': 0.017511383803807228, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5062268324240988, 'colsample_bytree': 0.2725613529503127, 'colsample_bylevel': 0.6228522014628176, 'gamma': 1.115181700990013, 'alpha': 6.582805417111444, 'lambda': 6.592509638984766}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:33,656] Trial 171 finished with value: 0.9693563371445931 and parameters: {'objective': 'multi:softprob', 'n_estimators': 267, 'learning_rate': 0.02380031797941487, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5208628308590099, 'colsample_bytree': 0.24029495954921917, 'colsample_bylevel': 0.6185253345925341, 'gamma': 1.7715822203169496, 'alpha': 6.493857037996937, 'lambda': 6.834614643865806}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:41,497] Trial 172 finished with value: 0.9623997446852859 and parameters: {'objective': 'multi:softprob', 'n_estimators': 280, 'learning_rate': 0.05730245750207439, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5041639906907018, 'colsample_bytree': 0.2128236736347468, 'colsample_bylevel': 0.6449290408363377, 'gamma': 1.4656597514824816, 'alpha': 6.025820404069585, 'lambda': 6.442271353257229}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:49,191] Trial 173 finished with value: 0.963755517944642 and parameters: {'objective': 'multi:softprob', 'n_estimators': 273, 'learning_rate': 0.05839751642301596, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5021207000718998, 'colsample_bytree': 0.21052175351056895, 'colsample_bylevel': 0.6372679930359719, 'gamma': 2.0000042783860064, 'alpha': 5.990715245127747, 'lambda': 7.031858975002187}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:36:57,032] Trial 174 finished with value: 0.9603983489754502 and parameters: {'objective': 'multi:softprob', 'n_estimators': 278, 'learning_rate': 0.05706704697333985, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5022431055138535, 'colsample_bytree': 0.20309747302947523, 'colsample_bylevel': 0.6421669285183662, 'gamma': 1.3680994893104208, 'alpha': 6.370562642063565, 'lambda': 5.963100984961393}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:04,803] Trial 175 finished with value: 1.084714259650085 and parameters: {'objective': 'multi:softprob', 'n_estimators': 280, 'learning_rate': 0.0007097238735435316, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5008599438691428, 'colsample_bytree': 0.20008008713005973, 'colsample_bylevel': 0.6338096140215481, 'gamma': 1.42239480504604, 'alpha': 6.757228887032463, 'lambda': 6.014445563009492}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:12,258] Trial 176 finished with value: 0.9587086796555991 and parameters: {'objective': 'multi:softprob', 'n_estimators': 259, 'learning_rate': 0.058534143807804875, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.513773498951048, 'colsample_bytree': 0.2348636509552663, 'colsample_bylevel': 0.6475565504002764, 'gamma': 0.7957011608609673, 'alpha': 6.384491152656462, 'lambda': 6.497559535704827}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:19,836] Trial 177 finished with value: 0.962704599569135 and parameters: {'objective': 'multi:softprob', 'n_estimators': 266, 'learning_rate': 0.05577241946518061, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5129353523945286, 'colsample_bytree': 0.2360875240319668, 'colsample_bylevel': 0.6389519626558798, 'gamma': 0.872008992360424, 'alpha': 6.38459016556914, 'lambda': 6.3642759625899}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:27,298] Trial 178 finished with value: 0.9602682067903175 and parameters: {'objective': 'multi:softprob', 'n_estimators': 258, 'learning_rate': 0.05782091951590119, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5129489992040439, 'colsample_bytree': 0.23902724315667748, 'colsample_bylevel': 0.6425280871928302, 'gamma': 0.823930287896372, 'alpha': 6.352194401761807, 'lambda': 6.407821216893535}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:36,702] Trial 179 finished with value: 0.974248146743638 and parameters: {'objective': 'multi:softprob', 'n_estimators': 259, 'learning_rate': 0.028831259938875742, 'max_depth': 2, 'min_child_weight': 6, 'subsample': 0.49139919857479764, 'colsample_bytree': 0.24165015941164383, 'colsample_bylevel': 0.6440264660437283, 'gamma': 0.5580839196152686, 'alpha': 6.377382212765274, 'lambda': 6.545891985108623}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:44,523] Trial 180 finished with value: 0.9680965542799711 and parameters: {'objective': 'multi:softprob', 'n_estimators': 270, 'learning_rate': 0.04758882597236852, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5150008502285249, 'colsample_bytree': 0.26693224386651143, 'colsample_bylevel': 0.6199568511358968, 'gamma': 0.7714507697470329, 'alpha': 6.257872827438343, 'lambda': 6.264915244890229}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:52,415] Trial 181 finished with value: 0.9602652200445084 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.05577276243016076, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5247411135688939, 'colsample_bytree': 0.21803740970858254, 'colsample_bylevel': 0.6357122548523371, 'gamma': 0.8394296524993412, 'alpha': 5.959168558220285, 'lambda': 7.079115552608622}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:37:59,779] Trial 182 finished with value: 0.9691475428806078 and parameters: {'objective': 'multi:softprob', 'n_estimators': 254, 'learning_rate': 0.027656082213776113, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5280762157680664, 'colsample_bytree': 0.2160909049616158, 'colsample_bylevel': 0.6333234108091674, 'gamma': 0.22248070950453047, 'alpha': 6.005172310797214, 'lambda': 5.7087100778363995}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:07,484] Trial 183 finished with value: 0.9600213235487915 and parameters: {'objective': 'multi:softprob', 'n_estimators': 263, 'learning_rate': 0.05917006108030544, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.511491448589022, 'colsample_bytree': 0.23677279676074753, 'colsample_bylevel': 0.6487783676733304, 'gamma': 0.899236918028053, 'alpha': 6.966460224034108, 'lambda': 6.938923089784748}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:14,919] Trial 184 finished with value: 0.9606498744041967 and parameters: {'objective': 'multi:softprob', 'n_estimators': 262, 'learning_rate': 0.06023943599992794, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5116751904020547, 'colsample_bytree': 0.2341023510165005, 'colsample_bylevel': 0.6129681903810705, 'gamma': 0.8564172656276237, 'alpha': 6.977896269634675, 'lambda': 7.059089473639772}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:22,326] Trial 185 finished with value: 0.969496900837198 and parameters: {'objective': 'multi:softprob', 'n_estimators': 260, 'learning_rate': 0.060123812144815485, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.49031361548605973, 'colsample_bytree': 0.21710766578416055, 'colsample_bylevel': 0.6075359094952033, 'gamma': 0.9374018479313468, 'alpha': 7.073487464936534, 'lambda': 7.085480724021844}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:30,225] Trial 186 finished with value: 0.9682355883619141 and parameters: {'objective': 'multi:softprob', 'n_estimators': 280, 'learning_rate': 0.058833451978878966, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5054079545317955, 'colsample_bytree': 0.28947820621141185, 'colsample_bylevel': 0.6449738259436075, 'gamma': 0.8202990479203219, 'alpha': 6.676088007498547, 'lambda': 6.810208518907904}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:37,534] Trial 187 finished with value: 0.9625401572656705 and parameters: {'objective': 'multi:softprob', 'n_estimators': 248, 'learning_rate': 0.05484429530223375, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5060054484782469, 'colsample_bytree': 0.2311085514403374, 'colsample_bylevel': 0.6488771767995012, 'gamma': 1.1464822113614666, 'alpha': 6.952396279747331, 'lambda': 6.729351746736836}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:44,823] Trial 188 finished with value: 0.989552214594075 and parameters: {'objective': 'multi:softprob', 'n_estimators': 250, 'learning_rate': 0.10975480835587723, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.48583434003026904, 'colsample_bytree': 0.2265414967516044, 'colsample_bylevel': 0.6490773023375999, 'gamma': 1.1695187373012617, 'alpha': 7.022659113395972, 'lambda': 6.390894066017868}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:52,391] Trial 189 finished with value: 0.9610307486192944 and parameters: {'objective': 'multi:softprob', 'n_estimators': 262, 'learning_rate': 0.05711902474608491, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4965702175671436, 'colsample_bytree': 0.2329825457658757, 'colsample_bylevel': 0.6158098838240517, 'gamma': 1.0733691739220448, 'alpha': 6.852677657560635, 'lambda': 6.699087278390429}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:38:59,876] Trial 190 finished with value: 0.9733202484455261 and parameters: {'objective': 'multi:softprob', 'n_estimators': 261, 'learning_rate': 0.04919674866513006, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5151760585056225, 'colsample_bytree': 0.9913638186862139, 'colsample_bylevel': 0.6046112794836878, 'gamma': 1.1432774245649004, 'alpha': 7.563596731953797, 'lambda': 6.747198934059989}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:39:07,536] Trial 191 finished with value: 0.9613310012678234 and parameters: {'objective': 'multi:softprob', 'n_estimators': 267, 'learning_rate': 0.054883706034818944, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.496556704304016, 'colsample_bytree': 0.23241149805957576, 'colsample_bylevel': 0.6273098122298728, 'gamma': 0.6612804118760753, 'alpha': 6.834685723213718, 'lambda': 6.991837134143644}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:39:14,755] Trial 192 finished with value: 0.9671024707900603 and parameters: {'objective': 'multi:softprob', 'n_estimators': 249, 'learning_rate': 0.05941863535470103, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5002508799583812, 'colsample_bytree': 0.21409920739893112, 'colsample_bylevel': 0.6209453303778174, 'gamma': 0.6489059326670451, 'alpha': 6.819709327380434, 'lambda': 7.018126930576357}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:39:22,436] Trial 193 finished with value: 0.9663106333460698 and parameters: {'objective': 'multi:softprob', 'n_estimators': 267, 'learning_rate': 0.041813737410396165, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.4792732275016455, 'colsample_bytree': 0.2620052375092973, 'colsample_bylevel': 0.6109857286854502, 'gamma': 0.9845063245290464, 'alpha': 7.166442700047387, 'lambda': 6.441951238250126}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:39:30,217] Trial 194 finished with value: 0.9648794808647488 and parameters: {'objective': 'multi:softprob', 'n_estimators': 275, 'learning_rate': 0.05747495185583295, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5271524901651966, 'colsample_bytree': 0.2368149272965559, 'colsample_bylevel': 0.6449564498374226, 'gamma': 0.2965657567210518, 'alpha': 6.416438324945143, 'lambda': 6.093337062503542}. Best is trial 153 with value: 0.9582422865647776.

[I 2026-09-01 09:39:37,755] Trial 195 finished with value: 0.9582183471886763 and parameters: {'objective': 'multi:softprob', 'n_estimators': 259, 'learning_rate': 0.03727502487190193, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5034531494745685, 'colsample_bytree': 0.237530968617811, 'colsample_bylevel': 0.6443792295166177, 'gamma': 0.40966268910126213, 'alpha': 6.353109353921474, 'lambda': 6.087251236544571}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:39:45,140] Trial 196 finished with value: 0.9679837830761261 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.03352509078067572, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5094972128647777, 'colsample_bytree': 0.27383950644458077, 'colsample_bylevel': 0.6515969243169949, 'gamma': 0.6417275230472381, 'alpha': 6.880805835484693, 'lambda': 5.664192700582055}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:39:52,408] Trial 197 finished with value: 1.002462967899822 and parameters: {'objective': 'multi:softprob', 'n_estimators': 246, 'learning_rate': 0.010905732302193397, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4846614627985645, 'colsample_bytree': 0.2021664611784196, 'colsample_bylevel': 0.6330372352868736, 'gamma': 0.10475007625365784, 'alpha': 6.683433915651015, 'lambda': 6.635919777953612}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:39:59,835] Trial 198 finished with value: 0.9649867652182023 and parameters: {'objective': 'multi:softprob', 'n_estimators': 259, 'learning_rate': 0.03775447599049361, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.4990980301998519, 'colsample_bytree': 0.24692027234434, 'colsample_bylevel': 0.6003310763166856, 'gamma': 0.43375031482669907, 'alpha': 7.247268581649265, 'lambda': 7.194293283018634}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:07,719] Trial 199 finished with value: 0.9833729488138735 and parameters: {'objective': 'multi:softprob', 'n_estimators': 283, 'learning_rate': 0.10085564718987464, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.467913612041862, 'colsample_bytree': 0.23410016911441403, 'colsample_bylevel': 0.6485898590729119, 'gamma': 0.8426980134619059, 'alpha': 6.263366920997473, 'lambda': 5.859425558646732}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:15,368] Trial 200 finished with value: 1.080680241458463 and parameters: {'objective': 'multi:softprob', 'n_estimators': 264, 'learning_rate': 0.0009111714402128268, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5270714937188514, 'colsample_bytree': 0.2612991084301429, 'colsample_bylevel': 0.620875530432712, 'gamma': 1.0955088340521422, 'alpha': 6.4701823219706185, 'lambda': 6.974209264465132}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:23,176] Trial 201 finished with value: 0.9650459985668077 and parameters: {'objective': 'multi:softprob', 'n_estimators': 277, 'learning_rate': 0.05677365974414929, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.52693122555866, 'colsample_bytree': 0.23536733853030056, 'colsample_bylevel': 0.6432275610767024, 'gamma': 0.18398271205364092, 'alpha': 6.293333052241345, 'lambda': 6.103542531108687}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:31,011] Trial 202 finished with value: 0.9644338377869743 and parameters: {'objective': 'multi:softprob', 'n_estimators': 276, 'learning_rate': 0.058081738269655014, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5003765880203832, 'colsample_bytree': 0.21413679625925097, 'colsample_bylevel': 0.635355899771346, 'gamma': 0.3351445671504003, 'alpha': 6.437031381903668, 'lambda': 6.251243601623688}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:38,239] Trial 203 finished with value: 0.9672765692413618 and parameters: {'objective': 'multi:softprob', 'n_estimators': 249, 'learning_rate': 0.04046128817058659, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.49693816676781566, 'colsample_bytree': 0.21383267525459138, 'colsample_bylevel': 0.6061650634773887, 'gamma': 0.02109737597110728, 'alpha': 6.879697816289039, 'lambda': 6.334790853324027}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:45,878] Trial 204 finished with value: 0.9759878268833446 and parameters: {'objective': 'multi:softprob', 'n_estimators': 265, 'learning_rate': 0.09400958403982468, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5100669254653674, 'colsample_bytree': 0.2139210959944021, 'colsample_bylevel': 0.6318915755737612, 'gamma': 0.6322769977703506, 'alpha': 6.510207002996971, 'lambda': 6.683368058878368}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:40:53,712] Trial 205 finished with value: 0.9643110667301791 and parameters: {'objective': 'multi:softprob', 'n_estimators': 278, 'learning_rate': 0.05660164682085797, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4774294125255111, 'colsample_bytree': 0.20000844258299016, 'colsample_bylevel': 0.5896606443563078, 'gamma': 0.3948137745099786, 'alpha': 6.1589627140036205, 'lambda': 6.488388816147642}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:01,587] Trial 206 finished with value: 0.9681487876053558 and parameters: {'objective': 'multi:softprob', 'n_estimators': 282, 'learning_rate': 0.06417675156161531, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.4746967673126681, 'colsample_bytree': 0.20265691399109292, 'colsample_bylevel': 0.6576587415273191, 'gamma': 0.3518525649617064, 'alpha': 6.154557239120008, 'lambda': 6.912526120534824}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:08,927] Trial 207 finished with value: 0.9659505506917864 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.09418191593858138, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.48944515785561077, 'colsample_bytree': 0.22700331769740312, 'colsample_bylevel': 0.5857105274439683, 'gamma': 0.4852850266504386, 'alpha': 6.1337147119620505, 'lambda': 7.299926787246486}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:16,201] Trial 208 finished with value: 0.9675466385560098 and parameters: {'objective': 'multi:softprob', 'n_estimators': 244, 'learning_rate': 0.06288801173805966, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.46599629745194177, 'colsample_bytree': 0.25594635708717933, 'colsample_bylevel': 0.594578690650956, 'gamma': 0.8874454521761446, 'alpha': 6.771202072073248, 'lambda': 6.217902645476244}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:24,119] Trial 209 finished with value: 0.9697327481773598 and parameters: {'objective': 'multi:softprob', 'n_estimators': 282, 'learning_rate': 0.07728824187579642, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.4975202314519177, 'colsample_bytree': 0.2006527248010106, 'colsample_bylevel': 0.6521421374132087, 'gamma': 0.6522695837130094, 'alpha': 6.33736461708318, 'lambda': 5.9062046248733315}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:31,837] Trial 210 finished with value: 0.9637476234652881 and parameters: {'objective': 'multi:softprob', 'n_estimators': 276, 'learning_rate': 0.04381225399900048, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4800546519744187, 'colsample_bytree': 0.22553955440022774, 'colsample_bylevel': 0.6353827259287311, 'gamma': 0.3205160410945799, 'alpha': 7.022249503846596, 'lambda': 6.413477023478896}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:39,598] Trial 211 finished with value: 0.9656835573903294 and parameters: {'objective': 'multi:softprob', 'n_estimators': 273, 'learning_rate': 0.055039407019496764, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4793171252073033, 'colsample_bytree': 0.22588997802387734, 'colsample_bylevel': 0.6835865935940876, 'gamma': 0.28978982357893035, 'alpha': 7.121203048605096, 'lambda': 6.396786448676408}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:47,473] Trial 212 finished with value: 0.9614500525451419 and parameters: {'objective': 'multi:softprob', 'n_estimators': 286, 'learning_rate': 0.04131647060830905, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5038218957167351, 'colsample_bytree': 0.21526607248684226, 'colsample_bylevel': 0.6347761163281982, 'gamma': 0.5277399419821407, 'alpha': 6.950145006267181, 'lambda': 6.723669455636027}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:41:55,490] Trial 213 finished with value: 0.9661102045585981 and parameters: {'objective': 'multi:softprob', 'n_estimators': 288, 'learning_rate': 0.03413589849141682, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4644597009133967, 'colsample_bytree': 0.24496312619165997, 'colsample_bylevel': 0.6102409006420828, 'gamma': 0.8016836848634595, 'alpha': 7.522850489601785, 'lambda': 6.786086185456274}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:03,128] Trial 214 finished with value: 0.9629933591906443 and parameters: {'objective': 'multi:softprob', 'n_estimators': 262, 'learning_rate': 0.045263006623947534, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5337666842135413, 'colsample_bytree': 0.23046960519600732, 'colsample_bylevel': 0.6556908472367138, 'gamma': 1.9839758527614872, 'alpha': 6.949417210505607, 'lambda': 7.038995085860652}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:10,514] Trial 215 finished with value: 0.9635700454321373 and parameters: {'objective': 'multi:softprob', 'n_estimators': 257, 'learning_rate': 0.0385636154861302, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5397665898459989, 'colsample_bytree': 0.28089710889320274, 'colsample_bylevel': 0.653191749983843, 'gamma': 1.3004877895999907, 'alpha': 7.014797514275537, 'lambda': 7.290859731841133}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:17,929] Trial 216 finished with value: 0.9635752338584953 and parameters: {'objective': 'multi:softprob', 'n_estimators': 255, 'learning_rate': 0.036347818980137545, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5386870032342432, 'colsample_bytree': 0.2824595016497769, 'colsample_bylevel': 0.6560213966243578, 'gamma': 1.23695106471712, 'alpha': 7.254067584736075, 'lambda': 7.196062547869125}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:25,074] Trial 217 finished with value: 0.9886376510475126 and parameters: {'objective': 'multi:softprob', 'n_estimators': 242, 'learning_rate': 0.013547017438515947, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5419446033617856, 'colsample_bytree': 0.284165294529207, 'colsample_bylevel': 0.6558109876116427, 'gamma': 1.274208870458962, 'alpha': 7.2998733506170925, 'lambda': 7.182635772892782}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:32,541] Trial 218 finished with value: 0.9716233251851532 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.08038645817289086, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5312457070237261, 'colsample_bytree': 0.2718159630305406, 'colsample_bylevel': 0.6911229232060548, 'gamma': 1.2710308066062226, 'alpha': 7.380629994725006, 'lambda': 7.3531775300496385}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:40,086] Trial 219 finished with value: 0.9671768707480364 and parameters: {'objective': 'multi:softprob', 'n_estimators': 263, 'learning_rate': 0.02590735417708815, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5522840333197312, 'colsample_bytree': 0.2586453219199197, 'colsample_bylevel': 0.6738777042650986, 'gamma': 0.9878804835076493, 'alpha': 7.864169537628589, 'lambda': 6.937816682480421}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:47,533] Trial 220 finished with value: 0.9683970612131102 and parameters: {'objective': 'multi:softprob', 'n_estimators': 253, 'learning_rate': 0.03863138166088986, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5211534539181332, 'colsample_bytree': 0.3149598517680049, 'colsample_bylevel': 0.6602360240046219, 'gamma': 1.2782105984059868, 'alpha': 7.00049060251536, 'lambda': 6.692158445610583}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:42:55,147] Trial 221 finished with value: 0.9622610505776945 and parameters: {'objective': 'multi:softprob', 'n_estimators': 265, 'learning_rate': 0.03568526062487172, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5359167518409441, 'colsample_bytree': 0.2359734385211331, 'colsample_bylevel': 0.6376939847519795, 'gamma': 1.4560088599389966, 'alpha': 7.024141369359521, 'lambda': 7.059666444321537}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:02,365] Trial 222 finished with value: 0.9630630823782329 and parameters: {'objective': 'multi:softprob', 'n_estimators': 241, 'learning_rate': 0.03777283129367198, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5424299487722075, 'colsample_bytree': 0.24821761441546455, 'colsample_bylevel': 0.61877796627935, 'gamma': 1.4493074147609288, 'alpha': 6.864092491176278, 'lambda': 7.178114525618383}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:09,590] Trial 223 finished with value: 0.9679454687651755 and parameters: {'objective': 'multi:softprob', 'n_estimators': 241, 'learning_rate': 0.07222453628300132, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5162608951190437, 'colsample_bytree': 0.24178526830010133, 'colsample_bylevel': 0.6152226855084059, 'gamma': 1.4630198376144896, 'alpha': 6.685875008306052, 'lambda': 7.511783293061146}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:17,217] Trial 224 finished with value: 0.9599166606491221 and parameters: {'objective': 'multi:softprob', 'n_estimators': 264, 'learning_rate': 0.08824593412111408, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5391310326511842, 'colsample_bytree': 0.25182703308304294, 'colsample_bylevel': 0.621681304265236, 'gamma': 1.9244588620460144, 'alpha': 6.889195119442501, 'lambda': 6.901756263284216}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:24,540] Trial 225 finished with value: 0.9775005738826344 and parameters: {'objective': 'multi:softprob', 'n_estimators': 244, 'learning_rate': 0.1048053314614142, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5154378325542667, 'colsample_bytree': 0.2529133704908216, 'colsample_bylevel': 0.6214410566431615, 'gamma': 1.8969512765199024, 'alpha': 6.765894735380411, 'lambda': 6.907074937907239}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:32,127] Trial 226 finished with value: 0.9674642947137212 and parameters: {'objective': 'multi:softprob', 'n_estimators': 264, 'learning_rate': 0.08872944083718423, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5540629560044253, 'colsample_bytree': 0.23366609972806218, 'colsample_bylevel': 0.6341157287797456, 'gamma': 2.102234524107753, 'alpha': 6.888909579872426, 'lambda': 6.746940254097353}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:40,080] Trial 227 finished with value: 0.9708871805040203 and parameters: {'objective': 'multi:softprob', 'n_estimators': 288, 'learning_rate': 0.0792081654884703, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5254662662137947, 'colsample_bytree': 0.24624963660521634, 'colsample_bylevel': 0.6131873711190796, 'gamma': 1.6950080427436036, 'alpha': 6.604475244406503, 'lambda': 7.098023685282523}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:47,728] Trial 228 finished with value: 0.9720444057283665 and parameters: {'objective': 'multi:softprob', 'n_estimators': 267, 'learning_rate': 0.06385701478011989, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.5051008385888226, 'colsample_bytree': 0.26334620325088165, 'colsample_bylevel': 0.677112301971429, 'gamma': 1.935672088699663, 'alpha': 6.686700718251251, 'lambda': 6.689329158382181}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:43:54,798] Trial 229 finished with value: 0.9774545826121916 and parameters: {'objective': 'multi:softprob', 'n_estimators': 234, 'learning_rate': 0.11639269495314519, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.534264137114711, 'colsample_bytree': 0.2246822635816396, 'colsample_bylevel': 0.6435630118783099, 'gamma': 0.9033771546663263, 'alpha': 7.12775788762338, 'lambda': 6.897106803426763}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:02,416] Trial 230 finished with value: 0.9776240985804909 and parameters: {'objective': 'multi:softprob', 'n_estimators': 265, 'learning_rate': 0.09021136964024962, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.49309935762363766, 'colsample_bytree': 0.23244597572305004, 'colsample_bylevel': 0.628103338606675, 'gamma': 1.55678730937617, 'alpha': 6.797279801320186, 'lambda': 7.02302300595361}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:09,775] Trial 231 finished with value: 0.9604367697318565 and parameters: {'objective': 'multi:softprob', 'n_estimators': 250, 'learning_rate': 0.04319367172435807, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5435982228780472, 'colsample_bytree': 0.2520397821026178, 'colsample_bylevel': 0.6529938850121987, 'gamma': 1.7486059618211114, 'alpha': 6.961995226016237, 'lambda': 7.394127809367306}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:17,103] Trial 232 finished with value: 0.9662165782378286 and parameters: {'objective': 'multi:softprob', 'n_estimators': 250, 'learning_rate': 0.048054488707913616, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5122411124131737, 'colsample_bytree': 0.2533555123485141, 'colsample_bylevel': 0.6429412472942121, 'gamma': 0.660750139028968, 'alpha': 6.889196168190366, 'lambda': 7.534031454314522}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:24,661] Trial 233 finished with value: 0.9904250334914951 and parameters: {'objective': 'multi:softprob', 'n_estimators': 261, 'learning_rate': 0.012936847747984523, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.5289474585708027, 'colsample_bytree': 0.23779943667411577, 'colsample_bylevel': 0.6674151931288037, 'gamma': 1.7235096514102386, 'alpha': 6.599314385065315, 'lambda': 6.615961661060872}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:32,634] Trial 234 finished with value: 0.9699733445431631 and parameters: {'objective': 'multi:softprob', 'n_estimators': 286, 'learning_rate': 0.06897640425878919, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5508830897274655, 'colsample_bytree': 0.21773275798396802, 'colsample_bylevel': 0.6031898908037563, 'gamma': 1.4216852447283448, 'alpha': 7.181908225229692, 'lambda': 7.308126127797094}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:39,901] Trial 235 finished with value: 0.9757684547971752 and parameters: {'objective': 'multi:softprob', 'n_estimators': 249, 'learning_rate': 0.048548821410455155, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5663844380683671, 'colsample_bytree': 0.9410041463513954, 'colsample_bylevel': 0.6237344159263389, 'gamma': 1.0759494418709663, 'alpha': 6.369467476371902, 'lambda': 6.878211861011741}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:47,400] Trial 236 finished with value: 0.9696947351352189 and parameters: {'objective': 'multi:softprob', 'n_estimators': 266, 'learning_rate': 0.025981968903262057, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5122878745105589, 'colsample_bytree': 0.2649216615042457, 'colsample_bylevel': 0.6446731667955148, 'gamma': 2.0033116814244902, 'alpha': 5.743442655751096, 'lambda': 7.081042339905871}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:44:54,533] Trial 237 finished with value: 0.9657048805000417 and parameters: {'objective': 'multi:softprob', 'n_estimators': 241, 'learning_rate': 0.07299844031600061, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5421114832113739, 'colsample_bytree': 0.24334949211455845, 'colsample_bylevel': 0.6820898032403353, 'gamma': 1.8089661961811248, 'alpha': 7.487059892576452, 'lambda': 6.533715999235943}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:02,166] Trial 238 finished with value: 0.9648383736544257 and parameters: {'objective': 'multi:softprob', 'n_estimators': 272, 'learning_rate': 0.047686208818421165, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.4899693265974425, 'colsample_bytree': 0.21720842782750774, 'colsample_bylevel': 0.6587686532338026, 'gamma': 0.7801559799469531, 'alpha': 6.952085657363118, 'lambda': 6.105722475021574}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:10,088] Trial 239 finished with value: 1.2623166456476858 and parameters: {'objective': 'multi:softprob', 'n_estimators': 290, 'learning_rate': 0.6268529333288049, 'max_depth': 1, 'min_child_weight': 7, 'subsample': 0.524089694300439, 'colsample_bytree': 0.23181971015237066, 'colsample_bylevel': 0.6127052077294821, 'gamma': 1.5055864175082383, 'alpha': 5.8792696590508315, 'lambda': 7.736726209902535}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:17,527] Trial 240 finished with value: 0.9670354743708266 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.08941913317984918, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5032410113189667, 'colsample_bytree': 0.25279175520261193, 'colsample_bylevel': 0.6308083505997524, 'gamma': 1.105511786981068, 'alpha': 6.610193863917428, 'lambda': 7.375935262353728}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:25,078] Trial 241 finished with value: 0.9692713729028631 and parameters: {'objective': 'multi:softprob', 'n_estimators': 256, 'learning_rate': 0.029972839582895646, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.541577172516559, 'colsample_bytree': 0.2758349867988021, 'colsample_bylevel': 0.658966394692829, 'gamma': 1.3416755527893107, 'alpha': 7.0103566547922895, 'lambda': 7.275279992188973}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:32,994] Trial 242 finished with value: 0.9650425398499539 and parameters: {'objective': 'multi:softprob', 'n_estimators': 267, 'learning_rate': 0.054332784721462885, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5349219965127399, 'colsample_bytree': 0.22861356178590866, 'colsample_bylevel': 0.6492844486526987, 'gamma': 0.9391558089292502, 'alpha': 7.086578082218712, 'lambda': 7.178176549715365}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:40,833] Trial 243 finished with value: 0.9649823089894993 and parameters: {'objective': 'multi:softprob', 'n_estimators': 281, 'learning_rate': 0.037532977679867706, 'max_depth': 1, 'min_child_weight': 8, 'subsample': 0.5119307681746151, 'colsample_bytree': 0.2666993491929382, 'colsample_bylevel': 0.6336428318153212, 'gamma': 1.184059678667122, 'alpha': 7.314412603357203, 'lambda': 7.509251194273495}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:48,171] Trial 244 finished with value: 0.9593776460583362 and parameters: {'objective': 'multi:softprob', 'n_estimators': 253, 'learning_rate': 0.06936906215437176, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5524224959698677, 'colsample_bytree': 0.24759538931177524, 'colsample_bylevel': 0.6714020755747456, 'gamma': 1.652529600589549, 'alpha': 6.884325422899912, 'lambda': 6.804530883288946}. Best is trial 195 with value: 0.9582183471886763.

[I 2026-09-01 09:45:55,112] Trial 245 finished with value: 0.9573965733004632 and parameters: {'objective': 'multi:softprob', 'n_estimators': 235, 'learning_rate': 0.06817931894555553, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5568913428530878, 'colsample_bytree': 0.24418401355357203, 'colsample_bylevel': 0.6868552758323151, 'gamma': 1.636535386821078, 'alpha': 6.792367006491196, 'lambda': 6.7466858813953}. Best is trial 245 with value: 0.9573965733004632.

[I 2026-09-01 09:46:02,124] Trial 246 finished with value: 0.9566561851933267 and parameters: {'objective': 'multi:softprob', 'n_estimators': 232, 'learning_rate': 0.06944674231648809, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5571182778160532, 'colsample_bytree': 0.24487911213829808, 'colsample_bylevel': 0.68029802481105, 'gamma': 1.6206834987019028, 'alpha': 6.808594659790542, 'lambda': 6.595550478811772}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:09,071] Trial 247 finished with value: 0.9607500378051983 and parameters: {'objective': 'multi:softprob', 'n_estimators': 228, 'learning_rate': 0.1052649676935759, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.581587832744225, 'colsample_bytree': 0.24020483257367164, 'colsample_bylevel': 0.6891025962902786, 'gamma': 2.086402492094529, 'alpha': 6.754012829356909, 'lambda': 6.739632901130735}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:16,060] Trial 248 finished with value: 0.9593387301618959 and parameters: {'objective': 'multi:softprob', 'n_estimators': 228, 'learning_rate': 0.11033897196890124, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5952235611931118, 'colsample_bytree': 0.2456991530311793, 'colsample_bylevel': 0.6812265882093266, 'gamma': 1.6591645222015976, 'alpha': 6.3927600229489565, 'lambda': 6.600058439774669}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:23,125] Trial 249 finished with value: 0.9742572864647296 and parameters: {'objective': 'multi:softprob', 'n_estimators': 230, 'learning_rate': 0.11489385045440657, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5990838334999217, 'colsample_bytree': 0.25439498429719637, 'colsample_bylevel': 0.6857369769488116, 'gamma': 1.7247339011704454, 'alpha': 6.629959366843378, 'lambda': 6.673537167970703}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:30,184] Trial 250 finished with value: 0.9602599960920727 and parameters: {'objective': 'multi:softprob', 'n_estimators': 231, 'learning_rate': 0.100960870398338, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5765021041052325, 'colsample_bytree': 0.24456459028316357, 'colsample_bylevel': 0.693706620854279, 'gamma': 2.111811946735819, 'alpha': 6.219237759086137, 'lambda': 6.527047043205534}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:42,458] Trial 251 finished with value: 2.3642953155319075 and parameters: {'objective': 'multi:softprob', 'n_estimators': 222, 'learning_rate': 0.13795823227730436, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.5847361037272116, 'colsample_bytree': 0.26260481931164503, 'colsample_bylevel': 0.7025440419167939, 'gamma': 1.9874382236994048, 'alpha': 6.177047388849035, 'lambda': 6.589009133922947}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:50,288] Trial 252 finished with value: 1.0587610248725756 and parameters: {'objective': 'multi:softprob', 'n_estimators': 232, 'learning_rate': 0.106200372646431, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.6124294691111432, 'colsample_bytree': 0.2467261545884586, 'colsample_bylevel': 0.6856810443875289, 'gamma': 1.727517502720568, 'alpha': 6.393519688720213, 'lambda': 6.253843825953915}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:46:57,024] Trial 253 finished with value: 0.9694099678295397 and parameters: {'objective': 'multi:softprob', 'n_estimators': 225, 'learning_rate': 0.098976767956901, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5736149249268128, 'colsample_bytree': 0.21541703480276417, 'colsample_bylevel': 0.6745169130216743, 'gamma': 1.9838283415146956, 'alpha': 6.13743656310632, 'lambda': 6.837784955232533}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:47:14,053] Trial 254 finished with value: 2.9409329343469715 and parameters: {'objective': 'multi:softprob', 'n_estimators': 235, 'learning_rate': 0.11907429297877328, 'max_depth': 10, 'min_child_weight': 5, 'subsample': 0.5755453915114142, 'colsample_bytree': 0.29482423428433213, 'colsample_bylevel': 0.6747551402086993, 'gamma': 2.1492196770300445, 'alpha': 6.498267189807842, 'lambda': 6.443126186236797}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:47:20,950] Trial 255 finished with value: 0.9692794639390945 and parameters: {'objective': 'multi:softprob', 'n_estimators': 230, 'learning_rate': 0.08466672597353524, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5954838124289809, 'colsample_bytree': 0.2667968774335989, 'colsample_bylevel': 0.6934853720894629, 'gamma': 1.590011490006526, 'alpha': 6.705951430546149, 'lambda': 6.538621813056416}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:47:28,030] Trial 256 finished with value: 0.9818627638111003 and parameters: {'objective': 'multi:softprob', 'n_estimators': 245, 'learning_rate': 0.13208170153628523, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5608690574606139, 'colsample_bytree': 0.2470172217263288, 'colsample_bylevel': 0.7113345066829821, 'gamma': 0.5544187435181913, 'alpha': 6.2865524029076, 'lambda': 6.889595658050334}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:47:34,932] Trial 257 finished with value: 0.9654165819568623 and parameters: {'objective': 'multi:softprob', 'n_estimators': 238, 'learning_rate': 0.09278316184170982, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5706912448842807, 'colsample_bytree': 0.21949565630343895, 'colsample_bylevel': 0.6720348479144382, 'gamma': 2.217716147148157, 'alpha': 5.985636145264836, 'lambda': 5.925473195442884}. Best is trial 246 with value: 0.9566561851933267.

[I 2026-09-01 09:47:41,870] Trial 258 finished with value: 0.9536605284485395 and parameters: {'objective': 'multi:softprob', 'n_estimators': 220, 'learning_rate': 0.07498795990965833, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.6062510906395202, 'colsample_bytree': 0.24147325980614068, 'colsample_bylevel': 0.6842950829495661, 'gamma': 1.8502644776605934, 'alpha': 6.540211548573163, 'lambda': 6.764937382394443}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:47:48,757] Trial 259 finished with value: 0.9663554838688183 and parameters: {'objective': 'multi:softprob', 'n_estimators': 225, 'learning_rate': 0.11040661388785833, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.6299706978234295, 'colsample_bytree': 0.24504130261833923, 'colsample_bylevel': 0.696269047075154, 'gamma': 1.8685796856350325, 'alpha': 6.7385010393159375, 'lambda': 6.754991075204021}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:47:55,523] Trial 260 finished with value: 0.9656979271263356 and parameters: {'objective': 'multi:softprob', 'n_estimators': 219, 'learning_rate': 0.08121264266438874, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.6118277504667899, 'colsample_bytree': 0.2641733192567711, 'colsample_bylevel': 0.7137487455170266, 'gamma': 1.5433787744506107, 'alpha': 6.592887639213367, 'lambda': 6.152883951838316}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:02,221] Trial 261 finished with value: 0.9597608251475216 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.07554259418956567, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5901565956089894, 'colsample_bytree': 0.23831924649191347, 'colsample_bylevel': 0.6876709632259596, 'gamma': 2.1177691527166735, 'alpha': 6.395193439883157, 'lambda': 6.480978051284387}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:08,982] Trial 262 finished with value: 0.9745418620284363 and parameters: {'objective': 'multi:softprob', 'n_estimators': 216, 'learning_rate': 0.09210977799174205, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5883075298440049, 'colsample_bytree': 0.2754278417937756, 'colsample_bylevel': 0.6948737092367907, 'gamma': 2.1199340153542443, 'alpha': 6.416177681222142, 'lambda': 6.6315273678973465}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:15,566] Trial 263 finished with value: 0.9606660235683518 and parameters: {'objective': 'multi:softprob', 'n_estimators': 207, 'learning_rate': 0.12223357915945471, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6523116740663935, 'colsample_bytree': 0.24008601650372355, 'colsample_bylevel': 0.6811278284747786, 'gamma': 2.2985243204569636, 'alpha': 6.75755602279462, 'lambda': 6.9544283508848}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:22,249] Trial 264 finished with value: 0.9605822354880664 and parameters: {'objective': 'multi:softprob', 'n_estimators': 210, 'learning_rate': 0.1225747232015228, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6492711727482886, 'colsample_bytree': 0.2468835963903465, 'colsample_bylevel': 0.6840993062489031, 'gamma': 2.3975197225596414, 'alpha': 6.751911380813656, 'lambda': 6.832988316718697}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:29,907] Trial 265 finished with value: 1.0893470687518139 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.15620626896144432, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6729314668271086, 'colsample_bytree': 0.2624051011129855, 'colsample_bylevel': 0.7324038111044583, 'gamma': 2.4038701885509135, 'alpha': 6.4911336068794485, 'lambda': 6.294961434156876}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:36,404] Trial 266 finished with value: 0.9669701897372661 and parameters: {'objective': 'multi:softprob', 'n_estimators': 205, 'learning_rate': 0.1218389206196531, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6581625256076862, 'colsample_bytree': 0.28590661830344644, 'colsample_bylevel': 0.7094103153351621, 'gamma': 2.3249439154750977, 'alpha': 6.707369968766757, 'lambda': 6.943845993331981}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:43,129] Trial 267 finished with value: 0.9624510948022698 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.13909996403909683, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6367629042453192, 'colsample_bytree': 0.25051636057041116, 'colsample_bylevel': 0.6774987956898887, 'gamma': 2.1478898316394126, 'alpha': 6.349321504634609, 'lambda': 6.873991976382011}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:49,983] Trial 268 finished with value: 0.9791941579384635 and parameters: {'objective': 'multi:softprob', 'n_estimators': 222, 'learning_rate': 0.11686828673102644, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6527405932095942, 'colsample_bytree': 0.23909888178143252, 'colsample_bylevel': 0.6854318413214284, 'gamma': 2.3746686722742827, 'alpha': 6.799551820776716, 'lambda': 6.505586626723019}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:48:57,083] Trial 269 finished with value: 0.9985537293374631 and parameters: {'objective': 'multi:softprob', 'n_estimators': 231, 'learning_rate': 0.14396422379912716, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6189480648037512, 'colsample_bytree': 0.2605482126114523, 'colsample_bylevel': 0.696773060690538, 'gamma': 2.0555328183365127, 'alpha': 6.5381840582116135, 'lambda': 6.774432119632213}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:07,866] Trial 270 finished with value: 1.01778928739583 and parameters: {'objective': 'multi:softprob', 'n_estimators': 458, 'learning_rate': 0.10516082842026435, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.6019555488514187, 'colsample_bytree': 0.2771484496003937, 'colsample_bylevel': 0.7208505586836867, 'gamma': 1.886981630062507, 'alpha': 0.02943455006080775, 'lambda': 6.343238969342447}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:14,255] Trial 271 finished with value: 0.9673191948450575 and parameters: {'objective': 'multi:softprob', 'n_estimators': 203, 'learning_rate': 0.12858718913988565, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.6898726932766946, 'colsample_bytree': 0.24646826877503472, 'colsample_bylevel': 0.669444127359504, 'gamma': 2.1850944621530015, 'alpha': 6.228667966345393, 'lambda': 6.551386449429999}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:21,030] Trial 272 finished with value: 0.9718868376100424 and parameters: {'objective': 'multi:softprob', 'n_estimators': 211, 'learning_rate': 0.09460052247784205, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6025381294037105, 'colsample_bytree': 0.23505409221979584, 'colsample_bylevel': 0.6839911378221405, 'gamma': 1.8150046480150446, 'alpha': 6.645649716498065, 'lambda': 5.681697602802239}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:28,106] Trial 273 finished with value: 0.969447590186671 and parameters: {'objective': 'multi:softprob', 'n_estimators': 237, 'learning_rate': 0.07452950978381218, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5787764280474602, 'colsample_bytree': 0.25392314778609754, 'colsample_bylevel': 0.6652246559421533, 'gamma': 2.391129086802199, 'alpha': 6.795290403201793, 'lambda': 6.048646547019306}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:35,122] Trial 274 finished with value: 0.9908442973591335 and parameters: {'objective': 'multi:softprob', 'n_estimators': 224, 'learning_rate': 0.16008011743281658, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5641490115882014, 'colsample_bytree': 0.2975279899129186, 'colsample_bylevel': 0.70138397957878, 'gamma': 7.877892472211102, 'alpha': 7.217461783694577, 'lambda': 7.070765264365374}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:43,602] Trial 275 finished with value: 1.065412289387479 and parameters: {'objective': 'multi:softprob', 'n_estimators': 247, 'learning_rate': 0.09839591499508742, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.6407517822677504, 'colsample_bytree': 0.23273127162781937, 'colsample_bylevel': 0.6858508540010181, 'gamma': 1.9499016188821652, 'alpha': 6.203381159529056, 'lambda': 6.867075072023151}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:49,896] Trial 276 finished with value: 0.9644325446472879 and parameters: {'objective': 'multi:softprob', 'n_estimators': 196, 'learning_rate': 0.0766170683525998, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5872892305563997, 'colsample_bytree': 0.27006943432938113, 'colsample_bylevel': 0.6706327507385186, 'gamma': 2.175430691003602, 'alpha': 5.846372329151216, 'lambda': 6.672266940926696}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:49:57,009] Trial 277 finished with value: 0.9803678003186056 and parameters: {'objective': 'multi:softprob', 'n_estimators': 236, 'learning_rate': 0.1220202228857549, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6610337624148823, 'colsample_bytree': 0.251263180420145, 'colsample_bylevel': 0.7110714183166983, 'gamma': 1.7325518235702115, 'alpha': 6.487163276773525, 'lambda': 6.378921192576877}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:04,289] Trial 278 finished with value: 0.9697211265716635 and parameters: {'objective': 'multi:softprob', 'n_estimators': 250, 'learning_rate': 0.07418067631724316, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5584977380221733, 'colsample_bytree': 0.2294818753175008, 'colsample_bylevel': 0.6657778656872233, 'gamma': 2.726823684904505, 'alpha': 6.790672947894536, 'lambda': 6.967657869334245}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:11,252] Trial 279 finished with value: 1.3605621047808791 and parameters: {'objective': 'multi:softprob', 'n_estimators': 224, 'learning_rate': 0.9866212873718627, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.6140181924313759, 'colsample_bytree': 0.20045640986730898, 'colsample_bylevel': 0.6770585615804385, 'gamma': 0.7935181359318484, 'alpha': 6.3021183227385205, 'lambda': 6.762670357350079}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:18,105] Trial 280 finished with value: 0.9587434921559829 and parameters: {'objective': 'multi:softprob', 'n_estimators': 213, 'learning_rate': 0.10860369450640604, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5733508779477658, 'colsample_bytree': 0.24256102435861418, 'colsample_bylevel': 0.6908907736348556, 'gamma': 1.8338937260711479, 'alpha': 6.5083552615616975, 'lambda': 6.218638863745734}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:31,072] Trial 281 finished with value: 2.8745595194409064 and parameters: {'objective': 'multi:softprob', 'n_estimators': 210, 'learning_rate': 0.176499035296586, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.5756587604096581, 'colsample_bytree': 0.28264346336059937, 'colsample_bylevel': 0.7004262755372923, 'gamma': 1.8637001428905935, 'alpha': 6.5138456834719705, 'lambda': 6.186120125273847}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:37,646] Trial 282 finished with value: 0.963782015713143 and parameters: {'objective': 'multi:softprob', 'n_estimators': 218, 'learning_rate': 0.10128235034486469, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5893351275603516, 'colsample_bytree': 0.25617766114073703, 'colsample_bylevel': 0.7322032533642687, 'gamma': 2.180313476031458, 'alpha': 5.800832243766025, 'lambda': 5.9178495846834664}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:44,194] Trial 283 finished with value: 0.9548246575204183 and parameters: {'objective': 'multi:softprob', 'n_estimators': 202, 'learning_rate': 0.11446670925000188, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5534688056219785, 'colsample_bytree': 0.2414578669258051, 'colsample_bylevel': 0.6946941914072433, 'gamma': 1.6598546732002923, 'alpha': 6.090399053966207, 'lambda': 5.560382030103437}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:50,768] Trial 284 finished with value: 0.9857828314532444 and parameters: {'objective': 'multi:softprob', 'n_estimators': 202, 'learning_rate': 0.14804781873081532, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5602363314393864, 'colsample_bytree': 0.2698963895444088, 'colsample_bylevel': 0.6927018711305858, 'gamma': 9.44953428107681, 'alpha': 5.996664785643609, 'lambda': 4.97176080935173}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:50:57,353] Trial 285 finished with value: 0.9668983397102633 and parameters: {'objective': 'multi:softprob', 'n_estimators': 195, 'learning_rate': 0.12626645160829744, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5971692495808455, 'colsample_bytree': 0.243400690458214, 'colsample_bylevel': 0.7181656019159075, 'gamma': 2.531145680564528, 'alpha': 6.204597818564796, 'lambda': 5.377173517365247}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:05,074] Trial 286 finished with value: 1.0536876339176853 and parameters: {'objective': 'multi:softprob', 'n_estimators': 207, 'learning_rate': 0.11215340707177761, 'max_depth': 2, 'min_child_weight': 3, 'subsample': 0.5553516601725095, 'colsample_bytree': 0.22183594094531173, 'colsample_bylevel': 0.6883862760904089, 'gamma': 1.657675732556201, 'alpha': 5.69066078647238, 'lambda': 5.4440633743808675}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:12,077] Trial 287 finished with value: 1.3918950271149726 and parameters: {'objective': 'multi:softprob', 'n_estimators': 230, 'learning_rate': 0.8737180735974299, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5774682984829023, 'colsample_bytree': 0.2571670304136294, 'colsample_bylevel': 0.7072006146280547, 'gamma': 1.9585150701331142, 'alpha': 6.387849456469624, 'lambda': 6.240114521583556}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:18,922] Trial 288 finished with value: 0.9641529775149289 and parameters: {'objective': 'multi:softprob', 'n_estimators': 215, 'learning_rate': 0.13707421333166547, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6324937531119038, 'colsample_bytree': 0.2439026552522569, 'colsample_bylevel': 0.660635397314585, 'gamma': 1.752059404757568, 'alpha': 6.217631457410969, 'lambda': 5.78169614458271}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:26,016] Trial 289 finished with value: 0.9697615038188637 and parameters: {'objective': 'multi:softprob', 'n_estimators': 230, 'learning_rate': 0.10380166204119139, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.6091170988045106, 'colsample_bytree': 0.28792615020910634, 'colsample_bylevel': 0.6829668588496798, 'gamma': 1.6038712137723605, 'alpha': 6.045037786736631, 'lambda': 6.008729734972522}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:33,229] Trial 290 finished with value: 0.9741732331042379 and parameters: {'objective': 'multi:softprob', 'n_estimators': 241, 'learning_rate': 0.08392575551998618, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.7071433636555416, 'colsample_bytree': 0.2179828814006921, 'colsample_bylevel': 0.7498850067990396, 'gamma': 2.0694198267757553, 'alpha': 6.582496119621089, 'lambda': 6.472064698457322}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:39,644] Trial 291 finished with value: 0.9790987097185672 and parameters: {'objective': 'multi:softprob', 'n_estimators': 193, 'learning_rate': 0.11617691577955794, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5568095084267978, 'colsample_bytree': 0.2664364432809153, 'colsample_bylevel': 0.6627912649581595, 'gamma': 2.3480775969702066, 'alpha': 6.385290909927094, 'lambda': 6.579001823323334}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:47,464] Trial 292 finished with value: 1.0288025277395532 and parameters: {'objective': 'multi:softprob', 'n_estimators': 216, 'learning_rate': 0.09083216893964038, 'max_depth': 2, 'min_child_weight': 4, 'subsample': 0.572204928962151, 'colsample_bytree': 0.23984646140193402, 'colsample_bylevel': 0.6889787846674326, 'gamma': 1.8399243966836056, 'alpha': 5.869682863452085, 'lambda': 5.599945308858388}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:51:54,500] Trial 293 finished with value: 0.9630046236052164 and parameters: {'objective': 'multi:softprob', 'n_estimators': 240, 'learning_rate': 0.0750602959420746, 'max_depth': 1, 'min_child_weight': 6, 'subsample': 0.5927190520183135, 'colsample_bytree': 0.22293415079068954, 'colsample_bylevel': 0.7043906490261156, 'gamma': 1.3488000104645237, 'alpha': 7.127060990629123, 'lambda': 6.349255920005868}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:52:01,052] Trial 294 finished with value: 0.9564848811442417 and parameters: {'objective': 'multi:softprob', 'n_estimators': 201, 'learning_rate': 0.10215814003441982, 'max_depth': 1, 'min_child_weight': 5, 'subsample': 0.5483214697136415, 'colsample_bytree': 0.24939336554062058, 'colsample_bylevel': 0.6763448705236406, 'gamma': 1.64163106023342, 'alpha': 6.128029973568144, 'lambda': 7.218256972211764}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:52:07,811] Trial 295 finished with value: 0.9866909812828275 and parameters: {'objective': 'multi:softprob', 'n_estimators': 206, 'learning_rate': 0.16341597347590026, 'max_depth': 1, 'min_child_weight': 2, 'subsample': 0.5516774122247584, 'colsample_bytree': 0.2742905765394664, 'colsample_bylevel': 0.6754459088430131, 'gamma': 1.9860425050434418, 'alpha': 6.635784560026546, 'lambda': 7.217145783631695}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:52:14,124] Trial 296 finished with value: 0.9773215464941947 and parameters: {'objective': 'multi:softprob', 'n_estimators': 189, 'learning_rate': 0.131591055361995, 'max_depth': 1, 'min_child_weight': 3, 'subsample': 0.5704040622587087, 'colsample_bytree': 0.25561407394420027, 'colsample_bylevel': 0.7173157949560321, 'gamma': 1.6573788306657375, 'alpha': 6.147794080751044, 'lambda': 7.330401064704333}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:52:20,802] Trial 297 finished with value: 0.9540195596434781 and parameters: {'objective': 'multi:softprob', 'n_estimators': 205, 'learning_rate': 0.10581475985784247, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5521548138047109, 'colsample_bytree': 0.24432121292310194, 'colsample_bylevel': 0.6629150518660362, 'gamma': 2.208219684877636, 'alpha': 6.418895006860756, 'lambda': 7.42942053316907}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:52:29,826] Trial 298 finished with value: 2.8082027095923547 and parameters: {'objective': 'multi:softprob', 'n_estimators': 204, 'learning_rate': 0.47605798269092375, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.9591779376853855, 'colsample_bytree': 0.25840182535180317, 'colsample_bylevel': 0.6676142448065623, 'gamma': 2.4421969355376225, 'alpha': 6.427589245980536, 'lambda': 7.597298714168295}. Best is trial 258 with value: 0.9536605284485395.

[I 2026-09-01 09:52:36,164] Trial 299 finished with value: 0.9964907351562915 and parameters: {'objective': 'multi:softprob', 'n_estimators': 201, 'learning_rate': 0.19908213617616638, 'max_depth': 1, 'min_child_weight': 4, 'subsample': 0.5501203723492567, 'colsample_bytree': 0.29669701854653785, 'colsample_bylevel': 0.6557546909605437, 'gamma': 2.2455858585829858, 'alpha': 6.357278261553955, 'lambda': 7.4975869751530535}. Best is trial 258 with value: 0.9536605284485395.

{'objective': 'multi:softprob',
 'n_estimators': 220,
 'learning_rate': 0.07498795990965833,
 'max_depth': 1,
 'min_child_weight': 5,
 'subsample': 0.6062510906395202,
 'colsample_bytree': 0.24147325980614068,
 'colsample_bylevel': 0.6842950829495661,
 'gamma': 1.8502644776605934,
 'alpha': 6.540211548573163,
 'lambda': 6.764937382394443}

In [14]:
from objectives import get_best_multiclass_model

# 7.0.5-era helper, unchanged: prints Log Loss Train / Dev (the article's dev metric)
selected_features, model = get_best_multiclass_model(
    study.best_params,
    x_train[best_features],
    y_ord_train,
    x_dev[best_features],
    y_ord_dev,
    w_train=w_train,
    w_dev=w_dev,
    train_on_full=False,
)

used features: ['VOCATION', 'KAPITAL40', 'TYPERS', 'KAPITAL41', 'KAPITAL42', 'RISK11', 'DEROG12', 'KAPITAL43', 'KAPITAL37', 'ACTIVIT2', 'DEROG4', 'ZONE', 'RISK10', 'DEROG5', 'AN_EXERC', 'total_surface_crossed', 'INDEM2', 'NBJFXI3S10_MM_A_NBJFXI3S10_MMAX_A', 'TXAB_VOR_MM_A_TXAB_VOR_MMAX_A', 'zone_vent_extinction_rate', 'NBJFXI3S16_MM_A_NBJFXI3S16_MMAX_A', 'NBJTX0_MM_A_NBJTX0_MMAX_A', 'NBJRR50_MM_A_NBJRR50_MMAX_A', 'NBJRR10_MM_A_NBJRR10_MMAX_A', 'NBJFXI3S28_MM_A_NBJFXI3S28_MMAX_A', 'IND_REGION', 'IND_SNV_REGION', 'LOG_REGION', 'TN_VOR_MM_A_TN_VOR_MMAX_A', 'NBJFF16_MM_A_NBJFF16_MMAX_A', 'NBJTN5_MM_A_NBJTN5_MMAX_A', 'RRAB_VOR_MM_A_RRAB_VOR_MMAX_A', 'NBJFF10_MM_A_NBJFF10_MMAX_A', 'NBJFXY8_MM_A_NBJFXY8_MMAX_A', 'NBJRR30_MM_A_NBJRR30_MMAX_A', 'SURFACE6', 'TAILLE1', 'TAILLE2', 'HAUTEUR_MAX', 'BDTOPO_BAT_MAX_HAUTEUR_MAX', 'HAUTEUR', 'BDTOPO_BAT_MAX_HAUTEUR', 'DISTANCE_213', 'PROPORTION_21', 'DISTANCE_411', 'CARACT4', 'DISTANCE_323', 'DISTANCE_212', 'DISTANCE_335', 'DISTANCE_334', 'KAPITAL32', 'KAPITAL_MAX', 'SURFACE10', 'SURFACE1', 'SURFACE7', 'KAPITAL21', 'NBBAT4', 'NBSINSTRT', 'KAPITAL23', 'EQUIPEMENT6', 'NBSINCONJ', 'SURFACE17', 'KAPITAL8', 'KAPITAL14', 'TAILLE3', 'KAPITAL24', 'KAPITAL27', 'KAPITAL3', 'CA3_CA_TOT', 'KAPITAL10', 'EQUIPEMENT1', 'NBBAT2', 'SURFACE13', 'CARACT5', 'RISK5', 'NBBAT8', 'ZONE_VENT', 'CA3_CA_MEAN', 'KAPITAL20', 'KAPITAL25', 'KAPITAL17', 'RISK2', 'NBBAT6', 'NBBAT9', 'KAPITAL1', 'DEROG10', 'RISK1', 'DEROG8_formatted', 'DUREE_REQANEUF', 'NBBAT7', 'DEROG11', 'EQUIPEMENT4', 'DEROG7', 'DEROG6', 'CA3', 'DEROG1', 'TYPBAT2', 'RISK4', 'KAPITAL28', 'KAPITAL19']

Log Loss Train: 0.8622874280647036

Log Loss Dev:   0.9536605284485395

## Result

Compare `Log Loss Dev` above against the shipped arm's **0.91991** and the 2025
winner's **0.91936**. Every other setting is identical, so the difference is the
selector and nothing else.